### ISSUE TITLE
org.nd4j.linalg.convolution.DefaultConvolutionInstance convolution may end up with ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by cycladessoa-tangel** [deeplearning4j/nd4j#100]
You may want to check on line 88 in this file:

 for (int i = kernel.shape().length - 1; i >= 0; i--)

I suspect this may need to be input.shape().length instead of kernel.shape().length.

**Comment by agibsonccc** [comment]
Fixed in bug fixes branch. Thanks!
