### ISSUE TITLE
hstack and vstack causing IllegalStateException with CUDA

### ISSUE THREAD

**Issue by melroderick** [deeplearning4j/nd4j#1001]
When running with CUDA, calls to hstack() or vstack() run without error, but using their output results in an IllegalStateException.

Example code that causes error (for either hstack or vstack):

    INDArray[] inputs = new INDArray[4];
    
    for (int i = 0; i < inputs.length; i++) {
        inputs[i] = Nd4j.zeros(1, 200);
    }
    
    INDArray output = Nd4j.hstack(inputs);
    //INDArray output = Nd4j.vstack(inputs);
    
    System.out.println(output.toString());`

**Comment by raver119** [comment]
Yep, this is know issue for 3.9, and it's already fixed on current master. New release coming out today hopefully.
