### ISSUE TITLE
Eps Op Problems

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#1007]
Quoteing @xuy from the gitter channel:
> just discovered that Nd4j.ones(100).eps(1.0) gives me a result array of [0.73, 0.73, ...]
> seems very strange to me.
> looked at the code, in BaseNDArray.java, I have
> ```java
>  @Override
> public INDArray epsi(Number other) {
>     return Nd4j.getExecutioner().execAndReturn(new Eps(this));
> }
> ```
> the parameter "other" is not even used... a bug?
> 

This looks like several bugs in one:
1) Eps  says it has OpNum 10:
https://github.com/deeplearning4j/nd4j/blob/e59d5f58942e283f4dc62169e193e22aefd1aa5a/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/comparison/Eps.java#L58

But according to libnd4j OpNum 10 for transforms is a Sigmoid: https://github.com/deeplearning4j/libnd4j/blob/master/include/transform.h#L50

And with Sigmoid(1) = 0.73 I'm pretty sure this is the reason for the results that @xuy is seeing.

2) The other issue here is that, like @xuy mentioned, the other number isn't even used.

**Comment by eraly** [comment]
Thanks @treo. I fixed it in https://github.com/deeplearning4j/nd4j/pull/1011
:)
