### ISSUE TITLE
mul() error when DataType is DOUBLE

### ISSUE THREAD

**Issue by Jajawah** [deeplearning4j/nd4j#1008]
When I run the code below: 
<pre><code>
int size=1000000 ;
int[] shapes=new int[]{size,1};
INDArray tensorA = Nd4j.create(random.doubles(size).toArray(), shapes, 'c');
DataTypeUtil.setDTypeForContext(DataBuffer.Type.DOUBLE);
INDArray res = tensorA.mul(tensorA);
</code></pre>

I am frequently (but not always) facing a bug:
<pre>
<code>#
[thread 140416397973248 also had an error]
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb59c4f9f36, pid=2700, tid=140416381187840
#
# JRE version: Java(TM) SE Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.91-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libnd4j.so+0x60f36]  _ZN9functions19pairwise_transforms17PairWiseTransformIdE4execEPdxS3_xS3_xS3_x._omp_fn.34+0x76
</code></pre>

If I remove the line `DataTypeUtil.setDTypeForContext(DataBuffer.Type.DOUBLE);
then no more bugs.

I'm running the last version of nd4j

ps : I know I can create random ndarray with nd4j directly, that's not the point ;)

**Comment by raver119** [comment]
Move DataTypeUtil call BEFORE you create your tensorA.

**Comment by treo** [comment]
Congratulations, you have run into the bad luck bug. Don't know why it triggers for you only when you are using doubles, but it is resolved by upgrading to rc3.10.

**Comment by Jajawah** [comment]
@raver119 thanks for the tip (obvious :/)
@treo Great !

**Comment by treo** [comment]
Oh, so it wasn't the bad luck bug after all. But you should still update to rc3.10 ;)

**Comment by raver119** [comment]
Can i close this issue now?

**Comment by Jajawah** [comment]
Yes :)
