### ISSUE TITLE
INDArray.putScalar won't accept (0,0,-1) as a valid index in a 3D array

### ISSUE THREAD

**Issue by justineyster** [deeplearning4j/nd4j#1018]
I've been getting an "illegal index" error from a three dimensional INDArray when using (0,0,-1) as the coordinate in the INDArray.putScalar method. All other combinations of positive and negative indices seem to work fine. For instance, (0,-1,0) works fine. Yet (0,0,-1) fails in every case. I created a trivial test case to isolate this behavior and it is as follows:

INDArray test = Nd4j.create(10,10,10);
test.putScalar(new int[]{0,0,-1}, 1.0);

This results in the following error message: java.lang.IllegalArgumentException: Illegal index -1.

I can change the second line to:

test.putScalar(new int[]{0,3,-1}, 1.0);

and it runs fine. Seems to be an isolated case with the very specific coordinate (0,0,-1).

**Comment by justineyster** [comment]
On further inspection, it seems that some other cases throw errors as well:

test.putScalar(new int[]{-1,0,-1}, 1.0);
throws java.lang.IllegalArgumentException: Illegal index -101.

test.putScalar(new int[]{-1,0,0}, 1.0);
throws java.lang.IllegalArgumentException: Illegal index -100.

test.putScalar(new int[]{-1,0,1}, 1.0);
throws java.lang.IllegalArgumentException: Illegal index -99.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/1022
