### ISSUE TITLE
ENFORCE_NUMERICAL_STABILITY

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1027]
We have NaN enforcer working in single thread, and it becomes serious bottleneck in current architecture. So we might use some perf improvements there.

https://github.com/deeplearning4j/deeplearning4j/issues/1701

**Comment by agibsonccc** [comment]
We MAY want to just disable this?

**Comment by raver119** [comment]
Why? Let's just make it simd-able like any other op out there?

**Comment by agibsonccc** [comment]
I mean it's just bad practice to use in general.

**Comment by raver119** [comment]
Implemented as native here: https://github.com/deeplearning4j/nd4j/pull/1025

However, removal of replaceNans call after each op is still a concern, and to be decided
