### ISSUE TITLE
DataSet.getRange() does not handle mask arrays

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1031]
https://github.com/deeplearning4j/nd4j/blob/8f759523f14288d706305c108a7c988891fa2bbf/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/DataSet.java#L337

getRange() simply splits the features/examples up; it should also split the features/labels mask arrays up if they are present.

**Comment by eraly** [comment]
Merged. Also added tests.
