### ISSUE TITLE
DataSet (and MultiDataSet) toString issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1032]
DataSet.toString():
- Will throw a NPE if features or labels are null
- Does not display any info about mask arrays

MultiDataSet.toString()
- Doesn't exist (i.e., MultiDataSet does not implement a .toString() method, other than that provided by Object.toString())

**Comment by eraly** [comment]
This is also related to the issue I just closed. Will close this out when I add support the separator.

**Comment by eraly** [comment]
https://github.com/deeplearning4j/nd4j/pull/1042
Added mask info for dataset 
Added toString for multidataset
