### ISSUE TITLE
Notify 32bit JVM users, that it isn't supported

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#1035]
Every now and then someone drops by in gitter and asks about "no nind4j in java.library.path" and in the end it turns out that they are using a 32 bit jvm.

There should be a message in that case that explicitly tells the user, that a 32 bit jvm isn't supported.

**Comment by raver119** [comment]
Implemented here: https://github.com/deeplearning4j/nd4j/pull/1025
