### ISSUE TITLE
Add time series support to balanced minibatch functionality

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1053]
Add time series support for the following:
https://github.com/deeplearning4j/nd4j/blob/4abc46e4eeea833742a04f32deeee94f567c4048/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/dataset/BalanceMinibatchesTest.java#L27-L27

Complication here is that there's many different type of ttime series variants (masking, many-to-one, etc)

**Comment by raver119** [comment]
Is this issue still viable?

**Comment by AlexDBlack** [comment]
Better off in datavec, so I'll close this.
