### ISSUE TITLE
Docs: add full maven example for maven classifiers (when build/deploy platforms are different)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1057]
This includes some basic info for sbt and classifiers: http://nd4j.org/getstarted.html

However, no maven examples (we should have specific and clear details on exactly how to use maven to solve the multiple platforms issue).

Also as of 3.11 and later: include details on this: https://github.com/deeplearning4j/nd4j/pull/1051

Currently, the following is required:
- Standard nd4j-native dependency
- nd4j-native dependency as above with extra classifier section (`<classifier>linux-x86_64</classifier>` or similar)

**Comment by saudet** [comment]
Using the new "-platform" artifacts this shouldn't be necessary anymore...

**Comment by treo** [comment]
Right, then we should try the `-platform` artifacts :) 

also, there is https://github.com/deeplearning4j/nd4j/issues/917 which asked pretty much for the same thing.

**Comment by huitseeker** [comment]
@saudet is this still up to date considering #1794 ?

**Comment by saudet** [comment]
Yes, I think we can consider this solved, @AlexDBlack ?

**Comment by RuralHunter** [comment]
with "-platform", I can see all the native libs are included. This makes the final deployment package very big. How can I only include jars only for some specific platforms?

**Comment by AlexDBlack** [comment]
@RuralHunter if you just want to build and deploy on the same platform: use ```nd4j-native``` or ```nd4j-cuda-8.0``` as appropriate.

As for say windows and linux only (no mac): you can use maven classifiers to do this.

**Comment by saudet** [comment]
It's also possible to set the "javacpp.platform" system property:
https://github.com/deeplearning4j/dl4j-examples/#build-and-run

**Comment by RuralHunter** [comment]
@AlexDBlack @saudet Thanks!
