### ISSUE TITLE
transpose() and linearViewColumnOrder()

### ISSUE THREAD

**Issue by mbabadi** [deeplearning4j/nd4j#1058]
One expects `arr.linearViewColumnOrder()` and `arr.tranpose().linearViewColumnOrder()` to have the same shape, but they differ. Using `reshape(1, arr.length())` is immune to this bug. Here's a test code:

    @Test
    public void testLinearView() {
        INDArray d = Nd4j.linspace(0, 100, 100);
        System.out.println("Shape info using linear view:");
        System.out.println(d.linearViewColumnOrder().shapeInfoToString());
        System.out.println(d.transpose().linearViewColumnOrder().shapeInfoToString());
        System.out.println("Shape info using reshape:");
        System.out.println(d.reshape(1, 100).shapeInfoToString());
        System.out.println(d.transpose().reshape(1, 100).shapeInfoToString());
    }

**Comment by mbabadi** [comment]
By the way -- is the complexity of making a linear view of an NDArray via reshape(...) the same as using linearView()?

**Comment by agibsonccc** [comment]
I'd advise staying away from linear view. I'm sorry we should have deprecated that.
