### ISSUE TITLE
Mixed op data types

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#1070]
It is possible when you load a data type of one type from serialization, and then change the data type to be another one that you will get mixed op data types.

Right now our underlying code assumes everything is the same inducing a crash.

A proposed solution is to have some sort of a coercion that happens when an op is created to be whatever the data type is set for nd4j. Need to think on this a bit more yet though.

Edit:Another part of this is to force data type on load. Do this within Nd4j.createBuffer() when the data buffer is loaded.

Edit: A warning that we loaded a data type != to the current data type in the context would be good as well. This will help for diagnosing issues as well as weird serde issues we could run in to with say: spark.

We should also throw an exception with op execution before an op is executed.
This will prevent an error prone crash.

Do it post load and then convert.

**Comment by eraly** [comment]
This forces a load to the data type defined.
https://github.com/deeplearning4j/nd4j/pull/1059

So unless a user redefines datatype midway through (I'd call that user error) we shouldn't see mixed data types ops on ndarrays and no more crashes.
But predicting with a model that was saved as a float and then streamed in as a double (or viceversa) won't give sensible results. I throw a warning.

**Comment by eraly** [comment]
Done and closing
https://github.com/deeplearning4j/nd4j/pull/1092
