### ISSUE TITLE
Transfer of DataSet.shuffle() to native code

### ISSUE THREAD

**Issue by mjakobus** [deeplearning4j/nd4j#1078]
I just noticed, that DataSet.shuffle() has a major drawback on performance when using the cuda backend. While the performance impact of shuffle when using the native backend is just minor.

**Comment by agibsonccc** [comment]
Interesting. You have a point here, we have a TAD implementation in c++ now so it shouldn't be that bad to add.

**Comment by eraly** [comment]
https://github.com/deeplearning4j/nd4j/issues/537
This issue filed by @LostSummer23 has some notes on shuffle. Consolidating here and closing older issue.

```
This method does not give a shuffle evenly.
If we view an ndarray as a list of vectors, then a vector with small index in the original list is more likely to have a small index in the new list after the shuffle, and so does a vector with large index.

The thing is that, in this method, every time after we swap the places of two vectors, we need to renew the value of the new index in 'vectorsAlongDimension', too.
```

**Comment by raver119** [comment]
I have this planned for next release as specialOp, since DataSet shuffle isn't actually an INDArray shuffle:

We have 4 n-dim arrays: features, labels, featuresMask, labelsMask, and shuffle should be symmetric.

**Comment by raver119** [comment]
https://github.com/deeplearning4j/libnd4j/pull/253

WIll be merged a bit later though.
