### ISSUE TITLE
Add Spark version of BalanceMinibatches

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1082]
https://github.com/deeplearning4j/nd4j/blob/77730aa8f657ef703564ede7bdd2817df1ba1a1f/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/BalanceMinibatches.java

This is good, but it would also be nice to have equivalent functionality that can be executed on Spark.

**Comment by huitseeker** [comment]
Scaffolding developed in `HashingBalancedPartitioner` here:
https://github.com/deeplearning4j/deeplearning4j/pull/3213
— the functionality for using element classes (in the context of this issue, labels) is not exercised yet.

**Comment by AlexDBlack** [comment]
I'll close this. It's functionality that will be better suited for datavec, post rewrite.
