### ISSUE TITLE
CUDA errors running LenetMnistExample

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/nd4j#1089]
Errors:
https://gist.github.com/Treiblesschorle/0bab9b5816e739d2c5dda23f1801a0d6

Java:
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

OS:
Windows 10 x86_64

CUDA:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Tue_Aug_11_14:49:10_CDT_2015
Cuda compilation tools, release 7.5, V7.5.17

GPU:
GTX 1080
Driver Version 368.25

POM:
https://gist.github.com/Treiblesschorle/0ecfe19d927ec763b8278a97505a2134

**Comment by raver119** [comment]
Pascal GPUs require CUDA 8. CUDA 7.5 do not support Pascal generation, and won't support it ever. Nvidia never provided forward/backward support for new architectures.
