### ISSUE TITLE
Error in transposei()

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#109]
I found the following error, using the latest nd4j version, workaround is using the normal tranpose();

Demonstration code:	
INDArray matrixtest = Nd4j.rand(3,5);
System.out.println("matrixtest: "+matrixtest.shape()[0]+"|"+matrixtest.shape()[1]);
matrixtest.transposei();
System.out.println("matrixtest: "+matrixtest.shape()[0]+"|"+matrixtest.shape()[1]);
matrixtest = matrixtest.transpose();
System.out.println("matrixtest: "+matrixtest.shape()[0]+"|"+matrixtest.shape()[1]);

Output:
matrixtest: 3|5
matrixtest: 3|5
matrixtest: 5|3

**Comment by agibsonccc** [comment]
Transposed is fixed in the bugfixes branch.
