### ISSUE TITLE
Potential broadcasting bug

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4j#1101]
I've been trying to broadcast a 6x5 INDArray to a 3x6x5 INDArray.
Unfortunately what I get is a 6x6x5 INDArray. 

Here is a link to the gist for the code I am using :
https://gist.github.com/rahulpalamuttam/917e6bb6a0418f45e0911d2953439128

If you run the snippet will show you a list of size 6x6x5 instead of 3x6x5.

**Comment by agibsonccc** [comment]
We fixed this a while back.
