### ISSUE TITLE
Problems with matrices with more than Integer.MAX_VALUE cells

### ISSUE THREAD

**Issue by andrewclegg** [deeplearning4j/nd4j#1107]
In WordVectorSerializer:

https://gist.github.com/andrewclegg/fb8ce3ee5ed1cd041475b5dfc036714d

and in BasicModelUtils:

https://gist.github.com/andrewclegg/c490625a7fc7878616720d80dfc28596

**Comment by raver119** [comment]
Ah yes, that's the same issue, except of w2v clearNans() calls, which should be removed.

**Comment by raver119** [comment]
Fixed.
