### ISSUE TITLE
Interval slicing of a column vector throws ArrayIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by mbabadi** [deeplearning4j/nd4j#1108]
Here's a test:

    @Test
    public void testVectorSlice() {
        final INDArray arr = Nd4j.linspace(1, 5, 5);
        System.out.println(arr.get(NDArrayIndex.interval(0, 2))); /* works fine */
        System.out.println(arr.transpose().get(NDArrayIndex.interval(0, 2))); /* throws exception */
    }

**Comment by mbabadi** [comment]
(on 0.4-rc3.10)

**Comment by mbabadi** [comment]
related to issue #1099

**Comment by eraly** [comment]
Fix in master. Closing. Thanks guys.
