### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by akhodakivskiy** [deeplearning4j/nd4j#1120]
I'm seeing weird performance issues.

Training code: https://gist.github.com/akhodakivskiy/2459ccf93566b8f2950257c090ff3864

It uses custom caching layer: https://gist.github.com/akhodakivskiy/0bb4639f7a8936f7e8eb48050b283f9d

Some screenshots: http://imgur.com/a/ldoMz

I'm using CUDA backend running on GTX 980 4g. Data set it split between 500 files containing 1m samples with 500 features. 

I'm seeing that training the first epoch takes 20 minutes, and after this it takes ~ 20 seconds per epoch once all the data is cached in RAM.

Please let me know of you need more details

**Comment by treo** [comment]
From the hotspot screenshot, you are seeing 2 GC Threads, which show up, but are mostly asleep. The next two runner ups, are AsyncDataIterator.next and Text.toDouble. This is where most of the time is spent. 

Going by the thread usage, I would guess that something forces synchronization along the way, so even the AsyncDataSetIterator isn't able to help here. 

Can you run this again, with ignores for `org.bytedeco.javacpp.*` and `org.nd4j.jita.allocator.impl.*` (you can set that up in the settings panel) and get some more screenshots from the Hotspots and their call trees?

**Comment by raver119** [comment]
@akhodakivskiy could you please post your text->features conversion? Reasonable suspect is there, since you say after first epoch is finished - everything works faster. 

For the first sight, the only thing that changes after first epoch is your cache becomes active.

**Comment by akhodakivskiy** [comment]
@treo Will be checking this shortly

@raver119: Text to features conversion is handled entirely by CSVRecordReader/RecordReaderDataSetIterator.

@AlexDBlack: https://gist.github.com/akhodakivskiy/417810031c53284be05169e7d0c72942
Which leads me to blame AsyncDataSetIterator. Note that training scores also differ in the version that uses AsyncDataSetIterator. Is this because it doesn't guarantee the order of batches?

**Comment by akhodakivskiy** [comment]
All in all I think it takes much more time to parse the data set from CSV files rather than fit the model - at least with my model/data/hardware combination.

**Comment by akhodakivskiy** [comment]
@AlexDBlack, @raver119, @treo  - ignore my comment about differing scores. It's due to bad application of the normalizing DataSetPreProcessor. My CachingDataSetIterator did not apply it properly. Scores in all cases are as they look in the 3rd case - with the AsyncDataSetIterator.

I think there is no bug. It just takes forever to read and parse data from CSV files. Doing this on every epoch is definitely not the best idea.
