### ISSUE TITLE
Assign (Set transform) with different array shapes slow

### ISSUE THREAD

**Issue by Jajawah** [deeplearning4j/nd4j#1132]
Still me, after #1128 
The bug is fixed, but now the reshape is very slow...

```
 INDArray a = Nd4j.linspace(0,1000 , 100000000).reshape(new int[] { 1000,1000,100 });
        a.permutei(0,2,1);
        INDArray b = a.dup();

        int[] newShape = new int[] { 500, 2000 ,100 };
        long startTime = System.nanoTime();
        a = a.reshape(newShape);
        System.out.println(String.format("%.3f s", (System.nanoTime() - startTime) / 1000000000.));
        startTime = System.nanoTime();
        b = b.reshape(newShape);
        System.out.println(String.format("%.3f s", (System.nanoTime() - startTime) / 1000000000.));
```

I get an execution time greater than 10 sec on original permuted array and ~ 0 sec on duplicate...

**Comment by eraly** [comment]
Yes. This makes sense. You will take a hit because of what happens under the hood when you do a permute in place. If you did b = a.permute(0,2,1) and did b.reshape(newShape) you will not take a hit. Any thoughts on this?

**Comment by AlexDBlack** [comment]
Confirming this as a problem.

Modified version of the above that I'm running:
```java
        INDArray a = Nd4j.zeros(1000, 1000, 100).permutei(0, 2, 1);

        long startDup = System.nanoTime();
        a.dup();
        System.out.println(String.format("Dup time: %.3f s", (System.nanoTime() - startDup) / 1000000000.));

        int[] newShape = new int[]{500, 2000, 100};
        long startTime = System.nanoTime();
        a = a.reshape(newShape);
        System.out.println(String.format("A Reshape: %.3f s", (System.nanoTime() - startTime) / 1000000000.));

        startTime = System.nanoTime();
        a.dup().reshape(newShape);
        System.out.println(String.format("A Dup Reshape: %.3f s", (System.nanoTime() - startTime) / 1000000000.));
```

0.4.1-SNAPSHOT (nd4j master, nd4j-native backend):
Dup time: 0.099 s
A Reshape: 0.654 s
A Dup Reshape: 0.075 s

That's on a 5960x (8 core + HT); way faster than what you are seeing, but still 6-8x slower than expected (I expect the "A Reshape" and "A Dup Reshape" to be about the same).
@Jajawah mind posting OS and hardware specs? Also: Doubt your hardware is >10x slower than mine. So something else might be up there.

**Comment by AlexDBlack** [comment]
What is happening here: reshape (can't do in-place) -> BaseNDArray.assign -> Set transform

https://github.com/deeplearning4j/nd4j/blob/b017281653dd0f37a826c6aed5d33480299defc6/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L3374

https://github.com/deeplearning4j/nd4j/blob/b017281653dd0f37a826c6aed5d33480299defc6/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L1102

Problem here is ultimately a problem with the Set transform op.
Specifically, we are hitting the "assign with different shapes" special case in there; looks like a performance issue with the libnd4j set transform code for that special case.

**Comment by raver119** [comment]
Which backend we're speaking about right now?

**Comment by AlexDBlack** [comment]
@raver119 Only tested on native; would be good to test on cuda too.
Should get about the same time for dup and assign here:

```java
    public static void main(String[] args){
        INDArray a = Nd4j.linspace(0,1000 , 100000000).reshape(1000, 1000, 100).permutei(0, 2, 1);

        long startDup = System.nanoTime();
        INDArray a2 = a.dup().reshape(500, 2000, 100);
        System.out.println(String.format("Dup time: %.3f s", (System.nanoTime() - startDup) / 1000000000.));

        int[] newShape = new int[]{500, 2000, 100};
        long startTime = System.nanoTime();
        INDArray b = Nd4j.createUninitialized(newShape, 'c').assign(a);
        System.out.println(String.format("Assign: %.3f s", (System.nanoTime() - startTime) / 1000000000.));

        if(!a2.equals(b)) throw new RuntimeException();
        System.out.println("done");
    }
```

**Comment by Jajawah** [comment]
@AlexDBlack currently I have an old I7-Q840, running Ubuntu 16.04.
In two weeks, after my vacations, I will have an E3-1545M with finally nvidia GPU

**Comment by raver119** [comment]
@AlexDBlack i'm afraid that CUDA dup time isn't viable for tests. I've added hack there long ago, and it's using it:

Dup time: 0.218 s
Assign: 0.157 s

**Comment by eraly** [comment]
I can look into CPU.
