### ISSUE TITLE
Optimize BaseNDArray.equals

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1133]
https://github.com/deeplearning4j/nd4j/blob/b017281653dd0f37a826c6aed5d33480299defc6/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L3854

Equals method uses the NDArrayIndex iterator + getDouble operations.
This could easy be optimized: for example, that component of the equals method could become a native operation (pairwise reduce), ideally with a short-circuit condition to exit on the first non-equal element.

**Comment by raver119** [comment]
I'll just make it a native op.

**Comment by raver119** [comment]
Hypothetically it's implemented here: https://github.com/deeplearning4j/nd4j/pull/1112

But reduce3 has some issues itself, both on CUDA and CPU: https://github.com/deeplearning4j/nd4j/issues/1135

Some of them i've already fixed, but still not there yet.
