### ISSUE TITLE
Iterate over all row to get specific indexes

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/nd4j#1136]
You have a tensor of indexes A of shape (M, 1).
a tensor containing your values of shape (M, N).
you want to iterate over all rows to get the element at the specified column and get a tensor of shape (M, 1)

@agibsonccc proposed this but it doesn't work actually.

    Nd4j.zeros(10, 20).get(NDArrayIndex.all(),new SpecifiedIndex(Nd4j.zeros(10).data().asInt()));

**Comment by eraly** [comment]
You can do this. It works but maybe later we can try to think of a more 'elegant' solution.
All I am doing is flattening the array and indexing out linearly.

m is of shape (M,1)
mn is of shape (M,N)

If you want to grab from columns instead of rows, switch the size(0/1) to size(1/0)
```
        INDArray these_indexes = Nd4j.linspace(0,m.size(0)-1,m.size(0)).mul(mn.size(1)).add(m.transpose());
        INDArray result = Nd4j.toFlattened(mn).get(new SpecifiedIndex(these_indexes.data().asInt())).transpose();
```
