### ISSUE TITLE
Can't compile the ND4J project using Maven 

### ISSUE THREAD

**Issue by nsiddiqui17** [deeplearning4j/nd4j#1143]
When I run (mvn clean install -DskipTests -Dmaven.javadoc.skip=true) in my nd4j directory after cloning the repository, I get a build failure that tells me that the files: (/home/hadoop/nd4j_7.20.2016/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/pwd/blas/NativeBlas.h) and (/home/hadoop/nd4j_7.20.2016/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/pwd/blasbuild/cpu/blas) are missing. 
I can't find the pwd directory inside nd4j-native.

**Comment by raver119** [comment]
That's because instead of "pwd", there should be valid path set to LIBND4J_HOME environment variable

**Comment by raver119** [comment]
P.s. here's instructions to build libnd4j on windows: https://github.com/deeplearning4j/libnd4j/blob/master/windows.md

and on linux: https://github.com/deeplearning4j/libnd4j/blob/master/README.md
