### ISSUE TITLE
Matrix inverse bug

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4j#1148]
I recently upgraded to 0.4.0 and for some reason the matrix inverse function isn't working quite as it should.
I've uploaded a gist [here](https://gist.github.com/rahulpalamuttam/81b94dbeb7875ace028c560cbe806684).

**Comment by rahulpalamuttam** [comment]
Another point to note is that it looks like the MatrixInverse tests have an @Ignore annotation on them
https://github.com/deeplearning4j/nd4j/blob/cf9fe733ace449bc797fb6b25879d8e5aa1683f1/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/inverse/TestInvertMatrices.java

**Comment by eraly** [comment]
So, I am thinking we don't support inverting matrices.

**Comment by eraly** [comment]
Yes. That was before we released the native backend. @agibsonccc ?

**Comment by agibsonccc** [comment]
Use commons-math for now. We need to get lapack in ther. Lapack is a little 1 off for us atm to focus on though :(

**Comment by agibsonccc** [comment]
I'd be fine with that.

**Comment by eraly** [comment]
So we now have a placeholder that uses commons math. Will sort out lapack etc etc for a later release.

**Comment by rahulpalamuttam** [comment]
Sounds good.
From what I see in checkUtils when you convert to RealMatrix it does involve a copy of the matrix right?
Thank you

**Comment by eraly** [comment]
Yeah. It honors the inplace flag.
