### ISSUE TITLE
CUDA: Run time query capabilities for storage

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#116]
Query the device to see what kind of memory model it supports. If it doesn't support memory mapped/host alloced, fall back to naive. To do this, I will create an allocation strategy. The allocation strategy will handle actually allocating memory for the gpu relative to what the compute capabilities are.

@EronWright Any thoughts on generalizing this? Perhaps for opencl? There's an interesting idea here. Since this won't be user facing I'm not afraid of doing some fun stuff with this.

**Comment by EronWright** [comment]
@agibsonccc My first thought is something akin to the OpenCL ICD; a vendor-specific module to supply implementations tailored to device capabilities.

Short of full-blown extensibility within the opencl backend, I suppose you'll extend the nd4j.properties with an allocation strategy class.   The OpenCL strategy would be to use device caps to adapt to the supported memory model.

**Comment by agibsonccc** [comment]
Yeah this makes sense. I'll add the memory management interface as part of the core nd4j interface and only people who need it can implement it. I'll leave the concrete strategies for each backend.

**Comment by agibsonccc** [comment]
Also going to add per device configurations. For now this will just include allocation strategies but there's other room for improvements.

**Comment by agibsonccc** [comment]
I've did a basic pass on this. It now will query for support for host allocation.
