### ISSUE TITLE
DataSet: remove columnNames field

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1174]
https://github.com/deeplearning4j/nd4j/blob/2e14432c843e4ad49d2b92015924219ec1e4ac2b/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/DataSet.java#L60

AFAIK the column Names field isn't used anywhere, and might as well be removed.

**Comment by eraly** [comment]
Deprecated. Will delete in the release after 0.0.5
