### ISSUE TITLE
DataSet.asList: assumes features and labels are the same rank

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1175]
https://github.com/deeplearning4j/nd4j/blob/2e14432c843e4ad49d2b92015924219ec1e4ac2b/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/DataSet.java#L884

In general, features and labels may be different rank, and should be handled separately.

**Comment by eraly** [comment]
https://github.com/deeplearning4j/nd4j/pull/1176

**Comment by lgp66** [comment]
One issue with the way features and labels are treated inside DataSet.merge() ...
There are two switch statements that separately process the features and the labels. The second of these appears to have a bug for the labels under the case where rank = 4. Current line 230 looks like this:
`labelsOut = merge4dCnnData(featuresToMerge);`
when it looks like it really should be
`labelsOut = merge4dCnnData(labelsToMerge);`
This later leads to errors when training a CNN.

**Comment by lgp66** [comment]
Sorry, only just realised this was closed. Will raise in a new issue.
