### ISSUE TITLE
NormalizeStandardize boken

### ISSUE THREAD

**Issue by akhodakivskiy** [deeplearning4j/nd4j#1180]
NormalizeStandardize seems to be broken now. 

There are now 6 state variables: 

    private INDArray featureMeanStd, labelMeanStd;
    private INDArray featureMean, featureStd, labelMean, labelStd;

But `save`/`load` only deal 2 of them:

    public void save(File...statistics) throws IOException {
        Nd4j.saveBinary(this.featureMean,statistics[0]);
        Nd4j.saveBinary(this.featureStd,statistics[1]);
    }

    public void load(File...statistics) throws IOException {
        this.featureMean = Nd4j.readBinary(statistics[0]);
        this.featureStd = Nd4j.readBinary(statistics[1]);
    }

Running such instance that was not 'fit' but 'load'ed results in this error:

```
Caused by: java.lang.RuntimeException: API_USE_ERROR: Preprocessors have to be explicitly fit before use. Usage: .fit(dataset) or .fit(datasetiterator)
        at org.nd4j.linalg.dataset.api.preprocessor.NormalizerStandardize.preProcess(NormalizerStandardize.java:160)
```

**Comment by eraly** [comment]
Thanks Anton!
