### ISSUE TITLE
Problems using GPU (code=4)

### ISSUE THREAD

**Issue by Jydago** [deeplearning4j/nd4j#1183]
Getting errors when trying to train new networks using GPU.
I am working on windows 10, Java1.8, Nd4j 0.5.0, Cuda 7.5.18 (though nvcc says 7.5.17).
Currently working with floats, I have converted all of my data using BalanceMiniBatches (also in floats).
Fitted NormalizerMinMaxScaler and transformed all the data.
Each input example are in the shape of [1, 1, 60, 50].
They are batched into batches of 128, though I rebatch them when I load them to train my network, to get a good split for train and validation data.

The network config is just conv(36) -> pool -> Output(2).
Using learnRate = 6e-5, l1 = 0e-7, l2 = 2e-6, momRate = 0.9

Error stack: https://gist.github.com/Jydago/4ad832b43fa1d4f8d0212ff8adc634bb

Error stack with debug: https://gist.github.com/Jydago/32627d21e25bced6f7379a8c5b2d6e70
The start of the error stack with debug is just an endless wall of the same as the beginning of the gist.

**Comment by Jydago** [comment]
Strange, the code works iff batch size is set to 2

**Comment by AlexDBlack** [comment]
Closing this - obsolete (about version 0.5.0)
