### ISSUE TITLE
Optimize boolean conditions (make native/c++)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1186]
https://github.com/deeplearning4j/nd4j/blob/cf9fe733ace449bc797fb6b25879d8e5aa1683f1/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/BooleanIndexing.java#L124

BooleanConditions.applyWhere: this still relies on Java loops.
Wherever possible, this should use native c++ code. This won't be possible in all cases, but it should be possible for frequently used (i.e., built-in) conditiotns and functions.

**Comment by raver119** [comment]
Already implemented/merged
