### ISSUE TITLE
Commons Random generator is very slow 

### ISSUE THREAD

**Issue by fac2003** [deeplearning4j/nd4j#1202]
When using dropConnect with DL4J, the apache commons random generator is used and accounts for 35-36% of the time of training:

I replaced the default random class with one using 
<img width="956" alt="cursor_and_trainsomaticmodel__5__-_jprofiler_9_1_1" src="https://cloud.githubusercontent.com/assets/1728407/17494410/8a8e6136-5d82-11e6-8255-163e74bdfd82.png">
http://dsiutils.di.unimi.it/docs/it/unimi/dsi/util/XoRoShiRo128PlusRandom.html

```
<dependency>
            <groupId>it.unimi.dsi</groupId>
            <artifactId>dsiutils</artifactId>
            <version>2.3.3</version>
</dependency>
```
I found that this overhead was mostly eliminated. The next bottleneck is in BinomialDistribution.sample (now 45% of time for training with dropConnect).

<img width="1293" alt="cursor_and_trainsomaticmodel__4__-_jprofiler_9_1_1_and_nd4j-native_properties_-_variation_-____ideaprojects_git_variationanalysis_" src="https://cloud.githubusercontent.com/assets/1728407/17494334/4bfadb5c-5d82-11e6-843f-5159a6f3b264.png">
 
Now this seems a lot of time considering that binomial or a uniform distribution give approximately the same results in practice as far as I know.

**Comment by AlexDBlack** [comment]
We did move the dropout implementation to native (c++) code for performance reasons.
We should be able to do the same for dropconnect.
cc @raver119

**Comment by fac2003** [comment]
C++ won't help if you don't use a state of the art random generator. The one I suggested is hard to beat in any language.

**Comment by AlexDBlack** [comment]
Sure. Though parallel generation + avoiding put operations from Java (which can be costly due to synchronization on GPUs) with a good RNG implementation will be best option here I think.

**Comment by raver119** [comment]
We already have native implementation suitable for dropConnect, and as discussed with @AlexDBlack it will be enabled right now.

**Comment by raver119** [comment]
P.s. thanks for flagging this issue. We've just forgot that we already have available nativeOp for that functionality.

**Comment by fac2003** [comment]
I am updating this issue with performance information on 0.7.0.

I can confirm the speed improvement for dropout in 0.7.0 on GPU when the dataset is very small, but see a huge penalty when training with thousands of minibatches:

# Training with one minibatch per epoch:
**0.7.0 without dropout:**

11:57:03.177 [main] INFO  o.c.dl.framework.tools.TrainModel - 3 epoch, 12s, 15.01 epoch/m, 4.00 s/epoch [15.01 epoch/m, 4.00 s/epoch]; 0% done, 1788973h 10m 48s to end
11:57:16.384 [main] INFO  o.c.dl.framework.tools.TrainModel - 7 epoch, 25s, 16.64 epoch/m, 3.60 s/epoch [18.13 epoch/m, **3.31 s/epoch**]; 0% done, 1881657h 58m 26s to end

**0.7.0, dropout-rate 0.15**

11:56:11.062 [main] INFO  o.c.dl.framework.tools.TrainModel - 2 epoch, 12s, 9.37 epoch/m, 6.41 s/epoch [9.37 epoch/m, 6.41 s/epoch]; 0% done, 2547154h 12m 44s to end
11:56:22.518 [main] INFO  o.c.dl.framework.tools.TrainModel - 4 epoch, 24s, 9.89 epoch/m, 6.07 s/epoch [10.47 epoch/m, **5.73 s/epoch**]; 0% done, 2895523h 46m 43s to end
without dropout:

This performance is much better than 0.6.0  where we saw dropout 4 times slower on GPU.

# Training with many minibatches per epoch:
0.7.0. Training with 2765 minibatches per epoch

**With dropout, full dataset, 0.15: -- 0.96% GPU utilization**
12:03:38.713 [main] INFO  o.c.dl.framework.tools.TrainModel - 2,048 mini-batch, 5m 39s, 6.04 mini-batch/s, 165.67 ms/mini-batch; 74% done, 1m 58s to end
12:05:40.904 [main] INFO  o.c.dl.framework.tools.TrainModel - 1 epoch, 7m 41s, 7.80 epoch/h, 7.69 m/epoch [7.80 epoch/h, **7.69 m/epoch**]; 0% done, 137644753h 51m 36s to end

**No dropout, full dataset: 44% GPU utilization**
12:55:18.055 [main] INFO  o.c.dl.framework.tools.TrainModel - 2,048 mini-batch, 38s, 53.13 mini-batch/s, 18.82 ms/mini-batch; 74% done, 13s to end
12:55:34.114 [main] INFO  o.c.dl.framework.tools.TrainModel - 1 epoch, 54s, 1.10 epoch/m, 54.61 s/epoch [1.10 epoch/m, **54.61 s/epoch**]; 0% done, 16287470h 24m 30s to end

This is much worse than 0.6.0 on GPU.

**Comment by raver119** [comment]
Can you please file new issue, instead posting to old closed one? Also, please show NN configuration you've used.
