### ISSUE TITLE
Nd4j compression

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1209]
As requested/described here: https://github.com/deeplearning4j/deeplearning4j/issues/1989

**Comment by raver119** [comment]
So, approximate plan is:

Single API entry point for compression/decompression over arrays
Extensible interface, suited for multiple possible conversion formats
Reflection to scan classpath for available compressors/decompressors

**Comment by rubenfiszel** [comment]
Compressing an DataBuffer should return a CompressedDataBuffer
Decompressing a CompressedDataBuffer should return a DataBuffer

Compressing an INDArray (which hold implictly a DataBuffer) should return a CompressedINDArray (holding implicitly a CompressedDataBuffer)
Decompressing a CompressedINDArray should return an INDArray.

**Comment by raver119** [comment]
CompressedINDArray implementation will make effectively impossible transparent decompression. Or at least i don't see the way for it to happen.

Ideal place for transparent compression is "first use" scenario: hooks in OpExecutioner, BlasLevels + put/get methods. But if we'll try to transparently create new decompressed INDArray instance, we have guarantees to break links within JVM. 

So, INDArray should be decompressed inplace, without objects replacement.

**Comment by saudet** [comment]
What about some conversion method that would reset an existing NDArray to
be able to reuse objects? That's basically what OpenCV does in
Mat.convertTo() to convert between different data types without having to
reallocate memory and it works well.

**Comment by raver119** [comment]
Yea, we definitely might use generic types conversion as separate native op set. We have it for fp16 now, but i think there should be something more generic.

But i don't see happening it on the same memory chunk: if you have fp8/uint8 array, it'll obv. require bigger chunk if you want that array as fp32/64. So i'm sure its bounded to be 2-param ops: op.X, op.Z

**Comment by raver119** [comment]
Native types convertion was added as separate op call.

However, on cuda i don't see any sense for compression/decompression using gpu - whole idea of compression is to minimize memory use. So, in compressed for only host memory is used for CUDA backend. And only upon decompression we get proper CudaDataBuffer, with GPU memory used.
