### ISSUE TITLE
Gradle does not import SerDe 

### ISSUE THREAD

**Issue by mbabadi** [deeplearning4j/nd4j#1219]
Here's the relevant part of my build.gradle:

> dependencies {
>     compile 'org.nd4j:nd4j-native-platform:0.5.0'
>     compile 'org.nd4j:nd4j-serde:0.5.0'
> }

However, I do not get `org.Nd4j.Nd4jRegistrator`. I had this issue since 0.4-rc3.8 and got around it by manually adding `Nd4jSerializer.java` and `Nd4jRegistrator.java` to my codebase.

**Comment by huitseeker** [comment]
Thanks for your report ! You seem to be using an old version of our software:
https://deeplearning4j.org/releasenotes
The latest version may not have that issue anymore, so we need to check we're not investing time in something that is already fixed. Can you please reproduce the problem using the latest version?

**Comment by mbabadi** [comment]
Hi! the issue is actually unrelated to nd4j build and resulted from my wrong gradle dependency wrong. Replacing `compile 'org.nd4j:nd4j-serde:<nd4j_version>' with `org.nd4j:nd4j-kryo_<scala_version>:<nd4j_version>' resolved the issue. Thanks for following up!
