### ISSUE TITLE
Nd4j argMax on (1, 1) INDArray

### ISSUE THREAD

**Issue by rubenfiszel** [deeplearning4j/nd4j#1226]
scala> val a = Nd4j.create(1)
a: org.nd4j.linalg.api.ndarray.INDArray = 0.00

scala> a.putScalar(0, 1.07)
res1: org.nd4j.linalg.api.ndarray.INDArray = 1.07

scala> Nd4j.argMax(a, Integer.MAX_VALUE)
res4: org.nd4j.linalg.api.ndarray.INDArray = 1.07

**Comment by raver119** [comment]
It looks like somehow max is used, instead of iamax. I'll take a look there

**Comment by raver119** [comment]
Fixed: https://github.com/deeplearning4j/nd4j/pull/1228
