### ISSUE TITLE
Tensors outer product is not easy

### ISSUE THREAD

**Issue by Jajawah** [deeplearning4j/nd4j#1229]
-----------------------------------------

I want to get the outer product between tensors with different shapes.
I give here a representative example of what I want, with Numpy.

```
import numpy as np
a= np.linspace(1,2,12).reshape((2,3,2))
b= np.linspace(3,4,4).reshape((2,2))
b=b.reshape(2,1,2)
result=a*b
print(result)
```
I get
```
[[[ 3.          3.63636364]
  [ 3.54545455  4.24242424]
  [ 4.09090909  4.84848485]]

 [[ 5.66666667  6.54545455]
  [ 6.33333333  7.27272727]
  [ 7.          8.        ]]]
```

If I "translate" this code into java with ND4j
```
INDArray a= Nd4j.linspace(1,2,12).reshape(2,3,2);
INDArray b= Nd4j.linspace(3,4,4).reshape(2,2);
b=b.reshape(2,1,2);
a.muli(b);
System.out.println(a);
```
I get
```
Exception in thread "main" java.lang.IllegalStateException: Mis matched lengths: [4] != [12]
```

Fine, I need to call the broadcast by myself.
```
INDArray a= Nd4j.linspace(1,2,12).reshape(2,3,2);
INDArray b= Nd4j.linspace(3,4,4).reshape(2,2);
b=b.reshape(2,1,2).broadcast(2,3,2);
a.muli(b);
System.out.println(a);
```
I get
```
[[[3.00, 3.27],
  [3.55, 4.24],
  [4.55, 4.85]],

 [[5.67, 6.00],
  [6.33, 7.27],
  [7.64, 8.00]]]
```
Not ok. I check the code, the broadcast func is not the solution. #994 #1101

So I do the broadcast by myself :
```
INDArray a= Nd4j.linspace(1,2,12).reshape(2,3,2);
INDArray b= Nd4j.linspace(3,4,4).reshape(2,2);
b=Nd4j.concat(0,b,b,b);
a.permutei(1,0,2).muli(b).permutei(1,0,2);
System.out.println(a);
```
I get 
```
[[[3.00, 3.64],
  [3.55, 4.24],
  [4.09, 4.85]],

 [[5.67, 6.55],
  [6.33, 7.27],
  [7.00, 8.00]]]
```
Works fine, but what about the perfs ?
```
Numpy : ~ 1.239776611328125e-05 s
ND4J: ~ 0.028957072 s
```
NB: I tried with bigger tensors, perfs are bad :/

An other way :
```
INDArray a= Nd4j.linspace(1,2,12).reshape(2,3,2);
INDArray b= Nd4j.linspace(3,4,4).reshape(2,2);
for(int i=0;i<a.tensorssAlongDimension(0,2);i++){
    a.tensorAlongDimension(i,0,2).muli(b);
}
System.out.println(a);
```
Works !... but perfs are worse, even with parallelisation.

So, what about the BroadcastMulOp. Since the first and third dims of a are matching the dims of b,
```
INDArray a= Nd4j.linspace(1,2,12).reshape(2,3,2);
INDArray b= Nd4j.linspace(3,4,4).reshape(2,2);
Nd4j.getExecutioner().exec(new BroadcastMulOp(a, b, a, new int[]{0,2}));
System.out.println(a);
```
I get

```
[[[ 3.00,  3.64],
  [13.00, 16.97],
  [15.00, 19.39]],

 [[ 5.67,  6.55],
  [ 1.73,  1.82],
  [ 1.91,  2.00]]]
```
Wrong !

Let's do it work :
```
INDArray a= Nd4j.linspace(1,2,12).reshape(2,3,2);
INDArray b= Nd4j.linspace(3,4,4).reshape(2,2);
a=a.permute(0,2,1).reshape(4,3);
Nd4j.getExecutioner().exec(new BroadcastMulOp(a, b, a, new int[]{0}));
a=a.reshape(2,2,3).permute(0,2,1);
System.out.println(a);
```
yes ! but the perfs... #1132

I have done several benchmarks with these 3 last working implementations. Depending on size of tensors, common dims etc... That is never the same implementation that performs the better !
Cuda is a little faster than native
Numpy is at less 10 time faster than my ND4j implementations.

So any ideas ? Is BroadcastMulOp supposed to work with tensors of order greater than 2 ?

**Comment by agibsonccc** [comment]
We have Nd4j.tensorMmul FYI.

Either way you really shouldn't be using for loops. We do everything in c++ like they do. On a lot of things we're faster.

**Comment by Jajawah** [comment]
I'll take a look on tensorMmul, don't know how it works and already find a bug :/

Yes I know about the loop, it's just for demo purpose.

**Comment by agibsonccc** [comment]
Itd similar to np.tensordot. Could you be less vague about finding a bug
though? That doesnt help either of us.

**Comment by Jajawah** [comment]
sure, I was writing #1230

**Comment by agibsonccc** [comment]
Thanks!

**Comment by Jajawah** [comment]
btw, tensordot is inner product, I want an outer, without summation

**Comment by agibsonccc** [comment]
Yeah just saw that sorry about that misread :(.

**Comment by eraly** [comment]
@Jajawah 

Yeah - this is something we are thinking about. Maybe add a couple more ops that will make life easier regarding slice operations with rank >2. 

So this gives better timing. I am seeing a really big jump and it would be kind what would happen under the hood anyway minus the call to the native code and bundled together.

        a= Nd4j.linspace(1,2,j*m*k).reshape(j,m,k);
        b= Nd4j.linspace(3,4,j*k).reshape(j,k);
        myb = b.repeat(0,new int[] {m}).reshape(a.shape());
        a.muli(myb);

I repeat values along the dimension and so no more broadcast. It ends up as the same thing as the concat in your post but takes the number of repeats as an argument.

Since we have another issue open on performance and another one for broadcast I am closing this.
Thanks!

**Comment by Jajawah** [comment]
@eraly 

I test repeat() on big tensors, and the perfs are slow. I guess repeat() is doing an hard copy, while I need only to simulate the shape to do the product.

Otherwise, I think that BroadcastMulOp is the answer to my issue, but when I run ```Nd4j.getExecutioner().exec(new BroadcastMulOp(a, b, a, new int[]{0,2}));``` I get odd results, as if the b tensor was multiplied by himself...

**Comment by eraly** [comment]
I agree. The BroadcastMulOp would be great here...
