### ISSUE TITLE
Adadelta issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1239]
Two issues here:
First, the implementation at lines 72 and 73: appears to differ from the paper
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/learning/AdaDelta.java#L73
Looks like we are doing ```(rho * E[g2] +(1-rho))*g^2``` instead of ```rho * E[g2] +(1-rho)*g^2```

Second, the adadelta epsilon value is hard-coded. This should be configurable, from within DL4J

Also: Adagrad epsilon is hard-coded (not settable from DL4J).

**Comment by mjakobus** [comment]
For documentation

Adapted MLPClassifierMoon Example:
https://gist.github.com/mjakobus/74739ffb8fff645bd6c1121eec76b626

And the output:
https://gist.github.com/mjakobus/f5564904c353ef907998458614b28d13

@treo found out, that it is working if rho is not set or set to 1.

**Comment by AlexDBlack** [comment]
Also: add some better tests. At the very least, some sanity checks along the lines of "doesn't converge to NaN, infinity or 0 with sensible input"; also look at the math and test what it should coverge to with fixed input at each iteration.

**Comment by mjakobus** [comment]
I just compared the math of the dl4j adadelta to the math of adadelta in convnet.js, where adadelta is my favorite updater when playing around ;) 

dl4j:
```
// modifiedGradient = sqrt(modifiedGradient^2)_t-1 / sqrt(avgSquaredRawGradient^2)_t * rawGradient
INDArray ret = gradient.muli(Transforms.sqrt(msdx.add(Nd4j.EPS_THRESHOLD), false).divi(Transforms.sqrt(msg.add(Nd4j.EPS_THRESHOLD), false))); 
```

Convnet.js
`var dx = - Math.sqrt((xsumi[j] + this.eps)/(gsumi[j] + this.eps)) * gij;`

Not that, the division the is happening inside the squareroot. That seems to be different from the to divided square roots in dl4j.

**Comment by AlexDBlack** [comment]
Fix for the adadelta implementation: https://github.com/deeplearning4j/nd4j/pull/1240/files
Would be good to have someone review this.

As for the convnetjs implementation:
https://github.com/karpathy/convnetjs/blob/5c653cb15a53c3361a6cf21c7277de941ff05352/src/convnet_trainers.js#L117
It's definitely doing sqrt((E[dx^2_{t-1}]+eps)/(E[g^2]+eps)) not sqrt(...)/sqrt(...) as is in the adadelta paper. Looks like a bug in the convnetjs implementation?

Still have the epsilon stuff to do yet.

On MLPClassifierMoon: results seem sensible, but not as good as momentum.
https://gist.github.com/AlexDBlack/53313d296d1401c5e944bd587791f443

**Comment by AlexDBlack** [comment]
Fixed: https://github.com/deeplearning4j/nd4j/pull/1240
I checked with MLPClassifierMoon: seem to be getting sensible results there.
https://gist.github.com/AlexDBlack/07be3885aa2e5fd13fadcff0e4845c5f

As for the difference between this and convnetjs (sqrt issue): I'm going to go by the paper, not the convnetjs implementation (unless someone can give me a reason to do otherwise).
