### ISSUE TITLE
Windox CUDA issue

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#126]
CUDA backend on windows throws exception on app startup:

Thats latest nd4j sources

09:57:48,891 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
09:57:48,891 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
09:57:48,891 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/C:/develop/HiveNeurality/lib/deeplearning4j-core-0.0.3.3.3.alpha1.jar!/logback.xml]
09:57:48,893 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
09:57:48,893 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/develop/HiveNeurality/lib/nd4j-api-0.0.3.5.5.4-SNAPSHOT.jar!/logback.xml]
09:57:48,893 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/C:/develop/HiveNeurality/lib/deeplearning4j-core-0.0.3.3.3.alpha1.jar!/logback.xml]
09:57:48,912 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@55a561cf - URL [jar:file:/C:/develop/HiveNeurality/lib/deeplearning4j-core-0.0.3.3.3.alpha1.jar!/logback.xml] is not of type file
09:57:49,007 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
09:57:49,014 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.FileAppender]
09:57:49,020 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FILE]
09:57:49,058 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:57:49,115 |-INFO in ch.qos.logback.core.FileAppender[FILE] - File property is set to [logs/application.log]
09:57:49,117 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
09:57:49,118 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
09:57:49,121 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
09:57:49,125 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.apache.catalina.core] to DEBUG
09:57:49,125 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.springframework] to DEBUG
09:57:49,125 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [org.deeplearning4j] to INFO
09:57:49,125 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
09:57:49,125 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
09:57:49,126 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FILE] to Logger[ROOT]
09:57:49,126 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
09:57:49,128 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@3b938003 - Registering current configuration as safe fallback point

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.deeplearning4j.models.embeddings.inmemory.InMemoryLookupTable$Builder.<init>(InMemoryLookupTable.java:568)
	at org.deeplearning4j.models.word2vec.Word2Vec$Builder.build(Word2Vec.java:634)
	at org.hive.cloud.neurality.tools.Word2Vec.WordToVectors.main(WordToVectors.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Please ensure cuda is installed and nvcc is in the path.
	at org.nd4j.linalg.jcublas.JCublasBackend.isAvailable(JCublasBackend.java:50)
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:104)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:3332)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:130)
	... 8 more
Caused by: java.lang.IllegalStateException: Please ensure cuda is installed and nvcc is in the path.
	at org.nd4j.linalg.jcublas.JCublasBackend.isAvailable(JCublasBackend.java:47)
	... 11 more

Process finished with exit code 1

**Comment by raver119** [comment]
Actual path generated by System.out.println(System.getenv("PATH")):

C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.0\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin

**Comment by raver119** [comment]
JCublasBackend:

 public boolean canRun() {
        return Paths.nameExistsInPath("nvcc");
    }

but Paths.nameExistsInPath looks for equal name, however there's no "nvcc" under windows, only "nvcc.exe"

**Comment by agibsonccc** [comment]
This has been fixed in master.
