### ISSUE TITLE
Add version of NormalizerStandardize with convolution property

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1262]
Current NormalizerStandardize: considers each value separately.
When doing images, we may want to do normalization along depth: i.e., calculate means and standard deviations for each input channel using *all* pixels, not for each pixel separately.

**Comment by eraly** [comment]
Hi Alex, Not sure I follow what using all pixels means. When I modified NormalizerStandardize to take 4d I had it calculate the mean/std along depth across samples. So it treats the channels separately. 
I have some tests I wrote back then as well 
https://github.com/deeplearning4j/nd4j/blob/cfeac52d5d597083b93f11beeaa0b7c9c26416c1/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/dataset/NormalizerStandardize3D4DTest.java#L216

**Comment by eraly** [comment]
Closing
