### ISSUE TITLE
Add DataNormalizer.transform(INDArray)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1264]
We have: DataNormalization.transform(DataSet), but this can't be used at test time, as no DataSet is available. Being able to apply the normalier on a features array only is required.

https://github.com/deeplearning4j/nd4j/blob/898e8e8e85030a61f5f93cbda480c10299f49e94/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/preprocessor/DataNormalization.java#L39

**Comment by eraly** [comment]
I'll add it to the interface.The minmax and standardize preprocessor have a transform(indarray features) method but the imagepreprocessor is missing it.

**Comment by eraly** [comment]
Done.
