### ISSUE TITLE
Softmax derivative: row vector edge case bug

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1273]
The following (new) unit test is failing on nd4j-native:
https://github.com/deeplearning4j/nd4j/blob/cccd588b7ddf80e4a8cb3c29ee9bde78e955adb8/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/ops/DerivativeTests.java#L128

It appears that the operation is not being applied: i.e., failing at line 157, but only for the minibatch size = 1 case.

**Comment by raver119** [comment]
Fixed few days ago
