### ISSUE TITLE
Mismatched shapes when using NormalizerMinMaxScaler with 0.6.0

### ISSUE THREAD

**Issue by vzamboni** [deeplearning4j/nd4j#1286]
I'm executing this code (which was working fine in 0.5.0) to load my dataset: 
https://gist.github.com/vzamboni/2c1f354c5c51f6de18875bfb84b6ed18

 and i'm getting this exception: https://gist.github.com/vzamboni/ed6747cf69d2303f003a3b1ed4f7261c

**Comment by eraly** [comment]
@vzamboni Only the current master supports datasets with rank>2 for the minmax scaler. I am not sure how you got it to work earlier. My guess, is you were you using a dataset with feature rank = 2.

If you don't want to build from current master then you can use the imagepreprocessing  scaler which supports 4d in 0.6. It simply scales every element in the dataset based on the the values you give it when you create it.
https://github.com/deeplearning4j/nd4j/blob/5d69719a03141688baf6e80001ea892d3d7feebe/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/preprocessor/ImagePreProcessingScaler.java#L42

**Comment by eraly** [comment]
Closing.
