### ISSUE TITLE
CUDA tests crash on CI

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1312]
According to @saudet report, there's an issue with nd4j-tests at CI server, however not reproducible via local nd4j-tests runs.

Obviously, issue is dataType change in the middle of running tests within JVM. I.e. we run 100500 tests as **float**, stuff gets cached into device constant memory, then we set dataType to **double**,  and occasionally - bam, issue. 

Obviously, issue is pointer alignment for extraParams or tadShape, or whatever else. 

But main concern here, is actually another one: should we enforce cache purge on dataType change or not. Both options have pro's and con's, and to be decided before release.

**Comment by raver119** [comment]
Hypothetically fixed here: https://github.com/deeplearning4j/nd4j/pull/1317

I've decided  **not** to purge cache, and force alignment instead.

Will be merged a bit later, as usually.

**Comment by agibsonccc** [comment]
Close this when PR is merged and we see the CI not crashing.  Either that or get your PR merged sooner.

**Comment by raver119** [comment]
PR is merged, and here's test that confirm fix: https://github.com/deeplearning4j/nd4j/blob/4dde0de75fb7f623d10441d3a60b4d067c8b093b/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/test/java/jcuda/jcublas/ops/SporadicTests.java#L203-L203

Even if fix won't help - that'll be another issue, because thing i've been speaking about - is fixed now.
