### ISSUE TITLE
tensorAlongDimension then data() fails

### ISSUE THREAD

**Issue by Jajawah** [deeplearning4j/nd4j#1314]
Running this test fails
```
    @Test
    public void testProjection() {
        int d1 = 2;
        int d2 = 3;
        INDArray array = Nd4j.linspace(1, d1 * d2, d1 * d2).reshape(new int[] { d1, d2 });
        INDArray projection = array.tensorAlongDimension(1, 0);
        assertEquals(projection.data(), projection.dup().data());
    }
```
with 
```
<dependency>
  		<groupId>org.nd4j</groupId>
  		<artifactId>nd4j-native-platform</artifactId>
  		<version>0.6.0</version>
</dependency>
```

**Comment by raver119** [comment]
DataBuffer.equals method isn't supposed to check content of underlying buffer. On cuda it's checking strict equality, and in BaseDataBuffer wasn't updated to proper equality like INDArray has.

Please, consider using checks on INDArrays.

**Comment by Jajawah** [comment]
OK for the checking, but the bug still remains.
```
@Test
    public void testProjection() {
        int d1 = 2;
        int d2 = 3;
        INDArray array = Nd4j.linspace(1, d1 * d2, d1 * d2).reshape(new int[] { d1, d2 });
        INDArray projection = array.tensorAlongDimension(1, 0);
        assertArrayEquals(projection.data().asFloat(), projection.dup().data().asFloat(),0.0001f);
    }
```

**Comment by raver119** [comment]
Sorry, but this is not a bug. 

`projection.data()` - it's a view over `array`. The same databuffer is used, but with different offset, stride, length set.

`projection.data().dup()` - it produces on DataBuffer, from view, so it contains "valid data only".

Please consider using INDArray.

**Comment by Jajawah** [comment]
Ok, it makes sense, thanks for explanation. But it's tricky that the databuffer can be unrelated to the view ! So I need to get raw data to ensure some retro-compatibilities and outputs in my progs, I have to be very carefull ...

**Comment by raver119** [comment]
Well, not even single op in nd4j operates on DataBuffer directly, so you have to be EXTRA CAUTIOUS there. I.e. use dup() when your DataBuffer is expected to contain required data, so after dup() resulting DataBuffer will be detached from original DataBuffer.
