### ISSUE TITLE
Provide random choice from INDArray (aka np.random.choice)

### ISSUE THREAD

**Issue by tteofili** [deeplearning4j/nd4j#1316]
it'd be nice to be able to have a NumPy np.random.choice counterpart in ND4J.
A sample API would look like Nd4j.rand(shape, probabilities).

**Comment by raver119** [comment]
This thing will be implemented during upcoming/planned rand overhaul in nearest time.

**Comment by raver119** [comment]
Implemented & available on current master.

**Comment by tteofili** [comment]
cool, thanks @raver119
