### ISSUE TITLE
Add histogram calculation as native op

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1318]
Histograms in DL4J (for the histogram listener etc) is currently based on this:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-ui-parent/deeplearning4j-ui-model/src/main/java/org/deeplearning4j/ui/weights/HistogramBin.java

Given the number of  histograms that may be calculated, this should be reimplemented as a native op.
Args: nBins
Auto-calculate min/max from source array
return an INDArray of length nBins, where each entry is a count for that bin.
Each bin i>=0 contains count for interval (min+i*step, min+(i+1)*step), where step = (max-min)/nBins

**Comment by raver119** [comment]
Implemented: https://github.com/deeplearning4j/libnd4j/pull/307
