### ISSUE TITLE
Remove org.nd4j.linalg.lossfunctions.LossCalculation

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#1329]
... or at least deprecated it.

As far as I can tell its last usage in DL4J should be removed if https://github.com/deeplearning4j/deeplearning4j/pull/2166 is merged.

**Comment by eraly** [comment]
https://github.com/deeplearning4j/nd4j/pull/1489

Confirmed no more uses of LossCalculation in dl4j.
