### ISSUE TITLE
Exception with ND4j.Concat() (maybe with big arrays?)

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#133]
Code works fine under 5.4 but with newer version I got always an error. I dont know whats wrong. The error occurs only at the last concat(). My old issue to this topic: https://github.com/deeplearning4j/nd4j/issues/87

Here the code.
// Initialize the 'theta' vector
		INDArray theta_return = Nd4j.toFlattened(w.get(0));
		//w:
		for (int j = 1; j < w.size(); j++) {
			// concatenate to stack
			theta_return = Nd4j.concat(0, Nd4j.toFlattened(theta_return), Nd4j.toFlattened(w.get(j)) );
		}
		//arrayInfo(theta_return, "after w theta_return");

		//v:
		for (int j = 0; j < v.size(); j++) {
			// concatenate to stack
			theta_return = Nd4j.concat(0, Nd4j.toFlattened(theta_return), Nd4j.toFlattened(v.get(j)) );
		}
		//arrayInfo(theta_return, "after v theta_return");
		
		//b:
		for (int j = 0; j < b.size(); j++) {
			// concatenate to stack
			theta_return = Nd4j.concat(0, Nd4j.toFlattened(theta_return), Nd4j.toFlattened(b.get(j)) );
		}
		//arrayInfo(theta_return, "after b theta_return");

		//U:
		for (int j = 0; j < u.size(); j++) {
			// concatenate to stack
			theta_return = Nd4j.concat(0, Nd4j.toFlattened(theta_return), Nd4j.toFlattened(u.get(j)) );
		}

		//Word Vectors:
		System.out.println("wordvectors shape: "+wordvectors.shape()[0]+"|"+wordvectors.shape()[1]);
		INDArray wvflatten = Nd4j.toFlattened(wordvectors);
		theta_return = Nd4j.concat(0, theta_return, wvflatten );	
		//System.out.println("Theta_return size"+theta_return.length());
		return theta_return;

---------------------
Exception in thread "main" java.lang.IllegalArgumentException: Illegal index 480000 derived from 480000 with offset of 0 and stride of 1
at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2829)
at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:845)
at org.nd4j.linalg.factory.BaseNDArrayFactory.concat(BaseNDArrayFactory.java:945)
at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:2067)
at NTN.parametersToStack(NTN.java:483)

**Comment by agibsonccc** [comment]
Ok give me a bear bones test case for this. I'll add it in as a unit test and ensure it gets integrated.

**Comment by agibsonccc** [comment]
K the problem was due to concat on different sized arrays. This is fixed now.
