### ISSUE TITLE
BaseNDArray.distance1 returns wrong values!

### ISSUE THREAD

**Issue by millenium-bug** [deeplearning4j/nd4j#1336]
Hi,
when playing around with http://deeplearning4j.org/ I saw that BaseNDArray.distance1 (nd4j/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java) has a severe bug and returns wrong values in most cases. In your coding you subtract the arrays and simply sum up the values. You need to sum up the absolute values instead! Your distance1 for the vectors [1,0] and [0,1] is 0 instead of 2.
Can you please fix?

**Comment by AlexDBlack** [comment]
Thanks for reporting.
Fixed here: https://github.com/deeplearning4j/nd4j/pull/1337
Workaround until the next release: use ```Nd4j.getExecutioner().execAndReturn(new ManhattanDistance(first,second)).getFinalResult().doubleValue();```
