### ISSUE TITLE
Why there are differences after the 4th decimal place in contrast to numpy

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#134]
Hey guys,

I m currently debugging my code and there are some issues in comparison to numpy. In Nd4j the numbers are different for the same data. Sometimes that already occured after read in some vector data from a txt file. 

For example numpy
 [[  0.00000000e+00   0.00000000e+00   0.00000000e+00 ...,   0.00000000e+00
    0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00  -2.93152889e-09  -5.86305778e-09 ...,  -2.84358302e-07
   -2.87289831e-07  -2.90221360e-07]
 [  0.00000000e+00  -5.86305778e-09  -1.17261156e-08 ...,  -5.68716604e-07
   -5.74579662e-07  -5.80442720e-07]

and the same in ND4j:
[[0.0, 0.0, 0.0, 0.0, , ..., 0.0, 0.0, 0.0]
 [0.0, -2.9315352367831338E-9, -5.8630704735662675E-9, -8.794605932394006E-9, , ..., -2.843589186340978E-7, -2.872904474315874E-7, -2.9022197622907697E-7]
  ,[0.0, -5.8630704735662675E-9, -1.1726140947132535E-8, -1.7589211864788012E-8, , ..., -5.687178372681956E-7, -5.745808948631748E-7, -5.804439524581539E-7]
 ]

Why is that, and which is the correct one? How dangerous is such a difference for furhter calculations in neural networks?

Thanks in advance for clarification!

**Comment by agibsonccc** [comment]
Have you tried with the double datatype? Nd4j's default data type is usually float. Try setting it to double before running anything and seeing the delta.

**Comment by c0der1337** [comment]
When I switch to double, I got from ND4j:

[[0.0, 0.0, 0.0, 0.0, , ..., 0.0, 0.0, 0.0]
 [0.0, -2.9315282179490864E-9, -5.863056435898173E-9, -8.79458465384726E-9, , ..., -2.8435823714106137E-7, -2.872897653590105E-7, -2.9022129357695956E-7]
  ,[0.0, -5.863056435898173E-9, -1.1726112871796345E-8, -1.758916930769452E-8, , ..., -5.687164742821227E-7, -5.74579530718021E-7, -5.804425871539191E-7]
 ]

Later I will post an better example with the initialization of the matrixes to better see the problem

**Comment by c0der1337** [comment]
Here is an better example:

Code:
Nd4j.dtype = DataBuffer.Type.DOUBLE;
		INDArray activation = Nd4j.zeros(2,2);
		activation.put(0,1,1);
		activation.put(1,1,0.9854321);
		activation.put(1,0,2);
		System.out.println("activation: "+activation);
		System.out.println(Nd4j.ones(activation.rows(), activation.columns()).sub(activation.mul(activation)));

Output:
activation: [[0.0, 1.0]
 [2.0, 0.9854321]]

[[1.0, 0.0]
 [-3.0, 0.02892357628958997]]

Numpy:
In [1]: import numpy as np

In [2]: w= np.zeros((2,2))

In [3]: w[0,0] = 0

In [4]: w[0,1] = 1

In [5]: w[1,0] = 3

In [6]: w[1,1] = 0.9854321

In [7]: 1-np.power(w,2)
Out[7]:
array([[ 1.        ,  0.        ],
       [-8.        ,  0.02892358]])

Difference:
ND4j: 0.02892357628958997
Numpy: 0.02892358

Maybe the difference occurs because in the calculation nd4j handles data as float and not as double ...can you please also look at the other issue https://github.com/deeplearning4j/nd4j/issues/133 and give me an advice how to fix it, than I could swith to the current version of nd4j

**Comment by agibsonccc** [comment]
Yes this is very common.

ND4j: 0.02892357628958997
Numpy: 0.02892358

Numpy is just rounding. I'm closing this.
