### ISSUE TITLE
MNIST example crashes on mac on spark-submit with default parameters

### ISSUE THREAD

**Issue by avkumar** [deeplearning4j/nd4j#1348]
https://gist.github.com/avkumar/acb6088b4af474e7780a5227583c9832
https://gist.github.com/avkumar/2735e5aae09d838e34d4b9bf953e70eb

**Comment by raver119** [comment]
You run non-modified example, right?

**Comment by avkumar** [comment]
Yes!

**Comment by avkumar** [comment]
One more example!
https://gist.github.com/avkumar/644cf03ee75edd7683c40d3c22dfc51e

**Comment by avkumar** [comment]
https://gist.github.com/avkumar/ed8730de3fb527271b2b455dfe765904

**Comment by raver119** [comment]
Issue should be fixed on current master. Please check (if possible) and confirm/decline.
