### ISSUE TITLE
Soft limit on [DEVICE] memory hit

### ISSUE THREAD

**Issue by vzamboni** [deeplearning4j/nd4j#1349]
I am training a ComputationGraph with a Nvidia Tesla K80 with 12G with cuda 8.0 backend and cudnn, nd4j and deeplearning4j 0.6.0 and I get some 

>  WARN org.nd4j.jita.handler.impl.CudaZeroHandler - Soft limit on [DEVICE] memory hit, please consider tuning memory parameters, deviceId [0]

at the beginning of the training. Training goes fine and the GPU Memory usage is around 7G.

I tried to increase memory with [this](https://gist.github.com/vzamboni/176023887d4e45e501167bee7f7a5065) but I still get the warning and after few iteration I get an out of memory and training crashes.

**Comment by raver119** [comment]
Reduce amount of allowed cache as temporary workaround, to 1-2 gigabytes.

**Comment by raver119** [comment]
Also, please show me the gist of your nn configuration

**Comment by raver119** [comment]
I remember we've got your issue resolved using HALF precision, but i still would like to get nn conf to reproduce original issue locally, and check what could be done there.

**Comment by vzamboni** [comment]
Graph conf is [here](https://gist.github.com/vzamboni/2f7763f59f8de7d015fe2539ec53f1a8). 

getNet() function returns the ComputationGraph I used.

With HALF I remember I solved the issue for that configuration, but bigger configurations and bigger datasets go easily out of memory.

**Comment by fac2003** [comment]
@raver119  I have the same problem when training in parallel on multiple GPUs. Code works fine with single GPU, but when running with parallel worker (0.7.1) all the mini-batches get allocated to the first GPU, the messages start to show up and training stalls. There is enough memory across the four GPUS to hold the dataset, but DL4J tries to cram everything into one card. This issue prevent us from using multi-GPU training. It could be a different issue. I can share code and datasets if needed. Let me know.

**Comment by raver119** [comment]
Yes please, anything that helps to localize issue is welcome.

**Comment by fac2003** [comment]
I put dataset and instructions to reproduce at https://www.dropbox.com/s/l9g7x4i3ac79b8c/small.zip?dl=0

Our project makes it easy to find these problems because we serialize the MDS into a cache file. It is  easy to see the complete size of the dataset when the cache is built on disk.

**Comment by raver119** [comment]
Right, that's current work model. Originally async iterator places data on one device (usually first), and then datasets gets relocated to target device. This is known behavior, and change for it is already planned: we have implemented special queue for multi-device handling, and i'll integrate it for 0.8.0 release.

Actually right after i finish distributed parameter server for w2v on spark, i'll focus on memory improvements for cuda & cpu, and magicqueue is planned part of those improvements.

**Comment by raver119** [comment]
Available on current master as option in ParallelWrapper, .useMQ(true)
