### ISSUE TITLE
Change cuda versions to 8.0 on the website.

### ISSUE THREAD

**Issue by juvaud** [deeplearning4j/nd4j#1353]
On the page https://deeplearning4j.org/buildinglocally.html#building-manually in the codefragment for building nd4j for CPU it says: 
`mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!:nd4j-cuda-7.5,!:nd4j-cuda-7.5-platform,!:nd4j-tests'`

but this fails as it now uses cuda 8.0 in my understanding.
I fixed this issue by setting the right version number.
`mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!:nd4j-cuda-8.0,!:nd4j-cuda-8.0-platform,!:nd4j-tests'`

small fix, most of the people who build the stack manually are probably able to figure that out by themselves but consitency is key! ;)

**Comment by raver119** [comment]
That mainly depends on actual cuda version built. There's still people using cuda 7.5 out there, so these modules should reflect actual version user has. 

However, default build is 8.0 these days, yes.

**Comment by agibsonccc** [comment]
Done.
