### ISSUE TITLE
Add line for building dl4j without cuda from source in the doc

### ISSUE THREAD

**Issue by juvaud** [deeplearning4j/nd4j#1354]
https://deeplearning4j.org/buildinglocally.html#building-manually states 
`mvn clean install -DskipTests -Dmaven.javadoc.skip=true` 
which fails at the point it is trying to build the cuda part for dl4j. in my opinion the doc should include 
`mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.deeplearning4j:deeplearning4j-cuda-8.0'` 
for the possibility to build dl4j without cuda support.

**Comment by agibsonccc** [comment]
This is handled in our build-dl4j-stack.sh script now.
