### ISSUE TITLE
OutOfMemoryError in restricted environments

### ISSUE THREAD

**Issue by olivermg** [deeplearning4j/nd4j#1356]
(Disclaimer: This is probably a non-issue, but as you asked me several times on Gitter to provide a VisualVM screenshot, I didn't want to silently drop this. Additionally, this might be of help to others in the future if it's documented)

After updating Nd4j (and DL4j) version from 0.4.0 to 0.6.0, I started constantly experiencing `OutOfMemoryError`s during building a configuration for a network, such as:

```
OutOfMemoryError Physical memory usage is too high (142573568 > Pointer.maxPhysicalBytes)
  org.bytedeco.javacpp.Pointer.deallocator (Pointer.java:547)
```

This issue was occurring on a JVM instance with a max heap of `-Xmx350m` and running a Clojure environment.

After tracking it down some, I found out that the error was caused during the very first access to the class `org.nd4j.linalg.factory.Nd4j`, e.g. when calling its static method `getRandom`.

While trying to isolate the problem to make it reproducible, I found out that the error would only appear when I was running the application in a Clojure REPL and that it's probably just a coincidence that 0.4.0 worked for me but 0.6.0 didn't, as it seems my REPL plugins seem to consume most of the memory. Without any REPL plugins loaded and in a tiny dummy project, I have to reduce the max heap size to a value as low as `-Xmx50m` in order to be able to reproduce the exception.

Steps to reproduce are:

```
$ lein new app nd4jtest
$ cd nd4jtest
```

Edit `project.clj` and add the dependency to `nd4j` as well as the JVM option `-Xmx50m`:

```
(defproject nd4jtest "0.1.0-SNAPSHOT"
  ...
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.nd4j/nd4j-native-platform "0.6.0"]]   ;; <- added
  :main ^:skip-aot nd4jtest.core
  :jvm-opts ["-Xmx50m"]     ;; <- added
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
```

Edit `src/nd4jtest/core.clj` to use some Nd4j stuff:

```
(ns nd4jtest.core
  (:import [org.nd4j.linalg.factory Nd4j])   ;; <- added
  (:gen-class))

(defn -main
  [& args]
  (println "Hello, World!")
  (Nd4j/getRandom)     ;; <- added
  (println "Bye, World!"))
```

Then run the REPL and invoke `main`:

```
$ lein repl
nREPL server started on port 50153 on host 127.0.0.1 - nrepl://127.0.0.1:50153
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.8.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_102-b14
...
nd4jtest.core=> (-main)
```

Will result in the error:

```
OutOfMemoryError Physical memory usage is too high (142008320 > Pointer.maxPhysicalBytes)
  org.bytedeco.javacpp.Pointer.deallocator (Pointer.java:547)
```

The VisualVM screenshot right afterwards:

![bildschirmfoto 2016-10-25 um 17 41 40](https://cloud.githubusercontent.com/assets/986278/19693186/eab51632-9ada-11e6-874e-43362d11e917.png)

Feel free to close this issue if you don't have anything to add.

**Comment by raver119** [comment]
Thanks for letting us know!
