### ISSUE TITLE
Save function of ImagePreProcessingScaler

### ISSUE THREAD

**Issue by JieZou1** [deeplearning4j/nd4j#1360]
I am trying to save a ImagePreProcessingScaler instance, but it seems that file is not saved. Codes as below, anything wrong?

 ImagePreProcessingScaler myScaler = new ImagePreProcessingScaler();
 myScaler.fit(datasetAll);
 myScaler.save(new File("statistics"));

**Comment by AlexDBlack** [comment]
ImagePreProcessingScaler doesn't have any internal statistics: unlike some of the other normalizers, it doesn't collect mean/standard deviation/min/max etc.
Consequently, there's no statistics to save.

The only state is has are a few parameters (or default  values) passed in via the constructor. It *might* make sense to save/serialize these using some mechanism... is this what you wanted?

**Comment by JieZou1** [comment]
@AlexDBlack Many thanks. I should read the source codes first. I have done now, and noticed that both load and save functions are empty. I am quite new to ND4J and DL4J. Sorry.

A separate quick question: I have completed offline training and understand that normalize, fit and output functions are all through DataSet (or DataSetInterator). However, in production, we have images (Mat) already. Are there a convenient way (and some sample codes) that we could convert Mat[] or List<Mat> to DataSet? From reading the documentations, it seems that I have to go through NDArray, i.e., Mat[] -> NDArray -> DataSet. Are there any sample codes that I could refer to? Many thanks.

**Comment by JieZou1** [comment]
@AlexDBlack I figured out a way, as below:

        NativeImageLoader imageLoader = new NativeImageLoader(width, height, channels);
        List<INDArray> slices = new ArrayList<>();
        for (int i = 0; i < images.length; i++)
        {
            INDArray arr = imageLoader.asMatrix(images[i]);
            slices.add(arr);
        }
        INDArray imageSet = new NDArray(slices, new int[] {images.length, channels, width, height});
        imageSet.divi(255.0);
        INDArray results = model.output(imageSet);

It is through INDArray, instead of DataSet. Is this a good way? I am trying to getting myself familiar with all kinds of classes implemented ND4J, DL4J, etc.

I also have to use divi function directly, instead of consistently (as training) using ImagePreProcessingScaler, because its transform function accepts DataSet only.
