### ISSUE TITLE
The Coursier sbt plugin causes nd4j-native and nd4j-native-platform to fail during dependency resolution

### ISSUE THREAD

**Issue by kbrowder** [deeplearning4j/nd4j#1366]
The coursier sbt plugin improves dependency resolution performance and allows sbt to work purely from cache, however it appears that it doesn't properly expand variables like ${os.name} as observed in alexarchambault/coursier#341.

A note should be added to the nd4j documentation mentioning this issue and recommending disabling coursier until the issue is resolve

**Comment by saudet** [comment]
Should be fixed with 0.6.0. Have you tried that version?

**Comment by kbrowder** [comment]
Sorry I should have been more specific, tested with the nd4s project on master (bf2ea7d5f829f0d3a61c11a0d8ba11ccc6e220dd) with the build.sbt changed to the following: https://gist.github.com/kbrowder/cb2a29f59a75a059a7bf64404be29e5d
which has nd4jVersion as 0.6.0 and removes the local repo.

I've also tried this on a very small project with only the following:
```
name := """hello-scala"""

version := "1.0"

scalaVersion := "2.11.7"

libraryDependencies ++= Seq(org.nd4j" % "nd4j-native-platform" % "0.6.0")
```

The error in this case is:
```
coursier.ResolutionException: 2 not found
  https://repo1.maven.org/maven2/org/nd4j/nd4j-native/0.6.0/nd4j-native-0.6.0-${os.name}-${os.arch}.${project.packaging}
  https://repo1.maven.org/maven2/org/nd4j/nd4j-native/0.6.0/nd4j-native-0.6.0-${os.name}-${os.arch}.jar
[error] (*:update) coursier.ResolutionException: 2 not found
[error]   https://repo1.maven.org/maven2/org/nd4j/nd4j-native/0.6.0/nd4j-native-0.6.0-${os.name}-${os.arch}.${project.packaging}
[error]   https://repo1.maven.org/maven2/org/nd4j/nd4j-native/0.6.0/nd4j-native-0.6.0-${os.name}-${os.arch}.jar
```
Basically any dependency with variables can't be resolved when using Coursier (tried both 1.0.0-M14 and M12)

**Comment by saudet** [comment]
Do you know if it's possible to work around this issue by excluding that dependency explicitly? Removing the profile associated with that would put a great burden on developers using Maven I think.

**Comment by kbrowder** [comment]
So I couldn't figure out the incantation to make sbt exclude the nd4j-native-...${os.name}-${.... dependency, and then I couldn't figure out how to re-include it with the variables filled in.

So I guess it should just be documented until the Coursier guys get a fix in, sounds like they're working on it though.  I imaging a lot of Scala users who use Emacs (like me) will trip over this as Ensime officially recommends Coursier (because it makes SBT a ton faster).

**Comment by saudet** [comment]
According to alexarchambault/coursier#341 this should be fixed now. @kbrowder can you confirm that?

**Comment by kbrowder** [comment]
@saudet yup "org.nd4j" % "nd4j-cuda-8.0-platform" % "0.7.2" works in a coursier enabled build.  Thanks!

I guess dl4j will also work once it's updated to use the new nd4j?

**Comment by saudet** [comment]
dl4j 0.7.2 is already using the new nd4j, so it should work exactly the same. Let us know if you still have problems with that, and thanks for the feedback!
