### ISSUE TITLE
Fix Jenkins unit test failures

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1368]
Opening this issue to track unit test failures on Jenkins.

Using this PR: https://github.com/deeplearning4j/nd4j/pull/1367

Test failures:

**nd4j-aeron**
org.nd4j.aeron.ipc.response.AeronNDArrayResponseTest.testResponse - assertion failure
org.nd4j.aeron.ipc.AeronNDArraySerdeTest.testToAndFrom
org.nd4j.aeron.ipc.AeronNDArraySerdeTest.testToAndFromCompressed
org.nd4j.aeron.ipc.AeronNDArraySerdeTest.timeOldVsNew
org.nd4j.aeron.ipc.NdArrayIpcTest.testIpc - java.lang.ExceptionInInitializerError
Other 3 tests: java.lang.NoClassDefFoundError: Could not initialize class org.nd4j.linalg.factory.Nd4j

Run locally (IntelliJ):
- AeronNDArraySerdeTest tests - all passing
- AeronNDArrayResponseTest - passing
- NdArrayIpcTest - failing - assertion error (failing on `assertFalse(running.get());`)

**nd4j-cuda-8.0**
org.nd4j.linalg.api.ndarray.TestSerialization
- .testSerializationOnViewsJava - looks like a legitimate test failure
- .testSerializationOnViewsNd4jWriteRead - IndexOutOfBoundsException

TestSerializationDoubleToFloat - failed assertion
- .testSerializationOnViewsJava - failed assertion
- .testSerializationOnViewsNd4jWriteRead

TestSerializationFloatToDouble
- .testSerializationOnViewsJava - failed assertion
- .testSerializationOnViewsNd4jWriteRead - failed assertion

(haven't run these locally yet)

**nd4j-kryo**
TestNd4jKryoSerialization.testSerialization: java.lang.ExceptionInInitializerError
-> Runs fine locally (IntelliJ)

**nd4j-parameter-server-client**
org.nd4j.parameterserver.client.ParameterServerClientTest.testServer: java.lang.ExceptionInInitializerError
-> Can't run this locally... "Unable to connect...trying again on channel aeron:udp?endpoint=localhost:40123" - repeatedly

**Comment by agibsonccc** [comment]
We need to rerun this.
