### ISSUE TITLE
LSTM crashes when run using eclipse on mac

### ISSUE THREAD

**Issue by avkumar** [deeplearning4j/nd4j#1369]
https://gist.github.com/avkumar/7dc0763b27cb0b0cf59f3aafcc4ce8fb
Same error when run through console too

**Comment by raver119** [comment]
Can i see your NN conf?

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/rnn/SparkLSTMCharacterExample.java

**Comment by raver119** [comment]
How long it takes to reproduce crash? Is crash 100% reproducible for you?

**Comment by avkumar** [comment]
Yes. I get the crash every time i run it on mac either through eclipse or console. However, it runs fine on linux VM or emr.

**Comment by avkumar** [comment]
Even the dl4j examples crash for me.

**Comment by raver119** [comment]
Amazing... No luck for me so far.
Can you post you Mac model name?

31 окт. 2016 г. 0:22 пользователь "sai kumar arava" <
notifications@github.com> написал:

**Comment by raver119** [comment]
And please tell me, this particular example: https://github.com/deeplearning4j/dl4j-examples/blob/4be838e15286210b2f4ac898455c0f17fa73ce65/dl4j-examples/src/main/java/org/deeplearning4j/examples/feedforward/mnist/MLPMnistSingleLayerExample.java

Does it fail for you? Could you please check it and confirm?

**Comment by avkumar** [comment]
MLPMnistSingleLayerExample.java is running good on my mac!

**Comment by raver119** [comment]
Okay. Can you get me a list of few examples that do crash, and few that don't then?

**Comment by avkumar** [comment]
https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/rnn/SparkLSTMCharacterExample.java
This program crashes.


Also, my mac config>
2.5 GHz Intel Core i7
16 GB 1600 MHz DDR3
Macintosh HD
AMD Radeon R9 M370X 2048 MB

**Comment by raver119** [comment]
Could you run this test multiple times please?

https://gist.github.com/AlexDBlack/0c57c73598c1895e7f673b5f60419df2

**Comment by avkumar** [comment]
https://gist.github.com/avkumar/03a1476e20c117a6a596d3dd6959f2c5
Total test types run: 256
Total mmuls executed: 25600

**Comment by raver119** [comment]
Now we 100% sure it's not related to gemm at all, and even have suspect.

**Comment by raver119** [comment]
I'm sorry, are you able to build libnd4j/nd4j/dl4j from sources?

**Comment by avkumar** [comment]
Yes. Im able to build dl4j from source. If you mean this ("mvn clean
install -DskipTests=true -Dmaven.javadoc.skip=truewithin all three
directories, in that order.) And I am able to run few examples too..except
the ones that i posted above.

**Comment by raver119** [comment]
Issue should be fixed on current master. Please check (if possible) and confirm/decline.

But libnd4j is slightly more then mvn clean install :)

**Comment by raver119** [comment]
Closing since stalled.
