### ISSUE TITLE
DropConnect and DropOut use configured Probability inconsistently

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#1373]
DropOut uses it like this:
`return rnd <= prob ? (T) 0.0 : d1;`

While DropConnect uses it like this:
`return rnd >= prob ? (T) 0.0 : d1;`

Notice the `<` vs `>` difference.

According to the doc, it should be like it is used in DropOut, i.e. it should be as the probability of retaining the value.

**Comment by raver119** [comment]
ok, fixed.
