### ISSUE TITLE
Creating inferred vectors using google vectors

### ISSUE THREAD

**Issue by rahulahuja16** [deeplearning4j/nd4j#1380]
//Code

 TokenizerFactory t = new DefaultTokenizerFactory();
        t.setTokenPreProcessor(new CommonPreprocessor());
        
        WordVectors googleVectors;

        // we load externally originated model
        ParagraphVectors vectors;
        ParagraphVectors pv;
		try {
			
			googleVectors = WordVectorSerializer.loadGoogleModel(new File("/home/tmuser/Rahul/GoogleNews-vectors-negative300.bin"), true);
			
			pv = new ParagraphVectors.Builder()
					.tokenizerFactory(t)
					.iterations(10)
					.trainWordVectors(false)
					.useExistingWordVectors(googleVectors)
					.negativeSample(5)
					.build();

 INDArray inferredVectorA = pv.inferVector("Hello. How are you?");
        INDArray inferredVectorA2 = pv.inferVector("I want to include my beneficiaries under HIS.");
        INDArray inferredVectorB = pv.inferVector("Who are my beneficiaries in HIS ?");
        INDArray inferredVectorB2 = pv.inferVector("how do I include my beneficiaries under Higher Hospitalisation ?");
        INDArray inferredVectorC = pv.inferVector("This is my world.");
  
        System.out.println("inferred vector A" + inferredVectorA);
        System.out.println("inferred vector A2" + inferredVectorA2);
        System.out.println("inferred vector B" + inferredVectorB);

        
        // high similarity expected here, since in underlying corpus words WAY and WORLD have really close context
        log.info("Cosine similarity A/B: {}", Transforms.cosineSim(inferredVectorA, inferredVectorB));

        // equality expected here, since inference is happening for the same sentences
        log.info("Cosine similarity A/A2: {}", Transforms.cosineSim(inferredVectorA, inferredVectorA2));
        
        log.info("Cosine similarity A2/B2: {}", Transforms.cosineSim(inferredVectorA2, inferredVectorB2));
        
        log.info("Cosine similarity A/C: {}", Transforms.cosineSim(inferredVectorA, inferredVectorC));
        
       
        System.out.println("Eq: " + inferredVectorA.equals(inferredVectorA2));
        
        
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

output

o.n.n.NativeOps - Number of threads used for NativeOps: 12
o.n.n.Nd4jBlas - Number of threads used for BLAS: 12
inferred vector A[0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00]
inferred vector A2[0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00]
inferred vector B[0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, -0.00, -0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, 0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, 0.00, -0.00, 0.00, -0.00, 0.00, 0.00, -0.00, -0.00, -0.00, -0.00, 0.00]
o.d.e.n.p.ParagraphVectorsInferenceExample - Cosine similarity A/B: 1.0
o.d.e.n.p.ParagraphVectorsInferenceExample - Cosine similarity A/A2: 1.0
o.d.e.n.p.ParagraphVectorsInferenceExample - Cosine similarity A2/B2: 1.0
o.d.e.n.p.ParagraphVectorsInferenceExample - Cosine similarity A/C: 1.0
Eq: true

**Comment by raver119** [comment]
Please check 0.7.0, things should be working there.

**Comment by raver119** [comment]
So, here's what happens inside, in case of Google Model:
1) We load model (in your case you're loading it normalized, which is **NOT** recommended)
2) Model has no frequency information, and negative sampling table (syn1Neg) is not available.
3) syn1Neg table is initialized as set of 0.0, like a new table.
4) During inferrence pass, gradient is calculated based on syn1Neg and neu1e in this particular case is always 0.0 at first iteration, because syn1Neg is 0.0 as well.
5) But since it's inference mode, we are **NOT** updaing syn1Neg table, it's meant to stay intact after initial training, regardless how many inference passes you'll do.
6) This causes all negativeSampling rounds to have 0 effect on resulting vector, because neu1e will be full of 0.0s.


In other words: Google Model is missing 2 important elements, and i'm not sure right now, how to step over it, if it's possible to step over it, after all.

**Comment by raver119** [comment]
Better handling for existingModel within ParaVec was merged today. However, GoogleModel concerns are still there.
