### ISSUE TITLE
getColumns doesn't work as expected on vector

### ISSUE THREAD

**Issue by JCalderan** [deeplearning4j/nd4j#1381]
Hi guys,

Here’s the issue : I have my vector X (say from 0 to 10), and I try to access to some of its items through indices (say indices 3, 5, 8).

```java
INDArray x = Nd4j.create(new double[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}); 
System.out.println(x.columns()); // 11 columns
int[] index = new int[]{2, 3, 4};
System.out.println(x.getColumns(index));
// output : [2.00, 3.00, 4.00] , which is fine
```

But then I tried this, and the results was not what I expected :
```java
NDArray x = Nd4j.create(new double[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}); 
int[] index = new int[]{2, 2, 4}; //retrieve the same columns twice
System.out.println(x.getColumns(index)); 
// output : [2.00, 3.00, 4.00] , expected  [2.00, 2.00, 4.00] 
```

Actually it seems the first indice retrieve the right columns, but then any following int value are just increasing by one the indice of the next columns ( but the int value itself should be the indice of the next column).
```java
NDArray x = Nd4j.create(new double[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}); 
int[] index = new int[]{5, 8, 9}; //retrieve the same columns twice
System.out.println(x.getColumns(index)); 
// output : [5.00, 6.00, 7.00], expected  [5.00, 8.00, 9.00] 
```

Any Ideas ? I might be missing very basics things, or maybe I'm not using the right method ?

**Comment by raver119** [comment]
This thing will be probably migrated to pullRows/pull nativeOp: https://github.com/deeplearning4j/nd4j/issues/1381

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/1392
