### ISSUE TITLE
IMax - wrong op num/result

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1395]
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/indexaccum/IMax.java#L91
IMax opnum: 0

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/indexaccum/IAMax.java

IAMax opnum: 0

```java
    @Test
    public void testIMaxIAMax(){
        INDArray arr = Nd4j.create(new double[]{-0.24, -0.08, -0.07, -0.01});

        double imax = Nd4j.getExecutioner().execAndReturn(new IMax(arr.dup())).getFinalResult();
        double iamax = Nd4j.getExecutioner().execAndReturn(new IAMax(arr.dup())).getFinalResult();
        System.out.println("IMAX: " + imax);
        System.out.println("IAMAX: " + iamax);

        assertEquals(3, imax, 0.0);
        assertEquals(0, iamax, 0.0);
    }
```

IMAX: 0.0
IAMAX: 0.0

Looks like IMax is wrong, IAMax OK

**Comment by raver119** [comment]
Fixed, also IAMin was added
