### ISSUE TITLE
get/getRow (edge case?) bug

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1396]
```java
    @Test
    public void testGet(){
        INDArray in = Nd4j.create(new double[][]{
                        {1, 2},
                        {3, 4}}, 'f');

        System.out.println("Input:\n" + in);
        System.out.println("Input data: " + Arrays.toString(in.data().asDouble()));
        System.out.println();

        INDArray out = in.getRow(1);
//        INDArray out = in.get(NDArrayIndex.interval(1,2), NDArrayIndex.all());
//        INDArray out = in.get(NDArrayIndex.point(1), NDArrayIndex.all());
        System.out.println("Out:        " + out);
        System.out.println("Out data:   " + Arrays.toString(out.data().asDouble()));        //Should be a view - data should be length 4...
    }
```

```
Input:
[[1.00, 2.00],
 [3.00, 4.00]]
Input data: [1.0, 3.0, 2.0, 4.0]

Out:        [3.00, 4.00]
Out data:   [3.0, 2.0]
```

Testing:
- Confirmed as an issue for 0.6.0 (native) also
- Output is correct for c order array (instead of f) + getRow(1)
- Output is *incorrect* for c order array + getColumn(1) (Out:        [2.00, 4.00], Out data:   [2.0, 3.0])
- Output is *incorrect* with getRow(1) and the following input array: ```Nd4j.create(new double[][]{{1, 2, 3},{4, 5, 6}}, 'f');``` (and similarly for 3x3 array). but operations on the array seem to be ok (out.add(0) for example gives correct results)

**Comment by raver119** [comment]
That's not a bug, but indexer behaviour. Indexer doesn't know anything about stride, so it gets 0 element as offset to original databuffer, and expects next element to be 0 index + 1, which isn't true for F rows or C columns.

Pointers themselves are ok, data is valid.
