### ISSUE TITLE
NormalzierStandardize not reverting labels with fitLabels(true)

### ISSUE THREAD

**Issue by dan-lind** [deeplearning4j/nd4j#1402]
The current (0.6.0) .revert()-method for NormalzierStandardize only takes a DataSet as input. 
If I have called .fitLabels(true) on my normalizer, I would expect the labels in my dataset to be reverted as well. Currently this is not the case, only the features are reverted regardless of calling fitLabels(true) or not.

**Comment by EdeMeijer** [comment]
Oh, if I get https://github.com/deeplearning4j/nd4j/pull/1406 accepted this will be fixed as a boyscouting side effect.

**Comment by eraly** [comment]
@dan-lind Thanks! 
@EdeMeijer We have a release coming out in the next few days. I wanted this fix in master if I didn't get to your PR in time.
