### ISSUE TITLE
Wrong / inconsistent standard deviations in NormalizerStandardize

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/nd4j#1405]
Fitting a DataSet gives a bias corrected std while fitting an iterator gives a non bias corrected std. Furthermore, iterators that don't produce equally sized chunks, even for 2D cases, give totally whack stds.

```
     @Test
    public void testDifferentBatchSizes() {
        // Create 6x1 matrix of the numbers 1 through 6
        INDArray values = Nd4j.linspace(1, 6, 6).transpose();

        DataSet dataSet = new DataSet(values, values);
        NormalizerStandardize norm1 = new NormalizerStandardize();
        norm1.fit(dataSet);
        assertEquals(3.5f, norm1.getMean().getFloat(0), 1e-6);
        assertEquals(1.8708387f, norm1.getStd().getFloat(0), 1e-6); // <-- bias corrected

        DataSetIterator testIter1 = new TestDataSetIterator(dataSet, 3); // Will yield 2 batches of 3 rows
        NormalizerStandardize norm2 = new NormalizerStandardize();
        norm2.fit(testIter1);
        assertEquals(3.5f, norm2.getMean().getFloat(0), 1e-6);
        assertEquals(1.7078355f, norm2.getStd().getFloat(0), 1e-6); // <-- not bias corrected

        DataSetIterator testIter2 = new TestDataSetIterator(dataSet, 4); // Will yield batch of 4 and batch of 2 rows
        NormalizerStandardize norm3 = new NormalizerStandardize();
        norm3.fit(testIter2);
        assertEquals(3.5f, norm3.getMean().getFloat(0), 1e-6);
        assertEquals(1.5433291f, norm3.getStd().getFloat(0), 1e-6); // <-- What's this? Not even close.
    }
```

**Comment by EdeMeijer** [comment]
As a side note, I found this while implementing a normalizer for MultiDataSet. A WIP pull request can be found at https://github.com/deeplearning4j/nd4j/pull/1406. I changed the offending code to an iterative implementation that's probably not fast enough but at least produced correct (non bias corrected) stds. This is a 1-on-1 implementation of https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Online_algorithm, and I have my doubts if this algorithm can be correctly implemented in vectorized way...

**Comment by eraly** [comment]
@EdeMeijer Why is it surprising that the results are *whacky* for a dataset of size 6? The iterator is meant to be used with larger datasets and it is an approximation for datasets that can't be held in memory.

**Comment by agibsonccc** [comment]
I would be curious how precision affects this. Have you tried setting the data type to double?

**Comment by eraly** [comment]
https://github.com/deeplearning4j/nd4j/blob/530e63a4b1f726e618174a7d7c5dff4aa36d71dc/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/dataset/NormalizerStandardizeTest.java#L36

Test with a larger dataset

**Comment by EdeMeijer** [comment]
@eraly if it's an approximation, it's fine. I just noticed these deviations while testing with a tiny data set. For normalization purposes, naturally a good approximation of the mean and std will do just fine. 
However, I don't quite agree that six data points cannot give a correct answer with an online algorithm. The online algorithm from Wikipedia gets this example right (I tried), and the difference is that that one processes incoming values one at a time (and can update a counter and running mean for every value). In fact, the implementation in NormalizerStandardize also gets is right as long as the batches are of equal length. However, as it process whole chunks of values at once, it becomes an approximation as soon as batch sizes are different. I get that (it's more efficient), but I just thought it might be worth having a look at.

At any rate, `fit(DataSetIterator iterator)` is not bias corrected, so we could at least make the `fit(DataSet dataSet)` version also non bias corrected for consistency :)

@agibsonccc I tried doubles, but that doesn't change anything. It's really an implementation detail, not a precision problem.

**Comment by EdeMeijer** [comment]
In my PR https://github.com/deeplearning4j/nd4j/pull/1406 I redid the running mean/std implementation based on https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Parallel_algorithm. This version does seem to deal correctly with varying batch sizes, while still processing whole batches in one go.

**Comment by eraly** [comment]
@EdeMeijer 
The online algorithm  is a special case of the parallel algorithm that can handle partitions n of any size. If you are going to implement it for multidataset make sure you are accounting for it's numerical stability. Closing it out.
