### ISSUE TITLE
Multiple DataSet Issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#141]
There's a number of issues related to org.nd4j.linalg.dataset.DataSet that I have discovered:

Issue 1. DataSet.copy():
Javadoc states that “@return a clone of the dataset”, but this function doesn’t copy either columnNames or labelNames list fields.
Issue is possibly also present with get(int i), get(int[] i) (Not sure if the returned DataSets in these cases should have a copy of column/label names?)

Issue 2. Both versions of DataSet.addFeatureVector():
I'm not sure exactly what the intent is for these functions, but they ignore the INDArray inputs, and call the Nd4j.hstack() varargs method with no input (which of course fails, due to an array index exception).

Issue 3. DataSet.asList() fails for DL4J MNIST and LFW data sets. This method has excessive memory use (i.e., throws an OutOfMemoryError exception). Tested with VM options "-Xms1G -Xmx16G" (on 32gb system) and ND4J JBLAS.
Reproduce with either of:
List<DataSet> list = DataSets.mnist().asList();
List<DataSet> list = DataSets.lfw().asList();
Data sets load ok and only use a few hundred mb; failure occurs on call to asList().

**Comment by agibsonccc** [comment]
Ok I have a PR in place. Need to add a test or 2 yet.
https://github.com/deeplearning4j/nd4j/pull/143
