### ISSUE TITLE
Documentation on L2 Loss

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#1415]
I expected the L2 Loss to calculate the L2 Norm of the difference, just as the L1 Loss calculates the L1 Norm. 

@AlexDBlack has pointed out that it is following the implementation of tensorflow but off by a constant multiple of 2.

So, to spare others the confusion, I guess that it should be explicitly stated in the javadoc that the L2 loss is not the L2 Norm of the Difference but the square of it, or as tensor flow says it: 
>the L2 norm of a tensor without the sqrt.

**Comment by eraly** [comment]
Thanks @treo
