### ISSUE TITLE
cuDNN & FP16

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1448]
At this moment cuDNN isn't working with FP16 dataType, and wasn't working before.
_Probably_ that's due to dataType difference behind cuDNN & nd4j. _Probably_ cuDNN expects only half2 datatype, and we're working on half.

To be investigated and fixed/improved in next release.

**Comment by raver119** [comment]
```
typedef struct __align__(2) {
   unsigned short x;
} __half;

typedef struct __align__(4) {
   unsigned int x;
} __half2;
```

**Comment by saudet** [comment]
cuDNN most likely does SIMD internally using half2, but all input and output arrays are supposed to be packed to half size. Is it that it doesn't appear to be doing that and aligning to half2? Or are you referring to something else?

**Comment by raver119** [comment]
Not sure i'm following the question. Right now if we provide half data to cudnn, it complaints, so i've assumed it doesn't like half, and wants half2 instead as input.

**Comment by raver119** [comment]
I guess you're using 1.0.0-beta, not current master, right?

**Comment by saudet** [comment]
No, master

**Comment by raver119** [comment]
Hm, why line numbers make no sense then... 

Ok i'll run it locally once everything rebuilt.

**Comment by saudet** [comment]
This one?
https://github.com/deeplearning4j/deeplearning4j/blob/master/libnd4j/blas/cuda/NativeOps.cu#L4340

**Comment by raver119** [comment]
This one: at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.ffToLayerActivationsInWs(MultiLayerNetwork.java:993)

**Comment by raver119** [comment]
Maybe lombok?

**Comment by saudet** [comment]
@raver119 I'm still getting error 74 with https://github.com/deeplearning4j/deeplearning4j/pull/5487. 

BTW, that error code 74 is "misaligned address". I wonder what that means...

**Comment by saudet** [comment]
Oh, look at that. Works with CUDA 9.2, but not CUDA 9.0. Must have something to do with CUDA 9.0 not supporting GCC 7 :)

**Comment by raver119** [comment]
Hm. I have CUDA 9.1 on Linux ithink, will check it out. But yea, on Windows i def have 9.2 and used it for tests yesterday.

**Comment by raver119** [comment]
Issue fixed. Problem was caused by cublasSgemmEx call O_o
