### ISSUE TITLE
Calling asList() on 3d MultiDataSet gives list of 2d MultiDataSets

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/nd4j#1454]
I was trying to split a batch of time series into individual time series data sets, and used `asList()`. Strange stuff happened and I figured out that the resulting objects had 2D arrays instead of 3D. A bunch of stuff breaks down at this point, like DataSetUtils that doesn't look at masks anymore when tailoring to 2D.

The actual problem appears to be that `INDArray.get(...)` drops dimensions that have size 1, and this is used in in `MultiDataSet::getSubsetForExample(...)` for getting 1 example from the batch.
```
INDArray SUT = Nd4j.create(
    new float[]{1, 2, 3, 4, 5, 6, 7, 8},
    new int[]{2, 2, 2}
);
System.out.println(SUT.rank());

INDArray slice = SUT.get(NDArrayIndex.point(0), NDArrayIndex.all(), NDArrayIndex.all());
System.out.println(slice.rank());
```
Will output
```
3
2
```
I mentioned this on gitter and @AlexDBlack was pretty sure this is a bug, so here.

**Comment by AlexDBlack** [comment]
Thanks. Fixed here: https://github.com/deeplearning4j/nd4j/pull/1458
