### ISSUE TITLE
Concurrency bug with mmuli in nd4j 0.7.0, native platform (CPU), Windows 64

### ISSUE THREAD

**Issue by Thomas-Philipp** [deeplearning4j/nd4j#1468]
I can reproduce with a testcase (see below) a concurrency bug with version 0.7.0 (from Maven Central) of nd4j of the Matrix Multiplication (mmuli) under Windows 64 with the native platform (CPU) backend (Java 8).

Running the same testcase with 0.6.0 is no Problem, but with 0.7.0 the testcase fails.

Remark also, that I can NOT reproduce the bug with smaller matrices, e.g. ROWS = 50 and COLS = 100 in the testcase below, even with a big number of samples, so it seams that the bug comes only with matrices which exceed a certain threshold (as in the appended testcase).

The bug is with C and Fortran ordering.

Setting the NUM_THREADS to 1 also lifts the Problem (but thats no Workaround for me :-)

    import static org.junit.Assert.assertEquals;

    import java.util.ArrayList;
    import java.util.List;
    import java.util.Random;
    import java.util.concurrent.ExecutionException;
    import java.util.concurrent.ExecutorService;
    import java.util.concurrent.Executors;
    import java.util.concurrent.Future;

    import org.junit.Test;
    import org.nd4j.linalg.api.ndarray.INDArray;
    import org.nd4j.linalg.factory.NDArrayFactory;
    import org.nd4j.linalg.factory.Nd4j;

    public class TestNd4jConcurrency {
	
	private static final int ROWS = 100;
	private static final int COLS = 200;
	private static final int NUM_SAMPLES = 500;
	private static final char ORDERING = NDArrayFactory.FORTRAN;
	private static final int NUM_THREADS = 2; //Must divide NUM_SAMPLES
	
	INDArray[] factor1 = new INDArray[NUM_SAMPLES];
	INDArray[] factor2 = new INDArray[NUM_SAMPLES];
	INDArray[] resultSequential = new INDArray[NUM_SAMPLES];
	INDArray[] resultParallel = new INDArray[NUM_SAMPLES];

	@Test
	public void test() throws InterruptedException, ExecutionException {
		
		//Init data
		for (int i = 0; i < NUM_SAMPLES; i++) {
			factor1[i] = Nd4j.create(ROWS,COLS,ORDERING);
			initRandom(factor1[i]);
			factor2[i] = Nd4j.create(COLS,ROWS,ORDERING);
			initRandom(factor2[i]);
			resultSequential[i] = Nd4j.create(ROWS,ROWS,ORDERING);
			resultParallel[i] = Nd4j.create(ROWS,ROWS,ORDERING);
		}
		
		//Do sequential operations (for compare later)
		for (int i = 0; i < NUM_SAMPLES; i++) {
			performFunction(i,resultSequential[i]);
		}
		
		//Do parallel operations
		ExecutorService executor = Executors.newFixedThreadPool(NUM_THREADS);
		List<Future<?>> futures = new ArrayList<>();
		for (int i = 0; i < NUM_THREADS; i++) {
			int finali = i;
			futures.add(executor.submit(() -> run(finali)));
		};
		for (Future<?> future : futures) {
			future.get();
		}
		
		//Check results
		for (int i = 0; i < NUM_SAMPLES; i++) {
			compare(i,resultSequential[i],resultParallel[i]);
		}
		
	}
	
	private void compare(int sampleIndex , INDArray expectedResult, INDArray actualResult) {
		for (int row = 0; row < expectedResult.rows(); row++) {
			for (int col = 0; col < expectedResult.columns(); col++) {
				assertEquals("Sampleindex=" + sampleIndex,expectedResult.getFloat(row, col), actualResult.getFloat(row, col),0.000001);
			}
		}		
	}

	private void run(int threadIndex) {
		for (int i = threadIndex; i < NUM_SAMPLES; i += NUM_THREADS) {
			performFunction(i,resultParallel[i]);
		}
	}

	private void performFunction(int index,INDArray result) {
		factor1[index].mmuli(factor2[index], result);
	}

	private void initRandom(INDArray indArray) {
		Random rnd = new Random();
		for (int row = 0; row < indArray.rows(); row++) {
			for (int col = 0; col <indArray.columns(); col++) {
				indArray.putScalar(row, col, rnd.nextDouble());
			}
		}
	}

    }

**Comment by raver119** [comment]
It's known openblas-related issue, and is considered fixed on current master.
