### ISSUE TITLE
NoArgs constructor for boolean conditions

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1478]
Some pairwise boolean indexing ops do not actually use numerical values being passed into them.

So, need to provide NoArgsConstructor for those, to avoid misleading params that are ignored anyway.

**Comment by raver119** [comment]
Added here: https://github.com/deeplearning4j/nd4j/pull/1157

But turns out that at this moment we actually do NOT have native op for Op.X <- Op.Y merge  based on Op.X and Op.Y comparison. Will add it after OpProfiler merge

**Comment by agibsonccc** [comment]
@raver119 update on this?

**Comment by raver119** [comment]
Implemented long ago.
