### ISSUE TITLE
Add Nd4j.linspace(double,double,int) overload

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1479]
Nd4j.linspace(int,int,int) only takes int arguments.

Being able to specify the minimum and maximum values as doubles (i.e., Nd4j.linspace(double,double,int)) would be an easy and useful addition.

**Comment by raver119** [comment]
No need, it's already added, and available as native op as of 0.7.0

5 дек. 2016 г. 13:06 пользователь "Alex Black" <notifications@github.com>
написал:

**Comment by raver119** [comment]
Sorry, just forgot to mention it's available :)

5 дек. 2016 г. 14:58 пользователь "raver real" <raver119@gmail.com> написал:

**Comment by raver119** [comment]
I'll add appropriate signatures to Nd4j.linspace(), as discussed with Alex

**Comment by raver119** [comment]
Implemented.
