### ISSUE TITLE
Rearchitect Nd4j's storage backend

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#148]
Currently nd4j has a DataBuffer. A DataBuffer is used to handle raw storage of data.

Data buffers have one or 2 ways of storing data called an allocation mode.

An allocation mode right now currently falls in to arrays (HEAP) and direct(Netty bytebuffers)

Bytebuffers allow us to overcome the inherent size limit of arrays(Integer.MAX_VALUE) while still keeping the speed of a linear buffer.
Bytebuffers have also proven to be faster in get and put (access operations) in element wise and scalar operations.

There is still a huge bottleneck in terms of how data buffers interact with BLAS.

Many blas backends take double[] or float[] for their parameters. Right now the way the underlying buffers are stored and passed to BLAS is via asDouble() or asFloat()

asDouble() or asFloat() can either be constant time (pass the reference to an underlying array) or O(n) to copy where n is the number of elements in the buffer.

The problem with this architecture is that NDArrays are often just views of other ndarrays.

Specifying offsets and strides when making BLAS calculations while passing the whole data buffer or underlying array is error prone at best.

My proposal is to overhaul the current interactions between blas and databuffers by:

Migrating everything to bytebuffer storage
Convert the blas based access to give us only what we need of the buffer and use that for the calculation.

This will be a huge boon in terms of speeding up something like hierarchical softmax in word2vec while allowing us to train a large lookup table.

Since we are changing how blas parameters are created, I also propose a new change for the blasbackend.

I propose a lombok based generator for better maintenance and the creation of a base backend. The base backend will handle this new storage mechanism (setting up the databuffer to be passed to blas).

Backend implementors then only have to handle implementing doGemm() -> and the like rather than handling the details specific to nd4j.

**Comment by agibsonccc** [comment]
@EronWright I know you're in to this kind of stuff. It'd be neat to hear about how this could play in with spark/hadoop number crunching.

**Comment by EronWright** [comment]
@agibsonccc I have some time tonight to reflect on it.   Then I could drop in on Saturday for some whiteboarding.

These improvements will hopefully lead to a follow-on Canova improvement project.

If you plan to make API-level breaking changes, now might be a good time to introduce an ndj4 context or session, to capture session-wide client input like RNG, backend-specific parameters, etc.    i.e. tackle the emerging 'static nd4j' problem.  Just a thought.

Finally, reduce the number of provided CPU backends if possible.

**Comment by agibsonccc** [comment]
Some more notes:

In the blas calcualtions add more robust routing (wrt the data type) doubles and floats should be transparent.

A base class should know how to route blas calculations to the proper implementation relative to the data type of the underlying buffer.

**Comment by agibsonccc** [comment]
Blas is semantically sub divided in to routine levels. This should be reflected in the newer blas wrapper api.

**Comment by agibsonccc** [comment]
Track this on the lombok branch. Pretty good progress so far. Different backends are now decoupled from the storage medium. This will allow people to say: use nio bytebuffers with jblas (even though it uses arrays)

This should free up the scalability problems we've been running in to(and also paves the way for different calculations to be run with the upcoming distributed backend)

**Comment by agibsonccc** [comment]
Done.
