### ISSUE TITLE
ND4J unit test failures

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1481]
Nd4jTestsComparisonFortran.testGemvApacheCommons
CompressionMagicTests.testMagicDecompression3
CompressionSerDeTests.testAutoDecompression1
DataSetTest.testShuffle4d:459
DataSetTest.testShuffleNd:496

Tests run: 858, Failures: 5, Errors: 0, Skipped: 19

Most likely due to recent linspace changes.

**Comment by AlexDBlack** [comment]
2 issues here:
- float precision issues when it should be an integer (no rounding should be required)
- Nd4j.linspace(anything1 ,anything2, 1) -> NaN

.testGemvApacheCommons: edge case with Nd4j.linspace(anything,anything,1) -> returns NaN
.testMagicDecompression3 and .testAutoDecompression1: looks like a precision issue - conversion of values like 11.9999999 to INT16 (or INT8 for second). Either test needs to change, or we need both int and double/float versions of linspace?
![image](https://cloud.githubusercontent.com/assets/2360237/20924329/01d0c87a-bc05-11e6-84c7-73b8bbdff70c.png)

.testShuffleNd: precision issue again with casting to int. 962.0 vs 965.9999389648438
```
        //Checking Nd dataset which is the data
        for (int dim = 1; dim < numDims; dim++) {
            //get tensor along dimension - the order in every dimension but zero should be preserved
            for (int tensorNum = 0; tensorNum < ds_data.tensorssAlongDimension(dim); tensorNum++) {
                //the difference between consecutive elements should be equal to the stride
                for (int i = 0, j = 1; j < shape[dim]; i++, j++) {
                    int f_element = ds.getFeatures().tensorAlongDimension(tensorNum, dim).getInt(i);
                    int f_next_element = ds.getFeatures().tensorAlongDimension(tensorNum, dim).getInt(j);
                    int f_element_diff = f_next_element - f_element;
                    if(f_element_diff != ds_data.stride(dim)){
                        System.out.println(ds.getFeatures().tensorAlongDimension(tensorNum, dim).getDouble(i) + "\t" + ds.getFeatures().tensorAlongDimension(tensorNum, dim).getDouble(j));
                        throw new RuntimeException();
                    }
                    assertTrue(f_element_diff == ds_data.stride(dim));
                }
            }
        }
```

**Comment by raver119** [comment]
Fixed: https://github.com/deeplearning4j/nd4j/pull/1483
