### ISSUE TITLE
List<DataSet> should be List<? extends DataSet> for greater flexibility in your methods

### ISSUE THREAD

**Issue by gforman44** [deeplearning4j/nd4j#1484]
Feedback on a snag I've hit: 

Because your ListDataSetIterator requires a **List < DataSet > **, users can't pass in a list of a _subclass_.  (I and @crockpotveggies at a minimum have subclassed DataSet.  It's a fairly common need.)

You should change things like this to take in a **List<? extends DataSet>** instead, so that it's more flexible.    

Further, it should probably be the interface DataSet rather than the concrete DataSet class, ideally, for greater flexibility.  

For now, we can work around, so this isn't high priority.  But this is an issue that probably applies to many APIs in the code, and you'll want to start using List<? extends Type> everywhere, when the codebase matures.  A Java "fine point" (read generics nuissance). 

Hope this helps,
   George

**Comment by agibsonccc** [comment]
Will look closer at this - re: the iterator. Some of these small changes sound like a great candidate for a pull request.

**Comment by huitseeker** [comment]
Fix in https://github.com/deeplearning4j/deeplearning4j/pull/3474
