### ISSUE TITLE
BooleanIndexing.applyWhere(...) uses float precision even on double precision INDArrays

### ISSUE THREAD

**Issue by StillNoNumber** [deeplearning4j/nd4j#1488]
As simple as it sounds, BooleanIndexing.applyWhere(...)'s Java implementation always uses floats. This line of code is to blame for the loss of precision:

```to.putScalar(coord[0], dynamic.apply(to.getDouble(coord[0])).floatValue());```
[BooleanIndexing.java](https://github.com/deeplearning4j/nd4j/blob/a928bb0133a39543b4b8766de6ab942edb5ba84e/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/BooleanIndexing.java#L227-L227) lines 213 and 246

**Comment by StillNoNumber** [comment]
Also happens with the (CPU, OS X) native implementation when I use a BasicCondition like this:

```INDArray test = Nd4j.create(new double[] {Double.NaN, Double.POSITIVE_INFINITY, Double.NEGATIVE_INFINITY, 0});
BooleanIndexing.applyWhere(test, Conditions.isInfinite(), -Float.MAX_VALUE);
System.out.println(test);```
Works correctly when using -Float.MAX_VALUE, but not with -Double.MAX_VALUE.

**Comment by StillNoNumber** [comment]
Seems that this is spread throughout some other parts of the code as well. Float precision will also go lost in Nd4j.create(...) and on some basic operations (CPU native, OS X, 0.7.1):
```System.out.println(Float.MAX_VALUE * 2d); // expected 6.805646932770577E38, output 6.805646932770577E38
System.out.println(Nd4j.create(new double[] {Float.MAX_VALUE})); // expected 3.4028235E38, output 3.4028235E38
System.out.println(Nd4j.create(new double[] {Float.MAX_VALUE * 2d})); // expected 6.805646932770577E38, output inf
System.out.println(Nd4j.create(new double[] {Float.MAX_VALUE}).mul(2)); // expected 6.805646932770577E38, output inf```

**Comment by raver119** [comment]
First message is a bug, you're right.

But second one isn't. When you create indarray from double[] - it gets downgraded to float. We have our own data type management.

Nd4j.dataType() and Nd4j.setDataType() available for that.

**Comment by raver119** [comment]
Original issue fixed here: https://github.com/deeplearning4j/nd4j/pull/1157

Thanks for highlighting.
