### ISSUE TITLE
Android Support Tutorial?

### ISSUE THREAD

**Issue by mikeholler** [deeplearning4j/nd4j#1490]
I've been looking for examples of this library being used with Android and although I have read it is compatible, I've not found any good examples of what needs to be done to include it.

From what I understand, nd4j calls to native libraries. Do these libraries need to be included somehow with and Android project? I'm used to Android needing some special treatment, so I'm skeptical when it seems like a native library like this "just works" with Android.

Thanks for your help,

Mike

**Comment by agibsonccc** [comment]
All code should just be the same, same adding a backend: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.nd4j%22%20AND%20a%3A%22nd4j-native%22 (android-arm), if you've never seen a backend before: http://nd4j.org/backend.html

**Comment by saudet** [comment]
@mikeholler Yes, adding http://search.maven.org/remotecontent?filepath=org/nd4j/nd4j-native/0.7.1/nd4j-native-0.7.1-android-arm.jar as dependency should "just work". If it doesn't, some reasons for that are documented here:
https://github.com/bytedeco/javacpp-presets/wiki/Issues-with-Build-Tools
https://github.com/bytedeco/javacpp-presets/wiki/The-UnsatisfiedLinkError-X-File-%28a-real-experience%29
If that still doesn't it get it working on your device, please let us know.
