### ISSUE TITLE
False calculation results for mmul in combination with slice(x), getRow(x), get Column(x) and tranpose() as first or second

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#150]
Demonstration example shows that there are different results for same operation. The last one is correct and similar to numpy. Here is the example.

INDArray x = Nd4j.rand(new int[]{2, 3,3});
		INDArray y = Nd4j.rand(3,4);
		INDArray z = Nd4j.create(3,2);
		z.putColumn(0, y.getColumn(0));
		z.putColumn(1, y.getColumn(2));
		System.out.println("x s0:" + x.slice(0));
		System.out.println(x.slice(0).mmul(z));
		
		INDArray sliceOfx=Nd4j.create(3,3);
		for (int i = 0; i < sliceOfx.linearView().length(); i++) {
			sliceOfx.put(i, x.slice(0).linearView().getScalar(i));
		}
		System.out.println("sliceOfx:"+sliceOfx);
		System.out.println(sliceOfx.mmul(z));

I debuged my whole project during the last two days against numpy results and found similar issues for the following operations:

getRow()/get Column and mmul:
INDArray temp_pos = temp_pos_all.getRow(k);
temp_pos.mmul(x); --> false result

mmul and tranpose:
temp_pos.mmul(x.tranpose()); --> false result

slice(x).tranpose().mmul(y) --> false result

I hope you can fix that error fast, please that I can run my project. You can find the mention errors of my project in the computeAt() function, mostly commented as BAM BAM BAM (https://github.com/c0der1337/Neural_Tensor_Network_For_KB_Completion/blob/master/src/NTN.java). 

Please let me know, when you fixed it and I will validate it again with python.

**Comment by agibsonccc** [comment]
I believe this is fixed. I'll add a unit test if this is still a problem though.

**Comment by c0der1337** [comment]
Hey adam, I checked it again and the calculation is stil false


From numpy:
In [31]: x[:,:,0]
Out[31]:
array([[ 0.12416201,  0.69573673,  0.53352316],
       [ 0.31312146,  0.58207025,  0.1932581 ],
       [ 0.87439873,  0.56029402,  0.2883761 ]])

In [32]: z
Out[32]:
([-0.5811914547732105, -0.9155495658618644],
 [-1.811871911345235, -0.6723976107028405],
 [1.3119959627460622, 1.9055709650931043])

In [33]: np.dot(x[:,:,0],z)
Out[33]:
array([[-0.6327675 ,  0.43517806],
       [-0.98306641, -0.30979384],
       [-1.1450258 , -0.62777462]])
-----

Code:
INDArray x = Nd4j.rand(new int[]{2, 3,3});
		INDArray y = Nd4j.rand(3,3);
		INDArray z = Nd4j.create(3,2);
		z.putColumn(0, y.getColumn(0));
		z.putColumn(1, y.getColumn(1));
		System.out.println("x s0:" + x.slice(0));
		System.out.println("y:" + y);
		System.out.println("z:" + z);
		System.out.println(x.slice(0).mmul(z));

		    INDArray sliceOfx=Nd4j.create(3,3);
		    for (int i = 0; i < sliceOfx.linearView().length(); i++) {
		        sliceOfx.put(i, x.slice(0).linearView().getScalar(i));
		    }
		    System.out.println("sliceOfx:"+sliceOfx);
		    System.out.println(sliceOfx.mmul(z));

Output:
x s0:[[0.12416200558051349, 0.6957367268336705, 0.5335231618638108]
 [0.3131214644536495, 0.5820702527101504, 0.19325810332436566]
  ,[0.8743987313940291, 0.5602940222206403, 0.28837609767116223]]

y:[[-0.5811914547732105, -0.9155495658618644, 0.2410630509310395]
 [-1.811871911345235, -0.6723976107028405, -0.14562650260183577]
  ,[1.3119959627460622, 1.9055709650931043, -1.7793051335863221]]

z:[[-0.5811914547732105, -0.9155495658618644]
 [-1.811871911345235, -0.6723976107028405]
  ,[1.3119959627460622, 1.9055709650931043]]

[[0.6044568476797607, 1.124449413167781]
 [-1.2392890229692826, -0.10584008224986441]
  ,[-0.7736506491453845, 0.3195219905291746]]

sliceOfx:[[0.12416200339794159, 0.6957367062568665, 0.5335231423377991]
 [0.3131214678287506, 0.5820702314376831, 0.1932581067085266]
  ,[0.8743987083435059, 0.5602940320968628, 0.2883760929107666]]

[[-0.6327674823622879, 0.43517804197123966]
 [-0.9830663684107382, -0.3097938198999567]
  ,[-1.1450258065532406, -0.6277746166093147]]


Only the second output of nd4j, after an iteration over the slice,is similar to numpy / correct. Please take a look again, I would be very happy if it works :-) Thanks in advance!

**Comment by agibsonccc** [comment]
Do me a favor when reporting bugs like this, make them reproducible with setting a seed, also please get them in this format:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-tests/src/test/java/org/nd4j/linalg/NDArrayTestsFortran.java#L214-214

I want to be able to drop them in to the tests and just run an assert equals.

Thanks!

**Comment by c0der1337** [comment]
Sure, as discussed, above is the bug in a reproducible linspace version:

 DataBuffer data = Nd4j.linspace(1, 10, 18).data();
	        INDArray x2 = Nd4j.create(data, new int[]{2,3,3});
	        System.out.println(x2);
	        data = Nd4j.linspace(1, 12, 9).data();
	        INDArray y2 =  Nd4j.create(data, new int[]{3,3});
	        INDArray z2 = Nd4j.create(3,2);
	        z2.putColumn(0, y2.getColumn(0));
	        z2.putColumn(1, y2.getColumn(1));
	        System.out.println("Slice 0 of x2: "+x2.slice(0));
	        System.out.println("z2: "+z2);
	        System.out.println("false mmul: "+ x2.slice(0).mmul(z2));
	        
	        INDArray sliceOfx2=Nd4j.create(3,3);
		    for (int i = 0; i < sliceOfx2.linearView().length(); i++) {
		        sliceOfx2.put(i, x2.slice(0).linearView().getScalar(i));
		    }
		    System.out.println("correct mmul: "+sliceOfx2.mmul(z2));

Output:
[[[1.0, 4.176470588235294, 7.352941176470589]
 [2.0588235294117645, 5.235294117647059, 8.411764705882351]
  ,[3.1176470588235294, 6.294117647058824, 9.470588235294118]]
[[1.5294117647058822, 4.705882352941176, 7.88235294117647]
 [2.588235294117647, 5.764705882352941, 8.941176470588236]
  ,[3.647058823529412, 6.823529411764706, 10.0]]

Slice 0 of x2: [[1.0, 4.176470588235294, 7.352941176470589]
 [2.0588235294117645, 5.235294117647059, 8.411764705882351]
  ,[3.1176470588235294, 6.294117647058824, 9.470588235294118]]

z2: [[1.0, 5.125]
 [2.375, 6.5]
  ,[3.75, 7.875]]

false mmul: [[22.808823529411764, 54.83823529411765]
 [26.580882352941174, 65.16176470588235]
  ,[30.352941176470587, 75.48529411764706]]

correct mmul: [[38.49264693260193, 90.17647057771683]
 [46.03676676750183, 110.8235342502594]
  ,[53.58088368177414, 131.47059106826782]]

**Comment by agibsonccc** [comment]
Will look in to this. Tip btw:
            sliceOfx2.put(i, x2.slice(0).linearView().getScalar(i));


Should be putScalar(i,...getDouble(i));

You created n NDArrays when you did this. I will work on some optimization notes on what to use. Avoiding object creation is a must. 

Also, no for loops! Use assign(INDArray)

**Comment by agibsonccc** [comment]
This is fixed now.

**Comment by c0der1337** [comment]
Hi Adam, thanks for the fast fix, but it is only fixed for slice(0). Can you please also fix slice(1) and slice(2) ... slice(n) :-)

here is an example for verficiation:

DataBuffer data = Nd4j.linspace(1, 10, 18).data();
        INDArray x2 = Nd4j.create(data, new int[]{2,3,3});
        System.out.println(x2);
        data = Nd4j.linspace(1, 12, 9).data();
        INDArray y2 =  Nd4j.create(data, new int[]{3,3});
        INDArray z2 = Nd4j.create(3,2);
        z2.putColumn(0, y2.getColumn(0));
        z2.putColumn(1, y2.getColumn(1));
        System.out.println("Slice 0 of x2: "+x2.slice(0));
        System.out.println("z2: "+z2);
        System.out.println("false mmul: "+ x2.slice(0).mmul(z2));
        
        INDArray sliceOfx2=Nd4j.create(3,3);
	    for (int i = 0; i < sliceOfx2.linearView().length(); i++) {
	        sliceOfx2.putScalar(i, x2.slice(0).getDouble(i));
	    }
	    System.out.println("correct mmul: "+sliceOfx2.mmul(z2));
	    
	    System.out.println("false mmul: "+ x2.slice(1).mmul(z2));
        INDArray slice2Ofx2=Nd4j.create(3,3);
	    for (int i = 0; i < slice2Ofx2.linearView().length(); i++) {
	        slice2Ofx2.putScalar(i, x2.slice(1).getDouble(i));
	    }
	    System.out.println("correct mmul: "+slice2Ofx2.mmul(z2));
Output:
false mmul: [[38.49264705882353, 90.1764705882353]
 [46.03676470588235, 110.8235294117647]
  ,[53.58088235294118, 131.47058823529412]]

correct mmul: [[38.49264705882353, 90.1764705882353]
 [46.03676470588235, 110.8235294117647]
  ,[53.58088235294118, 131.47058823529412]]

false mmul: [[49.80882352941177, 121.1470588235294]
 [57.352941176470594, 141.79411764705884]
  ,[23.42647058823529, 75.35294117647058]]

correct mmul: [[42.26470588235294, 100.5]
 [49.80882352941177, 121.1470588235294]
  ,[57.352941176470594, 141.79411764705884]]



For slice 0 the both results are the same, by slice(1) its still different

**Comment by agibsonccc** [comment]
Nope this passes.

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-tests/src/test/java/org/nd4j/linalg/NDArrayTestsFortran.java#L120

**Comment by c0der1337** [comment]
Hey Adam,

for me it seems there is an error in the assertequals() function caused by maybe false ordering or storing of the values. I dont know what is going wrong. The assertequals() function does not detect the difference. Look there, I used the junit code and added 3 print out at the end:
zeroOffsetResult: [[38.49264705882353, 90.1764705882353]
 [46.03676470588235, 110.8235294117647]
  ,[53.58088235294118, 131.47058823529412]]

offsetResult: [[38.49264705882353, 90.1764705882353]
 [46.03676470588235, 110.8235294117647]
  ,[53.58088235294118, 131.47058823529412]]

noOffsetResult: [[42.26470588235294, 100.5]
 [49.80882352941177, 121.1470588235294]
  ,[57.352941176470594, 141.79411764705884]]

slice1OffsetResult: [[49.80882352941177, 121.1470588235294]
 [57.352941176470594, 141.79411764705884]
  ,[23.42647058823529, 75.35294117647058]]

assertequals says equal, but they are not. The values are equal, but the positions of the values are not as expected. Would be cool if you could fix that soon... thanks in advance. I used the latest version of nd4j.

code with print outs:
DataBuffer data = Nd4j.linspace(1, 10, 18).data();
       INDArray x2 = Nd4j.create(data, new int[]{2,3,3});
       data = Nd4j.linspace(1, 12, 9).data();
       INDArray y2 = Nd4j.create(data, new int[]{3,3});
       INDArray z2 = Nd4j.create(3,2);
       z2.putColumn(0, y2.getColumn(0));
       z2.putColumn(1, y2.getColumn(1));
       INDArray nofOffset = Nd4j.create(3,3);
       nofOffset.assign(x2.slice(0));

       INDArray slice0 = x2.slice(0);
       INDArray zeroOffsetResult = slice0.mmul(z2);
       INDArray offsetResult = nofOffset.mmul(z2);
       System.out.println("zeroOffsetResult: "+zeroOffsetResult);
       System.out.println("offsetResult: "+offsetResult);

       INDArray slice1 = x2.slice(1);
       INDArray noOffset2 = Nd4j.create(slice1.shape());
       noOffset2.assign(slice1);
       INDArray noOffsetResult = noOffset2.mmul(z2);
       INDArray slice1OffsetResult = slice1.mmul(z2);
       System.out.println("noOffsetResult: "+noOffsetResult);
       System.out.println("slice1OffsetResult: "+slice1OffsetResult);
       System.out.println("noOffsetResult is equal: "+noOffsetResult.equals(slice1OffsetResult));
