### ISSUE TITLE
Nd4j.Vstack() with row- or column vector returns only zeros and not the numbers of the initial vectors

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#151]
if there is only a vector that has one row or one column (row or column vector), vstack does not work as expected and consists of zeros. Expected result would be the two vectors stacked as in numpy.
		
INDArray z = Nd4j.create(3,2);
		z.putColumn(0, y.getColumn(0));
		z.putColumn(1, y.getColumn(2));
		System.out.println(Nd4j.vstack(z.getColumn(0),z.getColumn(1)));

Output:
[[0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0]]

**Comment by agibsonccc** [comment]
Could you post a complete example please? I should be able to drop these things right in to my editor and turn around a fix.

**Comment by c0der1337** [comment]
INDArray z = Nd4j.create(3,2);
INDArray y = Nd4j.create(3,4);
z.putColumn(0, y.getColumn(0));
z.putColumn(1, y.getColumn(2));
System.out.println(Nd4j.vstack(z.getColumn(0),z.getColumn(1)));

Output:
[[0.0,
0.0,
0.0,
0.0,
0.0,
0.0]]

Expected output are the two stacked column vectors and not only zeros.

**Comment by agibsonccc** [comment]
The put/gets here are pointless. Everything here is only zeros regardless.

**Comment by agibsonccc** [comment]
The underlying bug had nothing to do with vstack. It was related to the fact that getScalar and the like weren't returning views of the same buffer. This is fixed now.
