### ISSUE TITLE
Add hard sigmoid and derivative

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1511]
```f(x) = min(1, max(0, 0.2*x + 0.5))```
or equivalently: clip 0.2*x+0.5 to range 0 to 1
where clipping bounds are -2.5 and 2.5

Hard sigmoid derivative:
f'(x) = 
    0 if x < -2.5 or x > 2.5
    0.2 otherwise

**Comment by raver119** [comment]
Implemented
