### ISSUE TITLE
Initialisation Error in Nd4j.zeros while using GPU

### ISSUE THREAD

**Issue by bikashg** [deeplearning4j/nd4j#1519]
I have the following error :

https://gist.github.com/bikashg/103719eec116bd6600df1ddd83b30035

for the statement : 
INDArray featuresValues = Nd4j.zeros(exampleSize,inputLayerNodesCount);

when using a GPU : 
NVIDIA Corporation GK107GL [Quadro K600] (rev a1)

on Ubuntu 14.04.3 LTS

BUT, I can run the program successfully on CPU.

**Comment by raver119** [comment]
```
Caused by: java.lang.RuntimeException: No CUDA devices were found in system
```

I'm not sure what i could say here - CUDA driver say there's no GPU available.

**Comment by raver119** [comment]
Can you run deviceQuery on your system and post it's output here?

deviceQuery is available in CUDA samples, you've got together with CUDA Toolkit during installation

**Comment by bikashg** [comment]
This was clearly a case of buggy CUDA configuration/setup on my system and I couldn't fix it now. I prefer to close this thread though, because the problem is not related to nd4j
