### ISSUE TITLE
Error in row wise subtraction?

### ISSUE THREAD

**Issue by hellrich** [deeplearning4j/nd4j#152]
There seems to be an error in row wise vector subtraction.
Given the following operation:
[2.0, 2.0]
[2.0, 2.0]
[2.0, 2.0] - [0.0, 1.0]

One would expect the result to be:
[2.0, 1.0]
[2.0, 1.0]
[2.0, 1.0]
 
Yet using INDArray.subRowVector and the jblas backend it is:
[2.0, 1.0]
[1.0, 2.0]
[1.0, 2.0]

The error does not occur during addition. I looks like the sum of all vector entries is being subtracted from the first entry in every row besides the first, e.g. subtracting [-1,1] leaves every row after the first unchanged.

**Comment by sheepdreamofandroids** [comment]
This is shown with the following unit test in NDArrayTestsFortran (only happens with destination matrix in fortran order):

    @Test
    public void testSubiRowVector() throws Exception {
        INDArray oneThroughSix = Nd4j.linspace(1, 6, 6).reshape(3, 2);
        INDArray row2 = Nd4j.create(new float[]{1,2}, new int[]{1, 2});
        oneThroughSix.subiRowVector(row2);
        INDArray res = Nd4j.create(new float[]{0,1,2,2,3,4}, new int[]{3, 2});
        assertEquals(res, oneThroughSix);
    }

In BlasWrapper is method     public INDArray axpy(float da, INDArray dx, INDArray dy)   which uses hardcoded strides 1 which is obviously wrong for fortran ordering.

**Comment by sheepdreamofandroids** [comment]
Also, I'm pretty sure that BaseNDArray.vectorAlongDimension(r,1) is creating the wrong strides for the destination row. But I can't really wrap my head around that method.

**Comment by agibsonccc** [comment]
Thanks this is really helpful. This should be an easy fix. I've just merged the new blas/databuffer interactions which should allow for condensing some of these operations.

**Comment by agibsonccc** [comment]
I've switched the subtraction over to use the opexecutioner infrastructure. Take a look and see if this fixes it. Feel free to verify yourself. I need to do a bit more extensive testing but I see tests passing on my side.
