### ISSUE TITLE
More broadcast issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1520]
I've added 2 new broadcasting tests: both are failing for some broadcast dimensions, but passing for others.
Nd4jTestsC.testBroadcast3d2d() and testBroadcast4d2d()
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L3361

**Comment by raver119** [comment]
Should be triaged on current master.
