### ISSUE TITLE
TAD equality between Java & Native side

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1525]
Right now TAD shapes calculated on Java & native side are ***not*** equal.

```
Original array shape:  [3, 2, 3, 5, 15, 5, 1, 0, 1, 99];
TAD dimensions: [0, 2]
native tad TAD: [2, 5, 2, 1, 15, 0, 1, 99];
java TAD: [2, 2, 5, 15, 1, 0, -1, 99]
```

It wasn't caught earlier due to lack of tests/use where's multiple tads mattered, but now Alex added test for multidimensional broadcast, and this problem was highlighted. Right now broadcasts were triaged by using swapped ind2sub/ind2subC, but it would be nice to provide equality for TADs between java & native code.

**Comment by raver119** [comment]
Here's test for it: https://github.com/deeplearning4j/nd4j/blob/6da924b761d0906d64b101823120795a4b02023f/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/shape/TADTests.java#L41-L41

**Comment by agibsonccc** [comment]
This has been fixed.
