### ISSUE TITLE
Feature request: public interfaces for future distributed storage model

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#154]
Please, consider some kind of public interfaces for distributed storage, so it would be possible to add custom storage like mongo/orientb/whatever manually.

**Comment by agibsonccc** [comment]
There was some discussion around the pistachio addition. The idea would be to be able to plug different distributed backends into this.

Right now, the baseline feature is to implement blas on top of pistachio to use it as a parameter server.

Still need to wait for pistachio to end up in maven central before I'll move on this yet.

**Comment by agibsonccc** [comment]
We have this done with parameter server addition.
