### ISSUE TITLE
0.7.1 in Ubuntu 14.04 fails to load

### ISSUE THREAD

**Issue by devlop16** [deeplearning4j/nd4j#1542]
A simple:
```
INDArray z = Nd4j.create(3,2);
```

With a POM 
```
     <dependency>
     <groupId>org.nd4j</groupId>
     <artifactId>nd4j-native-platform</artifactId>
     <version>0.7.1</version>             
     </dependency>
```
Fails with error:
```
java.lang.ExceptionInInitializerError
	org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:16)
	org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:9)
	org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:38)
	sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	java.lang.Class.newInstance(Class.java:442)
	org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5444)
	org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5352)
	org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:186)
	org.Test.Test(Test.java:121)
root cause

java.lang.NullPointerException
	org.bytedeco.javacpp.Loader.cacheResource(Loader.java:334)
	org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:772)
	org.bytedeco.javacpp.Loader.load(Loader.java:604)
	org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:37)
	org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:16)
	org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:9)
	org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:38)
	sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	java.lang.Class.newInstance(Class.java:442)
	org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5444)
	org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5352)
	org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:186)
	org.Test.Test(Test.java:121)

```

**Comment by raver119** [comment]
Please, show full pom.xml, not just a single dependency

**Comment by devlop16** [comment]
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org</groupId>
  <artifactId>Test</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>Test</name>
  


  
  <url>http://maven.apache.org</url>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>2.3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
  
        
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    
    
   

    <dependency>
    <groupId>javax.json</groupId>
    <artifactId>javax.json-api</artifactId>
    <version>1.0</version>
</dependency>
   
        
      <dependency>
     <groupId>org.nd4j</groupId>
     <artifactId>nd4j-native-platform</artifactId>
     <version>0.7.1</version>             
     </dependency>
  <dependency>
     <groupId>org.deeplearning4j</groupId>
     <artifactId>deeplearning4j-core</artifactId>
     <version>0.7.1</version>
   </dependency>
        
      
  
             <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.10.4</version>
           
        </dependency>


<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.4.4</version>    

        </dependency>


   <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-mllib_2.10</artifactId>
            <version>1.4.0</version>

        </dependency>
                                             
   <dependency>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-core_2.10</artifactId>
      <version>1.4.0</version>
      
      <exclusions>
         <exclusion>
         <groupId>javax.servlet</groupId>
         <artifactId>servlet-api</artifactId>
         </exclusion>         
      </exclusions>
   </dependency>   
     
     
     
     <dependency>
     <groupId>org.deeplearning4j</groupId>
     <artifactId>dl4j-spark</artifactId>
     <version>0.4-rc3.8</version>     
   </dependency>              
        
 
                   
   
   <dependency>
	<groupId>net.lingala.zip4j</groupId>
	<artifactId>zip4j</artifactId>
	<version>1.3.1</version>
</dependency>
   <dependency>
	<groupId>org.apache.ant</groupId>
	<artifactId>ant</artifactId>
	<version>1.8.2</version>
</dependency>
  </dependencies>
</project>

**Comment by devlop16** [comment]
Ubuntu 14.04.5 LTS

**Comment by raver119** [comment]
```
  <version>0.4-rc3.8</version>    
```

See that in your pom.xml?

**Comment by devlop16** [comment]
The error continues if last dependency was changed to 
       ```
 <dependency>
     <groupId>org.deeplearning4j</groupId>
     <artifactId>dl4j-spark_2.10</artifactId>
     <version>0.7.1</version>     
   </dependency> 
```

**Comment by saudet** [comment]
This is just caused by not having a home directory with write permission:
https://github.com/bytedeco/javacpp/blob/1.3/src/main/java/org/bytedeco/javacpp/Loader.java#L334
Will be fixed in next release by falling back on the tmp directory, but for now just set the "org.bytedeco.javacpp.cachedir" system property to some directory where you have write permission.

**Comment by devlop16** [comment]
Thanks @saudet This solves the issue
System.setProperty("org.bytedeco.javacpp.cachedir", "/yourfolder");
