### ISSUE TITLE
Nd4j.argMax return wrong result

### ISSUE THREAD

**Issue by djken2006** [deeplearning4j/nd4j#1544]
double[] ds = new double[] { -2.0, -1.0 };
INDArray nd = Nd4j.create(ds);
INDArray r = Nd4j.argMax(nd, 1);
System.out.println(r);

result is 0.00

**Comment by raver119** [comment]
Please consider upgrading to 0.7.1 version 

Отправлено с iPhone

**Comment by raver119** [comment]
1.00

That's what i get on current master as well
