### ISSUE TITLE
Documentation - rebuild project after version bump

### ISSUE THREAD

**Issue by EdeMeijer** [deeplearning4j/nd4j#1552]
I wasted some time trying to figure out why I was getting the issue about missing annotations from the shaded Jackson module, since I ignored it properly in my IDE. Turned out that after the version changes (in this case from 0.7.2 to 0.7.3), you really have to rebuild the project, otherwise the generated pom.xml with reduced dependencies still point to the old version and will not be properly ignored. Something to add to the building from source article.

**Comment by tomthetrainer** [comment]
When building locally from source, we recommend a clean install of everything, 

See.. https://deeplearning4j.org/buildinglocally

If someone followed those instructions would they still have to rebuild the project as you describe here.

**Comment by EdeMeijer** [comment]
Yes, that's absolutely true. The thing is, I've been using the master branch for several months now and actively pulling updates (and contributing fixes and features). In this workflow, 99% of the time just running git pull does the trick and you don't need to rebuild anything, as IntelliJ does most of the work like downloading new dependencies or new versions on the fly. Sometimes though, it doesn't work automatically, and that's where I got stuck. So I guess it's more of a friendly reminder for people already having built everything from source and using master that sometimes you might have to rebuild things again according to those docs.

**Comment by tomthetrainer** [comment]
We appreciate your contributions, so to be clear here this would be an appropriate patch to the docs on this page. 

https://deeplearning4j.org/buildinglocally

"* Note, if you are tracking master updates in git, remember to rebuild the project after any changes. If you do not rebuild subtle dependency management issues may result."

If that documentation change would be a satisfactory fix, go ahead and close, and I will edit that page today.
