### ISSUE TITLE
Should CachingDataSetIterator delegate the preProcessor?

### ISSUE THREAD

**Issue by vjames19** [deeplearning4j/nd4j#1553]
Currently, the CachingDataSetIterator preProcesses the data every time [next()](https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/api/iterator/CachingDataSetIterator.java#L145) is called, meaning it will get preProcessed on every epoch.

If the preProcessor is delagated to the sourceIterator, then preProcessing logic can be removed from the CachingDataSetIterator and it would only be calculated once.

Is there a reason for its current behavior? If not, I would love to submit a PR for the change.

**Comment by raver119** [comment]
Yes, that definitely looks like logic flaw in current implementation.

**Comment by raver119** [comment]
If you're going to provide fix for it - please do that, otherwise i'll pick it up.

**Comment by vjames19** [comment]
Yes, I'll link the PR to the issue.
