### ISSUE TITLE
No available [HOST] memory

### ISSUE THREAD

**Issue by ZhongBaby** [deeplearning4j/nd4j#1556]
I got no available host memory warning while I think I have enough memory for JVM/GPU.
![1](https://cloud.githubusercontent.com/assets/8222739/21537350/86a3505e-cdcb-11e6-8582-6859c8f4c8f5.jpg)
![2](https://cloud.githubusercontent.com/assets/8222739/21537352/879f5836-cdcb-11e6-944a-1c29e0c1caa9.jpg)

(1)[Stack dump](https://gist.github.com/ZhongBaby/54f0e61879b25ad8a8ccfadadcf904f2)
**Update1**
(2)My project is on [coding.net](https://coding.net/u/ZhongBaby/p/kaggle_start/git).

**Comment by raver119** [comment]
But according to your log - you don't have enough ram. This warning is issued when app gets close to  Xmx threshold. In your case threshold is 8GB. For decent model with decent inputs - you might need higher values obviously.

**Comment by ZhongBaby** [comment]
Ok, I will try.
