### ISSUE TITLE
GC - poor performance with static word vectors + CUDA

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1559]
nd4j-cuda-8.0 + Windows 10 + Cuda 8.0.44
GTX970 + 5960x @ 4GHz

Seeing excessive CPU usage + slow training performance when running a version of the w2v sentiment example on Windows

https://gist.github.com/AlexDBlack/3ea3d6faa0d003bbf985fd415a547634

![image](https://cloud.githubusercontent.com/assets/2360237/21565261/b94b9c9a-cee9-11e6-8fed-11f56c2a5a9a.png)

Earlier in training:
![image](https://cloud.githubusercontent.com/assets/2360237/21565274/dbe34fd2-cee9-11e6-9f7b-45676f0f0448.png)

Later in training:
![image](https://cloud.githubusercontent.com/assets/2360237/21565278/ebbf5982-cee9-11e6-97e0-8526c49b2d63.png)

**Comment by raver119** [comment]
Yep, one more case of JVM GC.

https://github.com/deeplearning4j/deeplearning4j/issues/2422

**Comment by raver119** [comment]
https://github.com/deeplearning4j/nd4j/pull/1731

**Comment by AlexDBlack** [comment]
Closing this on acconut of workspaces being implemented some time ago.
