### ISSUE TITLE
Backend initialization

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1561]
Since 0.7.2 backend initialization procedure was changed, and all out of sudden CudaEnvironment bean now requires Nd4j backend being initialized prior to configuration calls.

https://github.com/deeplearning4j/nd4j/issues/1560

**Comment by wmeddie** [comment]
As a consequence of the Nd4j.create(1) workaround however, directives like useDevice seem to do nothing.

**Comment by raver119** [comment]
This issue supposed to be fixed long ago.
