### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no jniopenblas in java.library.path

### ISSUE THREAD

**Issue by markWZX** [deeplearning4j/nd4j#1564]
I just use dl4j-examples to train network on **win10-64 bit**, but it has some errors.
on linux ,it runs correctly.

java version: 1.8.0_111
dl4j version:0.7.2

All Exceptions: https://gist.github.com/markWZX/3f05f1638ab4bf4397458610bd383af3

pom.xml https://gist.github.com/markWZX/f4fdb9108fd44e133ed277797ad502cc

And refered to @agibsonccc  I change nd4j-native to nd4j-native-platform, It also doesn't work.

@raver119 He mentioned that if there is any math software in my PC. Yeah, **Anaconda2** has been installed.

**Comment by saudet** [comment]
I'll check this out, but FYI, the usual workaround for this is to set the "java.library.path" to the empty string "".

**Comment by lefromage** [comment]
I have the same problem on macosx: 

adding 
-Djava.library.path=""  
to the VM option did not fix it

**Comment by raver119** [comment]
@lefromage do you have windows with anaconda installed on mac os? :) If yes - i'd like to have screenshots. If no - you probably have another issue. So file separate issue please.

**Comment by lefromage** [comment]
I have a solution for macos and probably for windows:
My problem was the same: java.lang.UnsatisfiedLinkError: no jniopenblas in java.library.path

what fixed it for me was to do this:
add this to SBT build.sbt: 
libraryDependencies += "org.bytedeco.javacpp-presets" % "openblas" % "0.2.19-1.3"

unmanagedBase := baseDirectory.value / "custom_lib"

then copy the native jar to the custom_lib directory declared above:
cp /Users/xxx/.ivy2/cache/org.bytedeco.javacpp-presets/openblas/jars/openblas-0.2.19-1.3-macosx-x86_64.jar /Users/xxx/Downloads/dl4j_local/custom_lib/

I would imagine it is the same in windows with:
/Users/xxx/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-windows-x86_64.jar

There are also other native jars: for windows, android, linux and macosx
/Users/xxx/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-android-arm.jar
/Users/xxx/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-android-x86.jar
/Users/xxx/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-ppc64le.jar
/Users/xxx/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-linux-x86_64.jar
/Users/xxx/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-macosx-x86_64.jar
/Users/xxx/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3-windows-x86_64.jar
/Users/xjxr170/.m2/repository/org/bytedeco/javacpp-presets/openblas/0.2.19-1.3/openblas-0.2.19-1.3.jar

Cheers

**Comment by saudet** [comment]
@markWZX I tried and installed both https://repo.continuum.io/archive/Anaconda2-4.2.0-Windows-x86_64.exe and https://repo.continuum.io/archive/Anaconda3-4.2.0-Windows-x86_64.exe but I am unable to reproduce this issue. Could you set the "org.bytedeco.javacpp.logger.debug" system property to "true" and show me what you get on the console or in the log? Thanks!

**Comment by saudet** [comment]
@lefromage That sounds more like a problem with sbt than Mac OS X. Could you open another issue and provide some sample project files to reproduce this issue? Thank you

**Comment by markWZX** [comment]
@saudet I just fix that error. This is not about Nd4j and system platforms. It's the maven path problem.
The problem is that my maven repository path ".m2" contains a strange symbol due to my system username "Mark Wang".  Obviously, it contains a blank. UrlDecoder will decode " " into "%20", but the system Explorer or Finder can't recognize it and find the need file. When I change a username without blanks, it runs correctly.

**Comment by saudet** [comment]
@markWZX Oh, that's a bit strange, that'd be a bug in JavaCPP. Thanks for pointing this out

**Comment by biswadeb** [comment]
I am running DL4J on MS Windows 7 with Java 8. I simply followed the instructions as described in the Quick Start Guide using GIT, IntelliJ and maven. In my case the problem was resolved by removing the environment variables pointing to the Anaconda installation included in the PATH environment variables specified.
