### ISSUE TITLE
Get the first/last non-zero element along a dimension

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1567]
A useful tool (for handling mask arrays, one-hot vectors etc) would be to allow users to get index of the first or last non-zero element.

Or more generally, get the index of the first or last element (along a dimension) that matches some condition.

(We could also implement the value (non-index) version too: i.e., get the first/last *value* that matches some condition).

**Comment by raver119** [comment]
I think method in BooleanIndexing with configurable condition would be best fit. What would you say on something like BooleanIndexing.firstMatch(INDArray, dimension, Condition)?

**Comment by AlexDBlack** [comment]
firstMatch(INDArray, int dimension, Condition) and lastMatch(...) sounds good.

Methods giving the index of the first/last index would also be good:
firstMatchIndex(INDArray, int dimension, Condition)
lastMatchIndex(INDArray, int dimension, Condition)

**Comment by raver119** [comment]
Implemented, but there's serious issue there, so we need to discuss it.
