### ISSUE TITLE
error when build nd4j

### ISSUE THREAD

**Issue by bingyupiaoyao** [deeplearning4j/nd4j#1572]
Follow the instructions in:https://deeplearning4j.org/buildinglocally
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!:nd4j-cuda-8.0,!:nd4j-cuda-8.0-platform,!:nd4j-tests'
I got:[ERROR] Could not find the selected project in the reactor: '!:nd4j-cuda-8.0

**Comment by saudet** [comment]
I'm pretty sure that `-DskipTests -pl '!nd4j-backends/nd4j-backend-impls/nd4j-cuda,!nd4j-backends/nd4j-backend-impls/nd4j-cuda-platform'` works.

**Comment by raver119** [comment]
@bingyupiaoyao that's pretty strange, because i'm successfuly using that command each and every day. Maybe you just have 7.5 defined in profile, so you should exclude 7.5 instead of 8.0

**Comment by bingyupiaoyao** [comment]
@raver119  do you use the windows platform to build? or linux? I use windows

**Comment by saudet** [comment]
`maven (3.3 or higher)` ← what about this

**Comment by bingyupiaoyao** [comment]
@saudet 
3.3.9, see the following information

H:\Workspace\Java\Git\DeepLearning4J_ALL\DL4J20170107DailyBuild\libnd4j>mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: H:\App\apache-maven-3.3.9\bin\..
Java version: 1.8.0_101, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_101\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"

------
H:\Workspace\Java\Git\DeepLearning4J_ALL\DL4J20170107DailyBuild\libnd4j>mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!nd4j-backends/nd4j-backend-impls/nd4j-cuda,!nd4j-backends/nd4j-backend-impls/nd4j-cuda-platform'
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: '!nd4j-backends/nd4j-backend-impls/nd4j-cuda @
[ERROR] Could not find the selected project in the reactor: '!nd4j-backends/nd4j-backend-impls/nd4j-cuda -> [Help 1]

**Comment by raver119** [comment]
@bingyupiaoyao i'm using 3 platforms usually: windows, linux and macos. But since i'm using cuda-8.0 on 2 of them, i have it set everywhere. In your case you might have cuda version defined as 7.5, so try the following comand:

```
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda-7.5,!org.nd4j:nd4j-cuda-7.5-platform,!org.nd4j:nd4j-tests'
```

**Comment by bingyupiaoyao** [comment]
@raver119 
The same error
H:\Workspace\Java\Git\DeepLearning4J_ALL\DL4J20170107DailyBuild\libnd4j>mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda-7.5,!org.nd4j:nd4j-cuda-7.5-platform,!org.nd4j:nd4j-tests'
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: '!org.nd4j:nd4j-cuda-7.5 @
[ERROR] Could not find the selected project in the reactor: '!org.nd4j:nd4j-cuda-7.5 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by bingyupiaoyao** [comment]
I am using:cuda_8.0.44_win10.exe

**Comment by raver119** [comment]
libnd4j <--- are you trying to build libnd4j with maven??

**Comment by raver119** [comment]
> H:\Workspace\Java\Git\DeepLearning4J_ALL\DL4J20170107DailyBuild\**libnd4j**>

**Comment by raver119** [comment]
What exactly you're trying to build? libnd4j or nd4j? i clearly see libnd4j in your path

**Comment by bingyupiaoyao** [comment]
Sorry for the mistake, indeed I have tried the nd4j first, see below
H:\Workspace\Java\Git\DeepLearning4J_ALL\DL4J20170107DailyBuild\nd4j>mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!nd4j-backends/nd4j-backend-impls/nd4j-cuda,!nd4j-backends/nd4j-backend-impls/nd4j-cuda-platform'
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: '!nd4j-backends/nd4j-backend-impls/nd4j-cuda 
[ERROR] Could not find the selected project in the reactor: '!nd4j-backends/nd4j-backend-impls/nd4j-cuda -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by bingyupiaoyao** [comment]
H:\Workspace\Java\Git\DeepLearning4J_ALL\DL4J20170107DailyBuild\nd4j>mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda-7.5,!org.nd4j:nd4j-cuda-7.5-platform,!org.nd4j:nd4j-tests'
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: '!org.nd4j:nd4j-cuda-7.5 @
[ERROR] Could not find the selected project in the reactor: '!org.nd4j:nd4j-cuda-7.5 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by bingyupiaoyao** [comment]
H:\Workspace\Java\Git\DeepLearning4J_ALL\DL4J20170107DailyBuild\nd4j>mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!:nd4j-cuda-8.0,!:nd4j-cuda-8.0-platform,!:nd4j-tests'
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: '!:nd4j-cuda-8.0 @
[ERROR] Could not find the selected project in the reactor: '!:nd4j-cuda-8.0 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by raver119** [comment]
Run the following please in ND4j folder: mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda-8.0,!org.nd4j:nd4j-cuda-8.0-platform,!org.nd4j:nd4j-tests'

And post output here.

**Comment by bingyupiaoyao** [comment]
H:\Workspace\Java\Git\DeepLearning4J_ALL\DL4J20170107DailyBuild\nd4j>mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!org.nd4j:nd4j-cuda-8.0,!org.nd4j:nd4j-cuda-8.0-platform,!org.nd4j:nd4j-tests'
[INFO] Scanning for projects...
[ERROR] [ERROR] Could not find the selected project in the reactor: '!org.nd4j:nd4j-cuda-8.0 @
[ERROR] Could not find the selected project in the reactor: '!org.nd4j:nd4j-cuda-8.0 -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

**Comment by raver119** [comment]
show me screenshot of nd4j folder please.

**Comment by bingyupiaoyao** [comment]
<img width="471" alt="1" src="https://cloud.githubusercontent.com/assets/1625353/21743195/4a4138be-d538-11e6-99a2-f03bfd134d1d.png">

**Comment by saudet** [comment]
@bingyupiaoyao Looks like you're using a shell different from MSYS2 then
