### ISSUE TITLE
repmat variant that produces a view instead of array allocation and copy

### ISSUE THREAD

**Issue by bennylut** [deeplearning4j/nd4j#1574]
Hello, 
Let me first describe a simple use-case:

Say I have a row based matrix `m` with dimensions `aXb` (i.e., a rows, b columns) and a row vector `v` of dimension `b`, I want to calculate a new column vector: `d` of dimension `a` such that for each `i in [0..a-1]` `d[i] = dist(m[i],v)` and dist is some distance function, e.g., euclidian. 

There are (at least) 2 ways that this can be achieved using nd4j that I am aware of:
```java
//first is using repmat and then performing a single vectorized operation
INDArray temp = v.repmat(a, b);
INDArray d1 = Nd4j.getExecutioner().exec(new EuclideanDistance(m, temp), 1);

//second way involves using multiple vectorized distance calculations
INDArray d2 = Nd4j.create(a);
for (int i = 0; i < a; i++) {
  d2.putScalar(i, m.getRow(i).distance2(v));
} 
```

For the input: `a=30000, b=1000` and using nd4j native-platform version 0.7.2 on my laptop
The first solution takes ~10 seconds to execute the `repmat` code and then `36` milliseconds to executed the vectorized distance.
The second solution takes total of 261 milliseconds. 

Just for comparison, the following 'vanilla-java' code takes 46 milliseconds to run:
```java
double[] d = new double[a];
for (int i=0; i<a; i++) {
    d[i] = dist(m[i], v);
}
```
where `dist` is a simple implementation of euclidean distance written purely in java.

As can be seen, if `repmat` was faster, the fastest solution was the first one (i.e., single vectorized method).
The current implementation of `repmat` actually creates and populates a new array and not only returns a "repeated view" of the current array. This takes significantly more time to execute which cause the first solution to be the slowest as it takes more than 10 seconds total.

Therefore, I would like to suggest a variant of `repmat` that only creates a "view" array without actually allocating and copying the repeated array.

In addition, I was actually very surprised that `repmat` is that slow, as the following "vanilla java" code that correspond to the given execution of `repmat` only took 41 milliseconds:
```java
double[][] temp = new double[a][b];
for (int i=0; i<a; i++) {
    System.arraycopy(v, 0, temp[i], 0, b);
}
```

**Comment by raver119** [comment]
In current NDArray design it's impossible to build such a view. But now we have optimized native ops for that, like `tile`, `repeat` etc.
