### ISSUE TITLE
nd4j build failure com.lewisd

### ISSUE THREAD

**Issue by lefromage** [deeplearning4j/nd4j#1583]
[ERROR] Failed to execute goal com.lewisd:lint-maven-plugin:0.0.11:check (pom-lint) on project nd4j: Error while performing check: No modelBuilder known for modelId 'versionProperties' -> [Help 1]

=========================================================
full output:

mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!:nd4j-cuda-8.0,!:nd4j-cuda-8.0-platform,!:nd4j-tests'
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 34 modules...
[INFO] Not installing Nexus Staging features:
[INFO]  * Preexisting staging related goal bindings found in 34 modules.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] nd4j
[INFO] nd4j-shade
[INFO] jackson
[INFO] nd4j-common
[INFO] nd4j-context
[INFO] nd4j-buffer
[INFO] nd4j-backends
[INFO] nd4j-api-parent
[INFO] nd4j-api
[INFO] nd4j-jdbc
[INFO] nd4j-jdbc-api
[INFO] nd4j-jdbc-mysql
[INFO] nd4j-native-api
[INFO] nd4j-serde
[INFO] nd4j-base64
[INFO] nd4j-jackson
[INFO] nd4j-backend-impls
[INFO] nd4j-native
[INFO] nd4j-instrumentation
[INFO] nd4j-perf
[INFO] nd4j-aeron
[INFO] nd4j-kryo
[INFO] nd4j-camel-routes
[INFO] nd4j-kafka
[INFO] nd4j-gson
[INFO] nd4j-bytebuddy
[INFO] nd4j-native-platform
[INFO] nd4j-parameter-server-parent
[INFO] nd4j-parameter-server-model
[INFO] nd4j-parameter-server
[INFO] nd4j-parameter-server-status
[INFO] nd4j-parameter-server-client
[INFO] nd4j-parameter-server-rocksdb-storage
[INFO] nd4j-parameter-server-node
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building nd4j 0.7.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ nd4j ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ nd4j ---
[INFO]
[INFO] --- lint-maven-plugin:0.0.11:check (pom-lint) @ nd4j ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] nd4j ............................................... FAILURE [  1.272 s]
[INFO] nd4j-shade ......................................... SKIPPED
[INFO] jackson ............................................ SKIPPED
[INFO] nd4j-common ........................................ SKIPPED
[INFO] nd4j-context ....................................... SKIPPED
[INFO] nd4j-buffer ........................................ SKIPPED
[INFO] nd4j-backends ...................................... SKIPPED
[INFO] nd4j-api-parent .................................... SKIPPED
[INFO] nd4j-api ........................................... SKIPPED
[INFO] nd4j-jdbc .......................................... SKIPPED
[INFO] nd4j-jdbc-api ...................................... SKIPPED
[INFO] nd4j-jdbc-mysql .................................... SKIPPED
[INFO] nd4j-native-api .................................... SKIPPED
[INFO] nd4j-serde ......................................... SKIPPED
[INFO] nd4j-base64 ........................................ SKIPPED
[INFO] nd4j-jackson ....................................... SKIPPED
[INFO] nd4j-backend-impls ................................. SKIPPED
[INFO] nd4j-native ........................................ SKIPPED
[INFO] nd4j-instrumentation ............................... SKIPPED
[INFO] nd4j-perf .......................................... SKIPPED
[INFO] nd4j-aeron ......................................... SKIPPED
[INFO] nd4j-kryo .......................................... SKIPPED
[INFO] nd4j-camel-routes .................................. SKIPPED
[INFO] nd4j-kafka ......................................... SKIPPED
[INFO] nd4j-gson .......................................... SKIPPED
[INFO] nd4j-bytebuddy ..................................... SKIPPED
[INFO] nd4j-native-platform ............................... SKIPPED
[INFO] nd4j-parameter-server-parent ....................... SKIPPED
[INFO] nd4j-parameter-server-model ........................ SKIPPED
[INFO] nd4j-parameter-server .............................. SKIPPED
[INFO] nd4j-parameter-server-status ....................... SKIPPED
[INFO] nd4j-parameter-server-client ....................... SKIPPED
[INFO] nd4j-parameter-server-rocksdb-storage .............. SKIPPED
[INFO] nd4j-parameter-server-node ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.030 s
[INFO] Finished at: 2017-01-11T00:32:21-06:00
[INFO] Final Memory: 25M/84M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.lewisd:lint-maven-plugin:0.0.11:check (pom-lint) on project nd4j: Error while performing check: No modelBuilder known for modelId 'versionProperties' -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by agibsonccc** [comment]
What's your maven version?

**Comment by lefromage** [comment]
mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: /usr/local/apache-maven-3.3.9
Java version: 9-ea, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-9-oracle
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-34-generic", arch: "amd64", family: "unix"

**Comment by lefromage** [comment]
do you think this might be java 9 causing an issue ?

**Comment by agibsonccc** [comment]
Try running on java 8 and see. The maven version looks fine.

**Comment by lefromage** [comment]
it's building fine on MacOSX with mvn built with Java 8.
so I'll try to build maven with java 8 on ubuntu now.

mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T10:41:47-06:00)
Maven home: /Users/xjxr170/Downloads/apache-maven-3.3.9
Java version: **1.8.0_60**, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

**Comment by lefromage** [comment]
java 8 worked, using both:

export JAVA_HOME=/usr/lib/jvm/java-8-oracle
sudo update-alternatives --config java

There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-9-oracle/bin/java              1091      auto mode
  1            /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java   1071      manual mode
* 2            /usr/lib/jvm/java-8-oracle/jre/bin/java          1072      manual mode
  3            /usr/lib/jvm/java-9-oracle/bin/java              1091      manual mode

Press enter to keep the current choice[*], or type selection number: 2
