### ISSUE TITLE
NaN in LossCosineProximity.computeGradient(INDArray labels, INDArray preOutput, IActivation activationFn, INDArray mask) 

### ISSUE THREAD

**Issue by HuichuanLiu** [deeplearning4j/nd4j#1586]
0/0=NaN also appears in LossCosineProximity.computeGradient(INDArray labels, INDArray preOutput, IActivation activationFn, INDArray mask). And it could be fixed by the way you did in NaN in scoreArrays(https://github.com/deeplearning4j/nd4j/pull/1582/files), they are actually the same.

**Comment by HuichuanLiu** [comment]
Precisely, in the masked part, features, labels and mask are all zeros.
```
INDArray dLda = labels.mulColumnVector(yhatL2normSq);
        dLda.subi(yhat.mulColumnVector(yhatDotyL1norm));
        dLda.diviColumnVector(yL2norm);
        dLda.diviColumnVector(yhatL2norm.mul(yhatL2normSq));
        dLda.muli(-1);
```
Hence yL2norm and  will be zero, and after dLda.diviColumnVector(yL2norm) the aLda will be an NaN.

**Comment by eraly** [comment]
Done. Thanks!
