### ISSUE TITLE
RecordReaderDataSetIterator empty on the first time using it 

### ISSUE THREAD

**Issue by AhmedSarhanDL** [deeplearning4j/nd4j#1590]
I have an issue using RecordReaderDataSetIterator, when ever i try to iterate over the data, the first time always gives me a set with one buffer holding one value, after resetting it gives me the right values.

` // ----- Load the training data -----
        SequenceRecordReader trainReader = new CSVSequenceRecordReader(0, ",");
        trainReader.initialize(new FileSplit(new File(baseDir.getAbsolutePath() + "/rvCleanTrain.csv")));
        DataSetIterator trainIter = new RecordReaderDataSetIterator(trainReader, miniBatchSize, 2, 2, true);
        // Without these lines the trainIter will give an empty set with only one variable 
		trainIter.reset();
        trainIter.hasNext();
        trainIter.next();
        trainIter.reset();`

**Comment by AhmedSarhanDL** [comment]
https://gist.github.com/AhmedSarhanDL/7d05425b5902cfa8803d1f4234be6918

**Comment by saudet** [comment]
Fixed in deeplearning4j, thanks for reporting!
