### ISSUE TITLE
Charting for ND4J

### ISSUE THREAD

**Issue by AhmedSarhanDL** [deeplearning4j/nd4j#1591]
What about extending ND4J with charting capabilities?

**Comment by raver119** [comment]
Do you have anything special in mind?

**Comment by AhmedSarhanDL** [comment]
Extending jfree charts to accept ND4J Objects?

**Comment by AlexDBlack** [comment]
There's plenty of good charting libraries out there. JFreeChart for example.
We'd rather focus on what we do well (HPC, deep learning) than investing resources in this right now

At some point in the future? Maybe. But right now adding charting isn't a priority for us. So I'll close this.

You'll see JFreeChart used in the examples. And we have some HTML charting functionality (line charts, scatter plots) in DL4J. Ask me in gitter if you want to know more about that.
