### ISSUE TITLE
NaN support for DataBuffer.Type.HALF

### ISSUE THREAD

**Issue by fahman** [deeplearning4j/nd4j#1594]
In some Network Configurations some values (what Gradient?) can be NaN. Currently this is not supported by org.nd4j.linalg.api.buffer.BaseDataBuffer that explicitly throws UnsupportedOp exception (https://github.com/deeplearning4j/nd4j/blob/master/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java#L801).

raver pointed out that NaN is actually supported by native (https://github.com/deeplearning4j/libnd4j/blob/8cbc66da8b0f66279d7cc3f11b956de90f6e8cc5/include/types/float16.h#L55)

Dunno tho what happens on CUDA tho.

**Comment by raver119** [comment]
Fixed.
