### ISSUE TITLE
Add boolean transform operations

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1595]
The following ops would be useful in some cases:
AND: (a[i] != 0 && b[i] != 0 ? 1 : 0)
OR: (a[i] != 0 || b[i] != 0 ? 1 : 0)
NOT: (a[i] == 0 ? 1 : 0)
XOR: (((a[i] == 0 && b[i] != 0) || (a[i] != 0 && b[i] == 0)) ? 1 : 0)

Edit: Transforms.and(...), Transforms.or(...) etc convenience methods would be good too.

**Comment by raver119** [comment]
Implemented, merged

https://github.com/deeplearning4j/nd4j/pull/1596
https://github.com/deeplearning4j/libnd4j/pull/356
