### ISSUE TITLE
Get Started

### ISSUE THREAD

**Issue by globalcaos** [deeplearning4j/nd4j#16]
Ok, I've deleted `quickstart.md`, merged all the redundant POM-backend explanations, and will now link the DL4J-quickstart.md to ND4J-quickstart.md.
Chris, we will need a new video soon, with some changes:
* In the POM file, we only have to include the 'default' backend, which will be Jblas. There is no need to add the API or the examples.
* The project to create from IntelliJ is a `maven-archetype-quickstart`, not a `wicket-archetype-quickstart`
* You don't need to go to the Maven central repository, too complicated. Just ask them to copy-paste the default Jblas backend dependency. Maven version check is explained in `dependencies.md` and it just informs you about what the latest version of the libraries are.
* We want them to `git clone` the nd4j-examples as a startup guide, this way they will be able to mess with it faster.
* The video should end with the execution of an example, until you can see the screen output.

**Comment by agibsonccc** [comment]
@chrisvnicholson

**Comment by chrisvnicholson** [comment]
Roger that.
ᐧ
