### ISSUE TITLE
MemcpyAsync H2H failed: [140103466419744] -> [8667232256]

### ISSUE THREAD

**Issue by n-gregori** [deeplearning4j/nd4j#1605]
@raver119 

first of all my  conf:

backend info:

CUDA version: 8.0
DL4J version: 0.7.1

hardware details:

Red Hat Enterprise Linux Server release 7.2
on aws amazon instance p2.xlarge
1 GPU Tesla k80 with 12g of memory
4 CPU 61g of memory (Intel Xeon E5-2686 v4)

XMX setting:

-J-Xmx60g

doing this operation:

`DataSet ret = new DataSet(Nd4j.vstack(inp.toArray(new INDArray[0])), Nd4j.vstack(lab.toArray(new INDArray[0])))`

i get the following exception:

https://gist.github.com/n-gregori/9f8276cc62afae569ea90c112cd1ccdb

the fastest workaround is to set ND4J_CUDA_DEBUG = true

the following code always reproduce the problem:

https://gist.github.com/1f84c62e45522059dbbcd6392ca99c5b.git
https://gist.github.com/bcf09b5bc6f4ad34d2a71054224e08bb.git

**Comment by raver119** [comment]
Yep, hot-fix/triage already applied at current master. Now proper fix is highly desired.

**Comment by raver119** [comment]
Proper fix applied and merged here: https://github.com/deeplearning4j/nd4j/pull/1617 and here: https://github.com/deeplearning4j/libnd4j/pull/363

Thanks for highlighting this issue.
