### ISSUE TITLE
DataSet merge error for CNNs.

### ISSUE THREAD

**Issue by lgp66** [deeplearning4j/nd4j#1611]
In `nd4j.linalg.dataset.DataSet.java`

An issue with the way features and labels are treated inside DataSet.merge(): There are two switch statements that process the features then the labels. The second of these (for the labels) appears to have a bug in the case where the data rank = 4. Current line 230 looks like this:

`labelsOut = merge4dCnnData(featuresToMerge);`

when it appears that it really should be:

`labelsOut = merge4dCnnData(labelsToMerge);`

This leads to later errors when training a CNN.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/1612 good find!
