### ISSUE TITLE
SEGFAULT error ?

### ISSUE THREAD

**Issue by asikist** [deeplearning4j/nd4j#1614]
Lately while deploying some experiments on our hpc cluster we are getting the following error:
[java_log](https://gist.github.com/tomdev55/9a47cb58b9e2c3fb11b6056fe7b6cae3) and
[native_log](https://gist.github.com/tomdev55/96620dee8c43abd400aa1300a25c5a9e)

The methods involving the call would try to calculate a noise for the same data in parallel. Some of those methods can be summarised in the following:
[relevant methods](https://gist.github.com/tomdev55/af8e09cfbd87a8469eff3611dad787e8)

**Comment by raver119** [comment]
I've added few simple tests, trying to mimic behavior of your app. Please check it out, and try to run it in your environment to check if it's reproducing your issue or not.


https://github.com/deeplearning4j/nd4j/blob/a2b3f41e9b7e7d86bf0e00e305f23224b9852783/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/crash/SpecialTests.java

**Comment by tomdev55** [comment]
I added 2 more tests with parallel execution as well:
[test 1](https://gist.github.com/tomdev55/0628affb1cce5268c5eb0a34558d49c5)
[test 2](https://gist.github.com/tomdev55/0e796cd968fef1716bf7d646b4318e0b)
[test 3](https://gist.github.com/tomdev55/3cfd716d775129a3bff4855c49da3ad4)

and deployed each application 100 times. No exceptions occurred and the execution finished successfully. Meanwhile by redeploying the code of the experiment (see relevant methods), I kept getting the same error. I am considering to redeploy the above tests with bigger shapes. @raver119  what do you thing about it?

**Comment by raver119** [comment]
I think we're missing something else then. Something beyond the scope you gave me. However, trying with bigger shapes won't hurt.

**Comment by huitseeker** [comment]
@tomdev55 any news on this one ?

**Comment by tomdev55** [comment]
@huitseeker 
Sorry for the late reply, 
No news on this. The error persists. It seems to do with the cluster setup, so whenever a node fails, we redeploy a new one.
