### ISSUE TITLE
use lengthLong() where possible

### ISSUE THREAD

**Issue by wobu** [deeplearning4j/nd4j#1615]
Version: 0.7.2

I am using TSNE on a Word2Vec model with 50000 x 100 shape. And this results into the exception:

`java.lang.IllegalArgumentException: Length is >= Integer.MAX_VALUE: lengthLong() must be called instead`

with shape 40000 x 100 it is working because the resulting Array length < Integer.Max

Params:
```
    val tsne = new BarnesHutTsne.Builder()
      .theta(0.0)
      .normalize(false)
      .numDimension(3)
      .perplexity(40)
      .useAdaGrad(false)
      .build()
```

i explicitley set theta to 0.0 to use the decomposed version.

see [Gist]( https://gist.github.com/wobu/555188a14ec5363f66ba7d2998e7268f) for logs and stacktraces

**Comment by raver119** [comment]
So in other words, we're getting back to known question: what we're going to do with Long Indexing :)

@agibsonccc @saudet ?

**Comment by saudet** [comment]
Wait after NVIDIA? Does this use BLAS?

**Comment by raver119** [comment]
Yes, TSNE relies on gemm as everything in ml... :(

**Comment by huitseeker** [comment]
Note for the future, @crockpotveggies has had to use conversions HDF5 -> int indexes that should one day be removed : https://github.com/crockpotveggies/deeplearning4j/commit/cc2f63d116c5f02a970f383c86e70ec2b79b7f42

**Comment by raver119** [comment]
We should just get rid of int indexes :(

Closing this issue now, new one is opened: https://github.com/deeplearning4j/nd4j/issues/1662
