### ISSUE TITLE
Undesirable behavior/bug in MiniBatchFileDataSetIterator()

### ISSUE THREAD

**Issue by mbkennel** [deeplearning4j/nd4j#1639]
I make a training iteration from an existing (all in memory) DataSet as 

```
MiniBatchFileDataSetIterator trainIter = new MiniBatchFileDataSetIterator(dataSet, minibatchSize)
```

However, if `dataSet.numExamples() < minibatchSize` (as it is in my unit test), I get NO iterations.   This is undesirable to me: data are silently dropped.  Is it intentional?

And what happens if `dataSet.numExamples() is not evenly divisible by minibatchSize`?  I would want there to be a runt minibatch at the end with the remaining data as the usual behavior, i.e. no dropping data (especially if this were a test set iteration and not a train set iteration)

**Comment by agibsonccc** [comment]
@mbkennel it already handles the left over case. We will add something for the minibatch size though.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/1670
