### ISSUE TITLE
@see type error 

### ISSUE THREAD

**Issue by liguozhong** [deeplearning4j/nd4j#1640]
error in class : org.nd4j.linalg.api.ops.Accumulation.calculateFinalResult(float accum, long n)

/** @see #calculateFinalResult(double, int) */
    float calculateFinalResult(float accum, long n);

int =>long.

/** @see #calculateFinalResult(double, long) */
    float calculateFinalResult(float accum, long n);
![Uploading image.png…]()

![Uploading image.png…]()

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/1670
