### ISSUE TITLE
SpecifiedIndex(0,1) and (0,2)

### ISSUE THREAD

**Issue by mlyz** [deeplearning4j/nd4j#1643]
hello,

new comer here, but found that 
`arr.get(NDArrayIndex.all(), new SpecifiedIndex(0, 2))`
gave me 0th and 1st columns of arr. (i.e., same as `get(NDArrayIndex.all(), new SpecifiedIndex(0, 1))`)

I searched w./ keyword SpecifiedIndex and there returned 5 results, which neither seems mentioning this one. So I file this report. Did I miss sth.?

Thx ~Ian

**Comment by agibsonccc** [comment]
Could you give us specific code to run please?

**Comment by mlyz** [comment]
Everything is trivial in fact -- I tried four diff arrays and all have the problem. 
e.g.
```
 scala> val threeByThree = Nd4j.linspace(1,16,16).reshape(4, 4)
 threeByThree: org.nd4j.linalg.api.ndarray.INDArray =
 [[1.00, 2.00, 3.00, 4.00],
  [5.00, 6.00, 7.00, 8.00],
  [9.00, 10.00, 11.00, 12.00],
  [13.00, 14.00, 15.00, 16.00]]

 scala> val t2 = threeByThree.get(NDArrayIndex.all(), new SpecifiedIndex(0, 2))
 t2: org.nd4j.linalg.api.ndarray.INDArray =
 [[1.00, 2.00],
  [5.00, 6.00],
  [9.00, 10.00],
  [13.00, 14.00]]
```
But I assume the result be
```
 [[1.00, 3.00],
  [5.00, 7.00],
  [9.00, 11.00],
  [13.00, 15.00]]
```

**Comment by agibsonccc** [comment]
I rewrote the specified indexing. It should be much better now: https://github.com/deeplearning4j/nd4j/pull/1669
