### ISSUE TITLE
what does `im2col` & `col2im` really do in Nd4j ?

### ISSUE THREAD

**Issue by izhangzhihao** [deeplearning4j/nd4j#1648]
I'm not found any document about this,especially `col2im`,it only has this
```java
    /**
     * Rearrange matrix
     * columns into blocks

     * @param col the column
     *            transposed image to convert
     * @param sy stride y
     * @param sx stride x
     * @param ph padding height
     * @param pw padding width
     * @param h height
     * @param w width
     * @return
     */
    public static INDArray col2im(INDArray col, int sy, int sx, int ph, int pw, int h, int w) {
        if(col.rank() != 6) throw new IllegalArgumentException("col2im input array must be rank 6");
        Col2Im col2Im = new Col2Im(col,sy,sx,ph,pw,h,w);
        return Nd4j.getExecutioner().exec(col2Im).z();
    }
```

so, can you tell me more details about the param h & w ? And how this function works? thx!

**Comment by AlexDBlack** [comment]
It's used for convolutional neural networks... given an input data array (an image, or CNN activations) it does a sliding window (of the given kernel size) over it.

It's not really intended for use directly by users - it's more for writing CNN layers.

See for example:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/convolution/ConvolutionLayer.java

**Comment by izhangzhihao** [comment]
@AlexDBlack could tell me about the parameters h & w ?

**Comment by AlexDBlack** [comment]
OK, so im2col does image (4d) to 6d sliding window. col2im does the reverse (by adding the components).

In the case of col2im, h and w are the height and width of the original 4d image (dimensions 2 and 3).

Also possibly relevant: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/conf/ConvolutionMode.java

I'd suggest googling the im2col and col2im algorithms - they aren't specific to DL4J or ND4J, but are widely used.
