### ISSUE TITLE
IND_array.remainder() like numpy.remainder()

### ISSUE THREAD

**Issue by SlightlyCyborg** [deeplearning4j/nd4j#1651]
This feature is important, especially if dealing with frequency data.

What would be the path to implementing this?

I could use already implemented subtraction, division, and floor methods to do this. I don't know if that is the speediest way to do it though.

**Comment by raver119** [comment]
Implemented & merged: https://github.com/deeplearning4j/nd4j/pull/1652

**Comment by SlightlyCyborg** [comment]
That was quick. You guys are awesome!
