### ISSUE TITLE
SGETRF and DGETRF return incorrect results with CUDA

### ISSUE THREAD

**Issue by nfrik** [deeplearning4j/nd4j#1681]
I initialized INDarray with the following values:
```
[[1.00, 2.00, 3.00],
 [4.00, 5.00, 6.00],
 [7.00, 8.00, 9.00]]
```
Calling getrf on this array returned the following incorrect LU result:
```
[[3.00, 0.33, 0.67],
 [6.00, 2.00, 0.50],
 [9.00, 4.00, 0.00]]
```
For this result INFO = 3 when debugged, which means according to LAPACK documentation that (3,3) element of U component is zero. But actual value should be 1.1102e-016 which is within single precision boundaries.

The correct result was obtained calling native CPU LAPACK (where INFO was 0):

```
[[7.00, 8.00, 9.00],
 [0.14, 0.86, 1.71],
 [0.57, 0.50, 0.00]]
```

I had similar result even using double precision of my INDarray.

**Comment by agibsonccc** [comment]
Thanks we will look in to this.

**Comment by saudet** [comment]
@rcorbish Would you know what might be wrong?

**Comment by rcorbish** [comment]
The CUDA library requires the arrays to be in column major order. If I remember correctly this might log a warning. If you transpose your input array you should see the expected result. 

It may be better to find a way to reject CUDA math when sent from a 'c' type array

**Comment by agibsonccc** [comment]
An arr.dup('f') could make sense here. We do this for GEMM when needed.

**Comment by nfrik** [comment]
Yes, thank you, 'f' formatting did help. It also would be great to return INFO from getrf in order to determine whether linear system is solvable. Maybe gerf could just through an exception with INFO parameter in it?

**Comment by raver119** [comment]
We definitely need auto-dup then.

**Comment by raver119** [comment]
Now we're enforcing F order for cuda backend for all those methods.
