### ISSUE TITLE
LibSvmRecordReader parsing

### ISSUE THREAD

**Issue by mbofb** [deeplearning4j/nd4j#1688]
There are exceptions while reading a libsvm file with LibSvmRecordReader. If the first row does not contain an entry for the highest dimension of the dataset, it causes the exception https://gist.github.com/mbofb/000e47d4488b92092add3b152037e213

If this fact is circumvented (by having the highest dimension in the first row), it processes without any logging until a "java.lang.OutOfMemoryError: Java heap space" (https://gist.github.com/mbofb/ca65f3d9761c9457596e264f96253d47) occurs (after appr. 9GB memory consumed)
The hereby used dimensions are rather tiny (e.g. 100 instances with max dimension 693 (https://github.com/apache/spark/blob/master/data/mllib/sample_libsvm_data.txt)) and should easly fit into memory as dense vectors. Even for only a subset of 11 instances the behaviour (processing to OutOfMemoryError) was the same.

**Comment by huitseeker** [comment]
Thanks for reporting ! This sounds like something we want to look into, but it seems to be filed under the wrong project.
You are registering this issue under project nd4j, whereas this seems to be an issue of DataVec
Here you can find an overview of our sub-projects:
https://deeplearning4j.org/overview
Would you mind filing the issue in the right project? It will help getting it seen by the people most likely to help fast.

**Comment by mbofb** [comment]
moved to datavec as https://github.com/deeplearning4j/DataVec/issues/207
