### ISSUE TITLE
Parallel run GPU devices

### ISSUE THREAD

**Issue by chamilka** [deeplearning4j/nd4j#1689]
I have a multi-gpu system and I want to run same program (example code dl4j-examples/dl4j-cuda-specific-examples/src/main/java/org/deeplearning4j/examples/multigpu/MultiGpuLenetMnistExample.java) in different GPUs without interacting each other.

Initially when I run it, it uses all 3 GPUs

![all_3](https://cloud.githubusercontent.com/assets/12293116/23698268/4bdf16d0-042e-11e7-9349-b7ff8f98a345.PNG)

Then to specify exact device, I use the code: 
`Nd4j.getAffinityManager().attachThreadToDevice(threadID, 1);`   to use only the 2nd GPU

Now the usage is;

![device_1](https://cloud.githubusercontent.com/assets/12293116/23698336/8d5cab86-042e-11e7-917e-2fffb34580be.PNG)

But the problem is, Still Ndj4 creates 3 process and use only 1. Therefore when I run the program second time (when gpu-1 is in use) I get the error **Can't create new cuBLAS handle!** 

Is there are way to release the other two GPUs?

**Comment by raver119** [comment]
It sounds like your gpus are running in exclusive mode. Can you please check that?

**Comment by chamilka** [comment]
Yes, compute_mode is Exclusive_Process. I will try changing it. Thank you

**Comment by chamilka** [comment]
I have changed the compute_mode of my multi-gpu system from Exclusive_Process to Default. But still when I run on single GPU it creates 3 process for the 3 GPUs and prevent me from starting another run of the same program in different GPU.

![image](https://cloud.githubusercontent.com/assets/12293116/23842965/ca7b4ab0-07fb-11e7-801f-b6bf46d9859d.png)

Is it because my initialization of the GPU environment is wrong?
Immediately after I run `Nd4j.getAffinityManager().attachThreadToDevice(thread, deviceId);` 
It creates 3 processes. But I'm expecting only 1 process.
