### ISSUE TITLE
Add outlier detection to ADAM method

### ISSUE THREAD

**Issue by Joshuaalbert** [deeplearning4j/nd4j#1692]
I have a feature request.
In ADAM method put an outlier detection part (only a few lines) that automatically updates `beta1` and `beta2`. The advantage is that it would adapt better to non-stationary losses and minimal extra computation. Idea is that if 50% of gradients are outliers with respect to accumulated m and v, then slow down momentum. Here's how I would do it (probably you have a better way):

```
//compute sqr deviation using already stored moving mean
INDArray diff2 = gradient.sub(m);
diff2.muli(diff2);

// var = v - m*m
INDArray var = m.mul(m);
var.rsubi(v);

//Get outlier levels squared: (g - m)**2 / var**2
diff2.divi(var);

// count outliers
diff2.replaceWhere(Nd4j.onesLike(diff2), org.nd4j.linalg.indexing.conditions.Conditions.greaterThan(outlierLevel*outlierLevel));
double count = diff2.sumNumber() / diff2.length();

// if more than 50% are outliers (maybe experiment)
if ( count > 0.50 ){
    //beta1 is equivalent to 1 - 1/(timescale); Let's slow down by increasing timescale up to a max
    double t1 = 1 / (1 - beta1);
    t1 = (t1 >= maxPeriod1? t1 : t1 + 1);
    beta1 = 1 - 1/t1;

    //likewise for beta2
    double t2 = 1 / (1 - beta2);
    t2 = (t2 >= maxPeriod2? t2 : t2 + 1);
    beta2 = 1 - 1/t2;
}
// You could also throw an else clause to decrease again (slower so by half) if you like
else {
    double t1 = 1 / (1 - beta1);
    t1 = (t1 <= minPeriod1? t1 : t1 - 0.5 );
    beta1 = 1 - 1/t1;

    double t2 = 1 / (1 - beta2);
    t2 = (t2 <= minPeriod2? t2 : t2 - 0.5);
    beta2 = 1 - 1/t2;
}
```
All it requires is a few more ops, and the definition of `outlierLevel`, `minPeriod1`, `minPeriod2` `maxPeriod1`, and `maxPeriod2`.

I would set these like this:
```
outlierLevel = 2;
minPeriod1 = 10;
minPeriod2 = 100;
maxPeriod1 = 100;
maxPeriod2 = 1000;
```

**Comment by AlexDBlack** [comment]
What might be better: add support for custom updaters (we already support most other custom functionality - layers, activation functions, etc).

For example, I've got a few updater ideas I'd like to test one day - but those (and this too, by the look of it) are more research/speculative, hence shouldn't be added to the main DL4J repo just yet.

**Comment by Joshuaalbert** [comment]
Yes, that would be wonderful eventually. 
I suppose this is closeable then.
Also until custom layer is finally implemented it's very easy to just compile with this extra code thrown into the src.

**Comment by AlexDBlack** [comment]
OK, I'll close this. If you did want to take a look at custom updaters in DL4J (as an alternative) feel free to message me on gitter. It shouldn't be *too* hard to add. Not sure exactly when we'll get to it otherwise.
