### ISSUE TITLE
BinomialDistribution might be rigged or used improperly in RBM

### ISSUE THREAD

**Issue by vlovsky** [deeplearning4j/nd4j#1699]
While debugging RBM, I found that it uses BinomialDistribution from Nd4j and the results were suspicious. 

Small test below showed (see attached files) that sampling produces 1s for very small probabilities more times than one would expect. It does it in a very interesting way. I.e. probability matrix in the example is 6x6. 1s were produced for almost all (but not all) probabilities of 0.03 from this matrix. The results are 100% consistent over all iterations of this mini test. There are also other nuisances in the results.

If the initialization of the distribution is factored outside of the sampling loop, the results are significantly improved. However, this is not how it is used in the RBM: https://gist.github.com/anonymous/23680f4b3d37c7afb91667c9a23abd56

Mini test:
https://gist.github.com/anonymous/9d220003669f4119c15a292e4e043326

See the mini test results below. I also compared Nd4j and Apache BinomialDistribution.

[problem in nd4j.txt](https://github.com/deeplearning4j/nd4j/files/837342/problem.in.nd4j.txt)
[problem in nd4j vs apache.txt](https://github.com/deeplearning4j/nd4j/files/837343/problem.in.nd4j.vs.apache.txt)
[problem has diminished.txt](https://github.com/deeplearning4j/nd4j/files/837344/problem.has.diminished.txt)

**Comment by raver119** [comment]
I've asked you yesterday - please provide links to original repository. Manual search for the code fragments you're providing is very misleading.

**Comment by raver119** [comment]
Also, i'm not sure what you're complaining about here:

>1s were produced for almost all (but not all) probabilities of 0.03 from this matrix. The results are 100% consistent over all iterations of this mini test. 

You're referring to the same rng seed over the same input. What kind of difference you expect on subsequent iterations? It HAS to be equal.

**Comment by raver119** [comment]
Please, poke me in gitter when you get online.

**Comment by raver119** [comment]
Aha, @AlexDBlack confirms bug in RBM impl.

**Comment by raver119** [comment]
There's few more reseed call used there in RBM impl btw, in both passes.

**Comment by vlovsky** [comment]
After commenting out the reseed in all places of RBM, I was still unhappy with the results. The randomizer kept generating 1s even for 0 probabilities. After substituting this [crude code using Apache impementation](https://gist.github.com/anonymous/69e9bdef16257c3f6abb9995337f391e) for the original sample calls in both positive and negative CD phases, I finally got what was expected.

**Comment by raver119** [comment]
Here's test for binomial distribution and zero probability:

```
@Test
    public void testBinomial() {
        Distribution distribution = Nd4j.getDistributions().createBinomial(1, Nd4j.create(new double[]{0.0, 0.0, 0.0, 0.0, 0.0}));

        for (int x = 0; x < 1000; x++) {
            INDArray z = distribution.sample(new int[]{1, 5});

            MatchCondition condition = new MatchCondition(z, Conditions.equals(1.0));
            int match = Nd4j.getExecutioner().exec(condition, Integer.MAX_VALUE).getInt(0);
            assertEquals(0, match);
        }
    }
```

It passes.

**Comment by raver119** [comment]
TL/DR: In this test we define 0.0 probabilities in distribution, and single attempt. Doing sampling 1000 times, and checking for any 1.0 in results. 

0.

**Comment by vlovsky** [comment]
Here the output from the original randomizer: https://gist.github.com/vlovsky/7b6b778e41426ebba12fd465a449429b

This the code the prints it out: https://gist.github.com/anonymous/18e75841b80cc7adb0f8506464926dcd
