### ISSUE TITLE
running DL4J NLP glove example using cuda is 6x slower than native

### ISSUE THREAD

**Issue by kingcw** [deeplearning4j/nd4j#1719]
Hi, I'm running DL4J NLP glove example using cuda, and it's 6x slower than native

example is 
[https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-examples/src/main/java/org/deeplearning4j/examples/nlp/glove/GloVeExample.java](url)

my graphic card is geforce gtx 680, windows 10, cuda 8.0

**Comment by raver119** [comment]
Unfortunately, NLP models are not suited for GPU at this moment, especially GloVe, by it's design there's significant amount of time spent for just cooccurrence list building.

Plus, tbh, GTX 680 isn worth using if you have any decent CPU.
