### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by pkarira** [deeplearning4j/nd4j#1721]
In android studio when I try to convert my double array to INDArray using ND4j.create(double[] ) then app crashes giving above error . My gradle https://gist.github.com/pkarira/b3cdb219af31814ae773a80f5659082f and logcat https://gist.github.com/pkarira/cdb8b5a41e700a116b2aea40b7f4114c

**Comment by raver119** [comment]
Issue persist in both emulator and attached device running snapdragon 410.

**Comment by saudet** [comment]
Could you copy/paste the list of files in the APK?

**Comment by pkarira** [comment]
Here's my complete project  https://drive.google.com/open?id=0B3OyLG30dXvybG5UelJVazNFZm8

**Comment by saudet** [comment]
I just want to know which files end up in your APK, not your whole project.

**Comment by pkarira** [comment]
Sorry for so much delay , here is the apk ,
https://drive.google.com/open?id=0B3OyLG30dXvyc0N2RW9mNFVacHc

**Comment by saudet** [comment]
@pkarira Sorry for the delay. You'll need to remove `lib/armeabi-v7a/libARM_ARCH.so` and then it will work as expected. Or you could move the content of `lib/armeabi` into `lib/armeabi-v7a/`, which would work as well.
