### ISSUE TITLE
Matrix decompsition

### ISSUE THREAD

**Issue by haifengl** [deeplearning4j/nd4j#1725]
Currently Lapack interface expose only LU decomposition. Can you please also expose QR, Cholesky, Eigen, and SVD decompositions? Thanks a lot!

**Comment by saudet** [comment]
@rcorbish Would you feel up to the task? :)

**Comment by rcorbish** [comment]
Let me see - SVD should be there already

**Comment by rcorbish** [comment]
Assign this to me 
[ SVD is there ( for double & single precision ) but is badly named (sgesvd ) ]

will add:
geqrf   ( general QR factor )
potrf    (positive definite triangular factor )
ggev    ( general 2 matrix eigenvalues & an (L/R) eigen vector )

**Comment by haifengl** [comment]
Thank you very much!

**Comment by huitseeker** [comment]
See also #540
