### ISSUE TITLE
Java heap objects overhaul

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1730]
We need to ensure, all short-living objects, like INDArray impls, DataBuffer, DataSet, etc - are all lightweight objects, or pointers to off-heap too. That'll give us further reduction of GC pressure. 

To start with: check for legacy fields for all those classes, and get rid of them.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/DataVec/issues/301

**Comment by raver119** [comment]
ND4j part got overhaul today, DataBuffer is 80 bytes now, looks like nothing to remove now :/
