### ISSUE TITLE
How to convert google news vector wordvectors model to word2vec ??

### ISSUE THREAD

**Issue by mani9229** [deeplearning4j/nd4j#1733]
package org.deeplearning4j.examples.nlp.word2vec;

import org.deeplearning4j.models.embeddings.loader.WordVectorSerializer;
import org.deeplearning4j.models.embeddings.wordvectors.WordVectors;
import org.deeplearning4j.models.word2vec.Word2Vec;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.util.Collection;

import static org.deeplearning4j.models.embeddings.loader.WordVectorSerializer.loadStaticModel;

/**
 * Created by agibsonccc on 10/9/14.
 *
 * Neural net that processes text into wordvectors. See below url for an in-depth explanation.
 * https://deeplearning4j.org/word2vec.html */
public class Word2VecRawTextExample {

    private static Logger log = LoggerFactory.getLogger(Word2VecRawTextExample.class);
    public static final String WORD_VECTORS_PATH = "D:/dl4j-files/GoogleNews-vectors-negative300.bin.gz";
    public static void main(String[] args) throws Exception {
        // Write word vectors to file
         WordVectors vec= WordVectorSerializer.loadStaticModel(new File(WORD_VECTORS_PATH));
        // Prints out the closest 10 words to "day". An example on what to do with these Word Vectors.
        log.info("Closest Words:");

        Collection<String> lst = vec.wordsNearest("insurance", 10);
        System.out.println("10 Words closest to 'insurance': " + lst);

        Collection<String> lst2 = vec.wordsNearest("travel", 10);
        System.out.println("10 Words closest to 'travel': " + lst2);
    }
}

Error:
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 4
Exception in thread "main" java.lang.UnsupportedOperationException: Method isn't implemented. Please use usual Word2Vec implementation
o.d.e.n.w.Word2VecRawTextExample - Closest Words:
	at org.deeplearning4j.models.word2vec.StaticWord2Vec.wordsNearest(StaticWord2Vec.java:255)
	at org.deeplearning4j.examples.nlp.word2vec.Word2VecRawTextExample.main(Word2VecRawTextExample.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1

I want to load the google news vector trained WordVectors model in word2vecRawText example program and use that trained model to get the closest word of given i/p word.? 
Kindly help me to fix this issue .!!
Thanks in advance.!!

**Comment by raver119** [comment]
This method: https://github.com/deeplearning4j/deeplearning4j/blob/7ea2e719efb3694e1a5772bdf20580b259f4b8e9/deeplearning4j-nlp-parent/deeplearning4j-nlp/src/main/java/org/deeplearning4j/models/embeddings/loader/WordVectorSerializer.java#L2267-L2267
