### ISSUE TITLE
UnsatisfiedLinkError: no nd4jcuda in java.library.path

### ISSUE THREAD

**Issue by Treiblesschorle** [deeplearning4j/nd4j#1734]
I'm trying to run LenetMnistExample using DL4J 0.8 on CUDA 8.0 on Windows 10 x64.

Error:
https://gist.github.com/Treiblesschorle/f4119ed346c42484b16851df5dd2db29

Pom:
https://gist.github.com/Treiblesschorle/898fb844e8b6fc8b368026de33c5db5d

CUDA:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Mon_Jan__9_17:32:33_CST_2017
Cuda compilation tools, release 8.0, V8.0.60

For some reason cuda ddls seem not to be extracted to .javacpp/cache. However, cpu dlls are.

**Comment by saudet** [comment]
What about other DLLs from `org/bytedeco/javacpp-presets`? Could you list all DLLs that do get extracted?

**Comment by Treiblesschorle** [comment]
https://gist.github.com/Treiblesschorle/01670951c6c94b5e8f0c6fbcd9ac6076

**Comment by raver119** [comment]
@Treiblesschorle sorry, weird question here. Can you please show, how dl4j.version & nd4j.version are defined?

**Comment by Treiblesschorle** [comment]
Parent pom:
https://gist.github.com/Treiblesschorle/8a7f52801f70dcb78090fc3cb7d695eb

**Comment by saudet** [comment]
The only possible explanation is for the DLLs to not be in the class path. Something strange seems to be happening with your version of Maven. You're not trying to use Eclipse by any chance?

**Comment by Treiblesschorle** [comment]
Yes, I'm using Eclipse.

**Comment by saudet** [comment]
Ok, so, please don't. :)

**Comment by raver119** [comment]
Ah...Eclipse...

**Comment by Treiblesschorle** [comment]
Hm, unfortunately this is not really an option here. Do you know any actual issue with eclipse?

**Comment by Treiblesschorle** [comment]
For some reason some .jars in my m2 repo were corrupt. Deleting the whole repo and running 'mvn clean install' on the dl4j-examples resolved the issue.

**Comment by saudet** [comment]
@Treiblesschorle I just never seems to work properly with Maven, not just in this cast, in general, that's all.
