### ISSUE TITLE
DataNormalization doesn't declare save/load

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#1737]
The implementations have it but not the interface itself. This should be fixed.

**Comment by huitseeker** [comment]
1. `ImagePreProcessingScaler`, `VGG16ImagePreProcessor` do not implement save/load, and it would make little sense for them to do so.
2. All this functionality has been replaced by `NormalizerSerializer` instead (save is even formally `@deprecated`).

==> closing as won't fix.
