### ISSUE TITLE
BaseComplexNDArray potential typo

### ISSUE THREAD

**Issue by jadedfire** [deeplearning4j/nd4j#1754]
i'm working to learn the code. it appears that line 1008 in BaseComplexNDArray.java should have an operation of type 'h' (reverse subtract) and not 't' (reverse divide) within the doColumnWise() method invokation. if that is not accurate, please feel free to slap me around as i become acquainted with the code.

**Comment by raver119** [comment]
ComplexNDArrays are not covered with tests at this moment, and have no native implementation :(
