### ISSUE TITLE
Support GEMV

### ISSUE THREAD

**Issue by haifengl** [deeplearning4j/nd4j#1758]
Current we have to use Nd4j.gemm for matrix-vector multiplication, which is a common operation in machine learning. Although it works, gemm is heavy as a generic matrix-matrix multiplication method that uses block algorithm. The block algorithm is not necessary for matrix-vector multiplication. Can you please support gemv function in BLAS to reduce the overhead? Thank you very much!

**Comment by raver119** [comment]
We support it.

It's in BlasWrapper. I.e.:
```
Nd4j.getBlasWrapper().gemv(....)
```

or 

```
Nd4j.getBlasWrapper().level2().gemv(...);
```

**Comment by haifengl** [comment]
Thanks! Why Nd4j has gemm in the top level while gemv is in BlasWrapper?

**Comment by raver119** [comment]
No idea. Legacy. Most popular methods are there. And in correspoding levels as well.

**Comment by haifengl** [comment]
What value should I pass to the first parameter `order`? Thanks!

**Comment by raver119** [comment]
I'm afraid that you shouldn't touch it then.

Stick to INDArray mmul/mmuli, which uses gemv when appropriate.

**Comment by raver119** [comment]
https://github.com/deeplearning4j/nd4j/blob/94734f2934716bd654b4645c9422da83a0c45814/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L2860-L2860

**Comment by haifengl** [comment]
I believe that it is wrong to pass `BlasBufferUtil.getCharForTranspose(result)` as the first parameter. The first parameter is to indicate if the matrix A is row major or column major.

**Comment by haifengl** [comment]
And we do have cases where I should set the parameters alpha and beta, which are set as 1.0 and 0.0 by default in mmul.

**Comment by raver119** [comment]
Ok. Just stick to BLAS reference then.

**Comment by haifengl** [comment]
The order parameter is ignored in the low level blas wrapper function (https://github.com/deeplearning4j/nd4j/blob/aafbd0101b1a10a0d4dae1a2671895410a1708b2/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/linalg/cpu/nativecpu/blas/CpuLevel2.java). Is it a bug?

**Comment by raver119** [comment]
If you think something is a bug - please file new issue, with code that reproduces it.
