### ISSUE TITLE
Standardize ClassPathResource (nd4j, datavec)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1764]
We currently have 2 ClassPathResource implementations, with similar functionality but different implementations:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-common/src/main/java/org/nd4j/linalg/io/ClassPathResource.java
https://github.com/deeplearning4j/DataVec/blob/master/datavec-api/src/main/java/org/datavec/api/util/ClassPathResource.java

Plus a copy/duplicate here:
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-ui-parent/deeplearning4j-ui-components/src/main/java/org/deeplearning4j/ui/standalone/ClassPathResource.java

We should have only one implementation (I suggest in ND4J) that is used throughout the entire ecosystem.

With regard to spaces in paths:
- Both handle standard files with spaces in paths
- For files in JARs (with paths that include spaces)
    - The ND4J implementation *does* seem to handle this OK
    - The DataVec implementation does not (file not found exceptions - see below)

@raver119 were there other reasons/issues for creating the DataVec version (with separate implementation to the ND4J version) that I'm not aware of?

DataVec version failing on JAR + spaces, system username being: ```Alex 2``` here:
```
Caused by: java.io.FileNotFoundException: C:\Users\Alex%202\.m2\repository\org\deeplearning4j\deeplearning4j-play_2.11\0.8.0\deeplearning4j-play_2.11-0.8.0.jar (The system cannot find the path specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:120)
```

**Comment by raver119** [comment]
Originally there was Spring used around. Then i've added DataVec cpr impl. To use it in nd4j - copy was added, and i've tried to keep nd4j version up to date. But all the time DataVec copy was considered proper & up-to-date.

**Comment by eraly** [comment]
When using the class path resource in nd4j I ran into this error when running "java -cp" from the command line. The file "part_0.header" is available in the resources and is copied over to target/classes. 

The datavec implementation worked okay with this.

Exception in thread "main" java.io.FileNotFoundException: class path resource [part_0.header] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/datadrive/Ericsson_VolteKPI/./etl/target/etl-1.0-shaded.jar!/part_0.header

**Comment by AlexDBlack** [comment]
DataVec ClassPathResource has been deprecated, uses the nd4j-common implementation now.
