### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by vimalaguti** [deeplearning4j/nd4j#1765]
on spark executors, an object creates an INDArray from a flat 3D array with:

`Nd4j.create(flat,shape,'c')`

but fails with following error:

https://gist.github.com/vimalaguti/375ef86e3b6c28204401907c778c691b

the dependency.jar is up to date, of course.
dependencies: 

scala: 2.10.6
nd4j: 0.8.0
dl4jVersion: 0.8.0
sparkVersion: 1.6.2

https://gist.github.com/vimalaguti/31f66a4a064906e9f9779621ffa4b19e

system infos: 
spark-submit --conf spark.executor.cores=2 --conf spark.cores.max=10 --conf spark.cassandra.read.timeout_ms=180000 --conf spark.executor.memory=5G --conf spark.rdd.compress=true --conf spark.driver.memory=2G  --conf "spark.executor.extraJavaOptions=-Dorg.bytedeco.javacpp.maxbytes=4294967296"

**Comment by saudet** [comment]
```
Caused by: java.io.FileNotFoundException: class path resource [nd4j-native.properties] cannot be opened because it does not exist
	at org.nd4j.linalg.io.ClassPathResource.getInputStream(ClassPathResource.java:106)
```
So, try to add that file...

**Comment by raver119** [comment]
That file can't be missing, it's nd4j backend properties file. We provide that file.

So this issue is probably caused by thin jar being submitted to spark?

**Comment by vimalaguti** [comment]
I've built the dependency fat jar with sbt assemblyPackageDependency and all other classes are loaded succesfully, sometimes it even starts the fit( ), should be something else

**Comment by agibsonccc** [comment]
This definitely isn't us.
