### ISSUE TITLE
Copy on reduction op edge cases

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1773]
My understanding is that the convention for reduction ops is to always return a new array.
This doesn't happen for the following edge cases, however:

```java
        INDArray row = Nd4j.linspace(1,3,3);
        INDArray mean0 = row.mean(0);
        System.out.println(mean0 == row);       //True: same object (should be a copy)

        INDArray col = Nd4j.linspace(1,3,3).transpose();
        INDArray mean1 = col.mean(1);
        System.out.println(mean1 == col);       //True: same object (should be a copy)
```

This can be problematic... for example, X.mean(0).addi(Y) can be perfectly fine for most cases (i.e., X is unmodified), but then cause a hard to identify/debug edge cases for row vectors (where X is modified)

**Comment by raver119** [comment]
Fixed in my branch, will be merged a bit later today.
