### ISSUE TITLE
Recent commit hampers performance by 20x

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/nd4j#1778]
#### Issue Description

After this commit: https://github.com/deeplearning4j/nd4j/commit/a8abc371dd6c60311c711f84aa3e5a3fb4fb61f8

Benchmarks slowed down by 20x. Have not been able to trace specific problem yet.

#### Version Information

https://github.com/deeplearning4j/nd4j/commit/a8abc371dd6c60311c711f84aa3e5a3fb4fb61f8

Using CUDA + cuDNN.

**Comment by raver119** [comment]
Add some details please, like perf listener output.

**Comment by agibsonccc** [comment]
@crockpotveggies mind following up on this?

**Comment by crockpotveggies** [comment]
This is now fixed. Closing...

**Comment by crockpotveggies** [comment]
Appears to have been a combination of things, one of which was migration which was one of the focuses of debugging I did with @raver119.
