### ISSUE TITLE
INDArray.dup() with cuda backend does not return independent copy

### ISSUE THREAD

**Issue by abholer** [deeplearning4j/nd4j#1780]
#### Issue Description
values of input.dup() seems get modified with original on cuda backend 
(with cpu or Nd4j.create(input.data().dup()) it works fine)

- maxInput = input.dup()
- maxInput <> input.dup()

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version 0.8.0
* platform information (OS, etc) win 10
* CUDA version, if used 8.0
* NVIDIA driver version, if in use 378.92

#### Contributing

Code:
https://gist.github.com/abholer/b65f17cae46fde708b1dd4904ccf3642

**Comment by raver119** [comment]
I've wrote simple test that does something similar to your code, but it passes for me:
```
@Test
    public void testStrangeDups1() throws Exception {
        INDArray array = Nd4j.create(10).assign(0);
        INDArray exp = Nd4j.create(10).assign(1.0f);
        INDArray copy = null;

        for (int x = 0; x < array.length(); x++) {
            array.putScalar(x, 1f);
            copy = array.dup();
        }

        assertEquals(exp, array);
        assertEquals(exp, copy);
    }
```

So, please give me something that i can run and see failure.

**Comment by raver119** [comment]
Reversed order passes as expected too. So i need to get something reproducible from you.

**Comment by abholer** [comment]
that fails for me

 @org.junit.Test
    public void test() {

        INDArray in = Nd4j.zeros(10);

        List<INDArray> out = new ArrayList<>();
        List<INDArray> comp = new ArrayList<>();

        for (int i = 0; i < in.length(); i++) {
            in.putScalar(i, 1);
            out.add(in.dup());
            in.putScalar(i, 0);
        }

        for (int i = 0; i < in.length(); i++) {
            in.putScalar(i, 1);
            comp.add(Nd4j.create(in.data().dup()));
            in.putScalar(i, 0);
        }

        for (int i = 0; i < out.size(); i++) {
            assertEquals(out.get(i), comp.get(i));
        }
    }

**Comment by abholer** [comment]
17:59:45,186 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
17:59:45,186 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
17:59:45,186 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/C:/Users/sascha/workspace/deepfour/target/classes/logback.xml]
17:59:45,243 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
17:59:45,259 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
17:59:45,259 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
17:59:45,335 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
17:59:45,335 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
17:59:45,335 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
17:59:45,335 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.base22] to TRACE
17:59:45,335 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
17:59:45,335 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
17:59:45,335 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
17:59:45,335 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@29774679 - Registering current configuration as safe fallback point

17:59:45.635 [main] INFO  org.nd4j.linalg.factory.Nd4jBackend - Loaded [JCublasBackend] backend
17:59:46.349 [main] INFO  org.nd4j.nativeblas.NativeOpsHolder - Number of threads used for NativeOps: 32
17:59:46.387 [main] DEBUG org.reflections.Reflections - going to scan these urls:
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-context/0.8.0/nd4j-context-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/jackson/0.8.0/jackson-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-common/0.8.0/nd4j-common-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-api/0.8.0/nd4j-api-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0-windows-x86_64.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0-linux-ppc64le.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0-macosx-x86_64.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-buffer/0.8.0/nd4j-buffer-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-native-api/0.8.0/nd4j-native-api-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0-linux-x86_64.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0.jar!/
17:59:46.486 [main] INFO  org.reflections.Reflections - Reflections took 99 ms to scan 11 urls, producing 29 keys and 189 values 
17:59:46.547 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CUDA]; OS: [Windows 10]
17:59:46.547 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Cores: [8]; Memory: [3,5GB];
17:59:46.547 [main] INFO  o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [CUBLAS]
17:59:46.547 [main] INFO  o.n.l.j.o.e.CudaExecutioner - Device name: [GeForce GTX 1080 Ti]; CC: [6.1]; Total/free memory: [11811160064]
17:59:46.944 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.944 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.944 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.944 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.960 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.a.c.impl.BasicContextPool - Creating new stream for thread: [1], device: [0]...
17:59:46.976 [main] DEBUG o.n.j.c.CudaAffinityManager - Mapping thread [1] to device [0], out of [1] devices...
17:59:46.976 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [18] to device [0], out of [1] devices...
17:59:46.976 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [19] to device [0], out of [1] devices...
17:59:46.976 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [20] to device [0], out of [1] devices...
17:59:46.976 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [21] to device [0], out of [1] devices...
17:59:46.976 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [22] to device [0], out of [1] devices...
17:59:46.976 [main] DEBUG o.n.j.c.CudaAffinityManager - Manually mapping thread [23] to device [0], out of [1] devices...
17:59:46.998 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 4
17:59:46.998 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 0
17:59:47.013 [main] DEBUG org.reflections.Reflections - going to scan these urls:
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-context/0.8.0/nd4j-context-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/jackson/0.8.0/jackson-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-common/0.8.0/nd4j-common-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-api/0.8.0/nd4j-api-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0-windows-x86_64.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0-linux-ppc64le.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0-macosx-x86_64.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-buffer/0.8.0/nd4j-buffer-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-native-api/0.8.0/nd4j-native-api-0.8.0.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0-linux-x86_64.jar!/
jar:file:/C:/Users/sascha/.m2/repository/org/nd4j/nd4j-cuda-8.0/0.8.0/nd4j-cuda-8.0-0.8.0.jar!/
17:59:47.161 [main] INFO  org.reflections.Reflections - Reflections took 148 ms to scan 11 urls, producing 391 keys and 1506 values 
17:59:47.161 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 5
17:59:47.161 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 1
17:59:47.161 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 3
17:59:47.176 [main] DEBUG o.n.j.handler.impl.CudaZeroHandler - Creating bucketID: 2

**Comment by raver119** [comment]
Test you've provided passes for me on both cuda & native backend. However, i'll add it to nd4j-tests to ensure stability.

**Comment by raver119** [comment]
Hm, no, i've found situations where it might fail.

Should be fixed now.
