### ISSUE TITLE
The ND4JRegistrator should move away

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/nd4j#1787]
#### Issue Description

The ND4J registrator is used to connect Spark's Kryo registrator with the ND4JSerializer. This makes ND4J dependent on (and shipping the jar of) Spark, which is bad for 2 reasons:

- we are dependent on Spark publishing Spark-core for 2.12 before we can smoothly publish nd4j (including the param server and the parts that only depend on kafka) for 2.12
- the Spark version is mishandled (no change-spark-version script in the repo, only publishes for 1.6.3).

A better approach would be to leave the Serializer here, but ship the registrator at the point of use, in DL4J / DataVec.

**Comment by AlexDBlack** [comment]
It's dependent on the API, yes - but the scope is provided, so it's not a direct dependency per-se
https://github.com/deeplearning4j/nd4j/blob/14410087388980c6c25111859a1272418e20ec54/nd4j-serde/nd4j-kryo/pom.xml#L33

Though it would be strictly more correct to do so, with the ```<scope>provided</scope>``` I don't think we actually need spark 1/2 versions for nd4j-kryo (afaik the interface we use - org.apache.spark.serializer.KryoRegistrator - is the same in spark 1/2). Though the same could be said for scala versions, which we do release different versions for...

**Comment by huitseeker** [comment]
My suggestion is : can we move this class out of the ND4J repo, into Datavec, and handle the Scala + Spark dependency in whatever way is suitable there ?

At the moment, we are dealing with artifactId mangling for Scala-dependent artifacts, whereas the nd4j artifact should really not have anything to do with it (no issue with the Serializer, though).

As a larger rule of thumb to simplify our lives, can we say we don't let any Scala (or related, incl Spark) in the nd4j repo ?

One example of consequence : leaving this in the repo currently multiplies the time necessary for production of snapshots by 2-4x what it should be.

**Comment by AlexDBlack** [comment]
I get what you are saying about multiplying snapshot production - that should certainly be fixed somehow.
But given it is essentially isolated, shouldn't it be possible to build only that module multiple times?
i.e., the build script is supposed to handle that - or am I missing something?
https://github.com/deeplearning4j/nd4j/blob/master/buildmultiplescalaversions.sh#L4-L10

I'm a little hesitant to move it into DataVec or DL4J (or elsewhere) - consider the case of someone who wants to use *only* ND4J on Spark. We'd be asking them to add a dependency from another project, for what is ultimately just a single (very small) class.

**Comment by raver119** [comment]
@AlexDBlack any ideas where we are with this one?

**Comment by AlexDBlack** [comment]
The only real remaining open question here (IMO) is whether we build Spark 1 + 2 versions of nd4j-kryo.
But given that the serializer interfaces haven't changed between versions of spark, this seems unnecessary, and the actual code would be identical in both versions.
That said, it's a little ugly having spark 1 as scope provided when adding this to a spark 2 project. But it doesn't actually matter in practice.

https://github.com/deeplearning4j/nd4j/blob/95d0d1db2b9da8ba892dc58ddc2e36c8644841bf/nd4j-serde/nd4j-kryo/pom.xml#L37

Anyway, given we've had 0 reports of problems with the current approach in a year since this issue, I think I'll close this.
