### ISSUE TITLE
Transforms.cosineSim() with INDArray [0.00, 0.00 ... 0.00] gives NaN

### ISSUE THREAD

**Issue by dpasch01** [deeplearning4j/nd4j#1789]
Issue Description

Calling Transforms.cosineSim(n, s) where either of n or s is an INDArray consisting only of 0.00 returns NaN.
Works great if change any single value of vector in 1e-5.

#

**Comment by treo** [comment]
That is pretty much expected, as the L2 Norm of a Zero Vector is 0 you will get a division by zero.

**Comment by AlexDBlack** [comment]
Mathematically, it is undefined, and (according to a very quick search) it looks like there isn't a standard convention for handling this case.
I'm going to close this as something we won't fix (unless someone can make a reasonable proposal of how this edge case should be handled).
