### ISSUE TITLE
Transitive dependencies pull in all javacpp platforms

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/nd4j#1794]
#### Issue Description

When a project uses nd4j as a dependency, it transitively pulls all the native artifacts of the nd4j platform (linux-x86_64, macosx, etc), irrespective of the platform on which the project is built.

This can be bypassed in some builds (e.g. [dl4j-examples](https://github.com/deeplearning4j/dl4j-examples#build-and-run)) where we can specify `-Djavacpp.platform=MYPLATFORM` so that at th resolution of the artifact, the reading of the nd4j pom will select the appropriate classifier thanks to the following line in the nd4j-backend pom:

`<classifier>${javacpp.platform}</classifier>`

But this is not a solution that's straightforwardly available to sbt, yielding errors similar to :

https://gist.github.com/ZizhengTai/3183e2688b0f0e77c16c6ce8d97d07b9
https://gist.github.com/ZizhengTai/be2ff148695bc8bdec7d52dfa928407f

(due to a snapshot rebuild where not all the snapshots were available at the same time) 

The solution being to instrument `javaOptions` (here done for tests: https://gist.github.com/padurean/f84a360a5d70c9eb7867 )

Conclusion:
It would be ideal to explain or provide a straightforward way to create a build for a project that has nd4j as a dependency to sparsely download just the classifiers it needs.

- for maven, we might look at the automatically-activated platform profiles we have in the nd4j build itself 
- for sbt we might look at a snippet that interacts with the platform to probe its nature .. or perhaps loading is possible with https://github.com/bytedeco/sbt-javacpp

Those mvn / sbt snippets would provide a more reliable way to build than just adding the nd4j dependency.

**Comment by saudet** [comment]
The artifacts need to work for other build tools than Maven and sbt, so by
default we need to pull in everything. Custom behavior can then be provided
with plugins and such. In the case of Maven profiles, they can only be
activated by system properties, so nothing that we can put in the pom.xml
file. Though, I don't think we would want to either...?
