### ISSUE TITLE
ND4j.shuffle fails for sequences

### ISSUE THREAD

**Issue by Stevod** [deeplearning4j/nd4j#1800]
I have modified one of the examples to work with CSV sequence reader, but the ND4j.shuffle(123) does not work with sequences, it seems.

Tracing the code, it looks like the shuffle routine needs more than one input, because it interleaves odd and even inputs in some way, but a sequence only has one input which is causing it to fail.

The source is at [https://gist.github.com/Stevod/ed02aec85b57ce2432dfb25256a7b224](url) and example data is at https://gist.github.com/Stevod/d531c5bfee41b053ae6613844f104ebe

**Comment by Stevod** [comment]
It may be my data at fault, rather than ND4j. Please hang fire until I can confirm.

**Comment by raver119** [comment]
Sequences are not any special really, it's just 3D input.
Here's our tests for shuffle, they also include 3D shuffle: https://github.com/deeplearning4j/nd4j/blob/aafbd0101b1a10a0d4dae1a2671895410a1708b2/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/ShufflesTests.java

Tests pass, sure.

So, please, give us something reproducible to confirm there's a bug.

**Comment by Stevod** [comment]
@raver119 I generated my data again, double checked it, and padded it to be a consistent rect. shape, then replaced the SequenceRecordReader with a standard CSVReader to feed to a dense NN. Unfortunately, I am still having the same problem. It might however related to the fact that I am doing classification, not regression (as in the DL4j examples that I based my code on).
Am I using RecordReaderDataSetIterator correctly for classification? I have checked the javacdocs. If not, I will post my code/data as GIST.
Many thanks.

 RecordReader recordReader = new CSVRecordReader(1, ",");
        recordReader.initialize(new FileSplit(new File( "<filename>")));
        int labelIndex = 0;
        int numClasses = 24;
        
        RecordReaderDataSetIterator iterator = new RecordReaderDataSetIterator(recordReader,batchSize,labelIndex, numClasses);
        iterator.setCollectMetaData(false);  //Instruct the iterator to collect metadata, and store it in the DataSet objects
        DataSet allData = iterator.next();
        allData.shuffle(123); < ERROR HERE

**Comment by Stevod** [comment]
Closing as Raver119 confirmed he had fixed it in his branch.
