### ISSUE TITLE
How to get indices of N maximum values in a nd4j array ?

### ISSUE THREAD

**Issue by boluoyu** [deeplearning4j/nd4j#1801]
in nd4j ,I found a similar function is sortWithIndices ,but it is very slow , is there other function like numpy argpartition in nd4j ? thanks a lot.

**Comment by agibsonccc** [comment]
Not sure what you'd expect? Rather than asking for an alternative function (not sure why we'd make 2 o_0) post some information on what kind of speed you expected and an example for us to look at?
