### ISSUE TITLE
Add sum along dimension with specified result array

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1803]
Idea: myArray.sum(0) -> return a new INDArray for the result.
In my case: I want to provide a specified result array, and I don't believe this is possible currently.
Why? In DL4J, there's a number of places (layer backprop) that essentially do ```whereIActuallyNeedTheResult.assign(myArray.sum(0))```. Better performance (1 less op) + less memory is possible there.

2 similar use cases here:

- Provide a (possibly uninitialized?) array - i.e., don't care about result array existing contents
- Add to an existing array: i.e., result array already has contents; essentially equivalent to ```myArray.addi(other.sum(0))```

These 2 cases could actually be the same implementation/method, if we decide to require users to manually initialize (or not) the result array. Not sure if the .set(0) first will have a performance cost (or if this would be handled by grid, for example) vs. having an 'initializeResultArray' boolean arg.

**Comment by raver119** [comment]
Surprisingly we have this option. It's just not introduced in public methods, but widely used internally. I'll make it publicly available.

**Comment by raver119** [comment]
Implemented
