### ISSUE TITLE
Addi and add do the same thing

### ISSUE THREAD

**Issue by gagatust** [deeplearning4j/nd4j#1806]
#### Issue Description
What should be the difference between these operations? In-place for result argument or this?
INDArray op(INDArray other, INDArray result) and INDArray opi(INDArray other, INDArray result)
add(addi), sub(subi) and etc do the same things. 

```java
        INDArray x = Nd4j.create(new double[]{1, 2});
        INDArray y = Nd4j.create(new double[]{3, 4});
        INDArray z = Nd4j.create(new double[]{5, 6});

        System.out.println(x);
        System.out.println(y);
        System.out.println(z);

        INDArray t = x.add(y, z);
        //INDArray t = x.addi(y, z);     //do the same   

        System.out.println();

        System.out.println(x);
        System.out.println(y);
        System.out.println(z);

        System.out.println();

        System.out.println(t);

        System.out.println(t == z);
````

#### Output
````
[1.00, 2.00]
[3.00, 4.00]
[5.00, 6.00]

[1.00, 2.00]
[3.00, 4.00]
[4.00, 6.00]

[4.00, 6.00]
true
````
#### Version Information
nd4j-native 0.8.0

**Comment by agibsonccc** [comment]
1 is in place 1 isn't. The i stands for in place.

**Comment by raver119** [comment]
Yes, in this particular case this two ops do the same.

X + Y -> Z. And Z is returned.
So this test has to pass, as in **t** has to be == **z**
```
x.add(y, z); 
```
in this signature, Z is target indarray, which will be used as return value.

**Comment by agibsonccc** [comment]
Yes that signature is so you can specify the result array. All ops have an x, (optional y), and a z.

The only difference between the 2 ops is how the z is set. An in place operation will set the "x" as the z. The other ops will allocate a new array.

**Comment by gagatust** [comment]
@raver119 
Why you need two identical functions?

**Comment by agibsonccc** [comment]
Java. The only way to do default values is with parametric overriding. Java doesn't have default values.

**Comment by raver119** [comment]
yep. those signatures like x.add(y, z) are used in x.add(y) and x.addi(y)

**Comment by gagatust** [comment]
x.addi(y) modify x but x.add(y) does not modify x
x.add(y, z) does not modify x and x.addi(y, z)  does not modify x too

**Comment by raver119** [comment]
for in that case you should use x.add(y,x)

**Comment by gagatust** [comment]
In what cases might it be necessary x.add(y, z) instead x.addi(y, z)?

**Comment by raver119** [comment]
none. That stuff should be made protected probably, if it doesn't break anything for nd4j users.

**Comment by gagatust** [comment]
What about "deprecated" INDArray opi(INDArray other, INDArray result) methods?

**Comment by raver119** [comment]
I don't see any opi method. Typo i guess?

**Comment by gagatust** [comment]
Yes, it's "i" suffix: addi, subi, divi and etc.

**Comment by raver119** [comment]
I'm afraid they all have the same behavior, because they are used in the same scenario.
Basically only inplace copies should stay, because dup() called for in, say, add(y, z) method is just redundant. Or, inplace methods should go, and dup() should go.

**Comment by gagatust** [comment]
If we look at the methods in BaseNDArray.java
````java
@Override
public INDArray sub(INDArray other, INDArray result) {
    return subi(other, result);
}
@Override
public INDArray mul(INDArray other, INDArray result) {
    return muli(other, result);
}
@Override
public INDArray div(INDArray other, INDArray result) {
    return divi(other, result);
}
@Override
public INDArray add(INDArray other, INDArray result) {
    return dup().addi(other, result); //has dup(). Why?
}
````
sub and subi are practically synonyms. subi don't modify _this_, it's not inplace method. We can exchange subi's and sub's bodies and mark subi "deprecated".
