### ISSUE TITLE
Supporting the creation of linear data view rather than ndarray

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4j#181]
For element wise operations it would be optimal to create a linear view of the data rather than relying on an ndarray, which is a set of vectors. 

We were looking into the resetLinearView - with hopes of getting the following line to pass
linearView = create(data(), new int[]{1,length}, Nd4j.getStrides(shape, ordering), offset);

but the tests threw errors like this :
https://gist.github.com/anonymous/ab4a1776bd768ddf35d7

**Comment by agibsonccc** [comment]
I now do this for the one case it's valid: c ordering and 0 offset. Give it a shot.
