### ISSUE TITLE
Ser/De performance

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1813]
To test ser/de performance, i've used TinyImageNet dimensions: 32x3x224x224.
Originally we had approx 110ms DataSet deserialialization time. I've got it down to 85ms, but. The java float array of the same size takes 17ms to deserialize, so my "gains" there are somewhat miserable.

According to profiler, all time spent now is spent on int->float bits conversion, which is single-threaded by java design, and happens in single loop by nd4j design. 

So, we need to introduce something better for faster ser/de, because we suffer too much from this issue: Spark suffers, presaved DataSet suffers, etc.

We should either change DataBuffer ser/de mechanics to single blob strategy somehow (i.e. put java float[]/double[] as a whole?) or introduce some kind of parallelism on deserialization. However, parallelism on deserialization might introduce undesired CPU utilization pressure.

What do you think guys? @agibsonccc @huitseeker @saudet @AlexDBlack

**Comment by raver119** [comment]
![screenshot from 2017-05-04 11-46-21](https://cloud.githubusercontent.com/assets/12250879/25696300/52cce694-30bf-11e7-9558-7f0b730ab5b3.png)

**Comment by AlexDBlack** [comment]
Thinking about deserialization - in this case, we're doing DataSet.load(File)... everything internally is handled via streams.

Two thoughts come to mind.

First, anything using DataInputStream.readFloat() or similar in a loop is going to have poor performance.
The only viable alternative on the DataInputStream I can see is read(byte[] b). Read blocks of bytes then do a bulk memcpy op somehow. That means allocating byte[]s - we could potentially cache + reuse them if that's a problem (at the expense of memory - though say, 4-8MB buffer times nCores wouldn't be the end of the world...)

Second: we can't do this once we get to InputStreams, but for things like DataSet.load(File) we can probably handle that in native code.
Assuming no conversion or compression, it's literally just "copy bytes X to Y from file to memory".

**Comment by raver119** [comment]
We can't really do bulk byte copies due to ***hypothetical*** bits order differences. I.e. on machine A there's LE, on machine B there's BE. We'll be screwed if that's not covered....

**Comment by AlexDBlack** [comment]
Can we store endianness as a header for DataSets, and flip it when reading (as a special case) if necessary? In 99% of cases we won't have to do that.

**Comment by raver119** [comment]
We can/should store it in header of DataBuffer then, but ye, not a big deal.

**Comment by agibsonccc** [comment]
I revisited the serde of ndarrays in aeron mor recently:
https://github.com/deeplearning4j/nd4j/blob/aafbd0101b1a10a0d4dae1a2671895410a1708b2/nd4j-serde/nd4j-aeron/src/main/java/org/nd4j/aeron/ipc/AeronNDArraySerde.java

**Comment by saudet** [comment]
ByteBuffer from Java NIO has pretty good semantics for readFloat(), putInt(), etc:
https://docs.oracle.com/javase/7/docs/api/java/nio/ByteBuffer.html
We can force endianness to say little-endian (like Aeron) and it will be efficient on x86 and pretty much all other platforms these days, but still work on big-endian machines. It can also read/write to native memory or Java arrays, transparently. And then the idea for performance is to use memory mapped files:
https://docs.oracle.com/javase/7/docs/api/java/nio/MappedByteBuffer.html

**Comment by agibsonccc** [comment]
We should just be using binary serde. That was merged in API recently, let's just migrate everything to that instead. Closing this.
