### ISSUE TITLE
StringUtils should include Levenshtein (edit) distance

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/nd4j#1820]
#### Issue Description
See nd4j-common/src/main/java/org/nd4j/linalg/io/StringUtils.java

For now, it contains mostly (String × String) → String functions, but it should be expanded with fast numerical functions on String, of which a good example is the [edit distance](https://people.cs.pitt.edu/~kirk/cs1501/Pruhs/Spring2006/assignments/editdistance/Levenshtein%20Distance.htm).

**Comment by raver119** [comment]
We have it, but in dl4j.

**Comment by raver119** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/f79799709ee1a99ebde92dde47ae9c093f94d22d/deeplearning4j-nn/src/main/java/org/deeplearning4j/berkeley/StringUtils.java#L941-L941
