### ISSUE TITLE
Build issues on windows

### ISSUE THREAD

**Issue by Joshuaalbert** [deeplearning4j/nd4j#1830]
#### Issue Description
I'm compiling the snapshot with the usual:
```
cd libnd4j; git pull
./buildnativeoperations.sh >& libnd4j_cpu.log
./buildnativeoperations.sh -c cuda -cc 50 >& libnd4j_gpu.log
export LIBND4J_HOME=`pwd`
cd ../ndj4; git pull
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -pl '!:nd4j-tests' >& nd4j_gpu.log
```
I get a linking error at ndj4 build.

```
C:\Users\josh\AppData\Local\Temp\ccgZw96y.o:jnind4jcpu.cpp:(.text+0x4980c): undefined reference to `NativeOps::numpyFromFile(std::string)'
C:\Users\josh\AppData\Local\Temp\ccgZw96y.o:jnind4jcpu.cpp:(.text+0x49f1f): undefined reference to `NativeOps::numpyFromFile(std::string)'
collect2.exe: error: ld returned 1 exit status
```
vcvars has been sourced. 
I have recloned the git repos.
The PATH variable doesn't have any quotation marks in it (which can be an issue sometimes).

libnd4j_cpu.log can be seen here:
https://gist.github.com/Joshuaalbert/aed8bd8c717943d3e81ca7e191d85dce

libnd4j_gpu.log can be seen here:
https://gist.github.com/Joshuaalbert/759b7ded7e2aa6996896183317f7ef74

nd4j_gpu.log can be seen here: https://gist.github.com/Joshuaalbert/f6f328db3bf1ed544e8d9acd8b382da2

#### Version Information
Quadro M2000M cc 5.0
Cuda 8.0
Windows 10 64bit
VS 12.0
```
$ uname -a
MSYS_NT-10.0 LAPTOP-OCQHOCUH 2.5.2(0.297/5/3) 2016-07-15 08:31 x86_64 Msys
```

**Comment by AlexDBlack** [comment]
For reference: I don't have any build issues in lastest libnd4j + nd4j masters (Windows 10, cuda 8, VS 12).
I'm running the libnd4j build through msys2, and the nd4j build through windows cmd (my LIBND4J_HOME is hardcoded globally as an env var).

I'm running:
Msys:
```
cd libnd4j; git pull
./buildnativeoperations.sh
./buildnativeoperations.sh -c cuda -cc 61
```
cmd:
```
cd ndj4
git pull
vcvars64
mvn clean install -DskipTests
```

**Comment by saudet** [comment]
It looks like you're trying to use an old version of MSYS.
Please try to use MSYS2, as per the instruction here:
https://github.com/deeplearning4j/libnd4j/blob/master/windows.md

**Comment by Joshuaalbert** [comment]
@saudet I reinstalled msys2 and followed that guide. I get the same error. I've compiled at least 10 times before with this same setup without problems. Has anything changed in libnd4j which would let it sucessfully compile but nd4j fails to find a reference?
Here is the last part of compiling before error:
```
C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native\target\classes\org\nd4j\nativeblas\jnind4jcpu.cpp:1:0: warning: -fPIC ignored for target (all code is position independent)
 // Generated by JavaCPP version 1.3.2: DO NOT EDIT THIS FILE
 ^
In file included from C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native/../../../../libnd4j//blas/NativeOps.h:28:0,
                 from C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native\target\classes\org\nd4j\nativeblas\jnind4jcpu.cpp:106:
C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native/../../../../libnd4j//include/types/float16.h: In function 'float cpu_half2float(half)':
C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native/../../../../libnd4j//include/types/float16.h:75:36: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     return *((float*)((void*)&temp));
                                    ^
C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native/../../../../libnd4j//include/types/float16.h: In function 'half cpu_float2half_rn(float)':
C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native/../../../../libnd4j//include/types/float16.h:92:37: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     unsigned x = *((int*)(void*)(&f));
                                     ^
C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native\target\classes\org\nd4j\nativeblas\jnind4jcpu.cpp: In function 'jint JavaCPP_totalCores()':
C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native\target\classes\org\nd4j\nativeblas\jnind4jcpu.cpp:306:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i = 0; i < length; i++) {
                           ^
C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native\target\classes\org\nd4j\nativeblas\jnind4jcpu.cpp: In function 'jint JavaCPP_totalChips()':
C:\Users\josh\dl4j\build\nd4j\nd4j-backends\nd4j-backend-impls\nd4j-native\target\classes\org\nd4j\nativeblas\jnind4jcpu.cpp:357:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i = 0; i < length; i++) {
                           ^
C:\Users\josh\AppData\Local\Temp\cc4t798k.o:jnind4jcpu.cpp:(.text+0xb23ef): undefined reference to `NativeOps::numpyFromFile(std::string)'
C:\Users\josh\AppData\Local\Temp\cc4t798k.o:jnind4jcpu.cpp:(.text+0xb295c): undefined reference to `NativeOps::numpyFromFile(std::string)'
collect2.exe: error: ld returned 1 exit status
```

**Comment by saudet** [comment]
Yes, you'll also need to build the latest version of libnd4j.

**Comment by Joshuaalbert** [comment]
I did build the latest version. I am on the master branch. Do you mean another branch?

**Comment by Joshuaalbert** [comment]
@AlexDBlack Do you have any plans to release 0.8.1 to Maven? This would be one way I can get a working project, while this issue is solved.

**Comment by saudet** [comment]
0.8.1-SNAPSHOT is already on the Maven Central Repository. Please use that if you don't need to make modifications to libnd4j, yes.

**Comment by Joshuaalbert** [comment]
Okay, I should have tried that. I was looking for 0.8.1 and missed 0.8.1-SNAPSHOT. Thanks, yes this will at least enable continued work while I figure out what is wrong with my environment assuming no one else finds the same issue as me.

**Comment by huitseeker** [comment]
Any more information on your build environment that could help pin down the issue ?

**Comment by Joshuaalbert** [comment]
The compilation of nd4j cpu backend is complaining about:
`C:\Users\josh\AppData\Local\Temp\cc4t798k.o:jnind4jcpu.cpp:(.text+0xb295c): undefined reference to `NativeOps::numpyFromFile(std::string)'
collect2.exe: error: ld returned 1 exit status`

I have the following os and Visual Studio:
Windows 10 64bit
VS 12.0
```
$ uname -a
MSYS_NT-10.0 LAPTOP-OCQHOCUH 2.6.0(0.304/5/3) 2016-09-07 20:45 x86_64 Msys
```

If you look in libnd4j_cpu.log:
https://gist.github.com/Joshuaalbert/aed8bd8c717943d3e81ca7e191d85dce

I note a lot of `warning: -mtune=x86-64 is deprecated; use -mtune=k8 or -mtune=generic instead` and some warnings around NativeOps.

**Comment by Joshuaalbert** [comment]
@huitseeker @AlexDBlack Would either of you be able to put up the output of libnd4j compilation for cpu on windows 10 (if you have that) so that I can compare? It is either libnd4j failing to compile (but showing a success), or nd4j failing to link (which usually means compiler is not given the right library). Could you also tell me which version of gcc / g++ you're using?

**Comment by Joshuaalbert** [comment]
I solved this finally. The problem was gcc was being found in another folder besides msys64/bin. Make sure that msys/ming64/bin is at the front of your PATH.

**Comment by huitseeker** [comment]
Thanks for the follow-up!
