### ISSUE TITLE
Possible typo in org.nd4j.linalg.dataset.Dataset.shuffle()

### ISSUE THREAD

**Issue by mbkennel** [deeplearning4j/nd4j#1835]
``        arrays.add(getFeatures());
        dimensions.add(ArrayUtil.range(1, getFeatures().rank()));

        arrays.add(getLabels());
        dimensions.add(ArrayUtil.range(1, getLabels().rank()));

        if (featuresMask != null) {
            arrays.add(getFeaturesMaskArray());
            dimensions.add(ArrayUtil.range(1, getFeaturesMaskArray().rank()));
        }

        if (featuresMask != null) {
            arrays.add(getLabelsMaskArray());
            dimensions.add(ArrayUtil.range(1, getLabelsMaskArray().rank()));
        }

The second test for featuresMask != null seems like it should be labelsMask != null.  Everywhere else in this class, featuresMask and labelsMask are treated in parallel and independently. 

It appears that as currently written, if there is null featuresMask, but there is a non-null labelsMask, the labels will not be shuffled along with the examples.  Would this result in the wrong labels mask being applied to the examples?

**Comment by raver119** [comment]
Fixed.

Thanks for highlighting this issue. And no, it won't affect labelsMask shuffle.
