### ISSUE TITLE
INDArray JSON serialize/deserialize

### ISSUE THREAD

**Issue by loretoparisi** [deeplearning4j/nd4j#1838]
I'm trying to serialize/deserialize INDArray to a JSON String, in order to be saved on a DB. In my understanding I have to use a `NDArraySerializer`, but I do not find any concrete example how to implement serialize/deserialize.

I'm starting from this example in the `https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/serde/jackson/NdArraySerializerTest.java`

```java
ObjectMapper mapper = new ObjectMapper();
        SimpleModule nd4j = new SimpleModule("nd4j");
        nd4j.addDeserializer(INDArray.class, new NDArrayDeSerializer());
        nd4j.addSerializer(INDArray.class, new NDArraySerializer());
        mapper.registerModule(nd4j);
```

Thank you.

**Comment by marcel-93** [comment]
Not sure if this helps but Nd4j object has a write and read method (there are a few of them)

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L2424

**Comment by loretoparisi** [comment]
Thanks a lot, solved with those ones `readTxtString` and `writeTxtString`!

**Comment by marcel-93** [comment]
no problem 😄
