### ISSUE TITLE
cudaStreamSynchronize failure

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/nd4j#1844]
#### Issue Description

Experienced a cudaStreamSynchronize error about 2 hours into a training process. No other processes running at that time.

https://gist.github.com/crockpotveggies/9a149b5c076dd1208f7a3e0606050054

#### Version Information

Master

**Comment by raver119** [comment]
UI crash. Not sure what to do here without reproducible code.

**Comment by huitseeker** [comment]
@crockpotveggies Do you have a minimization for this one ?

**Comment by raver119** [comment]
I think this issue was resolved long ago. If not - please let me know.
