### ISSUE TITLE
vStack bad perf on GPU

### ISSUE THREAD

**Issue by n-gregori** [deeplearning4j/nd4j#1845]
#### Issue Description

Concatening INDArrays with vStack method takes a very long time on GPU backend.

the experiment was perfomed by the following code:

https://gist.github.com/n-gregori/36c8aa14d9cea5759e0a640443d875be

on my laptop:

* Deeplearning4j version 0.8.0
* platform information (win 7)
* CUDA version,  NOT USED
* intel i7

c ordered INDArr shape:  Rank: 3,Offset: 0
 Order: c Shape: [1,100000,150],  stride: [15000000,150,1]
f ordered INDArr shape:  Rank: 3,Offset: 0
 Order: f Shape: [1,100000,150],  stride: [1,1,100000]

Start testing with C-order: 
Elapsed time (millis): 125  with minibatch size: 2 
Elapsed time (millis): 249  with minibatch size: 4 
Elapsed time (millis): 510  with minibatch size: 8 
Start testing with F-order: 
Elapsed time (millis): 4680  with minibatch size: 2 
Elapsed time (millis): 8092  with minibatch size: 4 
Elapsed time (millis): 18575  with minibatch size: 8 

on aws GPU instance:

* Deeplearning4j 0.8.0
* platform information (centOs)
* CUDA version,  8.0 
* NVIDIA cudnn
* Tesla K80

Start testing with C-order:
Elapsed time (millis): 148653  with minibatch size: 2
Elapsed time (millis): 149443  with minibatch size: 4
Elapsed time (millis): 150001  with minibatch size: 8

Start testing with F-order:
Elapsed time (millis): 142798  with minibatch size: 2
Elapsed time (millis): 144089  with minibatch size: 4
Elapsed time (millis): 144393  with minibatch size: 8

**Comment by raver119** [comment]
So, C order is easy fix/improvement.

F order (and/or non-0 concat dimension) is a bit more complex. So far got it down to 
```
20:51:45,185 INFO  ~ Time spent: 10451 ms
```

That's batch size of 32.

**Comment by raver119** [comment]
For C order batch size 32:

```
20:54:45,440 INFO  ~ Time spent: 1034 ms
```

**Comment by raver119** [comment]
Looks like done. F order, minibatch of 32:

```
22:27:33,073 INFO  ~ Time spent: 1434 ms
```

**Comment by raver119** [comment]
Merged.
