### ISSUE TITLE
INDArray slicing

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#185]
So I'm trying to get my head around array slicing along a specified dimension for arbitrary dimensional arrays.
Specifically I'm using INDArray.slice(int i,int dimension)

Here's my intuition as to what slicing along a specific dimension should return:
Slicing a 2D array of shape [5,7]:
Slice on dimension 0: can get 5 slices of shape [1,7]
Slice on dimension 1: can get 7 slices of shape [5,1]

Slicing a 3D array of shape [5,7,9]:
Slice on dimension 0: get 5 of [7,9] i.e., from [1,7,9]
Slice on dimension 1: get 7 of [5,9] i.e., from [5,1,9]
Slice on dimension 2: get 9 of [5,7] i.e., from [5,7,1]

Slicing on 4D array of shape [5,7,9,11]
Slice on dimension 0: get 5 of [7,9,11] i.e., from [1,7,9,11]
Slice on dimension 1: get 7 of [5,9,11] i.e., from [5,1,9,11]
Slice on dimension 2: get 9 of [5,7,11] i.e., from [5,7,1,11]
Slice on dimension 3: get 11 of [5,7,9] i.e., from [5,7,9,1]

And so on.

As to what I'm actually getting:
For 2D INDArrays: slicing on d0 gives 7 of shape [5,1] not 5 of [1,7]. Slicing on d1 gives 5 of [1,7] not 7 of [5,1].

For 3+D arrays: slicing appears to be incorrect. Specifically slice i=2 is giving incorrect shapes for 3d, i=3 gives incorrect shapes for 4d, i=4 gives incorrect shape for 5d, etc. Otherwise (for all other values of i) it seems to be returning correct shape arrays (as listed above).

Tested on jblas, java and netlib-blas backends; issue is present for all of them.

Unit tests:
```java
	@Test
	public void test2DArraySlice(){
		INDArray array2D = Nd4j.ones(5,7);
		
		for( int i=0; i<5; i++ ){
			INDArray slice = array2D.slice(i,0);
			assertArrayEquals(slice.shape(),new int[]{1,7});
		}
		
		for( int i=0; i<7; i++ ){
			INDArray slice = array2D.slice(i,1);
			assertArrayEquals(slice.shape(),new int[]{5,1});
		}
	}
	
	@Test
	public void test3DArraySlice(){
		INDArray array3D = Nd4j.ones(5,7,9);
		
		for( int i=0; i<5; i++ ){
			INDArray slice = array3D.slice(i,0);
			assertArrayEquals(slice.shape(),new int[]{7,9});
		}
		
		for( int i=0; i<7; i++ ){
			INDArray slice = array3D.slice(i,1);
			assertArrayEquals(slice.shape(),new int[]{5,9});
		}
		
		for( int i=0; i<9; i++ ){
			INDArray slice = array3D.slice(i,2);
			assertArrayEquals(slice.shape(),new int[]{5,7});
		}
	}
	
	@Test
	public void test4DArraySlice(){
		INDArray array4D = Nd4j.ones(5,7,9,11);
		
		for( int i=0; i<5; i++ ){
			INDArray slice = array4D.slice(i,0);
			assertArrayEquals(slice.shape(),new int[]{7,9,11});
		}
		
		for( int i=0; i<7; i++ ){
			INDArray slice = array4D.slice(i,1);
			assertArrayEquals(slice.shape(),new int[]{5,9,11});
		}
		
		for( int i=0; i<9; i++ ){
			INDArray slice = array4D.slice(i,2);
			assertArrayEquals(slice.shape(),new int[]{5,7,11});
		}
		
		for( int i=0; i<11; i++ ){
			INDArray slice = array4D.slice(i,3);
			assertArrayEquals(slice.shape(),new int[]{5,7,9});
		}
	}
```

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/commit/9f873b5af18ebb72283e0630dac0d89f12233787
