### ISSUE TITLE
Failing tests on master : LapackTestsC LapackTestsF

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/nd4j#1851]
#### Issue Description

At master, d27065c8177fc6896b9a8f59ee0cd5e56b18332c, two failing tests  on cpu or cuda :
```
  LapackTestsC.testGetRF1DifferentOrders:47 » Blas Failed to execute dgetrf
  LapackTestsF.testGetRF1DifferentOrders:47 » Blas Failed to execute dgetrf
```

Bisection shows them failing since c82ced7a31453bbc0646041c95a37ffb4e6a5331 where the defensive condition introduced by @rcorbish triggers on 
https://github.com/deeplearning4j/nd4j/commit/c82ced7a31453bbc0646041c95a37ffb4e6a5331#diff-40677e3ab82a3c8df095927ea2daa9c0R41

/cc @raver119 @agibsonccc @rcorbish

**Comment by saudet** [comment]
Strange, I remember Adam asking me to check this, but it didn't fail on my
end when I last checked 2 weeks ago. Let me see now.

**Comment by rcorbish** [comment]
Sorry - silly bug. Thanks @saudet
