### ISSUE TITLE
mmul with row vector view array incorrect

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1854]
Reported in gitter earlier:

```
public static void main(String[] args) throws Exception {

    INDArray a = Nd4j.zeros(3,3);
    a.put(0,0, 1);
    a.put(1,0, 1);
    a.put(2,0, 1);
    INDArray b = Nd4j.rand(1,5);
    System.out.println(b);
    INDArray c = a.get(NDArrayIndex.all(),NDArrayIndex.interval(0, 1)).mmul(b);
    System.out.print(c);
}
```

I checked earlier on 0.8.0, and ```a.get(...).dup().mmul(b)``` gives different (expected) results.

**Comment by raver119** [comment]
Indexing is the first suspect I guess?

**Comment by AlexDBlack** [comment]
@raver119 Thinking about this again: indexing probably wouldn't be my first guess.
I'm thinking strides or 'need to dup' check in gemvParameters
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/blas/params/GemvParameters.java
