### ISSUE TITLE
wrong Matrix Multiplication 

### ISSUE THREAD

**Issue by jianqiangyao** [deeplearning4j/nd4j#1855]
#### Issue Description
When computing matrix multiplication, C = A * B. if A is a view and with shape of [N, 1], the result of C is wrong .

public class Data {
public static void main(String[] args) throws Exception {
    INDArray a = Nd4j.zeros(3,3);
    a.put(0,0, 1);
    a.put(1,0, 1);
    a.put(2,0, 1);
    INDArray b = Nd4j.rand(1,5);
    System.out.println(b);
    INDArray c = a.get(NDArrayIndex.all(),NDArrayIndex.interval(0, 1)).mmul(b);
    System.out.print(c);
}
}
here is the output :
[0.39, 0.63, 0.99, 0.15, 0.65]
[[0.39, 0.63, 0.99, 0.15, 0.65],
[0.00, 0.00, 0.00, 0.00, 0.00],
[0.00, 0.00, 0.00, 0.00, 0.00]]

Expected output:
[0.39, 0.63, 0.99, 0.15, 0.65]
[[0.39, 0.63, 0.99, 0.15, 0.65],
[0.39, 0.63, 0.99, 0.15, 0.65],
[0.39, 0.63, 0.99, 0.15, 0.65]]

#### Version Information
Nd4j 0.8.0,  Intel CPU,  Java 1.8.

**Comment by huitseeker** [comment]
Thanks for your report. We're going to focus discussion on #1854, which is the same issue.
