### ISSUE TITLE
Add tan (and sinh, cosh) element-wise operations

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1861]
We have cos, sin, arctan, tanh, but no vanilla tangent (tan) function.

A couple of others I noticed: sinh and cosh (hyperbolic sine/cosine).

Low priority - I don't need them for anything I'm currently doing; I just noticed that we don't have them.

**Comment by raver119** [comment]
Implemented: https://github.com/deeplearning4j/nd4j/pull/1862
