### ISSUE TITLE
Upgrade shaded Jackson versions

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1867]
We are currently using 2.5.1 for our shaded Jackson version, which was released on 25-Apr-2015. We may want to upgrade to a more recent version.

These is no pressing need to do so, but we *can* if we want, for new features and bug fixes.

Also note that it probably won't be a drop-in replacement: it appears that there are at least *some* API changes between 2.5.1 and more recent versions - https://github.com/deeplearning4j/DataVec/issues/309#issuecomment-307991474

**Comment by huitseeker** [comment]
I vote for jackson 2.6.5, which is also the version used by Spark 2.1.1
