### ISSUE TITLE
broadcast is broken

### ISSUE THREAD

**Issue by Atry** [deeplearning4j/nd4j#1869]
#### Issue Description

`broadcast` simply does not work

##### encountered behavior
``` scala
$ amm
Welcome to the Ammonite Repl 0.9.5
(Scala 2.12.2 Java 1.8.0_131)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import $ivy.`org.nd4j:nd4j-native-platform:0.8.0`  
import $ivy.$                                     
@ import org.nd4j.linalg.factory.Nd4j 
import org.nd4j.linalg.factory.Nd4j
@ Nd4j.ones(1,1).broadcast(5, 3) 
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
res2: org.nd4j.linalg.api.ndarray.INDArray = [[1.00, 1.00, 1.00],
 [1.00, 1.00, 0.00],
 [0.00, 0.00, 0.00],
 [0.00, 0.00, 0.00],
 [0.00, 0.00, 0.00]]
```
##### expected behavior
The result should be all ones.
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.8.0
* platform information (OS, etc): macOS
* CUDA version, if used: Not used
* NVIDIA driver version, if in use: Not used

**Comment by Atry** [comment]
Another ridiculous result:
```
scala> Nd4j.ones(1,1,1).broadcast(2,1,1)
res14: org.nd4j.linalg.api.ndarray.INDArray =
[1.00,

 0.00]
```

**Comment by agibsonccc** [comment]
@Atry thanks for posting the issue. We had mainly been using broadcast for rows/columns. Just update your original comment with the test cases you're seeing. We honestly don't use it a ton and appreciate the results here. We'll look in to it.
Please back off on the language though. You've made your case.

**Comment by aleSuglia** [comment]
Hi to all,

I am trying to reproduce in ND4j this Python code:
```
In [1]: import numpy as np
In [2]: x = np.random.randn(5, 20, 200)
In [3]: y = np.random.randn(200, 4)
In [4]: res = np.matmul(x, y)
In [5]: res.shape
Out[5]: (5, 20, 4)
```

So I've tried with INDArray methods to do the same, hoping that `INDArray.mmul` is smart enough to figure out the dimensions by itself:
```
        INDArray x = Nd4j.create(5, 20, 200),
                y = Nd4j.create(200, 6);

        INDArray res = x.mmul(y);
        System.out.println(res);
        System.out.println(Arrays.toString(res.shape()));
```
Unfortunately, this is not the case because I receive this weird error:
```
java.lang.IllegalStateException: Unable to get number of of rows for a non 2d matrix
```
Anyone knows how to fix it or in general to reproduce that use-case?

Thank you,
Alessandro
