### ISSUE TITLE
Checking Nan element in a INDArray with IsNaN condition incorrect

### ISSUE THREAD

**Issue by jianqiangyao** [deeplearning4j/nd4j#1871]
#### Issue Description

public static void main(String[] args){
        Condition c = new IsNaN();
        INDArray a = Nd4j.create(1,1);
        a.put(0, 0, 4.0F);
        boolean ret = BooleanIndexing.or(a, c);
        System.out.println(ret);
    }
Expect a result of "false", but got a "true".

#### Version Information
ND4J version: 0.8.0

**Comment by AlexDBlack** [comment]
As per gitter discussion: it looks like this has already been fixed after 0.8.0 was released.
Current master (0.8.1-SNAPSHOT) returns false for this code, as expected.
