### ISSUE TITLE
The linearView method do nothing.

### ISSUE THREAD

**Issue by sjsy** [deeplearning4j/nd4j#1876]
Hi
in the following code the output of 
`System.out.println(nd.linearView()); `
is the same as 
`System.out.println(nd); `

```
INDArray nd = Nd4j.create(new float[]{1, 2, 3, 4, 5, 6}, new int[]{2, 3});
System.out.println(nd);
System.out.println();
System.out.println(nd.linearView());
```
Please check the source!

**Comment by agibsonccc** [comment]
Closing this. Just use reshape(1,arr.length())
