### ISSUE TITLE
Add SELU Activation Function

### ISSUE THREAD

**Issue by mdavis95** [deeplearning4j/nd4j#1878]
https://arxiv.org/pdf/1706.02515.pdf

![screenshot from 2017-06-15 12-21-27](https://user-images.githubusercontent.com/7322079/27191314-6ae78802-51c5-11e7-8778-b8e3dab7c908.png)

α ≈ 1.6732632423543772848170429916717
λ ≈ 1.0507009873554804934193349852946

**Comment by raver119** [comment]
Implemented and merged.

**Comment by mdavis95** [comment]
Thanks!
