### ISSUE TITLE
Add version of ExistingMinibatchDataSetIterator that doesn't require a pattern

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1880]
ExistingMinibatchDataSetIterator works well - but it would be nice to be able to just list files in the root directory, instead of having to define a pattern.
Two use cases:
- Pattern may change between runs
- File namess don't follow a predictable pattern in the first place

**Comment by raver119** [comment]
As in "just grab all files and try to deserialize"?

**Comment by AlexDBlack** [comment]
@raver119 well, we probably want to specify valid extensions - but otherwise yes.
Typical use case would be "every .bin file in this directory (and maybe subdirectories??) is a DataSet or MultiDataSet"

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/deeplearning4j/blob/c54aeda16b375bb60f9cf4e2fe25a50b939205f7/deeplearning4j-nn/src/main/java/org/deeplearning4j/datasets/iterator/file/FileDataSetIterator.java
