### ISSUE TITLE
Add broadcast comparison ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1884]
Add broadcast element-wise comparison ops (less than, greater than etc). For example, we have an addiRowVector but no equivalent "gtRowVector" operation and the like; we have full-array ops of this type, but not broadcast versions.

We probably don't need a convenience method on the INDArray interface, just BroadcastGreaterThan, BroadcastLessThan, etc ops.

Priority: lowish. Will allow for some optimizations for (the soon to be implemented) EvaluationBinary with custom decision threshold cases; can use a for loop until then.

**Comment by raver119** [comment]
You probably want that to be TAD-compatbile, with multi-dimensionality support? Not just rows?

**Comment by raver119** [comment]
I mean - it sounds like TAD-based equality reduction, not just a broadcast :)

**Comment by AlexDBlack** [comment]
Right, the general implementation should be TAD based. I just want to use it with row cases right now :)

Basically if I can do this with element-wise comparisons and get the resulting bit-mask, I'll be happy
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L2410-L2431

**Comment by raver119** [comment]
Ah, so you want bit-basks, not reductions. Ok.

**Comment by AlexDBlack** [comment]
Right, broadcast versions of these: https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/comparison

**Comment by raver119** [comment]
Implemented, tested, merged.

Tests as guide for them: https://github.com/deeplearning4j/nd4j/blob/dff336eb06c7fad5a748190ee56fadaab6065402/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L4217-L4284
