### ISSUE TITLE
addi vs subi on row view of INDArray using jblas

### ISSUE THREAD

**Issue by soumen-chakrabarti** [deeplearning4j/nd4j#189]
nd4j-jblas 0.0.3.5.5.5

        INDArray arr = Nd4j.create(new float[]{1,2,3,4},new int[]{2,2});
        System.err.println("arr=" + arr);
        INDArray brr = Nd4j.create(new float[]{5,6},new int[]{1,2});
        System.err.println("brr = " + brr);
        arr.getRow(1).addi(brr);
        System.err.println("arr=" + arr);

addi does what it's supposed to; if you replace with subi, the output is not as expected.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/190

**Comment by soumen-chakrabarti** [comment]
Thanks. If https://github.com/deeplearning4j/nd4j/pull/190 has a fix, how do i upgrade to that version? Thus far, pom.xml was fetching (apparently buggy) nd4j to build my project. How do I replace the Maven default with the bugfixed revision?

And how do I teach IntelliJ to also fetch source/api-doc for a package if available, so hover can show me param lists, comments on variables and classes, etc.

**Comment by agibsonccc** [comment]
Do a git pull and install from source for the moment.

**Comment by soumen-chakrabarti** [comment]
Is this fix in mainline maven packages yet?

**Comment by agibsonccc** [comment]
You should be set to go now. Run it and take a look.
