### ISSUE TITLE
IntervalIndex has a wrong behaviour when used with a SpecifiedIndex

### ISSUE THREAD

**Issue by audreyloeffel** [deeplearning4j/nd4j#1893]
The lower bound of the interval is not taken into account, it always begins at 0 (See: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/NDArrayIndex.java#L296)

Example of the wrong behaviour:
``` 
array = 
[[[0.39,  0.99,  0.57],  
  [0.73,  0.01,  0.80]],  

 [[0.40,  0.78,  0.53],  
  [0.07,  0.75,  0.49]],  

 [[0.38,  0.47,  0.61],  
  [0.89,  0.39,  0.55]],  

 [[0.38,  0.97,  0.17],  
  [0.54,  0.03,  0.27]]]

// array.shape = [4, 2, 3]
INDArray subarray = arr.get(
                NDArrayIndex.interval(1, 3),
                new SpecifiedIndex(new int[]{0}),
                new SpecifiedIndex(new int[]{0, 2}));
```

After the indexes resolution,  the index of the 0th dimension becomes a SpecifiedIndex with indexes = [0, 1, 2] instead of [1, 2]. 
It returns:
```
subarray = 
[[0.39,  0.57],  

 [0.40,  0.53],  

 [0.38,  0.61]]

// subarray.shape = [3, 1, 2]
```
instead of:
```
subarray = 
[[0.40, 0.53],
[0.38, 0.61]]
//subarray.shape = [2, 1, 2]
```

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/1960
