### ISSUE TITLE
Unable to run FFT due to UnsupportedOperationException of BaseComplexNDArray

### ISSUE THREAD

**Issue by locuslin** [deeplearning4j/nd4j#1898]
#### Issue Description

I tried to run FFT.fft(INDArray),but failed,even if tried to convert INDArray to IComplexNDArray by myself,it still can't work.I find that many methods will throw UnsupportedOperationException ,so is there any way to do FFT properly ?

#### Version Information
nd4j:0.8.0

**Comment by eraly** [comment]
Complex ndarrays are currently not supported. ROI for this is low for this. It is closer to the end of a very long to-do list.
