### ISSUE TITLE
testTadReduce3_3() 

### ISSUE THREAD

**Issue by lukeczapla** [deeplearning4j/nd4j#1903]
#### Issue Description

I tried to use the broadcast op to combine 5x10 and 2x10 to get 10D euclidean distances and it threw a fatal error that not even Java caught.  Is this possible?

```   
public void testTadReduce3_3() throws Exception {
        INDArray initial = Nd4j.create(5, 10);
        for (int i = 0; i < initial.rows(); i++) {
            initial.getRow(i).assign(i + 1);
        }
        INDArray needle = Nd4j.create(2, 10).assign(1.0);
        INDArray reduced = Nd4j.getExecutioner().exec(new EuclideanDistance(initial, needle), 1);
        log.info("Reduced: {}", reduced);
    }
```

[response is a total system crash]

#### Version Information
Nd4j 0.8.1-snapshot

#### Contributing

I can't really help here :)

**Comment by raver119** [comment]
Your code is wrong. Along dimension 1 you don't have 2x10 arrays. 

However, i should add better params validation there.

**Comment by raver119** [comment]
Probably my answer isn't clear enough.

Two comparison options here:
1) Compare X vs Y as in X.tad along dimension 1vs Y.tad along dimension 1.
2) Compare X vs Y as in X.tad along dimension 1 vs Y full array

Obviously, your code doesn't fall into any of those cases, so it goes into option 1 as default, TAD vs TAD. and along dimension 1 your X has 5 rows, and Y only 2. Obviously causing segfault. Better params validation incoming

**Comment by raver119** [comment]
Additional validation added, thanks for highlighting this issue.

**Comment by lukeczapla** [comment]
So wait, I thought that they both have size 10 along dimension 1?  If there any way to fix this so if does what was intended, that is, produces a 5x2 matrix with all the 10D distances?
