### ISSUE TITLE
reopening #1902

### ISSUE THREAD

**Issue by lukeczapla** [deeplearning4j/nd4j#1904]
#### Issue Description
I get this error occasionally using Transforms.atan2 that was just implemented

`m.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise_transform.h:409[ERROR] Unknown opNum=69 on /Volumes/extHD/jenkins/workspace/dl4j/all-multiplatform_macosx-x86_64/stream0/libnd4j/include/loops/pairwise`

#### Version Information
ND4j-0.8.1.SNAPSHOT

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
I think it just means your copy of libnd4j was compiled before op was added. And nd4j has op declared.

Bad luck i think. 

@huitseeker any other ideas?

**Comment by lukeczapla** [comment]
Yes I'm just using your snapshots.  How would I compile me up a libnd4j that has the updates?  I don't see any *.cpp or *.c or *.nvcc files anywhere in the Nd4j folder

**Comment by huitseeker** [comment]
Yes, I've seen this error before and can confirm @raver119's diagnosis is probably correct. Please clean your local cache (`mvn dependency:purge-local-repository`), recompile libnd4j and nd4j and retry. If you have any issues, report the commit hashes of each (libnd4j, nd4j) directory (`gi rev-parse HEAD`). If you don't, please report here so we can close this.

**Comment by lukeczapla** [comment]
Huitseeker.  It seems to work now.  The order of the arguments is unusual but if it's going to stay atan2(x, y) that's OK.  It caused me about 2 hours of wasted time thinking my code was broken but now that I know, it's all good with me :)

**Comment by raver119** [comment]
It's not x,y. It's y,x. Read variables names in Transforms.atan2 method.

**Comment by saudet** [comment]
@raver119 why is the order reversed here?
https://github.com/deeplearning4j/libnd4j/blob/master/include/ops/ops.h#L1214
