### ISSUE TITLE
SELU Activation missing in IActivation @JsonSubTypes.Type

### ISSUE THREAD

**Issue by mjakobus** [deeplearning4j/nd4j#1905]
#### Issue Description

Loading a ComputationGraph with a SELU activation function fails, when using the ModelSerializer.
It seems that the SELU Activation is missing in the Json annotations of the IActivation Interface.
Sorry, I currently can't provide a stacktrace. If necessary I could provide it later.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: Snaptshot 8.1 (reimportet yesterday)

**Comment by raver119** [comment]
Oops.

**Comment by raver119** [comment]
Fixed, thanks for highlighting this issue.
