### ISSUE TITLE
dl4j-spark_2.10: no nd4jcpu in java.library.path

### ISSUE THREAD

**Issue by singh-abhijeet** [deeplearning4j/nd4j#1909]
#### Issue Description
Trying out [Spark example](https://github.com/deeplearning4j/dl4j-examples/blob/master/dl4j-spark-examples/dl4j-spark/src/main/java/org/deeplearning4j/rnn/SparkLSTMCharacterExample.java), but getting  `java.lang.ExceptionInInitializerError`.

Used `nd4j-native-platform` as described [here](https://github.com/deeplearning4j/nd4j/issues/1118), but still the problem persists.

#### Version Information

* Deeplearning4j version: 0.8.0
* platform information: Win 7, SP1 x64
* JVM: 1.8, 64-bit

#### POM.xml:

`<dependencies>
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>dl4j-spark_2.10</artifactId>
			<version>0.8.0_spark_1</version>
		</dependency>
		<dependency>
			<groupId>com.beust</groupId>
			<artifactId>jcommander</artifactId>
			<version>1.72</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>${nd4j.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-streaming_2.10</artifactId>
			<version>1.6.1</version>
		</dependency>
	</dependencies>
	<properties>
		<nd4j.version>0.8.0</nd4j.version>
	</properties>`

[Attachment: stacktrace.txt](https://github.com/deeplearning4j/nd4j/files/1119918/stacktrace.txt)

**Comment by agibsonccc** [comment]
Are you running spark 1 or 2

**Comment by singh-abhijeet** [comment]
Hey Adam, am using Spark 1.6.1. Quoting from POM.xml:
```xml
<dependency>
		<groupId>org.deeplearning4j</groupId>
		<artifactId>dl4j-spark_2.10</artifactId>
		<version>0.8.0_spark_1</version>
</dependency>
```
Will try with Spark 2.2 and share the result. Btw, why closed the issue?

**Comment by saudet** [comment]
It says the file is missing, but error messages on Windows are not helpful. Could you check that the DLLs get properly extracted inside `.javacpp/cache` in your home directory?

**Comment by singh-abhijeet** [comment]
@saudet Just checked, `C:\Users\user_name\.javacpp\cache` has DLLs in the following folders:

- mkl_rt.dll
- nd4j-native-0.8.1-SNAPSHOT-windows-x86_64.jar
- openblas-0.2.19-1.3-windows-x86_64.jar

**Comment by saudet** [comment]
Those are directories, what's in them?

**Comment by singh-abhijeet** [comment]
@saudet @agibsonccc Tried with Spark 2, but in vain.

POM.xml:
```xml
<dependencies>		
		<dependency>
			<groupId>org.deeplearning4j</groupId>
			<artifactId>dl4j-spark_2.11</artifactId>
			<version>${nd4j.version}_spark_2</version>
		</dependency>
		<dependency>
			<groupId>com.beust</groupId>
			<artifactId>jcommander</artifactId>
			<version>1.72</version>
		</dependency>
		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-native-platform</artifactId>
			<version>${nd4j.version}</version>
		</dependency>
	</dependencies>

	<properties>
		<nd4j.version>0.8.0</nd4j.version>
	</properties>
</project>
```

**Comment by singh-abhijeet** [comment]
> Those are directories, what's in them?

@saudet DLL files:
### mkl_rt.dll
1. libopenblas.dll

### nd4j-native-0.8.1-SNAPSHOT-windows-x86_64.jar
1. jnind4jcpu.dll
2. libnd4jcpu.dll

### openblas-0.2.19-1.3-windows-x86_64.jar
1. jniopenblas.dll
2. libopenblas.dll

**Comment by saudet** [comment]
So, it's all there. There's something else that prevents Java from loading those DLLs. Try to use Dependency Walker to find out what that is exactly:
https://github.com/bytedeco/javacpp-presets/wiki/Debugging-UnsatisfiedLinkError-on-Windows
Replace `<module>` with Nd4jCpu, and fix whatever needs to be fixed with your OS.

**Comment by singh-abhijeet** [comment]
As @saudet mentioned, this seems more like a _Java DLL load_ problem than a DL4J specific one. I tried [this ](https://stackoverflow.com/questions/1403788/java-lang-unsatisfiedlinkerror-no-dll-in-java-library-path) and included the DLLs manually in `java.library.path`, and it worked! 🥇 

Code:
```java
System.setProperty("java.library.path", "C:/Users/user_name/.javacpp/cache/mkl_rt.dll;C:/Users/user_name/.javacpp/cache/nd4j-native-0.8.0-windows-x86_64.jar/org/nd4j/nativeblas/windows-x86_64;C:/Users/user_name/.javacpp/cache/openblas-0.2.19-1.3-windows-x86_64.jar/org/bytedeco/javacpp/windows-x86_64");
```

@agibsonccc Currently am not building an Uber JAR, just running the Main class via Eclipse. Are the DLLs included while creating a shaded JAR❔ 

Meanwhile, will try DWalker to see what prevents Java from loading the DLLs.
