### ISSUE TITLE
Nd4j.writeTxt assumes its input is a matrix

### ISSUE THREAD

**Issue by radiodee1** [deeplearning4j/nd4j#191]
I am using a convolutional neural net layer. I am trying to save the bias values. 

INDArray test = null;
key = ConvolutionParamInitializer.CONVOLUTION_WEIGHTS;
test = layer.getParam(key);

when I use 

Nd4j.writeTxt(test, "somefilename", ","); 

I get this: 

java.lang.IllegalStateException: Unable to get number of of rows for a non 2d matrix

**Comment by agibsonccc** [comment]
I'm going to combine this with: https://github.com/deeplearning4j/nd4j/issues/101

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/commit/212110892873ab4279dcd43787460eec4bc417df
