### ISSUE TITLE
a pairwise EuclideanDistance reduction - new functionality request

### ISSUE THREAD

**Issue by lukeczapla** [deeplearning4j/nd4j#1910]
#### Issue Description

This is a request for new functionality in Nd4j.  I have to calculate pairs of distances (an N^2 problem) in a Monte Carlo algorithm, so I've adopted Nd4j as a platform.  Basically, the functionality I am looking for is a reduction that can take two matrices that have the same size along one dimension, and calculate a matrix of euclidean distances.  That size just needs to be 3 for my application, since it's spatial coordinates.

For instance, one might have shape of [805, 3] and the other might have shape of [805, 3] and the result I'm looking for is [805, 805] (or any shape that's 805^2) where each element is the distance between rows i and rows j of the two separate matrices (sqrt((x1-x2)^2+(y1-y2)^2+(z1-z2)^2).    It's somewhat similar to  testTadReduce3_3() but quite different in that it would report all pair-wise distances.

If it could work with different numbers of rows that'd be good too, like combining [5000, 3] with [805, 3] and returning all pairs as [5000, 805] or any shape with the same total number of elements.  The optimization of this kind of thing has a lot of applications in many problems and would definitely lead to more scientific computing work using Nd4j.

#### Version Information

Nd4j 0.8.1-snapshot

#### Contributing

CUDA has N-body examples on NVIDIA's web site, so I can look up how they dealt with this issue.

**Comment by raver119** [comment]
So, basically for any given dimension you want to compare All vs All...

**Comment by lukeczapla** [comment]
Yep, all pairs, if it's Nx3 and Mx3 then NxM distances are calculated.  It's to detect whether two objects that consist of little points overlap and use distances coming out to calculate energies.

**Comment by raver119** [comment]
Implemented and merged: https://github.com/deeplearning4j/nd4j/pull/1915
