### ISSUE TITLE
Missing entropy-calculation for INDArrays

### ISSUE THREAD

**Issue by RayBreslin** [deeplearning4j/nd4j#1914]
Hello,

as already discusses with raven119 on Gitter I would like to file an issue regarding a potential addon-functionality for the INDArray-class.

Currently when I want to calculate the entropy of an INDArray it would need to look like this:

```
// f.ex. mxn-matrix with random-data
INDArray data;
INDArray entropy;
double[] tmpEntropy;

for (int i = 0; i < n; i++) {
    tmpEntropy[i] = MathUtils.entropy(data.getColumn(i).data().asDouble());
}
entropy = Nd4j.create(tmpEntropy);
```

Since a lot of other functions like mean(), std(), var(), etc. are already available for INDArrays I thought it might be a good addon!

Kind regards,

Ray

**Comment by raver119** [comment]
Implemented and merged: https://github.com/deeplearning4j/nd4j/pull/1915
