### ISSUE TITLE
incorrect answer in Nd4j user guide for Index Accumulation Ops example.

### ISSUE THREAD

**Issue by drewnoff** [deeplearning4j/nd4j#1916]
I believe there is incorrect answer for example for Index Accumulation Ops  along dimention `1` in nd4j user guide http://nd4j.org/userguide#indexaccumops.
Provided example:
input 3x3 array
```
[[0, 8, 4],
 [5, 3, 5],
 [2, 3, 6]]
```
and example says ` had we instead done the operation along dimension 1, we would get a column vector with shape [3,1], with values (2,0,2)`. But I think that the correct answer would be `(1, 0, 2)` as 
for the first row the index of max element is `1` but not `2`.

**Comment by tomthetrainer** [comment]
@drewnoff , I assigned this issue to myself and will patch the docs if needed.

Can you share your code that exhibits this error in agist so I can quickly confirm?

**Comment by drewnoff** [comment]
@tomthetrainer , here is the gist 
https://gist.github.com/drewnoff/41e44efebf43170405a3a5aac5902864

**Comment by tomthetrainer** [comment]
Thanks for the report and the code to verify updating the page.
