### ISSUE TITLE
Copy throws unsupported operation exception

### ISSUE THREAD

**Issue by lineback** [deeplearning4j/nd4j#192]
var y = Nd4j.ones(4,4)           //> Y  : Org.Nd4j.Linalg.Api.Ndarray.Indarray = [[1.0, 1.0, 1.0, 1.0]
                                        //|  [1.0, 1.0, 1.0, 1.0]
                                        //|   ,[1.0, 1.0, 1.0, 1.0]
                                        //|  ]
                                                  //| 
    var z = Nd4j.zeros(4,4)          //> Z  : Org.Nd4j.Linalg.Api.Ndarray.Indarray = [[0.0, 0.0, 0.0, 0.0]
                                        //|  [0.0, 0.0, 0.0, 0.0]
                                        //|   ,[0.0, 0.0, 0.0, 0.0]
                                        //|  ]
                                        //| 
  
    Nd4j.copy(y, z)                      //> Java.Lang.Unsupportedoperationexception
                                       //| 	At Org.Nd4j.Linalg.Api.Ndarray.Linearviewndarray.Data(Linearviewndarray.
                                      //| Java:135)
                                      //| 	At Org.Nd4j.Linalg.Api.Ndarray.Basendarray.Createscalarforindex(Basendar
                                     //| Ray.Java:2967)
                                     //| 	At Org.Nd4j.Linalg.Api.Ndarray.Basendarray.Getscalar(Basendarray.Java:19
                                     //| 61)
                                     //| 	At Org.Nd4j.Linalg.Factory.Basendarrayfactory.Copy(Basendarrayfactory.Ja
                                                  //| Va:434)
                                                  //| 	At Org.Nd4j.Linalg.Factory.Nd4j.Copy(Nd4j.Java:1260)

**Comment by agibsonccc** [comment]
As a work around y.assign(z) will work as well

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/commit/70855bc59808e48f583a70078cfda32b61448892
