### ISSUE TITLE
symmetricGeneralizedEigenvalues()

### ISSUE THREAD

**Issue by lukeczapla** [deeplearning4j/nd4j#1926]
#### Issue Description

The functions in Eigen.java are mis-documented (it is indeed returning the Eigenvectors, which is what I want, and it is solving A x = L x) and I suggest these changes to Eigen.java JavaDoc for the `public static INDArray symmetricGeneralizedEigenvalues(INDArray A)`   :

https://gist.github.com/lukeczapla/3d79c65e1a8989721966bf6378843c1b

And here are my tests: https://gist.github.com/lukeczapla/f8e14e93dfa816a5ad88a2a466ff40c0

The other version `public static INDArray symmetricGeneralizedEigenvalues(INDArray A, INDArray B)` is not doing what it claims.  I could only think of something like this to do it, but I'm not sure if this is good:

`    /**
     * Compute generalized eigenvalues of the problem A x = L B x.
     *
     * @param A symmetric Matrix A.
     * @param B symmetric Matrix B.
     * @return a vector of eigenvalues L.
     */

    public static INDArray symmetricGeneralizedEigenvalues(INDArray A, INDArray B) {
        assert A.rows() == A.columns();
        assert B.rows() == B.columns();
        INDArray W = Nd4j.create(A.rows());
        Nd4j.getBlasWrapper().syev( 'V', 'L', InverseMatrix.inverse(B, false).mmul(A), W);
        return W;
    }
`

#### Version Information

ND4J 0.8.1-SNAPSHOT

#### Contributing

My code and documentation gist is above, and there is a related pull request that attempts to fix everything, keeping in mind that syev() is the lapack one that's best implemented at the moment.

**Comment by saudet** [comment]
@rcorbish What do you think?

**Comment by rcorbish** [comment]
I took a quick look. This looks fine, it's nice to have a better interface to syev in Eigen.

**Comment by lukeczapla** [comment]
Thank you.  I have been doing some work on principal component analysis in my workspace, might this be useful for Nd4j?   The test is generating correlated data, performing an "inverse harmonic analysis", and then using this new symmmetricGeneralizedEigenvalues(A, B) to get the principal components along the variables (two files in one gist):

https://gist.github.com/lukeczapla/c9736b74e765478de277d68d3f8f8d40


You can see I'm still testing it but it's coming out correctly, putting the orthonormal basis vector of greatest variance first in the list (since syev() does that automatically with eigenvalues in increasing order).

**Comment by saudet** [comment]
@rcorbish Thanks!

@lukeczapla There's already some PCA code in ND4J, but anything to improve on that is very welcome, yes, thanks! Can we close this issue though?
