### ISSUE TITLE
Add matrix power operation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#1933]
Moved from here: https://github.com/deeplearning4j/deeplearning4j/issues/3661

https://docs.scipy.org/doc/numpy-1.11.0/reference/generated/numpy.linalg.matrix_power.html

```
Raise a square matrix to the (integer) power n.

For positive integers n, the power is computed by repeated matrix squarings and matrix multiplications.
If n == 0, the identity matrix of the same shape as M is returned. If n < 0, the inverse is computed and then raised to the abs(n).
```

**Comment by lukeczapla** [comment]
is somebody going to write a GPU-accelerated version of this?  because I already have this in my code, just not optimized beyond the basic functions (which already are GPU accelerated but not for vectorizing this long calculation).  Would that be ok?

**Comment by lukeczapla** [comment]
https://gist.github.com/lukeczapla/09217fa7f25ed1315832d71ae54bc963

**Comment by lukeczapla** [comment]
I can make it mpow and mpowi if that's better  (instead of boolean inplace)

**Comment by saudet** [comment]
Yes, sure, please do send as a PR. I'm sure @raver119 will approve once he wakes up :)

**Comment by lukeczapla** [comment]
Ok excellent.  I just changed my existing PR to include it in Transforms, replacing boolean inplace with boolean dup (basically !inplace) to go with all the other Transforms syntax.  It's where it fit the best.  My tests were fairly simple like this

`      
        System.out.println(ns.format(Transforms.mpow(x, -5, false))+"\n"+ns.format(x));
        x = Nd4j.eye(10).muli(5);
        System.out.println(ns.format(Transforms.mpow(x, 0, true))+"\n"+ns.format(x));
`

And I changed that to try lots of positive and negative numbers.  It's just a bunch of mmuli's so if it works for factors of the identity matrix for all the cases then it's definitely going to work for everything.

**Comment by lukeczapla** [comment]
It could be improved though, the idea of repeated matrix squarings makes sense.  If you want the 9th power, well log_2 (9) rounded down is 3.  I could multiply the result matrix with itself three times and then multiply in one more of the original matrix (or its inverse if n < 0) and it would save a lot of operations.

**Comment by lukeczapla** [comment]
OK, That is done and tested with a non-identity matrix and weird powers like 15.  added to PR.

**Comment by lukeczapla** [comment]
It could be optimized even more with storing power matrices in memory and doing a little count in binary type of routine.   Like M^15 = M^8 * M^4 * M^2 * M      (1111 in binary)

**Comment by lukeczapla** [comment]
can we close this?  it's been merged with the snapshot and I'll optimize it further in next iteration as described in the last comment.

**Comment by ThodorisZois** [comment]
Well done!
