### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#1945]
Documentation should be reviewed.

http://nd4j.org/introduction#elementwise-vector-operations

I.e. 

```
INDArray nd = Nd4j.create(new float[]{1,2,3,4},new int[]{2,2});
[[1.0 ,3.0]
 [2.0 ,4.0]]
```

It's clearly wrong for C order, which is default. It's output of F order.

**Comment by tomthetrainer** [comment]
I patched only that section, agree perhaps a full review is needed, for now a quick patch of the three vector operations that had the error.
