### ISSUE TITLE
problem by compiling 

### ISSUE THREAD

**Issue by sg2013test** [deeplearning4j/nd4j#195]
When I attempt to compile nd4j using mvn clean install -DskipTests -Dmaven.javadoc.skip=true
I getting this:

"
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.21022.08 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

jniLoop.cpp
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(222) : warning C4244: '=' : co
nversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(228) : warning C4244: '=' : co
nversion from 'int' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(234) : error C3861: 'roundf':
identifier not found
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(240) : error C3861: 'roundf':
identifier not found
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(355) : warning C4244: '=' : co
nversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(361) : warning C4244: '=' : co
nversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(367) : warning C4244: '=' : co
nversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(373) : warning C4244: '=' : co
nversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(379) : warning C4244: '=' : co
nversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(385) : warning C4244: '=' : co
nversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(473) : warning C4244: 'argumen
t' : conversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(483) : warning C4244: 'argumen
t' : conversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(536) : error C3861: 'round': i
dentifier not found
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(542) : warning C4244: 'initial
izing' : conversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(543) : error C3861: 'roundf':
identifier not found
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(548) : warning C4244: 'initial
izing' : conversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(624) : warning C4244: 'argumen
t' : conversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(632) : warning C4244: 'argumen
t' : conversion from 'double' to 'float', possible loss of data
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(718) : error C3861: 'fmaxf': i
dentifier not found
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(747) : error C3861: 'fminf': i
dentifier not found
C:\github\nd4j\nd4j-x86/src/main/resources/Loop.h(765) : error C3861: 'fmaxf': i
dentifier not found
C:\github\nd4j\nd4j-x86\target\classes\org\nd4j\linalg\cpu\javacpp\jniLoop.cpp(2
04) : warning C4996: 'strcpy': This function or variable may be unsafe. Consider
 using strcpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. Se
e online help for details.
        C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\include\string.h(7
4) : see declaration of 'strcpy'
C:\github\nd4j\nd4j-x86\target\classes\org\nd4j\linalg\cpu\javacpp\jniLoop.cpp(4
03) : warning C4244: 'argument' : conversion from 'jlong' to 'size_t', possible
loss of data
C:\github\nd4j\nd4j-x86\target\classes\org\nd4j\linalg\cpu\javacpp\jniLoop.cpp(4
20) : warning C4244: 'argument' : conversion from 'jlong' to 'size_t', possible
loss of data
C:\github\nd4j\nd4j-x86\target\classes\org\nd4j\linalg\cpu\javacpp\jniLoop.cpp(4
33) : warning C4244: 'argument' : conversion from 'jlong' to 'size_t', possible
loss of data
C:\github\nd4j\nd4j-x86\target\classes\org\nd4j\linalg\cpu\javacpp\jniLoop.cpp(4
50) : warning C4244: 'argument' : conversion from 'jlong' to 'size_t', possible
loss of data
C:\github\nd4j\nd4j-x86\target\classes\org\nd4j\linalg\cpu\javacpp\jniLoop.cpp(4
68) : warning C4244: 'argument' : conversion from 'jlong' to 'size_t', possible
loss of data
C:\github\nd4j\nd4j-x86\target\classes\org\nd4j\linalg\cpu\javacpp\jniLoop.cpp(9
77) : warning C4800: 'jboolean' : forcing value to bool 'true' or 'false' (perfo
rmance warning)
"

Any ideas why ??
tnx

**Comment by agibsonccc** [comment]
This was figured out as expressed in gitter.
