### ISSUE TITLE
The most efficient way to sample with replacement from NDArray

### ISSUE THREAD

**Issue by rzykov** [deeplearning4j/nd4j#1952]
Hi,

I'm working with nd4j from Scala and need to write function for random sampling rows with replacement from NDArray.
Now I wrote:

```
  def sampleWithReplacementByRow(data: INDArray, sampleSize: Int ): INDArray = {
    val index = (0 until data.rows).toArray.toNDArray
    val probs = (0 until data.rows).map(_ => 1.0/data.rows).toArray.toNDArray
    val sample = Nd4j.choice(index, probs, sampleSize)
    val sampleIndex =  for( i <- 0 until sampleSize) yield {sample.getInt(i)}
    data.getRows(sampleIndex.toArray : _*).dup()
  }
```
The function take 2D Matrix, sample size (number of rows of a target matrix) and generates a 2D matrix with sampled rows. I suspect there is more effective way to do it with indices.

Thanks in advance,
Roman

**Comment by raver119** [comment]
Take a look at Nd4j.pullRows()

**Comment by rzykov** [comment]
Thanks, I changed it.
Is it possible to add another version of getRows, where indices would be represented by NDArray rather than Array?

**Comment by rzykov** [comment]
I found the DataSet class is more appropriate for my task. It has sample method in a box. So I closed issue
