### ISSUE TITLE
SSL certificate

### ISSUE THREAD

**Issue by damianoporta** [deeplearning4j/nd4j#1966]
The userguide https://nd4j.org/userguide has a problem with ssl certificate.

**Comment by jsteggink** [comment]
Problem is it's hosted by github with a *github.com certificate.

**Comment by ejunprung** [comment]
@damianoporta Sorry about that. Could you remove https for the time being? So for example, just navigate to http://nd4j.org/userguide and it should work.  

I'm going to acquire an SSL certificate for ND4J.org so it'll be fixed in the coming days.
