### ISSUE TITLE
Where operation on nd-arrays

### ISSUE THREAD

**Issue by michaelpetruzzellocivicom** [deeplearning4j/nd4j#1968]
Right now the only way to search through these kinds of arrays is manually. This results in bad performance. It would be great if there could be a where function,[ much like described here.](https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html) so that everything is running efficiently on the backend.

**Comment by raver119** [comment]
basically all you need is javadoc for 3 classes:
1) Nd4j
2) INDArray
3) Transforms, this one is optional though.

**Comment by agibsonccc** [comment]
You'll want the BooleanIndexing class that handles that.

**Comment by michaelpetruzzellocivicom** [comment]
Thank you, that was very helpful.
