### ISSUE TITLE
Changing factory order changes exec order

### ISSUE THREAD

**Issue by njenwei** [deeplearning4j/nd4j#1971]
#### Issue Description
I've recently decided to switch to a pure fortran implementation in my project, and the executor seems to be working on the dimensions differently, although the order of the INDArray is the same. for example: 

        INDArray mat1 = Nd4j.arange(0., 18.).dup('f').reshape('f', 3, 3, 2);
        System.out.println(mat1.min(1));
        Nd4j.factory().setOrder('f');
        INDArray mat2 = Nd4j.arange(0., 18.).reshape(3, 3, 2);
        System.out.println(mat2.min(1));
        System.out.println(mat1.min(1));

gives

```
[[0.00, 9.00],
 [1.00, 10.00],
 [2.00, 11.00]]

[[0.00, 10.00],
 [9.00, 2.00],
 [1.00, 11.00]]

[[0.00, 10.00],
 [9.00, 2.00],
 [1.00, 11.00]]
```

I would have expected the executor, within `min()` to provide the same behaviour for all three calculations, given that the order of the array was set before it was called.

Is there documentation that points to this case?

#### Version Information
I'm using Nd4j 0.8.0.

**Comment by raver119** [comment]
There's "default order" thing. If you don't specify shape - default one will be used. In first case - you have F data, but C order of result.

**Comment by njenwei** [comment]
But even when I specify
```
        INDArray mat1 = Nd4j.arange(0., 18.).dup('f').reshape('f', 3, 3, 2);
        System.out.println(mat1.min(1).dup('f'));
        System.out.println(mat1.min(1).dup('f').shapeInfoToString());
        Nd4j.factory().setOrder('f');
        System.out.println(mat1.min(1));
        System.out.println(mat1.min(1).shapeInfoToString());
```
I get the same result. mat1 is also of F order.
```
[[0.00, 9.00],
 [1.00, 10.00],
 [2.00, 11.00]]
Rank: 2,Offset: 0
 Order: f Shape: [3,2],  stride: [1,3]

[[0.00, 10.00],
 [9.00, 2.00],
 [1.00, 11.00]]
Rank: 2,Offset: 0
 Order: f Shape: [3,2],  stride: [1,3]
```

Perhaps I am not understanding it right?

**Comment by njenwei** [comment]
@raver119 Do you have any input to this issue?

**Comment by raver119** [comment]
Yep, sorry.

So, here's the fact: by design reduction results are stored linearly. So, for TAD 0, result index will be 0, for TAD 1, result index will be 1, etc. That happens pretty much regardless of result shape.
