### ISSUE TITLE
Missing information for INDarray-documentation

### ISSUE THREAD

**Issue by RayBreslin** [deeplearning4j/nd4j#1983]
Hello,

I was looking for a way to calculate the norm of a vector and I came across the INDArray-functions norm1() and norm2(). 

But since the java-documentation didnt specify what the difference between these 2 was, I had to figure it out by trial n error (didnt wanted to look into the code itself).

So the addon "abs norm" and "square norm" might have helped there!

Kind regards,

Ray

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/nd4j/pull/2009
