### ISSUE TITLE
Race Conditions cause inconsistent results in tests

### ISSUE THREAD

**Issue by olafhel** [deeplearning4j/nd4j#199]
I tried to run the test and the result was https://gist.github.com/olafhel/2ba3f2b60387c3329039

After I tried again it was ok : Strange behaviour , as seen with Adam possible race condition even if racecheck doesn't say so

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2015 NVIDIA Corporation
Built on Mon_Feb_16_23:23:36_CST_2015
Cuda compilation tools, release 7.0, V7.0.27

========= CUDA-MEMCHECK
========= Nothing to check
========= No CUDA-MEMCHECK results found

**Comment by agibsonccc** [comment]
I'll keep an eye on this. This will be a good reminder for me to double check.

**Comment by olafhel** [comment]
Still the same problem.
I uninstalled an reinstalled CUDA several times.
Reboot my Mac several times too.

testOnes(jcuda.jcublas.fft.JCudaFftTest)  Time elapsed: 1.09 sec  <<< FAILURE!
java.lang.AssertionError: expected:<[[25.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i]
[0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i]
 ,[0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i]
 ,]
> but was:<[[15.0 + 4.316356658935547i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i]
[10.194209098815918 - 5.194209098815918i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i]
 ,[0.6836433410644531 - 4.316356658935547i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i ,0.0 + 0.0i]
 ,]
>

**Comment by agibsonccc** [comment]
I'll let you know when I try this. This is easily a day of my time. I'm focused on other areas of testing atm.

**Comment by olafhel** [comment]
We took the race condition route but are we sure that the issue doesn't come from JCudaFft or JCufft ?

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/204
