### ISSUE TITLE
`Nd4j.hstack()` performance seems to be sub-par

### ISSUE THREAD

**Issue by firasdib** [deeplearning4j/nd4j#1992]
#### Issue Description

I've profiled my application since it seems to run slow, and `hstack` seems to be consistently taking 
up around 25-30% of total time.

Please see the screenshot attached. In comparison you can see `vstack` which seems to perform much better.

<img width="1207" alt="screen shot 2017-07-29 at 16 01 07" src="https://user-images.githubusercontent.com/1335165/28745363-397148ba-7477-11e7-8edc-9996acd1fd20.png">

The code that does `hstack` looks something like this:

```java
final List<INDArray> wordEmbeddings = new ArrayList<>();

for (int i = 0; i < iterations; i++) {
    final List<INDArray> nGramEmbedding = new ArrayList<>();

    for (int j = 0; j < nGramSize; j++) {
        final INDArray wordEmbedding = Word2Vec.getWordVector(...);

        nGramEmbedding.add(wordEmbedding);
    }

    wordEmbeddings.add(Nd4j.hstack(nGramEmbedding));
}

return Nd4j.vstack(wordEmbeddings);
```

Btw, if there is a better way to do this I'd very much appreciate it a heads up!

#### Version Information

* Deeplearning4j version 0.8.1
* platform information OSX

**Comment by raver119** [comment]
Fixed. Now ** are reused.
