### ISSUE TITLE
Compute the offset when getting a view with a newAxis

### ISSUE THREAD

**Issue by audreyloeffel** [deeplearning4j/nd4j#2006]
When getting a view, the resolution of the indexes (in ShapeOffsetResoution) usually returns an offset. But when the indexes array contains a newAxis, no offset is returned. That's because it doesn't match any special cases that could be short-circuited and the computation (which begins here https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/ShapeOffsetResolution.java#L332) doesn't compute it. 

In my sparse representation of a view of a ndarray I'm using the dense resolution to get the shape and the offset to compute the sparse offsets which define the "bounds" of each dimension of a COO sparse matrix. It would be great if I could also get an offset when using a newaxis.

For example if  I have a array with shape 4x2x3 and I take a subarray with get(newAxis, all(), point(1)) I get :
* strides [0, 6, 1]
* shape [1, 4, 3]
* offset 0

The first element that belongs to this view is at the position 3 in the databuffer. How can I compute offset = 3 ?

Additionally, in ShapeOffsetResoution, a comment mentions a special case with all() and newaxis() but the if-condition contains ` newAxis < 1` and that part of code is never reached. https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/ShapeOffsetResolution.java#L258
Shouldn't be ` newAxis > 0` ?

**Comment by huitseeker** [comment]
Even after these fixes and #2013, I still have:

```
Results :

Failed tests: 
  IndexingTestsC.testAllWithNewAxis:42 expected:<[[[4.00,  5.00,  6.00],  
  [10.00,  11.00,  12.00],  
  [16.00,  17.00,  18.00],  
  [22.00,  23.00,  24.00]]]> but was:<[[[4.00,  5.00,  6.00],  
  [7.00,  8.00,  9.00],  
  [10.00,  11.00,  12.00],  
  [13.00,  14.00,  15.00]]]>

Tests run: 35, Failures: 1, Errors: 0, Skipped: 0

```

When running:
` mvn clean test -DfailIfNoTests=false -Dtest=IndexingTestsC -pl '!:nd4j-cuda-8.0'`

**Comment by agibsonccc** [comment]
Yeah I'm messing with the tests now, there are a few different ones at play here. Looking closer at this today.

**Comment by huitseeker** [comment]
After the merge of #2105 I see 
```
Failed tests: 
  IndexingTestsC.testAllWithNewAxisAndInterval:74 expected:<[[7.00,  8.00,  9.00]]> but was:<[[7.00,  13.00,  19.00]]>
  IndexingTestsC.testAllWithNewAxis:99 expected:<[[[4.00,  5.00,  6.00],  
  [10.00,  11.00,  12.00],  
  [16.00,  17.00,  18.00],  
  [22.00,  23.00,  24.00]]]> but was:<[[[5.00,  6.00,  7.00],  
  [8.00,  9.00,  10.00],  
  [11.00,  12.00,  13.00],  
  [14.00,  15.00,  16.00]]]>

```

**Comment by agibsonccc** [comment]
@huitseeker https://github.com/deeplearning4j/nd4j/pull/2018 mind sanity checking?

**Comment by huitseeker** [comment]
```

Results :

Failed tests: 
  ShapeTests.testNewAxis:152 expected:<[[1.00,  3.00]]> but was:<[1.00,  3.00]>

Tests run: 1210, Failures: 1, Errors: 0, Skipped: 30

[ERROR] There are test failures.
```

Full log : https://gist.github.com/5805d59612c8f71227040bf50690f529

**Comment by agibsonccc** [comment]
k that one had the wrong assertion: https://github.com/deeplearning4j/nd4j/pull/2019
