### ISSUE TITLE
Incorrect 3D subarrays when using only interval indexing

### ISSUE THREAD

**Issue by Ewande** [deeplearning4j/nd4j#2010]
Consider a simple 3D array:
```
INDArray arr = Nd4j.arange(8).reshape(2, 2, 2);
[[[0.00,  1.00],  
  [2.00,  3.00]],  

 [[4.00,  5.00],  
  [6.00,  7.00]]]
```
Now, if I want a view of the first part of the array, I can use:
`arr.get(interval(0, 1), all(), all())`
or
`arr.get(interval(0, 1), interval(0, 2), interval(0, 2))`
Both cases give a correct result:
```
[[[0.00,  1.00],  
  [2.00,  3.00]]]
```
However, if I want a view of the second part of the array. 
`arr.get(interval(1, 2), all(), all())`
gives a correct result:
```
[[[4.00,  5.00],  
  [6.00,  7.00]]]
```
whereas
`arr.get(interval(1, 2), interval(0, 2), interval(0, 2))`
gives:
```
[[[1.00,  2.00],  
  [3.00,  4.00]]]
```

Seems like the problem lies in https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/ShapeOffsetResolution.java#L600, where the offset is set to 1 instead of 4.

Of course, this is not a big problem in case of slicing only a single axis (as in my example) because one can use either arr.get(interval(1, 2)) or all() if this is not the main axis.  However, if one builds a general interface for getting interval-selected subarrays, looks like there is no alternative to achieve correct subarrays.

Checked using 0.9.0.

**Comment by Ewande** [comment]
It seems the problem still exists (checked on current master). Is there any reason for dividing the offset by the number of interval indices in https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/indexing/ShapeOffsetResolution.java#L586? I removed division and it passed all tests.

**Comment by agibsonccc** [comment]
@Ewande I'm having a hard time believing that. These tests all pass for me.
https://github.com/deeplearning4j/nd4j/blob/447c23789378692786a5f8f5e2614da1db549c50/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/api/indexing/IndexingTestsC.java#L57

Could you give me a specific case here?

**Comment by Ewande** [comment]
Try this one, please: https://github.com/Ewande/nd4j/blob/interval_indexing/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/api/indexing/IndexingTestsC.java#L67

**Comment by agibsonccc** [comment]
@Ewande https://github.com/deeplearning4j/nd4j/pull/2023 didn't break any of my test suite here so not complaining. I'm pretty sure this was an edge case at one point..not worried about it. Thanks again!
