### ISSUE TITLE
Having installed gcc 4.9 in centos,but show you need at least gcc 4.9

### ISSUE THREAD

**Issue by wangfeng-skymind** [deeplearning4j/nd4j#2037]
[root@d8 libnd4j]# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/4.9.4/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 4.9.4 (GCC) 

but show error==============================
- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
NOT CLION
CPU BLAS
CMake Error at blas/CMakeLists.txt:137 (message):
  You need at least GCC 4.9
-- Configuring incomplete, errors occurred

**Comment by saudet** [comment]
Looks like your "/usr/bin/c++" isn't pointing to that version of GCC though.

**Comment by wangfeng-skymind** [comment]
please check your server,as follow

1. rpm -qa|grep gcc, maybe show below content
[root@d10 libnd4j]# rpm -qa|grep gcc
gcc-gfortran-4.8.5-11.el7.x86_64
gcc-4.8.5-11.el7.x86_64
libgcc-4.8.5-11.el7.x86_64
gcc-c++-4.8.5-11.el7.x86_64

2. rpm -e xxx(gcc*),
3.and then it's ok

**Comment by agibsonccc** [comment]
Something @wangfeng-skymind isn't mentioning: He compiled gcc from source..so a lot of the rpm output isn't relevant.

**Comment by wangfeng-skymind** [comment]
ok,yeah,I'll improve the installation later;
the problem had been solved.
