### ISSUE TITLE
Dependencies page needs to be updated

### ISSUE THREAD

**Issue by brycepratt** [deeplearning4j/nd4j#2047]
#### Issue Description

Currently the page containing instructions for how to set up dependencies for ND4J is about a year outdated. The webpage can be found at http://nd4j.org/dependencies

Currently it suggests that the most current version is 0.4-rc3.10, so that should probably be updated.

**Comment by tomthetrainer** [comment]
@huitseeker Can you look into this and do a quick upgrade of the versions?
