### ISSUE TITLE
LogSumExp operation (new feature)

### ISSUE THREAD

**Issue by jsteggink** [deeplearning4j/nd4j#2049]
Hi,

I'd like to have the LogSumExp operation like this:
https://en.wikipedia.org/wiki/LogSumExp
https://hips.seas.harvard.edu/blog/2013/01/09/computing-log-sum-exp/

I tried adding it myself, but I'm a bit stuck on how to implement it for all the different backends.

Cheers,
Jeroen

**Comment by jsteggink** [comment]
Hi raver119,
I noticed you added the following: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/accum/LogExpSum.java

I'm not exactly sure this implementation is correct or I'm missing something. 

Firstly, you are referring to the wikipedia article in the class description, so I guess the class named LogExpSum should actually be LogSumExp right? :)
Secondly, why the pow2? Thirdly, the max is not set and used. And lastly, the opNum returns 19, which is already used by HardTanh.

Maybe you could clarify it for me?

Cheers,
Jeroen

**Comment by raver119** [comment]
0) ugh, ye, just renamed. Thanks :)
1) op is implemented in c++, java class is just a wrapper.
2) pow2 is irrelevant, due to ^^^
3) max is calculated in c++ ^^^
4) opNums tied to different op groups can overlap. Thats totally fine.

**Comment by raver119** [comment]
p.s. Here's test: https://github.com/deeplearning4j/nd4j/blob/2e8058c65f24cfa584dd2721be28173bae00891d/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L5284

**Comment by jsteggink** [comment]
Thanks for your explanation!

One small thing though, the name() method still returns "logexpsum".
