### ISSUE TITLE
INDArray shape() return int[] instead of int cause Nd4j.zeros() error

### ISSUE THREAD

**Issue by olafhel** [deeplearning4j/nd4j#205]
https://gist.github.com/olafhel/566ab93b2ecbd65c80e4

**Comment by olafhel** [comment]
caused by f139952229efad88a1e0e3f5ba6f8d2fc0099ff6

**Comment by olafhel** [comment]
Actually the problem occur when building dl4j-spark-ml.

**Comment by EronWright** [comment]
Fixed  in deeplearning4j/deeplearning4j@0850a4fced80d0b27d655d2f13d17f02c74a4d6f
