### ISSUE TITLE
New distributions

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#2062]
We should add 2 new distributions for features parity with keras/tf/whatever:
- truncated normal distribution
- log normal distribution

**Comment by raver119** [comment]
Merged few days ago.

**Comment by maxpumperla** [comment]
cool, @raver119 can you please point me to where I can find these, might want to pick them up in dl4j core and model import soon.

**Comment by raver119** [comment]
Check out these 2 tests: https://github.com/deeplearning4j/nd4j/blob/3ee140f23784b06d2b128f4a5363839963c9b330/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/rng/RandomTests.java#L1253-L1306

They use both new distribution ops.

**Comment by raver119** [comment]
If you need something else to use them - please let me know.
