### ISSUE TITLE
Nd4j-x86 fail to build on ubuntu 14.04

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4j#207]
https://gist.github.com/rahulpalamuttam/285f97cdbf509ec7c98c

The above gist shows that nd4j-x86 fails to build. 
It throws an error saying 
as : unrecognized option --64

Not that this error appears even after installing build-essentials

**Comment by rahulpalamuttam** [comment]
Has there been any update on this issue?

**Comment by agibsonccc** [comment]
Not as of yet. Some google searching:
http://askubuntu.com/questions/502524/i-am-not-able-to-compile-a-simple-program-using-gcc
We've had other users build it just fine. Maybe check the version of gcc?

**Comment by rahulpalamuttam** [comment]
This issue was an error on my part. 
I had a 32 bit mips assembler on my PATH from a previous project.
The issue can be closed.
