### ISSUE TITLE
deeplearning4j-master.zip fails to install

### ISSUE THREAD

**Issue by kirtu** [deeplearning4j/nd4j#2071]
Downloaded deeplearning4j-master.zip from git on 2017-08-27
unzipped to directory ~/dl4j/dl4j-examples/deeplearning4j-master
mvn clean install fails with Mojo Execution Exception
This appears to be a Maven specific error but solutions are unclear

So the initial package, DeepLearning4J, fails to build an the rest are skipped
I have not found anything relevant for the outstanding Warning:
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireActiveProfile failed with message:
Profile "test-nd4j-native" is not activated.
Profile "test-nd4j-cuda-8.0" is not activated.

-- System
Ubuntu 17.04
Java 8.0
Cuda 8.0
Maven 3.3.9
CUDA_ROOT=/usr/local/cuda
JAVAFX_HOME=/opt/java/jdk1.8.0_141/jre/lib/ext/jfxrt.jar
JAVA_HOME=/usr/lib/jvm/java-8-oracle

-- Install log 
 mvn clean install[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] DeepLearning4j
[INFO] deeplearning4j-nearestneighbors-parent
[INFO] nearestneighbor-core
[INFO] deeplearning4j-nn
[INFO] deeplearning4j-modelimport
[INFO] deeplearning4j-ui-parent
[INFO] deeplearning4j-ui-components
[INFO] deeplearning4j-core
[INFO] deeplearning4j-ui-model
[INFO] deeplearning4j-play
[INFO] DeepLearning4j-scaleout-parent
[INFO] org.deeplearning4j.spark
[INFO] dl4j-spark
[INFO] Dl4j Streaming
[INFO] DeepLearning4j-AWS
[INFO] deeplearning4j-nlp-parent
[INFO] deeplearning4j-nlp
[INFO] dl4j-spark-nlp
[INFO] deeplearning4j-parallel-wrapper
[INFO] dl4j-spark-parameterserver
[INFO] dl4j-spark-nlp-java8
[INFO] dl4j-spark-ml
[INFO] deeplearning4j-scaleout-parallelwrapper-parameter-server
[INFO] deeplearning4j-ui-resources
[INFO] deeplearning4j-ui
[INFO] deeplearning4j-ui-remote-iterationlisteners
[INFO] deeplearning4j-graph
[INFO] deeplearning4j-cuda
[INFO] deeplearning4j-nlp-uima
[INFO] deeplearning4j-nlp-korean
[INFO] deeplearning4j-nlp-japanese
[INFO] deeplearning4j-nlp-chinese
[INFO] deeplearning4j-zoo
[INFO] deeplearning4j-nearestneighbors-model
[INFO] deeplearning4j-nearestneighbors-client
[INFO] deeplearning4j-nearestneighbor-server_2.11
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building DeepLearning4j 0.9.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ deeplearning4j-parent ---
[INFO] Deleting /home/kirtu/dl4j/dl4j-examples/deeplearning4j-master/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ deeplearning4j-parent ---
[INFO] 
[INFO] --- lint-maven-plugin:0.0.11:check (pom-lint) @ deeplearning4j-parent ---
[INFO] Writing summary report
[INFO] [LINT] Completed with no violations
[INFO] Writing xml report
[INFO] 
[INFO] --- git-commit-id-plugin:2.2.2:revision (default) @ deeplearning4j-parent ---
[INFO] 
[INFO] --- build-helper-maven-plugin:3.0.0:add-resource (add-resource) @ deeplearning4j-parent ---
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:add-source (scala-compile-first) @ deeplearning4j-parent ---
[INFO] Add Source directory: /home/kirtu/dl4j/dl4j-examples/deeplearning4j-master/src/main/scala
[INFO] Add Test Source directory: /home/kirtu/dl4j/dl4j-examples/deeplearning4j-master/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:compile (scala-compile-first) @ deeplearning4j-parent ---
[INFO] No sources to compile
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:add-source (scala-test-compile) @ deeplearning4j-parent ---
[INFO] 
[INFO] --- scala-maven-plugin:3.2.2:testCompile (scala-test-compile) @ deeplearning4j-parent ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-choice-of-nd4j-test-backend) @ deeplearning4j-parent ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireActiveProfile failed with message:
Profile "test-nd4j-native" is not activated.
Profile "test-nd4j-cuda-8.0" is not activated.

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DeepLearning4j ..................................... FAILURE [ 11.619 s]
[INFO] deeplearning4j-nearestneighbors-parent ............. SKIPPED
[INFO] nearestneighbor-core ............................... SKIPPED
[INFO] deeplearning4j-nn .................................. SKIPPED
[INFO] deeplearning4j-modelimport ......................... SKIPPED
[INFO] deeplearning4j-ui-parent ........................... SKIPPED
[INFO] deeplearning4j-ui-components ....................... SKIPPED
[INFO] deeplearning4j-core ................................ SKIPPED
[INFO] deeplearning4j-ui-model ............................ SKIPPED
[INFO] deeplearning4j-play ................................ SKIPPED
[INFO] DeepLearning4j-scaleout-parent ..................... SKIPPED
[INFO] org.deeplearning4j.spark ........................... SKIPPED
[INFO] dl4j-spark ......................................... SKIPPED
[INFO] Dl4j Streaming ..................................... SKIPPED
[INFO] DeepLearning4j-AWS ................................. SKIPPED
[INFO] deeplearning4j-nlp-parent .......................... SKIPPED
[INFO] deeplearning4j-nlp ................................. SKIPPED
[INFO] dl4j-spark-nlp ..................................... SKIPPED
[INFO] deeplearning4j-parallel-wrapper .................... SKIPPED
[INFO] dl4j-spark-parameterserver ......................... SKIPPED
[INFO] dl4j-spark-nlp-java8 ............................... SKIPPED
[INFO] dl4j-spark-ml ...................................... SKIPPED
[INFO] deeplearning4j-scaleout-parallelwrapper-parameter-server SKIPPED
[INFO] deeplearning4j-ui-resources ........................ SKIPPED
[INFO] deeplearning4j-ui .................................. SKIPPED
[INFO] deeplearning4j-ui-remote-iterationlisteners ........ SKIPPED
[INFO] deeplearning4j-graph ............................... SKIPPED
[INFO] deeplearning4j-cuda ................................ SKIPPED
[INFO] deeplearning4j-nlp-uima ............................ SKIPPED
[INFO] deeplearning4j-nlp-korean .......................... SKIPPED
[INFO] deeplearning4j-nlp-japanese ........................ SKIPPED
[INFO] deeplearning4j-nlp-chinese ......................... SKIPPED
[INFO] deeplearning4j-zoo ................................. SKIPPED
[INFO] deeplearning4j-nearestneighbors-model .............. SKIPPED
[INFO] deeplearning4j-nearestneighbors-client ............. SKIPPED
[INFO] deeplearning4j-nearestneighbor-server_2.11 ......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.947 s
[INFO] Finished at: 2017-08-27T16:17:27-04:00
[INFO] Final Memory: 23M/174M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-choice-of-nd4j-test-backend) on project deeplearning4j-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by kirtu** [comment]
changed JAVA_HOME to JAVA_HOME=/opt/java/jdk1.8.0_141

No change

**Comment by kirtu** [comment]
However I don't have a GPU ---
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.66                 Driver Version: 384.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  NVS 4200M           Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   52C    P8    N/A /  N/A |    110MiB /   454MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0                  Not Supported                                         |
+-----------------------------------------------------------------------------+

**Comment by raver119** [comment]
1) Please read maven error message, it's pretty much self-containing:
```
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-choice-of-nd4j-test-backend) @ deeplearning4j-parent ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireActiveProfile failed with message:
Profile "test-nd4j-native" is not activated.
Profile "test-nd4j-cuda-8.0" is not activated.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4.1:enforce (enforce-choice-of-nd4j-test-backend) on project deeplearning4j-parent: Some Enforcer rules have failed. Look above for specific messages explaining why the rule failed. -> [Help 1]
```

2) Please, consider reading dl4j local build instructions if for some reason you're going to build from sources instead of using maven dependencies.

**Comment by raver119** [comment]
https://deeplearning4j.org/buildinglocally

**Comment by kirtu** [comment]
I read the maven message and it is completely unclear to people who don't know maven.

I am following the quickstart instructions . 
$ git clone https://github.com/deeplearning4j/dl4j-examples.git
 $ cd dl4j-examples/
 $ mvn clean install

 Out of the box the software doesn't work.\

**Comment by raver119** [comment]
Output log you've posted was from `deeplearning4j` repo. 
Post your output from dl4j-examples `mvn clean install`

**Comment by AlexDBlack** [comment]
@kirtu before you go through debugging all this - is there a reason you are building DL4J from source?
99.9% of users don't need to, and shouldn't build from source like you are trying to do.
But as @raver119 said, you are trying to install DL4J, *not the examples* according to what you posted above.

For DL4J, you should use 0.9.1 on maven central (as per the quick-snart guide), or if you *really* need the development version (you probably don't) https://deeplearning4j.org/snapshots
