### ISSUE TITLE
More weight inits

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/nd4j#2074]
The plebs demands more inits!

Though this might not be high priority, supporting more weight initialisers should be relatively simple to do. I'll refer to https://keras.io/initializers/ for naming conventions. This ticket collects weight init enhancements, for more complicated inits we could split it up.

Low hanging:
- [ ] Ones
- [ ] Constant
- [ ] Identity

a bit less trivial:
- [ ] Normal
- [ ] Orthogonal
- [ ] Lecun uniform
- [ ] Variance scaling (seems to be the new default initialiser in keras).

**Comment by AlexDBlack** [comment]
Duplicate - https://github.com/deeplearning4j/deeplearning4j/issues/3916
Any need to have a separate issue for this?

Orthogonal and variance scaling *might* require ND4J changes, but we should open issues specifically for those IMO...

**Comment by raver119** [comment]
Everything implemented now.
