### ISSUE TITLE
Conv2DTranspose / Deconvolution2D ops support

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/nd4j#2077]
#### Issue Description

In essence deconvolutions swap forward and backward pass in a convolution. If we had both passes properly available in (lib)nd4j, we could 

a) simplify the Convolution layer in dl4j, which currently defines both ff and backprop in this very layer
b) Deconv layer would be a simple follow-up impl, by just swapping passes.

**Comment by maxpumperla** [comment]
see https://arxiv.org/abs/1603.07285v1 for a quick overview and http://www.matthewzeiler.com/wp-content/uploads/2017/07/cvpr2010.pdf for the original paper.

keras reference: https://keras.io/layers/convolutional/#conv2dtranspose

**Comment by agibsonccc** [comment]
We can close this now I believe?

**Comment by maxpumperla** [comment]
yes!
