### ISSUE TITLE
Support separable convolutions (2d)

### ISSUE THREAD

**Issue by maxpumperla** [deeplearning4j/nd4j#2078]
#### Issue Description

Separable convs chain two special 2d convolutions, one depth-wise, one point-wise. Would be awesome to have this as an op in our backend, since it's very useful for many CV application we have in mind.

**Comment by maxpumperla** [comment]
Not sure where this appeared first for DL, since this has been around for ages in computer vision... here are a few pointers: 

Starting with slide 26: https://bcb9f395-a-8ac90a7d-s-sites.googlegroups.com/a/vanhoucke.com/vincent/publications/vanhoucke-iclr14.pdf?attachauth=ANoY7cr2M1S6WfWyERbUflUntDcGrDH5G-EKP0uhoE440Y0geCeNwuwHqHDWD-dG_dJv3ShS_OL5gaEZbPvQ0fvs1aQiPVDeAbQ8SHnhdyw3Gis8rfurMQHVcQczYf1Em5iclRCD1jJ4UdnAQ-NrByoKbtUScxugO5jZKoNdvAu_ZXxaigdQ5KTMi1i5EiAzhVAEoErQrea0-pi41mypj1Q0hgX1GRy9FypefF8pVHo3L6J80wJTzSE%3D&attredirects=0

TF impl: https://www.tensorflow.org/api_docs/python/tf/nn/separable_conv2d

related paper: https://arxiv.org/pdf/1610.02357.pdf

keras reference: https://keras.io/layers/convolutional/#separableconv2d

**Comment by agibsonccc** [comment]
We can close this now I believe?
