### ISSUE TITLE
CPU twenty times faster than GPU on Tsne

### ISSUE THREAD

**Issue by deborahduong** [deeplearning4j/nd4j#2079]
#### Issue Description

In the performance with the GPU vs. CPU on Tsne:  the CPU is much much faster.  On the GPU with the UI listener on,  The GPU version does 35 or 40 seconds per handling 500 records, while the CPU version does 5 seconds per handling 500 records.  The GPU version takes about an hour per iteration, while the CPU version takes 3 minutes per iteration.  You can see my GPU and CPU training outputs, with times, at https://gist.github.com/anonymous/80230b3dcbd4a8409acd6238b7573f38.  This should not be, because I am running on a HP Z440 /Intel Xeon E5 1620 v4 processor 3.5 GHz that has 77 GB/s memory bandwidth , with a Nvidia quadro p5000: fp 32 performance 8.9 tflpos, 2560 cores, that has a memory bandwidth 288 GB/s.  So I am looking at software reasons.  From looking at my output, do you have any suggestions?   The GPU stack  differs from the CPU stack (both below) in that it has more Garbage Collectors and different math.
#### Version Information

0.9.1 for all dl4j modules, cuda 8.0, java 1.8, windows 10

**Comment by deborahduong** [comment]
cuda 8.0, java 1.8

**Comment by deborahduong** [comment]
windows 10

**Comment by deborahduong** [comment]
Here are the stacks.  I have to use a screenshot because eclipse wont let me copy it.  sorry.
![trainingtsnecpustacktop](https://user-images.githubusercontent.com/16463098/29889435-c620ca76-8d89-11e7-9cd5-51d1a4435704.PNG)  has the top of the cpu stack.
![trainingtsnecpustackbottom](https://user-images.githubusercontent.com/16463098/29889471-dfbd114c-8d89-11e7-9f19-dc6c2c1ed117.PNG) has the bottom of the cpu stack. 

![trainingtsnegpustacktop](https://user-images.githubusercontent.com/16463098/29889490-f25eb09e-8d89-11e7-9a46-283b15d4aa5b.PNG) has the top of the GPU stack

![trainingtsnegpustackbottom](https://user-images.githubusercontent.com/16463098/29889509-02f09454-8d8a-11e7-9a22-709979e5093b.PNG)  has the bottom of the GPU stack.

**Comment by raver119** [comment]
Closed as duplicate
