### ISSUE TITLE
Unexpected Results from Transforms.pow(INDArray, INDArray)

### ISSUE THREAD

**Issue by jiyer2016** [deeplearning4j/nd4j#2084]
I am running nd4j-native-platform (v 0.9.1 ) on a Windows 7,  64 bit architecture.
I am trying to perform an element-wise power operation between two NDArrays.

Here is my code:

double[] a1 = {1d,2d,3d,4d};
double[] a2 = {2d,2d,2d,2d};
INDArray arr1 = Nd4j.create(a1);
		
INDArray arr2 = Nd4j.create(a2);
		
INDArray arr3 = Transforms.pow(arr1, arr2);		
System.out.println("arr3 is "+arr3);

Here is what I get:
arr3 is [1.00,  0.50,  0.33,  0.25]

I would expect to get the following instead:
arr3 is [1.00,  4.00, 9.00,  16.00]

Am I doing something wrong ? or is this a bug ??

**Comment by hotou** [comment]
I've got the same thing

**Comment by raver119** [comment]
Yes, that's a bug. 
pow isn't announced in pairwise transforms, operation used by this signature is ReverseDivide.

**Comment by jiyer2016** [comment]
Thanks for confirming that this is a bug. Until a fix is available - Is there a workaround available ? I have a need to use an element-wise power operation in my app.

**Comment by raver119** [comment]
I can provide fast fix, but obviously it'll be only available at snapshots. 
Is that suitable for you?

**Comment by jiyer2016** [comment]
Thanks so much - A fix in the snapshot is good - That will get me started on a basic integration. Very much appreciated.

**Comment by raver119** [comment]
Implemented/fixed and merged: https://github.com/deeplearning4j/nd4j/pull/2098
