### ISSUE TITLE
BooleanIndexing.replaceWhere(INDArray, 1,  Conditions.isNan());

### ISSUE THREAD

**Issue by yylonly** [deeplearning4j/nd4j#2088]
My purpose is
1. if the value of array is NaN, replace with 0
2. if the value of array is not NaN, replace with 1

ND4J is the function to do finding and replacing with isNaN() by

> BooleanIndexing.replaceWhere(INDArray,  0,  Conditions.isNan());

But ND4J is not the function of isNotNaN(), when I use 

> BooleanIndexing.replaceWhere(INDArray, 1,  new Not(new IsNaN()));

we will get

> Exception in thread "main" java.lang.UnsupportedOperationException: Only static Conditions are supported

So, how could I do the isNotNaN() operation, thanks!!!

**Comment by eraly** [comment]
You can do Nd4j.clearNans(someArr.divi(someArr)). It's hacky but will work.

Note that not Nan is not so straightforward Double.NaN != Double.NaN returns true.
