### ISSUE TITLE
TF concepts parity

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#2094]
Right now we're missing few graph concepts on Java side, which TF (and probably others) has:

- Conditional ops execution
- Multi-output operations

**Comment by raver119** [comment]
ping @agibsonccc

**Comment by agibsonccc** [comment]
@raver119 Can you include code links to some of these?
What does "multi output operations" mean?
I've still seen those kinds of ops just get decomposed.

Conditional op execution means.. "Only traverse this graph path"?

**Comment by raver119** [comment]
Here's regression graph provided by @maxpumperla 
It contains operation with > 1 output. I've saw others as well, like Switch op mentioned below.

[log_reg.txt](https://github.com/deeplearning4j/nd4j/files/1272141/log_reg.txt)


Yes, by conditional op execution i mean exactly "only traverse this graph path, based on condition X". TF op name "Switch", if i'm understanding this properly.

**Comment by agibsonccc** [comment]
@AlexDBlack do you think we could add these to our comp graph api to compensate? I know @firasdib has a paper that needs multi input/output. It doesn't seem like it would be hard to add?

**Comment by raver119** [comment]
Ye, on C++ side i already have both conditionals and multi-outputs... Only Java side needs some tweaks

**Comment by AlexDBlack** [comment]
We could in principle add multi-input layers and multi-output vertices it to compgraph - I've opened an issue here: https://github.com/deeplearning4j/deeplearning4j/issues/3998

Conceptually it's reasonably easy to do, but would take a bit of time to implement.

**Comment by raver119** [comment]
I was speaking about Graph/IGraph classes and, corresponding SameDiff support for multi-output nodes. And, as @AlexDBlack says CompGraph has slightly different code base.

**Comment by agibsonccc** [comment]
Yeah the use case I'd have here is allowing an easy 1 to 1 mapping when we have a "same diff layer". One of the most common use cases we'll have for this is "use dl4j layers for certain things" and "autodiff layers" as complimentary.

**Comment by raver119** [comment]
I'm more pragmatic here: i need SameDiff to be able to handle TF graph. It wasn't an issue when i was importing graph in C++, but now it's being imported in Java as SameDiff. So it means i need both concepts to move forward :(

**Comment by raver119** [comment]
Another issue: Placeholder variables, which are meant to be variable inputs for graph.

As discussed in gitter, i've used SameDiff.var(varName, null) to "register" SDVariable for future use, and i've got NPE:

```
java.lang.IllegalArgumentException: Array for Placeholder must not be null
at org.nd4j.autodiff.samediff.SameDiff.var(SameDiff.java:657)
```

Where Placeholder in future variable name, derived from TF graph

**Comment by raver119** [comment]
UPD: Placeholder issues are expected to be fixed now.

**Comment by raver119** [comment]
re: multi-output nodes.

There are cases, when operations produce > 1 output arrays as result. So there are cases when vertex should take indexed input. I.e. we have vertexes: 1, 2, 3, 4.

Vertex 1 generates 2 INDArrays. 
Vertex 2 takes output 0 of vertex 1 as its input.
Vertex 3 takes output 1 of vertex 1 as its input.
Vertex 4 takes both outputs of vertex 1 as its input. 

I'm able to express that with c++, but unable with Java: edges right now contain no information about output index.

**Comment by raver119** [comment]
Implemented long ago.
