### ISSUE TITLE
Add dummy/constant RNG "distribution"

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2095]
We have a few RNG distributions:
https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/random/impl

It would be useful for Keras import (see here: https://github.com/deeplearning4j/deeplearning4j/issues/3916#issuecomment-326886461) to add a "distribution" that just returns a constant value.

**Comment by raver119** [comment]
Added.
