### ISSUE TITLE
How to use ND4j in android, please ??

### ISSUE THREAD

**Issue by Yi-Coder** [deeplearning4j/nd4j#2102]
#### Issue Description

Please describe your issue, along with:
 ND4J is probably missing dependencies???

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information: androind-arm64-v8a

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by saudet** [comment]
Please try to follow the instructions here for starters: https://deeplearning4j.org/android
