### ISSUE TITLE
unnecessary for loop

### ISSUE THREAD

**Issue by jcremer** [deeplearning4j/nd4j#2104]
https://github.com/deeplearning4j/nd4j/blob/27fb5a46882c40532e8e45a13f51caae9bdd6238/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java#L760

for loop should be removed as it is already inside `assign(value, offset)` and replace 
`assign(value, i);`
by
`assign(value, 0);`

**Comment by saudet** [comment]
Please send a pull request!
