### ISSUE TITLE
Add scatter ops

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2105]
https://www.tensorflow.org/api_docs/python/tf/scatter_update
there's also a "gather" op, but that's our pullRows.

Eventually, we'll want to implement the full set: add/sub/mul/div etc
https://www.tensorflow.org/api_guides/python/state_ops#Sparse_Variable_Updates

**Comment by raver119** [comment]
Prototype for ops were added, java wrapper too. Performance might (and probably will) be suboptimal for now, but will catch up on later stages as usually.

**Comment by raver119** [comment]
P.s. https://github.com/deeplearning4j/nd4j/pull/2106/files
