### ISSUE TITLE
Add clipping op(s)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2111]
https://www.tensorflow.org/versions/r1.2/api_docs/python/tf/clip_by_value

This is possible with 2 boolean indexing ops, sure - but it might be easier/more efficient to have an explicit clip op...
For now: just the scalar clipping is required (not the array version, but that might be useful one day).

Priority: low.

**Comment by raver119** [comment]
Implemented as CustomOp and merged.
