### ISSUE TITLE
Missing android (arm, x86) presets for MKL

### ISSUE THREAD

**Issue by huitseeker** [deeplearning4j/nd4j#2126]
In an ND4J build:
```

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project nd4j-native: Could not resolve dependencies for project org.nd4j:nd4j-native:jar:0.9.2-SNAPSHOT: Could not find artifact org.bytedeco.javacpp-presets:mkl:jar:android-x86:2017.3-1.3 in local-public (http://master-jenkins.eastus.cloudapp.azure.com:8088/nexus/content/groups/public/) -> [Help 1]
```

(local-public is a proxy that includes central and sonatype-snapshots)
Build: http://master-jenkins.skymind.io:8080/job/dl4j/job/all-multiplatform/2526/console

cc @saudet

**Comment by saudet** [comment]
I'm sorry, I neglected to deploy empty JARs for unsupported platforms. It's done now:
http://repo2.maven.org/maven2/org/bytedeco/javacpp-presets/mkl/2017.3-1.3/
Should fix the same error with linux-ppc64le as well.

**Comment by huitseeker** [comment]
👍 thanks!
