### ISSUE TITLE
Get Dataset

### ISSUE THREAD

**Issue by anas86samara** [deeplearning4j/nd4j#2133]
I have splitted the dataset into traing and testing
   
`DataSet allData = completeDatasetIterator.next();`
`allData.shuffle();`
`SplitTestAndTrain testAndTrain = allData.splitTestAndTrain(0.80);`
`DataSet trainingDataPortion = testAndTrain.getTrain();`
`DataSet testDataPortion = testAndTrain.getTest();`
`// building the model`
`// Evaluate on the test set:`
`Evaluation evaluation = net.evaluate(DATASET_ITERATOR_OBJECT);`
`log.info(String.format(str, i, evaluation.accuracy(), evaluation.f1()))`

how to convert Dataset (org.nd4j.linalg.dataset.api.DataSet) object to DatasetIterator (org.nd4j.linalg.dataset.api.iterator) object so can be be used with evaluate API.

**Comment by agibsonccc** [comment]
Use: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-nn/src/main/java/org/deeplearning4j/datasets/iterator/impl/ListDataSetIterator.java

**Comment by anas86samara** [comment]
Many thanks @agibsonccc 
this is what I'm looking for :)
