### ISSUE TITLE
NativeOpExecutioner.exec returns a NPE

### ISSUE THREAD

**Issue by PedroFFernandes** [deeplearning4j/nd4j#2137]
#### Issue Description
When executing the following code:
```
	private INDArray measureDistance(INDArray feature, INDArray featureMatrix, BaseAccumulation distanceMeasure) {
		int numberOfRows = featureMatrix.rows();
		int numberOfInput = feature.rows();
		INDArray distances = Nd4j.zeros(numberOfRows, numberOfInput);

		for (int inputIndex = 0; inputIndex < numberOfInput; inputIndex++) {
			distanceMeasure.setX(feature.getRow(inputIndex));
			for (int rowIndex = 0; rowIndex < numberOfRows; rowIndex++) {
				distanceMeasure.setFinalResult(0);
				distanceMeasure.setY(featureMatrix.getRow(rowIndex));
				Nd4j.getExecutioner().execAndReturn(new EuclideanDistance());
				distances.put(rowIndex, inputIndex, distanceMeasure.currentResult());
			}
		}
		return distances;
	}
```
The method execAndReturn() return an error:

> Exception in thread "main" java.lang.NullPointerException
> 	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:923)
> 	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(NativeOpExecutioner.java:106)
> 	at org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.execAndReturn(DefaultOpExecutioner.java:228)
> 	at com.kpmg.controller.ai.dl4j.KNearestNeighbor.measureDistance(KNearestNeighbor.java:143)

#### Version Information
DL4J version 0.9.1
ND4J version 0.9.1
Windows 10
No CUDA

Note: Using ND4J version 0.8.0 the error didn't occurred.

**Comment by raver119** [comment]
What exactly you're trying to do? By the look of it - you have 2d matrix, and you want to measure distance of all rows of matrix A, to all rows of matrix B?

If yes - we've already added such native op that works in parallel. To call for that - you can use something like Transforms.allCosineDistances or Transforms.allEuclideanDistances or whatever...

**Comment by raver119** [comment]
`Nd4j.getExecutioner().execAndReturn(new EuclideanDistance());`

This isn't even close to proper use.

**Comment by PedroFFernandes** [comment]
Really sorry about the code snippet. Actually that line of code is:
`Nd4j.getExecutioner().execAndReturn(distanceMeasure);`
I think I copy pasted it somewhere with that change to indicate i was using a Accumulation instance and forgot to change it back before creating this issue.
Either way I'm going to have a look at that Transforms class. Thank you @raver119!

**Comment by PedroFFernandes** [comment]
Bypassed this by using the method suggested by @raver119 .
The final method code is now:

```
	private INDArray measureDistance(INDArray feature, INDArray featureMatrix) {
		int numberOfInput = feature.rows();
		return Transforms.allEuclideanDistances(featureMatrix, feature, numberOfInput);
	}
```

**Comment by raver119** [comment]
no, numberOfInput should be either 0 or 1, target dimension to compare. In your case you want that to be rows.
