### ISSUE TITLE
Support Batched(parallel) Matrix-matrix multiplication using batched_gemm

### ISSUE THREAD

**Issue by Bam4d** [deeplearning4j/nd4j#2139]
#### Issue Description

I've been trying to get a parallel/batch matrix matrix multiply to work using Nd4j through a variety of different methods.

What i am am trying to acheive parallel multiplication of two tensors `Txnxm` `Txm` which will give me a `Tx1xm`. 

Here is an example of how to do this is numpy:
```
import numpy as np

T = 4
m = 2
T_m_m = np.arange(T*m*m).reshape([T,m,m])
T_m = np.arange(T*m).reshape([T,m])

print("\n\nres = %s" % np.matmul(T_m_m, T_m.reshape(T,m,1)))
```

In tensorflow this operation is acheived by tf.batch_matmul

I have no been able to reproduce this behaviour in Nd4j. I am currently having to loop along the first dimension.

##### N.B Low level apis exist for these in cublas and MKL
In cublas:
https://devblogs.nvidia.com/parallelforall/cublas-strided-batched-matrix-multiply/

in MKL: 
https://software.intel.com/en-us/articles/introducing-batch-gemm-operations

#### Version Information

latest version 0.9.1

**Comment by raver119** [comment]
I think we have batched_gemm implemented now in C++.
