### ISSUE TITLE
Use gpu or cpu by Environment Variables 

### ISSUE THREAD

**Issue by allmelgr** [deeplearning4j/nd4j#2145]
#### Issue Description

- I both import nd4j-native and nd4j-cuda-8.0 in maven
- I want use gpu or cpu by  set Environment Variables
- success on eclipse but failed after mvn clean package jar

#### Version Information

* Deeplearning4j version:0.7.2
* platform information:Ubuntu 16.04
* CUDA version:8.0
* NVIDIA driver version:384.69

**Comment by saudet** [comment]
Which environment variable did you set and to what value?

**Comment by agibsonccc** [comment]
Of note here: Could you try the latest release and ensure this still occurs?

**Comment by allmelgr** [comment]
@saudet 
export BACKEND_PRIORITY_GPU=100
export BACKEND_PRIORITY_CPU=-1

**Comment by allmelgr** [comment]
I print the Environment Variables,but jar still use [CpuBackend] not [JCublasBackend]

**Comment by raver119** [comment]
What happens in latest versions? 0.7.2 is a bit outdated...

**Comment by allmelgr** [comment]
the same thing happened in 0.9.1

**Comment by allmelgr** [comment]
@raver119 In eclipse (IDE) it can choose GPU or CPU to run by set  Environment Variables(BACKEND_PRIORITY_GPU and BACKEND_PRIORITY_CPU) , but after I build a jar package,it just run by CPU

**Comment by raver119** [comment]
Show your pom.xml please that you’re using for uber jar.

**Comment by allmelgr** [comment]
<dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native</artifactId>
            <version>0.9.1</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-cuda-8.0</artifactId>
            <version>0.9.1</version>
        </dependency>

**Comment by allmelgr** [comment]
Thank you!
In pom.xml , need reference.conf
    <transformers>
        <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
            <resource>reference.conf</resource>
        </transformer>
        <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
            <mainClass>
                org.deeplearning4j.examples.multigpu.MultiGpuLenetMnistExample
            </mainClass>
        </transformer>
    </transformers>
