### ISSUE TITLE
ScatterUpdater - race condition with repeated indices?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2153]
See code below - looks to be a race condition related to repeated indices for the update. Result is ok *most* of the time, but the more repeated indices, the more likely it is to fail. I've had it fail at iterations 3, 727, 624, 1858, etc. With 4 of 5 being index 0, fails at attempts 10, 21, 56, 3, etc.

```
    @Test
    public void testScatterUpdaterConsistency(){
        INDArray source = Nd4j.rand(5,5);

        int[] idxs = new int[]{0,1,2,3,0};

        INDArray exp = Nd4j.create(10,5);
        ScatterUpdate op = new ScatterUpdate(exp, source, idxs, new int[]{1}, ScatterUpdate.UpdateOp.ADD);
        Nd4j.getExecutioner().exec(op);

        for( int i=0; i<10000; i++ ){
            INDArray destination = Nd4j.create(10,5);

            op = new ScatterUpdate(destination, source, idxs, new int[]{1}, ScatterUpdate.UpdateOp.ADD);
            Nd4j.getExecutioner().exec(op);

//            System.out.println(i);
            assertEquals(String.valueOf(i), exp, destination);
        }
    }
```

As discussed in gitter: if possible (and performance hit isn't too bad) a check for uniqueness on indices may allow us to retain parallelism when possible, and fall back to single thread if not...

**Comment by raver119** [comment]
Yes, race condition is definitely possible there since openmp is used.
The only workaround - to disable openmp.

**Comment by raver119** [comment]
OpenMP pragma was removed there.
