### ISSUE TITLE
Workspace UUIDs can block excessively on network interfaces

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2154]
A very strange one here... looks like workspaces can stall on getting a UUIDs (due to network interfaces, it seems). This is temporary, but a test that should be taking < 2 seconds can stall for >60 seconds. (Some runtimes in seconds for the one test, shows below: 28, 13, 15, 10, 3, 73, 77 sec)
Why this is occurring now: My internet isn't working temporarily, so I'm running via a USB tethered phone for internet access with no LAN plugged in...

Idea for possible solution: Don't use Java UUIDs, replace with an atomic long (counts sequentially up from 0) instead?

![image](https://user-images.githubusercontent.com/2360237/30842479-df7f61c0-a2c5-11e7-9cbd-ed5f95e234f9.png)

Manually pausing in debugger, while test is frozen:
![image](https://user-images.githubusercontent.com/2360237/30842368-29556f98-a2c5-11e7-8f72-840416fbb08a.png)

**Comment by raver119** [comment]
O_o

I'll fix in my current branch, and merge later

**Comment by AlexDBlack** [comment]
Thanks, it's definitely an odd one, but we might as well fix it in case someone else runs into it...

**Comment by raver119** [comment]
Not a big deal, literally anything could be used as ID, including long counter.

**Comment by AlexDBlack** [comment]
Fixed a long time ago.
