### ISSUE TITLE
Cut redundant ops

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#2158]
#### Issue Description
In samediff, it's really hard to maintain 2 sets of ops. I'm proposing moving these 2 things in to the same package.
They started off as fairly different things but ended up converging on something that looks like the nd4j api anyways.

I'm proposing to extend ops to have DifferentialFunction as part of the api.
This way we can get rid of the weird instantiation behavior we are seeing when trying to ensure
op names are the same for the op factories and the graph api.

This would also mean collapsing samediff in to the nd4j-api module.
Personally, this seems like the most straightforward thing to do.

@raver119 
Please describe your issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Well, i think it will make perfect sense if all ops will be available in nd4j, and just used in SD. After all SD isn't a replacement for ND4j numpy-style use.

**Comment by agibsonccc** [comment]
That's the idea. I'm going to make existing nd4j ops support symbolic compute. It will basically be "same object 2 modes"

**Comment by agibsonccc** [comment]
This was done in a recent PR.
