### ISSUE TITLE
std is incorrectly calculated  on a column

### ISSUE THREAD

**Issue by cpuheater** [deeplearning4j/nd4j#2159]
following code returns 706 instead of 0
INDArray columnStd = Nd4j.create(new double[][] {{1000d, 1}, {1000d,2}}).getColumn(0).std(0);

but when std is calculated for the whole array it's correct  [0.00, 0.71]
INDArray columnStd = Nd4j.create(new double[][] {{1000d, 1}, {1000d,2}}).std(0);

there is no any test which would cover this scenario

**Comment by raver119** [comment]
Issue confirmed, and fixed in my branch. Will be merged a bit later though.
