### ISSUE TITLE
Excess GC in LimitedContextPool (I think)

### ISSUE THREAD

**Issue by jamesecahill** [deeplearning4j/nd4j#2160]
#### Issue Description

There's a ton of full GC activity using the CUDA backend. My use case creates lots of small matrices and vectors from multiple threads, and it seems to be performing poorly due to GC overhead. I think I've narrowed it down to https://github.com/deeplearning4j/nd4j/blob/8cfba0f671399c56f4e29d635b444da9b409be64/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/jita/allocator/context/impl/LimitedContextPool.java#L138. Should this be wrapped in a:

```
if (System.currentTimeMillis() > Nd4j.getMemoryManager().getLastGcTime() + Nd4j.getMemoryManager().getAutoGcWindow()) {
...
}
```
Most other non-error-state `invokeGc()` calls are wrapped in this condition. @raver119 what do you think? 

Some more background: We're using Nd4j inside of elasticsearch to do document-level dot products for word similarity, so there are lots of threads operating and allocating simultaneously. **Note:** GC is not an issue with the CPU backend.  

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 0.9.1
* platform information (OS, etc): ubuntu 16.04
* CUDA version, if used: 8.0
* NVIDIA driver version, if in use: 375

#### Contributing

Please let me know if you'd like a PR for it if this is an OK change to make.

**Comment by raver119** [comment]
I'd say: use workspaces.

**Comment by raver119** [comment]
https://deeplearning4j.org/workspaces

**Comment by raver119** [comment]
Also: are your threads relatively short-living, or long-living?

**Comment by jamesecahill** [comment]
Thanks. I'll give workspaces a shot.

RE: Thread life, I'll have to dig into the elasticsearch threading model to see how it's allocating them during scoring. 

Should this `invokeGc()` be wrapped though?

**Comment by raver119** [comment]
Yes, it can be wrapped easily, but:
1) If threads are short-living (i.e. no pool used) - it might help actually.
2) If threads are long-living (i.e. served via some pool) - this invoke method shouldn't be called once all threads in a pool got their contexts assigned.

**Comment by jamesecahill** [comment]
I just checked into how ES allocates the scoring threads, and they're long lived, from a pool. I guess this call isn't what's causing the GC overhead. I'll give workspaces a shot and see how that performs. Thanks!

**Comment by raver119** [comment]
Yes, in this case it’s just background go calls used to release memory. Use
workspaces, and you’ll be able to disable it.

пт, 29 сент. 2017 г. в 23:21, James Cahill <notifications@github.com>:

**Comment by jamesecahill** [comment]
Using workspaces has significantly reduced the GC overhead. Thanks @raver119!
