### ISSUE TITLE
NewAxis failing tests in org.nd4j.linalg.api.indexing.IndexingTestsC

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/nd4j#2162]
testAllWithNewAxisAndInterval
testAllWithNewAxisInMiddle
testAllWithNewAxis

fail.

The intent is to drop a dimension and add back however the resulting arrays all end up with one extra dimension

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/2168
