### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no opencv_imgproc320 in java.library.path

### ISSUE THREAD

**Issue by neerajkunturkar** [deeplearning4j/nd4j#2169]
I am using javacv 1.2 , javacpp 1.2 and opencv 310 and opencv-3.2.0-1.3 jars.
I am getting following issue while I train model using org.bytedeco.javacpp.opencv_face.createFisherFaceRecognizer().trainModel(String trainingDirectory)

java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
	java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	java.lang.Runtime.loadLibrary0(Runtime.java:849)
	java.lang.System.loadLibrary(System.java:1088)
	org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
	org.bytedeco.javacpp.Loader.load(Loader.java:492)
	org.bytedeco.javacpp.Loader.load(Loader.java:409)
	org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
	java.lang.Class.forName0(Native Method)
	java.lang.Class.forName(Class.java:274)
	org.bytedeco.javacpp.Loader.load(Loader.java:464)
	org.bytedeco.javacpp.Loader.load(Loader.java:409)
	org.bytedeco.javacpp.opencv_core$MatVector.<clinit>(opencv_core.java:475)
	com.policy.tt.trainModel(tt.java:497)
	com.policy.tt.doPost(tt.java:88)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

java.lang.UnsatisfiedLinkError: no opencv_imgproc320 in java.library.path
	java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
	java.lang.Runtime.loadLibrary0(Runtime.java:849)
	java.lang.System.loadLibrary(System.java:1088)
	org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:654)
	org.bytedeco.javacpp.Loader.load(Loader.java:483)
	org.bytedeco.javacpp.Loader.load(Loader.java:409)
	org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
	java.lang.Class.forName0(Native Method)
	java.lang.Class.forName(Class.java:274)
	org.bytedeco.javacpp.Loader.load(Loader.java:464)
	org.bytedeco.javacpp.Loader.load(Loader.java:409)
	org.bytedeco.javacpp.opencv_core$MatVector.<clinit>(opencv_core.java:475)
	com.policy.tt.trainModel(tt.java:497)
	com.policy.tt.doPost(tt.java:88)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

Can you please help.

**Comment by saudet** [comment]
Please try again with the latest version of JavaCPP and JavaCV.

**Comment by neerajkunturkar** [comment]
I used latest version of JavaCPP (1.3.3) and JavaCV (1.3.3). I am facing same issue. Is there anything I am missing.

**Comment by saudet** [comment]
Since you're using Tomcat, you'll need to make sure to load these classes with the shared classloader:
https://wiki.apache.org/tomcat/HowTo#I.27m_encountering_classloader_problems_when_using_JNI_under_Tomcat

**Comment by neerajkunturkar** [comment]
I tried that. Getting following error.
java.lang.NoClassDefFoundError: Could not initialize class org.bytedeco.javacpp.opencv_core$MatVector
	com.policy.tt.trainModel(tt.java:497)
	com.policy.tt.doPost(tt.java:88)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by saudet** [comment]
Check the Cause of that exception. It'll tell you what's missing.
