### ISSUE TITLE
org.nd4j.linalg.indexing.conditions.NotEqualsCondition  behaves like EqualsCondition   

### ISSUE THREAD

**Issue by cpuheater** [deeplearning4j/nd4j#2170]
apply method from NotEqualsCondition is the same as in EqualsCondition

**Comment by raver119** [comment]
Got some reproducible code?

**Comment by cpuheater** [comment]
scala> val  vector = Nd4j.create(Array(1,2,3d))
vector: org.nd4j.linalg.api.ndarray.INDArray = [1.00, 2.00, 3.00]

scala> BooleanIndexing.applyWhere(vector, Conditions.notEquals(1), new Value(100))

scala> vector
res3: org.nd4j.linalg.api.ndarray.INDArray = [100.00, 2.00, 3.00]

**Comment by raver119** [comment]
Can you please try Number instead of Value? You're using legacy signature right now, not related to native code.

**Comment by raver119** [comment]
Java side fixed, anyway.

Thanks for highlighting this one.
