### ISSUE TITLE
NdArrayJSONWriter.write: Strange output

### ISSUE THREAD

**Issue by jhannink** [deeplearning4j/nd4j#2174]
#### Issue Description

The function NdArrayJSONWriter.write produces a json file with strange output on the first three lines. I guess this is just a typo in the corresponding file:
- expected behavior: 
 ```text 
  {
  "filefrom": "dl4j",
  "ordering": "c",
  [...]
```
- encountered behavior:
 ```text 
  {
  "filefrom:" "dl4j",
  "ordering:" "c",
  [...]
```

#### Version Information

I am using nd4j-native-platform:0.9.1

**Comment by tomthetrainer** [comment]
@eraly this looks like an easy fix

**Comment by eraly** [comment]
Yes.

**Comment by eraly** [comment]
@tomthetrainer Thanks. @jhannink Thanks.
