### ISSUE TITLE
Build error on NVIDIA Jetson TX2

### ISSUE THREAD

**Issue by iandow** [deeplearning4j/nd4j#2180]
#### Issue Description

I got the build error after `mvn clean install`

```[ERROR] Failed to execute goal on project nd4j-native: Could not resolve dependencies for project org.nd4j:nd4j-native:jar:0.9.2-SNAPSHOT: The following artifacts could not be resolved: org.bytedeco.javacpp-presets:openblas:jar:linux-aarch64:0.2.19-1.3, org.bytedeco.javacpp-presets:mkl:jar:linux-aarch64:2017.3-1.3: Could not find artifact org.bytedeco.javacpp-presets:openblas:jar:linux-aarch64:0.2.19-1.3 in central (https://repo.maven.apache.org/maven2)```

Here's the full `mvn clean install` output:

https://gist.github.com/iandow/ecdbe5eba5408603a09d052e9e6edd99

#### Version Information

* platform information: NVIDIA Jetson TX2, Ubuntu 16.04:
* CUDA version: 8.0.72

**Comment by saudet** [comment]
Looks like we need a 64-bit version of CUDA and OpenBLAS for ARM to run on that platform.
We will need to create builds for those as well:
https://github.com/bytedeco/javacpp-presets/tree/master/cuda
https://github.com/bytedeco/javacpp-presets/tree/master/openblas
If you have further discussions regarding those, open a thread over there. Thank you!

**Comment by saudet** [comment]
BTW, @vb216 might be interested in working those builds...

**Comment by Spawn32** [comment]
Hi,
Was this resolved ? having the exact same problem :/

**Comment by jackerxff** [comment]
need to compile some  javacpp-presents sub projects  first ,  at lestest  opencv cuda  leptonica ffmpeg  hdf5  ,but most of the projects do not support aarch64 or arm64 ,need to change cppbuild.sh .
libnd4j compile cuda version need create swap file first
deeplearing4j at jetson tx2  with cuda's performance  is close to  my MBP  2GHz With cpu

**Comment by saudet** [comment]
@Spawn32 @jackerxff We only really need OpenBLAS and libnd4j for starters
