### ISSUE TITLE
INDArray interval indexing not working for stride > 2

### ISSUE THREAD

**Issue by arzt** [deeplearning4j/nd4j#2184]
#### Issue Description

The following (scala) code shows the issue
```scala
import org.nd4j.linalg.factory.Nd4j
import org.nd4j.linalg.indexing.NDArrayIndex

object Prototype {
  def main(args: Array[String]): Unit = {
    val data = Array[Double](1, 2, 3,
                             4, 5, 6,
                             7, 8, 9)
    val mat = Nd4j.create(data, Array(3, 3))
    val stride = 3
    val rows = NDArrayIndex.interval(1, stride, 1)
    val cols = NDArrayIndex.interval(1, stride, 1)
    val result = mat.get(rows, cols)
    val y1 = result.getDouble(0)
    val y2 = mat.getDouble(1, 1)
    assert(y1 == y2, "Must be equal")
  }
}
```
A 3 by 3 matrix is created and one element is accessed by interval indexing using `stride = 3`.
For both rows and cols the indexes start at 1 thus the result should be equal to accessing index `(1,1)` directly. But `y1` is equal to 7 not 5 here. When `stride = 1` or `stride = 2` the code works as expected. I hope it wasn't reported yet and I did not miss something.

#### Version Information
nd4j-native-platform version 0.9.1
java8
Ubuntu LTS 16.04

#### Contributing

At first glance I suspect the problem in `org.nd4j.linalg.indexing.ShapeOffsetResolution`, but I haven't digged deeper yet. Help is appreciated.

**Comment by agibsonccc** [comment]
This isn't even valid. I'm closing this.

Even if you test it in numpy:
a = np.reshape(np.linspace(1,9,9),(3,3))
a[1:1:3,1:1:3]
Out[21]: array([], shape=(0, 0), dtype=float64)

You get an empty array..

**Comment by arzt** [comment]
Sorry, I made a mistake in my example, be setting the wrong end values of the interval. I corrected it above and added the respective working python code.
