### ISSUE TITLE
Next step

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#2185]
Next dev cycle will bring in:

- [ ] batched gemm (postponed from previous cycle, waiting for Sam)
- [x] Graph logical constructs: If, Condition, While, For (not sure)
- [x] SRU
- [x] LSTM

and lots of by-product ops, derived from tasks mentioned above

**Comment by raver119** [comment]
cc @agibsonccc

**Comment by saudet** [comment]
I have an idea to let JavaCPP load, collect, and pass around function pointers in a platform agnostic way. It would also let us do without trying to figure out how to link OpenBLAS explicitly with libnd4j.

**Comment by saudet** [comment]
In the end, I've added a `Loader.addressof()` method that basically wraps `dlsym()` and `GetProcAddress()`: https://github.com/bytedeco/javacpp/commit/6aafacfcd608a2e82b27af1ead054009c608b06c

It lives with other platform-specific features, and we might as well have all those in the same place... I've tested it on Linux, Mac, and Windows, and it works pretty well, for example:
```java
System.out.println(Loader.addressof("cblas_sgemm"));
System.out.println(Loader.addressof("cblas_dgemm"));
System.out.println(Loader.addressof("cblas_sgemm_batch"));
System.out.println(Loader.addressof("cblas_dgemm_batch"));
```
prints outs something like the following when MKL is loaded:
```
org.bytedeco.javacpp.Pointer[address=0x7f4be374c640,position=0,limit=0,capacity=0,deallocator=null]
org.bytedeco.javacpp.Pointer[address=0x7f4be3745380,position=0,limit=0,capacity=0,deallocator=null]
org.bytedeco.javacpp.Pointer[address=0x7f4be3749af0,position=0,limit=0,capacity=0,deallocator=null]
org.bytedeco.javacpp.Pointer[address=0x7f4be3742820,position=0,limit=0,capacity=0,deallocator=null]
```
When MKL isn't loaded, the last 2 are just `null`. So, we can simply pass them to some init function of libnd4j, and we're done.

**Comment by raver119** [comment]
Hmm, that's very interesting approach. It should work like that i think
- we build list of "desired extern functions".
- we check their availability at libnd4j start time, if they are available - that's one story, if they are not available - that's another story
- we allow to pass pointers from nd4j, to enforce use of specific methods at libnd4j

**Comment by saudet** [comment]
How do you check if they are available? Maybe the DLLs are still in JAR files...

**Comment by raver119** [comment]
I need to check for their availability in runtime, i.e. for running tests. So i'll be checking them the same way i did earlier for omp_set_num_threads etc.

**Comment by saudet** [comment]
Yes, you could do it that way for tests, it doesn't need to be part of libnd4j proper.

**Comment by raver119** [comment]
It's only the matter of time, when we'll want standalone libnd4j execution, or compilation via LLVM for weird devices available out there. So yes, i want this approach in c++ too. Will be cheaper to build it in right now, then to hack for it later.

**Comment by saudet** [comment]
Java can run on a lot of weird devices too you know, for example: https://github.com/ReadyTalk/avian  But this is really just politics at this point, so whatever.

**Comment by raver119** [comment]
Road to LSTM turns out to be long. Another set of ops, originally not planned for this cycle added:

- fill_like
- size
- rank
- one_hot
- square
- rsquare
- floordiv
- truncatediv
- strided_slice
- slice
- expand_dims

cc @agibsonccc
