### ISSUE TITLE
【HELP】Please！ How to set decimal point accuracy?

### ISSUE THREAD

**Issue by PerkinsZhu** [deeplearning4j/nd4j#2200]
#### Issue Description

my code：
      ` val ddds = Nd4j.create(Array[Double](0.22222222222d), Array[Int](1,1))
       println(ddds)`
result:
  0.22
it is only two decimal point!

**Comment by raver119** [comment]
It's just print truncation. Internally it's still float/double/float16, whatever you uses in your session.

**Comment by PerkinsZhu** [comment]
@raver119  Thanks!

**Comment by PerkinsZhu** [comment]
@raver119 
How to print it completely?All decimal points？

**Comment by raver119** [comment]
You can do that manually, using NDArrayStrings class. It allows you to tweak format.
