### ISSUE TITLE
Nd4j.create(new float[] {0,1,2,3,4,5}) makes a rank 2 dataset

### ISSUE THREAD

**Issue by gerring** [deeplearning4j/nd4j#2202]
#### Issue Description

When I create an nd array from a 1d float[] it has rank 2.
```
INDArray array = Nd4j.create(new float[] {0,1,2,3,4,5}); 
int rank = array.rank(); // Is 2!
```
From the documentation this is supposed to be rank 1: 
http://nd4j.org/userguide#createfromjavaAny 

-- | --

Please describe your issue, along with:
- expected behavior
- encountered behavior

#### Version Information

I tried with all versions from 0.7.0 - 0.9.1

Please indicate relevant versions, including, if relevant:

* nd4j

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
That’s expected behavior. There’s no 1d arrays in nd4j. Even scalar is 2d: 1x1 edge case. Row vector is 1xY, column vector is Yx1

**Comment by gerring** [comment]
Looks like it is just the doc that is out of date then :  http://nd4j.org/userguide#createfromjavaAny

**Comment by gerring** [comment]
The doc says:

To create a 1d NDArray from a 1d Java array, use:
Row vector: Nd4j.create(float[]) or Nd4j.create(double[])

**Comment by raver119** [comment]
I'm afraid ND4j never had 1D NDArrays in your or java meaning.
 
For ND4J Being rank 2 doesn't make vector a matrix. I.e. if you have matrix multiplication, and second operand is  vector - it'll be treated as vector. All this stuff is handled internally, via shape information. 

So rank 2 NDArray with one of shapes being equal to 1, automagically treated as vector.

**Comment by tomthetrainer** [comment]
@gerring 

Is there a specific patch to the documentation for this topic that you would like to provide? 

No need for a pull request, responding here is fine. 

For Example a specific line on that page that you feel is unclear, and then a proposed change that makes it more clear? 

Thanks
