### ISSUE TITLE
Add dependecies to android project

### ISSUE THREAD

**Issue by Rehckover** [deeplearning4j/nd4j#2212]
This in gradle file: compile 'org.nd4j:nd4j-native:0.9.1'
    compile 'org.nd4j:nd4j-native:0.9.1:android-x86'
    compile 'org.nd4j:nd4j-native:0.9.1:android-arm'
    compile 'org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-x86'
    compile 'org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-arm'

The error is: Error:Execution failed for task ':app:transformNativeLibsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/x86/libjniopenblas.so
	File1: C:\Users\1\.gradle\caches\modules-2\files-2.1\org.bytedeco.javacpp-presets\openblas\0.2.19-1.3\2189141b6c83cc8e5b342b04e8f49e22996f72f4\openblas-0.2.19-1.3-android-x86.jar
	File2: D:\Smart House\Sip projects\Camera\tipit\build\intermediates\bundles\default\jni

**Comment by saudet** [comment]
I'm afraid that is specific to your project. Try to remove "File2: D:\Smart House\Sip projects\Camera\tipit\build\intermediates\bundles\default\jni" from your build.
