### ISSUE TITLE
Prevent string unpack by default

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/nd4j#2222]
#### Issue Description

A while back I added an env variable `ND4J_PREVENT_UNPACK` that prevents printing of arrays. This was important since some software - such as Zeppelin or IntelliJ debugger - has a tendency to call .toString on every object in scope.

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L154

I've found myself disabling this more often than not. I think this should be the default behavior. Instead, we should use the env `ND4J_PRINT_ARRAYS` to allow printing of entire arrays when present. And if a user would want to grab a "glimpse" of an array, we add the signature `toString(int maxChars)`.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Master

#### Contributing

Yup, easy for me to code if we're happy with this.

**Comment by raver119** [comment]
No. Just No.

I believe disabling toString() is a terrible idea. We should do something else, like limit number of elements being printed out. I.e. 3-5 per dimension. Something like that. But bing disabled by default - just isn't a good way to solve this problem.

**Comment by crockpotveggies** [comment]
I see your point. You think 3-5 per dimension is a reasonable number?

**Comment by raver119** [comment]
numpy does something like that for long arrays, so why not?

**Comment by raver119** [comment]
as reference: another/additional option: silently prohibit toString() method, while MLN/CG fit() is running.

**Comment by AlexDBlack** [comment]
Yeah, disabled by default is a terrible idea. I'd be fine with truncation, as long as:
(a) it's obvious to users that it's truncated, and
(b) we have some over overloads to print the full array... maybe ```toString(boolean allowTruncate)``` and ```toString(boolean allowTruncate, boolean fullPrecision)``` where ```toString() == toString(true, false)```

As far as how much to display/truncate: I'd be tempted to do the same amount as numpy.

**Comment by saudet** [comment]
BTW, numpy has modes for that, but it's really user-unfriendly, for example:
https://stackoverflow.com/questions/21008858/formatting-floats-in-a-numpy-array

**Comment by raver119** [comment]
Where we ended up on this issue?

**Comment by AlexDBlack** [comment]
Yeah, this can be closed.
