### ISSUE TITLE
deeplearning4j-zoo dependency is duplicated in dl4j-cuda-specific-examples pom

### ISSUE THREAD

**Issue by facundomaldonado** [deeplearning4j/nd4j#2223]
deeplearning4j-zoo dependency is duplicated in dl4j-cuda-specific-examples pom.xml.
It makes the build process to fail with a LINT failure:

[INFO] [LINT] DuplicateDep: Dependency 'org.deeplearning4j:deeplearning4j-zoo:jar' is declared multiple times with the same version: 91:21 : 86:21 C:\dev\proj\pocs\dl4j-examples\**dl4j-cuda-specific-examples\pom.xml**                                                                                                                                                                           
[INFO] Writing xml report                                                                                                                                                                       
[INFO] ------------------------------------------------------------------------                                                                                                                 
[INFO] Reactor Summary:                                                                                                                                                                         
[INFO]                                                                                                                                                                                          
[INFO] DeepLearning4j Examples Parent ..................... SUCCESS [  1.520 s]                                                                                                                 
[INFO] DeepLearning4j Examples ............................ SUCCESS [ 56.549 s]                                                                                                                 
[INFO] dl4j-spark-examples ................................ SUCCESS [  0.115 s]                                                                                                                 
[INFO] dl4j-spark ......................................... SUCCESS [ 58.100 s]                                                                                                                 
[INFO] datavec-examples ................................... SUCCESS [ 12.650 s]                                                                                                                 
[INFO] DeepLearning4j CUDA special examples ............... FAILURE [  0.260 s]                                                                                                                 
[INFO] nd4j-examples ...................................... SKIPPED                                                                                                                             
[INFO] Reinforcement Learning4j Examples .................. SKIPPED                                                                                                                             
[INFO] lstm-hdfs .......................................... SKIPPED                                                                                                                             
[INFO] ------------------------------------------------------------------------                                                                                                                 
[INFO] BUILD FAILURE                                                                                                                                                                            
[INFO] ------------------------------------------------------------------------                                                                                                                 
[INFO] Total time: 02:09 min                                                                                                                                                                    
[INFO] Finished at: 2017-10-27T12:12:30-03:00                                                                                                                                                   
[INFO] Final Memory: 155M/1937M                                                                                                                                                                 
[INFO] ------------------------------------------------------------------------                                                                                                                 
[ERROR] Failed to execute goal com.lewisd:lint-maven-plugin:0.0.11:check (pom-lint) on project dl4j-cuda-specific-examples: [LINT] Violations found. For more details, see error messages above,
 or results in C:\dev\proj\pocs\dl4j-examples\dl4j-cuda-specific-examples\target\maven-lint-result.xml -> [Help 1]

I removed one of the entries in pom.xml and it works.

        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-zoo</artifactId>
            <version>${dl4j.version}</version>
        </dependency>

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/dl4j-examples/pull/585
