### ISSUE TITLE
ClassPathResource.getTempFileFromArchive() assumes write access

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2238]
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-common/src/main/java/org/nd4j/linalg/io/ClassPathResource.java#L65-L74

AFAIK this will put it in the JAR directory? I've run into situations where this can fail when that directory cannot be written to.
Perhaps instead it should be placed in the java.io.tmpdir by default instead.

**Comment by raver119** [comment]
It's clearly fixed now: temp file is created in temp folder.
