### ISSUE TITLE
reshape does't thrown exception when incorrect shape is given

### ISSUE THREAD

**Issue by cpuheater** [deeplearning4j/nd4j#2259]
In this examples I can reshape score to any shape, exception is not thrown, mmul somehow corrupts ndarray 

import org.nd4j.linalg.api.ndarray.INDArray
import org.nd4j.linalg.factory.Nd4j
val a: INDArray = Nd4j.linspace(1, 4, 4).reshape(2,2)
val b: INDArray = Nd4j.linspace(1, 4, 4).reshape(2,2)
val score = a.mmul(b)
val reshaped1 = score.reshape(2,100)
val reshaped2 = score.reshape(2,1)

**Comment by raver119** [comment]
Thanks for highlighting this issue. Validation + test added.
