### ISSUE TITLE
nd4j-x86 resulting in errors

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4j#226]
I have been trying to create an array, and the build breaks.

Here is the code :
val arr = (1 to 8 by 1).toArray
    arr.map(println(_))
    val m2 = Nd4j.create((1 to 8 by 1).toArray, Array(2, 2, 2))

Here is the error I am seeing

 java.lang.IllegalArgumentException: Illegal index 40320 derived from 1 with offset of 0 and stride of 40320
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2931)
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:3380)
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:4511)
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:4539)
[info]   at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:4539)

Note that the jblas package didn't present me with these errors.

**Comment by agibsonccc** [comment]
I believe the indexing issues were fixed in nd4s.
