### ISSUE TITLE
API changes report for Nd4j Api snapshot

### ISSUE THREAD

**Issue by lvc** [deeplearning4j/nd4j#2265]
Hi,

I'd like to share report on API changes and backward compatibility for the Nd4j library: https://abi-laboratory.pro/java/tracker/timeline/nd4j-api/

BC — binary compatibility
SC — source compatibility

The report is generated by the https://github.com/lvc/japi-tracker tool according to the article https://wiki.eclipse.org/Evolving_Java-based_APIs_2. Hope it will be helpful for users and maintainers of the library.

Feel free to request other Nd4j modules to be included to the tracker if you are interested.

Thank you.

![nd4j-api-1](https://user-images.githubusercontent.com/1517837/32765995-fa571f64-c91d-11e7-9355-604c435ae5b4.png)

![nd4j-api-2](https://user-images.githubusercontent.com/1517837/32765993-fa3a0fbe-c91d-11e7-82d7-c44306f76eb1.png)

**Comment by agibsonccc** [comment]
Thanks!
