### ISSUE TITLE
Some operations are skipped silently when nd4j is executed by multiple threads

### ISSUE THREAD

**Issue by Atry** [deeplearning4j/nd4j#2271]
#### Issue Description

Given an 3x1 `INDArray` whose content is `[2.75, 12.61, 19.72]`, and minus it with `[3.0, 13.0, 19.0]` in thread 1,
When passing the result of minus operator to thread 2 and then multiply by itself in thread 2,
Then I expect the result should be `[0.125, 0.1521, 0.5184]`
But I actually got  `[7.54, 159.09, 388.77]`

Note that both the minus and multiplication are immutable operators, not in-place operators.

The pseudocode is
``` java
void runInThread1() {
  INDArray input = [2.75, 12.61, 19.72];
  INDArray step1Result = input - [3.0, 13.0, 19.0];
  postToThread2(step1Result);
}

void runInThread2(INDArray step1Result) {
  INDArray step2Result = step1Result * step1Result;
  assert(step2Result == [0.125, 0.1521, 0.5184]); // Actually step2Result == [7.54, 159.09, 388.77]
}
```

This bug only occurs one or two times during 10000 runs. Adding a `println` function call in thread 1 right before `postToThread2` will prevent this bug.
#### Version Information

Please indicate relevant versions, including, if relevant:

* nd4j version - 0.8.0 and 0.9.1
* platform information (OS, etc) - Ubuntu 16.04
* CUDA version, if used - 8.0
* NVIDIA driver version, if in use - 384.90

**Comment by raver119** [comment]
No, sorry. It's not a bug and it doesn't work like that.

INDArray isn't immutable, and isn't thread-safe. Especially on CUDA.

**Comment by raver119** [comment]
P.s. That's about CUDA streams: thread A uses stream SA to invoke op. thread B useses its own stream SB. And with given stream SB there's no way to find out if stream SA finished calculations.

So that's just a pure race condition, caused by wrong assumptions about INDArray immutability

**Comment by raver119** [comment]
P.s. if you want to ensure ops in thread A finished, add this line: Nd4j.getExecutioner().commit(); instead of print.
