### ISSUE TITLE
Add ops to "reverse" an array

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2313]
Not a priority, but might come in handy sometimes (like here: https://github.com/deeplearning4j/deeplearning4j/pull/4336)

Numpy has fliplr and flipup
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.fliplr.html
Tensorflow has reverse
https://www.tensorflow.org/api_docs/python/tf/reverse

But, TBH: I'd prefer more general "permute/reverse TADs" behaviour - i.e., it would be possible to swap the order of 2d tensors in a 3d array... That could be viewed as a special case of Nd4j.pullRows with fixed indices {n-1, n-2, ..., 1, 0}, where n = number of TADs.

**Comment by raver119** [comment]
It's already available. Was added few weeks ago. Please try and confirm it matches your expectations.

**Comment by raver119** [comment]
p.s. op name is ultra-surprising: `reverse`

**Comment by AlexDBlack** [comment]
So we have ND4J.reverse(...) and Reverse class (was made native in July)
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/Reverse.java

This seems to reverse all values element-wise, not permute/reverse the order of each TAD, which is what I was looking for here.

**Comment by raver119** [comment]
No, we also have CustomOp reverse, that can be invoked via DynamicCustomOp

**Comment by AlexDBlack** [comment]
Yep, looks good. For reference (in case anyone is looking at this), some simple usages of this:

```
    @Test
    public void testReverse(){

        INDArray arr = Nd4j.linspace(1,50,50).reshape(10,5);
        INDArray result = Nd4j.createUninitialized(10,5);

        CustomOp op = DynamicCustomOp.builder("reverse")
                .addIntegerArguments(1)
                .addInputs(arr)
                .addOutputs(result)
                .callInplace(false)
                .build();

        Nd4j.getExecutioner().exec(op);

        System.out.println("Original:");
        System.out.println(arr);
        System.out.println("Result:");
        System.out.println(result);
    }

    @Test
    public void testReverse3D(){

        INDArray arr = Nd4j.linspace(1,3*4*5,3*4*5).reshape('f',3,4,5);
        INDArray result = Nd4j.createUninitialized(new int[]{3,4,5});

        CustomOp op = DynamicCustomOp.builder("reverse")
                .addIntegerArguments(new int[]{0,1})
                .addInputs(arr)
                .addOutputs(result)
                .callInplace(false)
                .build();

        Nd4j.getExecutioner().exec(op);

        for( int i=0; i<5; i++ ){
            System.out.println(arr.tensorAlongDimension(i, 0,1));
            System.out.println(result.tensorAlongDimension(i, 0,1));
            System.out.println("------");
        }
    }
```
