### ISSUE TITLE
matmul - libnd4j exec

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/nd4j#2329]
Run [this](https://github.com/deeplearning4j/nd4j/blob/8eafbc5c6b0e444d63f37c43d5e2ad3ea9385b21/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/imports/TFGraphTestList.java#L26) 

with the list set to "math_mul_order"

**Comment by raver119** [comment]
Fixed i think.
