### ISSUE TITLE
Windows: Can't link with 2018 MKL (master and 0.9.1)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2335]
Works:
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2017.0.109\windows\redist\intel64_win\mkl
Fails:
C:\Program Files (x86)\IntelSWTools\compilers_and_libraries_2018.1.156\windows\redist\intel64_win\mkl

Note that installing and overriding latest javacpp (1.3.4-SNAPSHOT) on 0.9.1 and master does not make any difference (earlier 2017 version works with default javacpp version, 2018 fails whether I force 1.3.4-SNAPSHOT in examples or not)

```
o.d.e.c.LenetMnistExample - Load data....
o.d.e.c.LenetMnistExample - Build model....
o.n.l.f.Nd4jBackend - Loaded [CpuBackend] backend
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.n.Nd4jBlas - Number of threads used for BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: NONE; inference: SEPARATE]
o.d.e.c.LenetMnistExample - Train model....
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.
```

![image](https://user-images.githubusercontent.com/2360237/33509117-0503dcc0-d753-11e7-88ac-33b42a6850af.png)

**Comment by saudet** [comment]
You'll probably need the latest SNAPSHOT one for OpenBLAS there as well...

**Comment by AlexDBlack** [comment]
Adding the following dependencies give me the 'cannot load' error on both versions or MKL, when running on master.
```
        <dependency>
            <groupId>org.bytedeco</groupId>
            <artifactId>javacpp</artifactId>
            <version>1.3.4-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.bytedeco.javacpp-presets</groupId>
            <artifactId>openblas-platform</artifactId>
            <version>0.2.20-1.3.4-SNAPSHOT</version>
        </dependency>
```

The 2017 MKL only works if I remove the openblas dependency...

**Comment by saudet** [comment]
MKL doesn't include its DLLs in the system PATH anymore, so you'll need to make sure the PATH is alright. If it's not in the PATH, 0.2.20-1.3 will still look in the default path of 2017, while 0.2.20-1.3.4-SNAPSHOT will look in the default one of 2018.

**Comment by saudet** [comment]
The patch should work with the versions that gets picked up from the nd4j module for the javacpp and openblas ones...
