### ISSUE TITLE
Transforms.pow(INDArray, INDArray) function calculate result is wrong

### ISSUE THREAD

**Issue by yelangchs** [deeplearning4j/nd4j#2337]
#### Issue Description

Please describe your issue, along with:
- I create a rand INDArray like that Nd4j.rand(2, 4, 10), then stdNumber(true).doubleValue(). but it's result is wrong.

the code like that:

```
  public static void main(String[] args) throws Exception{
        INDArray indArray1 = Nd4j.create(new double[]{1, 2, 3});
        INDArray indArray2 = Nd4j.create(new double[]{1, 1, 1});
        INDArray indArray3 = TransformsHelper.pow(indArray1.dup(), indArray2.dup());
        System.out.println("input: " + indArray1);
        System.out.println("power: " + indArray2);
        System.out.println("result: " + indArray3);
    }
```
but the result:
```
input: [1.00,  2.00,  3.00]
power: [1.00,  1.00,  1.00]
result: [1.00,  0.50,  0.33]
```
#### Version Information
* nd4j-native-platform 0.9.1
* macOS Sierra

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by yelangchs** [comment]
it may be is the result for indarray1 / indarray2

**Comment by raver119** [comment]
There were no pow(INDArray, INDArray) earlier. Now it's fixed on current master.
