### ISSUE TITLE
NoClassDefFoundError when saving ComputationGraphConfiguration

### ISSUE THREAD

**Issue by turambar** [deeplearning4j/nd4j#2367]
#### Issue Description

When attempting to call a `ComputationGraphConfiguration.toJson(...)`, I get a `NoClassDefFoundError` for `com.google.protobuf.GeneratedMessageV3` (from within ND4J shaded jackson, looks like).

Gist in comments.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Versions are all 0.9.2 master (built from source on ~Thursday, Dec 7)
* Linux but I assume it happens on all platforms

**Comment by turambar** [comment]
https://gist.github.com/turambar/8fe027494606cd43a33b70561fb67f20

**Comment by turambar** [comment]
@saudet @wmeddie @AlexDBlack @emsixteeen so you guys can track this

**Comment by AlexDBlack** [comment]
So far (using latest DL4J/ND4J masters, linux): I'm not able to reproduce this using either:
- DL4J core unit tests
- DL4J Examples (SaveLoadComputationGraph)

@turambar have you got a pom file or something that could help reproduce this?

**Comment by turambar** [comment]
@AlexDBlack see gitter channel for details (this is on a customer project)

**Comment by saudet** [comment]
It just says it's not finding the class com.google.protobuf.GeneratedMessageV3, so maybe just adding protobuf as a dependency?

**Comment by turambar** [comment]
Solved by adding the following to my pom:

```
 <dependency>
     <groupId>com.google.protobuf</groupId>
     <artifactId>protobuf-java</artifactId>
     <version>3.5.0</version>
</dependency>
```

I will leave this open for the time being to give @agibsonccc a chance to comment, but I'm happy to close it with the current solution.

**Comment by turambar** [comment]
So this is solved for me (the problem was `hadoop-common` pulling in outdated `protobuf-java` -- I removed that because I didn't need it), but I understand that we want a longer term fix (shading?) so I'll leave this open.

**Comment by raver119** [comment]
I believe this issue is resolved now.
