### ISSUE TITLE
expand_dim core dumps with samediff executor

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/nd4j#2393]
Output when run with "just_print" execute mode

https://gist.github.com/eraly/b71000de04e49d495ebc0faff4cf110b#file-gistfile1-txt-L351

**Comment by agibsonccc** [comment]
Juries out on this one but I'm waiting till flatbuffers is fixed before verifying which kind of bug it is.

**Comment by raver119** [comment]
At this moment everything related to TF import is irrelevant. We're making important changes/fixes now.

TL/DR: most of issues are caused by graph inconsistency due to issues with var names. Fixes incoming.

**Comment by raver119** [comment]
Fixed.
