### ISSUE TITLE
Need SameDiff scalar power op (and derivative?)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2426]
https://github.com/deeplearning4j/nd4j/blob/7599752c6e2185b46d7cfb347a431d109c855275/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/autodiff/functions/DifferentialFunctionFactory.java#L353-L356

SameDiff.pow incorrectly uses ScalarMultiplication internally.

Looks like we don't have a scalar power op in nd4j OR libnd4j:
https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/scalar

https://github.com/deeplearning4j/libnd4j/blob/c1d372a5d53c75add5e1e6eac0a53c26278ddb94/include/loops/legacy_ops.h#L146-L170

We may want/need the derivative op too:
If ```out = in ^ x``` then ```dL/dIn = dL/dOut * dOut/dIn = dL/dOut * x * in^(x-1)```

Edit: simple ND4J unit test...
```
    @Test
    public void testPow3(){

        SameDiff sd = SameDiff.create();
        INDArray inArr = Nd4j.linspace(-3, 3, 7);
        SDVariable in = sd.var("in", inArr.dup());

        SDVariable out = sd.pow("out", in, 3);
        INDArray outExp = Transforms.pow(inArr, 3, true);

        INDArray outAct = sd.execAndEndResult();

        assertEquals(outExp, outAct);
    }
```

**Comment by raver119** [comment]
scalar pow for us is one of Transforms op, opNum == 7

**Comment by raver119** [comment]
and CubeDerivative is  exactly that: https://github.com/deeplearning4j/libnd4j/blob/bb6a625a1b1a23f003925af0fb3b2df1f3ca23d5/include/ops/ops.h#L1276

**Comment by agibsonccc** [comment]
I switched this to cube and cubederivative.

**Comment by raver119** [comment]
Right, but first part of the issue is about Pow derivative, which is not just a scalar multiplication.

**Comment by AlexDBlack** [comment]
Closing this - Pow and PowDerivative ops were added recently
https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms
