### ISSUE TITLE
no nd4jcpu in java.library.path

### ISSUE THREAD

**Issue by Porama6400** [deeplearning4j/nd4j#2443]
I have this error: **UnsatisfiedLinkError: no nd4jcpu in java.library.path**

List of installed library

- org.deeplearning4j:deeplearning4j-core:0.9.1
- org.nd4j:nd4j-native-platform:0.9.1
- org.datavec:datavec-api:0.9.1

I installed all via Intellij IDEA's Project structure
I've read that **nd4j-native-platform** suppose to contain all library I need but look like something went wrong

	D:\Java\jdk1.8.0_112\bin\java "-javaagent:D:\JetBrains\IntelliJ IDEA 2017.3.1\lib\idea_rt.jar=56080:D:\JetBrains\IntelliJ IDEA 2017.3.1\bin" -Dfile.encoding=UTF-8 -classpath D:\Java\jdk1.8.0_112\jre\lib\charsets.jar;D:\Java\jdk1.8.0_112\jre\lib\deploy.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\access-bridge-64.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\cldrdata.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\dnsns.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\jaccess.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\jfxrt.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\localedata.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\nashorn.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\sunec.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\sunjce_provider.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\sunmscapi.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\sunpkcs11.jar;D:\Java\jdk1.8.0_112\jre\lib\ext\zipfs.jar;D:\Java\jdk1.8.0_112\jre\lib\javaws.jar;D:\Java\jdk1.8.0_112\jre\lib\jce.jar;D:\Java\jdk1.8.0_112\jre\lib\jfr.jar;D:\Java\jdk1.8.0_112\jre\lib\jfxswt.jar;D:\Java\jdk1.8.0_112\jre\lib\jsse.jar;D:\Java\jdk1.8.0_112\jre\lib\management-agent.jar;D:\Java\jdk1.8.0_112\jre\lib\plugin.jar;D:\Java\jdk1.8.0_112\jre\lib\resources.jar;D:\Java\jdk1.8.0_112\jre\lib\rt.jar;E:\Project\Java\TestMachineLearning\out\production\TestMachineLearning;C:\Users\Porama\.m2\repository\org\deeplearning4j\deeplearning4j-core\0.9.1\deeplearning4j-core-0.9.1.jar;C:\Users\Porama\.m2\repository\org\deeplearning4j\nearestneighbor-core\0.9.1\nearestneighbor-core-0.9.1.jar;C:\Users\Porama\.m2\repository\org\deeplearning4j\deeplearning4j-modelimport\0.9.1\deeplearning4j-modelimport-0.9.1.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp\1.3.3\javacpp-1.3.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\hdf5-platform\1.10.0-patch1-1.3\hdf5-platform-1.10.0-patch1-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\hdf5\1.10.0-patch1-1.3\hdf5-1.10.0-patch1-1.3.jar;C:\Users\Porama\.m2\repository\org\slf4j\slf4j-api\1.7.12\slf4j-api-1.7.12.jar;C:\Users\Porama\.m2\repository\org\deeplearning4j\deeplearning4j-nn\0.9.1\deeplearning4j-nn-0.9.1.jar;C:\Users\Porama\.m2\repository\org\nd4j\nd4j-common\0.9.1\nd4j-common-0.9.1.jar;C:\Users\Porama\.m2\repository\com\github\stephenc\findbugs\findbugs-annotations\1.3.9-1\findbugs-annotations-1.3.9-1.jar;C:\Users\Porama\.m2\repository\org\nd4j\nd4j-jackson\0.9.1\nd4j-jackson-0.9.1.jar;C:\Users\Porama\.m2\repository\org\nd4j\nd4j-base64\0.9.1\nd4j-base64-0.9.1.jar;C:\Users\Porama\.m2\repository\commons-net\commons-net\3.1\commons-net-3.1.jar;C:\Users\Porama\.m2\repository\org\apache\commons\commons-math3\3.4.1\commons-math3-3.4.1.jar;C:\Users\Porama\.m2\repository\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\Porama\.m2\repository\org\apache\commons\commons-compress\1.8\commons-compress-1.8.jar;C:\Users\Porama\.m2\repository\org\tukaani\xz\1.5\xz-1.5.jar;C:\Users\Porama\.m2\repository\com\google\guava\guava\20.0\guava-20.0.jar;C:\Users\Porama\.m2\repository\org\nd4j\nd4j-api\0.9.1\nd4j-api-0.9.1.jar;C:\Users\Porama\.m2\repository\org\nd4j\nd4j-buffer\0.9.1\nd4j-buffer-0.9.1.jar;C:\Users\Porama\.m2\repository\org\nd4j\nd4j-context\0.9.1\nd4j-context-0.9.1.jar;C:\Users\Porama\.m2\repository\net\ericaro\neoitertools\1.0.0\neoitertools-1.0.0.jar;C:\Users\Porama\.m2\repository\junit\junit\4.8.2\junit-4.8.2.jar;C:\Users\Porama\.m2\repository\org\reflections\reflections\0.9.10\reflections-0.9.10.jar;C:\Users\Porama\.m2\repository\org\javassist\javassist\3.19.0-GA\javassist-3.19.0-GA.jar;C:\Users\Porama\.m2\repository\com\google\code\findbugs\annotations\2.0.1\annotations-2.0.1.jar;C:\Users\Porama\.m2\repository\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;C:\Users\Porama\.m2\repository\org\nd4j\jackson\0.9.1\jackson-0.9.1.jar;C:\Users\Porama\.m2\repository\org\yaml\snakeyaml\1.12\snakeyaml-1.12.jar;C:\Users\Porama\.m2\repository\org\codehaus\woodstox\stax2-api\3.1.4\stax2-api-3.1.4.jar;C:\Users\Porama\.m2\repository\joda-time\joda-time\2.2\joda-time-2.2.jar;C:\Users\Porama\.m2\repository\org\projectlombok\lombok\1.16.16\lombok-1.16.16.jar;C:\Users\Porama\.m2\repository\org\datavec\datavec-api\0.9.1\datavec-api-0.9.1.jar;C:\Users\Porama\.m2\repository\org\freemarker\freemarker\2.3.23\freemarker-2.3.23.jar;C:\Users\Porama\.m2\repository\com\clearspring\analytics\stream\2.7.0\stream-2.7.0.jar;C:\Users\Porama\.m2\repository\it\unimi\dsi\fastutil\6.5.7\fastutil-6.5.7.jar;C:\Users\Porama\.m2\repository\net\sf\opencsv\opencsv\2.3\opencsv-2.3.jar;C:\Users\Porama\.m2\repository\org\datavec\datavec-data-image\0.9.1\datavec-data-image-0.9.1.jar;C:\Users\Porama\.m2\repository\com\github\jai-imageio\jai-imageio-core\1.3.0\jai-imageio-core-1.3.0.jar;C:\Users\Porama\.m2\repository\com\twelvemonkeys\imageio\imageio-jpeg\3.1.1\imageio-jpeg-3.1.1.jar;C:\Users\Porama\.m2\repository\com\twelvemonkeys\imageio\imageio-core\3.1.1\imageio-core-3.1.1.jar;C:\Users\Porama\.m2\repository\com\twelvemonkeys\imageio\imageio-metadata\3.1.1\imageio-metadata-3.1.1.jar;C:\Users\Porama\.m2\repository\com\twelvemonkeys\common\common-lang\3.1.1\common-lang-3.1.1.jar;C:\Users\Porama\.m2\repository\com\twelvemonkeys\common\common-io\3.1.1\common-io-3.1.1.jar;C:\Users\Porama\.m2\repository\com\twelvemonkeys\common\common-image\3.1.1\common-image-3.1.1.jar;C:\Users\Porama\.m2\repository\com\twelvemonkeys\imageio\imageio-tiff\3.1.1\imageio-tiff-3.1.1.jar;C:\Users\Porama\.m2\repository\com\twelvemonkeys\imageio\imageio-psd\3.1.1\imageio-psd-3.1.1.jar;C:\Users\Porama\.m2\repository\com\twelvemonkeys\imageio\imageio-bmp\3.1.1\imageio-bmp-3.1.1.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacv\1.3.3\javacv-1.3.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\opencv\3.2.0-1.3\opencv-3.2.0-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\ffmpeg\3.2.1-1.3\ffmpeg-3.2.1-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\flycapture\2.9.3.43-1.3\flycapture-2.9.3.43-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\libdc1394\2.2.4-1.3\libdc1394-2.2.4-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\libfreenect\0.5.3-1.3\libfreenect-0.5.3-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\libfreenect2\0.2.0-1.3\libfreenect2-0.2.0-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\librealsense\1.9.6-1.3\librealsense-1.9.6-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\videoinput\0.200-1.3\videoinput-0.200-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\artoolkitplus\2.3.1-1.3\artoolkitplus-2.3.1-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\flandmark\1.07-1.3\flandmark-1.07-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\opencv-platform\3.2.0-1.3\opencv-platform-3.2.0-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\leptonica-platform\1.73-1.3\leptonica-platform-1.73-1.3.jar;C:\Users\Porama\.m2\repository\org\bytedeco\javacpp-presets\leptonica\1.73-1.3\leptonica-1.73-1.3.jar;C:\Users\Porama\.m2\repository\org\deeplearning4j\deeplearning4j-ui-components\0.9.1\deeplearning4j-ui-components-0.9.1.jar;C:\Users\Porama\.m2\repository\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;E:\Project\Java\TestMachineLearning\lib\nd4j-native-platform-0.9.1.jar;E:\Project\Java\TestMachineLearning\lib\openblas-platform-0.2.19-1.3.jar;E:\Project\Java\TestMachineLearning\lib\openblas-0.2.19-1.3.jar;E:\Project\Java\TestMachineLearning\lib\nd4j-native-0.9.1.jar;E:\Project\Java\TestMachineLearning\lib\javacpp-1.3.3.jar;E:\Project\Java\TestMachineLearning\lib\nd4j-native-api-0.9.1.jar;E:\Project\Java\TestMachineLearning\lib\nd4j-buffer-0.9.1.jar;E:\Project\Java\TestMachineLearning\lib\nd4j-api-0.9.1.jar;E:\Project\Java\TestMachineLearning\lib\slf4j-api-1.7.10.jar;E:\Project\Java\TestMachineLearning\lib\jackson-0.9.1.jar;E:\Project\Java\TestMachineLearning\lib\snakeyaml-1.12.jar;E:\Project\Java\TestMachineLearning\lib\stax2-api-3.1.4.jar;E:\Project\Java\TestMachineLearning\lib\joda-time-2.2.jar;E:\Project\Java\TestMachineLearning\lib\lombok-1.16.16.jar;E:\Project\Java\TestMachineLearning\lib\nd4j-context-0.9.1.jar;E:\Project\Java\TestMachineLearning\lib\nd4j-common-0.9.1.jar;E:\Project\Java\TestMachineLearning\lib\commons-io-2.4.jar;E:\Project\Java\TestMachineLearning\lib\findbugs-annotations-1.3.9-1.jar;E:\Project\Java\TestMachineLearning\lib\commons-math3-3.4.1.jar;E:\Project\Java\TestMachineLearning\lib\commons-lang3-3.3.1.jar;E:\Project\Java\TestMachineLearning\lib\neoitertools-1.0.0.jar;E:\Project\Java\TestMachineLearning\lib\junit-4.8.2.jar;E:\Project\Java\TestMachineLearning\lib\reflections-0.9.10.jar;E:\Project\Java\TestMachineLearning\lib\guava-15.0.jar;E:\Project\Java\TestMachineLearning\lib\javassist-3.19.0-GA.jar;E:\Project\Java\TestMachineLearning\lib\annotations-2.0.1.jar;E:\Project\Java\TestMachineLearning\lib\datavec-api-0.9.1.jar;E:\Project\Java\TestMachineLearning\lib\commons-compress-1.8.1.jar;E:\Project\Java\TestMachineLearning\lib\commons-math3-3.3.jar;E:\Project\Java\TestMachineLearning\lib\slf4j-api-1.7.7.jar;E:\Project\Java\TestMachineLearning\lib\joda-time-2.9.2.jar;E:\Project\Java\TestMachineLearning\lib\lombok-1.16.10.jar;E:\Project\Java\TestMachineLearning\lib\freemarker-2.3.23.jar;E:\Project\Java\TestMachineLearning\lib\stream-2.7.0.jar;E:\Project\Java\TestMachineLearning\lib\fastutil-6.5.7.jar;E:\Project\Java\TestMachineLearning\lib\opencsv-2.3.jar com.Porama6400.TML.TestMachineLearning
	SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
	SLF4J: Defaulting to no-operation (NOP) logger implementation
	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
	Exception in thread "main" java.lang.ExceptionInInitializerError
		at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:53)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at java.lang.Class.newInstance(Class.java:442)
		at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:6185)
		at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6087)
		at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:201)
		at com.Porama6400.TML.TestMachineLearning.getTrainingData(TestMachineLearning.java:97)
		at com.Porama6400.TML.TestMachineLearning.main(TestMachineLearning.java:50)
	Caused by: java.lang.RuntimeException: ND4J is probably missing dependencies. For more information, please refer to: http://nd4j.org/getstarted.html
		at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:51)
		at org.nd4j.nativeblas.NativeOpsHolder.<clinit>(NativeOpsHolder.java:19)
		... 11 more
	Caused by: java.lang.UnsatisfiedLinkError: no jnind4jcpu in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
		at java.lang.Runtime.loadLibrary0(Runtime.java:870)
		at java.lang.System.loadLibrary(System.java:1122)
		at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
		at org.bytedeco.javacpp.Loader.load(Loader.java:777)
		at org.bytedeco.javacpp.Loader.load(Loader.java:684)
		at org.nd4j.nativeblas.Nd4jCpu.<clinit>(Nd4jCpu.java:10)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:348)
		at org.bytedeco.javacpp.Loader.load(Loader.java:739)
		at org.bytedeco.javacpp.Loader.load(Loader.java:684)
		at org.nd4j.nativeblas.Nd4jCpu$NativeOps.<clinit>(Nd4jCpu.java:63)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:264)
		at org.nd4j.nativeblas.NativeOpsHolder.<init>(NativeOpsHolder.java:29)
		... 12 more
	Caused by: java.lang.UnsatisfiedLinkError: no nd4jcpu in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
		at java.lang.Runtime.loadLibrary0(Runtime.java:870)
		at java.lang.System.loadLibrary(System.java:1122)
		at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:976)
		at org.bytedeco.javacpp.Loader.load(Loader.java:765)
		... 22 more
	
	Process finished with exit code 1

#### Version Information

* Deeplearning4j Version 0.9.1
* Platform: Windows 10
* IDE: Intellij IDEA 2017.3.2
* Java Version:
	java 9.0.1
	Java(TM) SE Runtime Environment (build 9.0.1+11)
	Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**Comment by AlexDBlack** [comment]
> I installed all via Intellij IDEA's Project structure

Does this mean you are not using a build tool, such as Maven? If so, this is not something we support (and can't/won't help you with that), for exactly this sort of reason. The projects are too complex, and there are too many transitive dependencies, for manual management of JARs.

If you are not familiar with Maven (or another suitable build tool - Gradle, for example), I'd strongly encourage you to do some reading. It's standard practice with Java, and will save you a lot of time in the long run.
This (along with some google searches) may be a good place to start: https://deeplearning4j.org/maven

I'll close this assuming you are manually managing your JAR files. If this is not the case, please post your pom.xml (or similar) and we can re-open the issue.
