### ISSUE TITLE
kafka and slicing

### ISSUE THREAD

**Issue by gedw99** [deeplearning4j/nd4j#25]
I am wondering if this module will supporting steaming of data from data producers ?

For example kaffka.

**Comment by agibsonccc** [comment]
Depends on what you mean. Could you give me an example? Are we talking about the underlying storage or something else?

**Comment by gedw99** [comment]
its best you see what kafka is on google. But its a message queue that is able to do fan in and fan out patterns, using this fan in and map out pattern is how map reduce is done. For example arrays of data are being sent into Kafka, and then you want kafka to fan out the arrays to many computation instances, and then nd4k works on them.
The opposite pattern is a fan in. This is where many computation instances are working on arrays (using nd4j) and they want to send them all into a single kafka topic.

**Comment by agibsonccc** [comment]
I'm aware of what kafka is. I've used every message queue you can think of. I was trying to figure out what you meant as far as using it to distributed workloads.
Do you know how nd4j works? I'd need to know what parts you want sharded based on kafka. Storage,computations (writing my own distributed blas impl?)

**Comment by gedw99** [comment]
i am not familiar with exactly how nd4j worrds. i worked with other nd array libraries though.

i guess i am curious about the level of CFG i can get out of nd4j. i assume that its the high level that you rely on to do the fan out and then feed a slice of data to the nd arrays, with that nd array operation NOT being paralell ?

**Comment by agibsonccc** [comment]
So we are looking at using: https://github.com/lyogavin/Pistachio/ for distributed matrix representations. More on this soon!

**Comment by agibsonccc** [comment]
Closing this, we will implement the distributed partitioning as part of a new backend.
