### ISSUE TITLE
SameDiff: Transform op gradients - don't account for auto broadcasting

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2503]
Consider the following: [3,4,5]+[3,1,5]
This is a valid broadcast add op... however, AddOp.doDiff() returns the same gradient (with shape [3,4,5]) for *both* inputs. The second input should have gradient shape [3,1,5] same as the input.

https://github.com/deeplearning4j/nd4j/blob/a0abb838187011ec77113eba919521a544472531/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/arithmetic/AddOp.java#L67-L74

This appears to be the case for: AddOp and SubOp at least.
Not sure on Mul/Div ops yet (they are failing gradient checks, however with wrong return shape...)

**Comment by AlexDBlack** [comment]
Conceptually this is simple to fix:
in the [3,4,5]+[3,1,5] case, we just want to return grad.sum(keepDim=true,1).

Mathematically, this is just the multivariable chain rule.

Q: can we implement this in Java? Simple enough to do with an if statement, but that's brittle to changing inputs...

Perhaps the most robust solution here is add "AddGradient", "SubGradient" etc ops at the C++ level that handle the 'un-broadcasting'?

**Comment by raver119** [comment]
Yes, that sounds legit. I'll file an issue, and we'll add _bp for broadcastable ops

**Comment by raver119** [comment]
https://github.com/deeplearning4j/libnd4j/issues/705

**Comment by AlexDBlack** [comment]
Implemented here: https://github.com/deeplearning4j/nd4j/pull/2550
