### ISSUE TITLE
SameDiff: Multiple Transform gradients failing

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2508]
Reproduce using:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/autodiff/gradcheck/GradCheckTransforms.java#L29

List of failing transforms:
- ~~pow~~
- ~~sigmoid~~
- ~~tanh~~
- acosh
- ~~atanh~~
- ~~square (pow)~~
- ~~logsigmoid~~
- ~~swish~~
- ~~leakyrelu~~
- logsoftmax

**Comment by raver119** [comment]
Ah, for both ACosh and ACoshDerivative native ops aren't used. Can we just use those instead?

**Comment by AlexDBlack** [comment]
Closing this for now - only logsoftmax remains from this list.
