### ISSUE TITLE
ND4J/libnd4j: maxpool2d_bp cannot handle 'weird' strides

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2517]
Reproduce using the tests here: https://github.com/deeplearning4j/nd4j/pull/2516

Seems there's some non-determinism here, with different tests failing for different runs. Note that I also saw a JVM crash on one instance.

![image](https://user-images.githubusercontent.com/2360237/34855876-458aee38-f796-11e7-97f4-deafc7890046.png)

java.lang.AssertionError: input=get4dSubArraysWithShape(12345,[1, 1, 4, 3]).get(3), eps=getAll4dTestArraysWithShape(12345,[1, 1, 4, 3]).get(0)/Nd4j.rand([1, 1, 4, 3],'c')

![image](https://user-images.githubusercontent.com/2360237/34855905-69659d6c-f796-11e7-820c-d5bdeef2eed6.png)

java.lang.AssertionError: input=get4dSubArraysWithShape(12345,[1, 1, 4, 3]).get(3), eps=getAll4dTestArraysWithShape(12345,[1, 1, 4, 3]).get(1)/Nd4j.rand([1, 1, 4, 3],'f')

```org.nd4j.linalg.exception.ND4JIllegalStateException: Op execution failed: ND4J_STATUS_BAD_OUTPUT```

**Comment by AlexDBlack** [comment]
Update: on this same test (below) I'm getting on, at different times:
- Incorrect results (most common result)
- Odd error: ```Provided output array for [maxpool2d_bp] has length of 12, but actual result has length of 0```
- JVM crash (windows only so far)

https://github.com/deeplearning4j/nd4j/blob/862f503179db4c54a4d7bad0c7cee18f580cf5cf/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/convolution/ConvolutionTestsC.java#L343

JVM crash:
https://gist.github.com/AlexDBlack/6d1181b58c220bb43b3119e94418e0a0


Note that I've checked (and double checked) the old DL4J implementation that this was sourced from - I can't see any issues...
https://github.com/deeplearning4j/deeplearning4j/blob/45db8d202b43aa80ae0d3bf2d9f80dcf69fecacb/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/layers/convolution/subsampling/SubsamplingLayer.java

**Comment by raver119** [comment]
Confirmed as fixed by @AlexDBlack
