### ISSUE TITLE
Cross op descriptor not found

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#2532]
#### Issue Description
org.nd4j.linalg.exception.ND4JIllegalStateException: No op found for cross

Graph: g_02

Seeing similar for depth_to_space
Graph: g_03

Please describe your issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Was implemented quite a while ago.
