### ISSUE TITLE
Contiguous feature detection in nd4j

### ISSUE THREAD

**Issue by rahulpalamuttam** [deeplearning4j/nd4j#254]
It would be nice to have the following feature from scipy ndimage.
Based on a 3x3 structure - we do a scan of the matrix and label all contiguous occurrences of that structure.

Here's the feature documentation in scipy
http://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.ndimage.measurements.label.html

**Comment by agibsonccc** [comment]
We're going to use opencv for this. Closing this.
