### ISSUE TITLE
SameDiff: greater/less than ops (gt/lt) fail

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2544]
Seems like other ops - gte, etc - are fine - only gt/lt are failing like this.

```
Node 1; Non-existent variable requested: [1:0]
11:52:00.727 [main] ERROR o.n.l.c.n.ops.NativeOpExecutioner - Failed to execute. Please see above message (printed out from c++) for a possible cause of error.
```

Reproduce using SameDiffTests.testPairwiseBooleanTransforms() in https://github.com/deeplearning4j/nd4j/pull/2543

Edit: I should note that looking at this in the debugger, there isn't an obvious cause (input/output arrays are all set and have correct size, for example).

**Comment by raver119** [comment]
Probably already fixed?

On current master this test passes.

**Comment by AlexDBlack** [comment]
I just ran this same test after building libnd4j/nd4j masters. I'm seeing the same failure as before.

**Comment by raver119** [comment]
mmmkay.

**Comment by raver119** [comment]
Fixed.
