### ISSUE TITLE
simple_cond graph test scalar shape comparison failure

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#2547]
#### Issue Description

See: 
Executing op: [less]
Debug info for node_1 input[0]; shape: [1, 1]; mean value: [2.000000]
Debug info for node_1 input[1]; shape: []; mean value: [2.000000]
Error at [/home/agibsonccc/code/libnd4j/include/ops/declarable/generic/boolean/less.cpp:14:0]:

Please describe your issue, along with:
- expected behavior

[1,1] and [] should be equivalent.

- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Should be fixed long ago.
