### ISSUE TITLE
DataTypeUtil.setDTypeForContext  doesn't have any effect

### ISSUE THREAD

**Issue by cpuheater** [deeplearning4j/nd4j#2561]
Setting type by invoking  DataTypeUtil.setDTypeForContext(DataBuffer.Type.DOUBLE) requires  Nd4j to be initialize first.

To reproduce run following two statements
  DataTypeUtil.setDTypeForContext(DataBuffer.Type.DOUBLE)
    Nd4j.create(1, 2).data.dataType()
after nitialization it takes an effect
  DataTypeUtil.setDTypeForContext(DataBuffer.Type.DOUBLE)
    Nd4j.create(1, 2).data.dataType()

Nd4j version 0.9.1

**Comment by raver119** [comment]
That method was deprecated. Please use Nd4j.setDataType() instead..

Also, if you have found this method somewhere on our website - please let me know.
