### ISSUE TITLE
SameDiff failing tests - testLinearModule2, testRollAxis

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2563]
Tests were added here: https://github.com/deeplearning4j/nd4j/pull/2562

**Comment by raver119** [comment]
We don't have rollAxis as native op. What're we testing then?

**Comment by raver119** [comment]
Or it's just permute in disguise?

**Comment by AlexDBlack** [comment]
Looks like rollAxis is execSpecial in Java:
https://github.com/deeplearning4j/nd4j/blob/79eb921012122cbe903aecb609cf9e960234aa3b/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/shape/RollAxis.java#L93-L102

And also incorrect...
https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.rollaxis.html

I can't find a roll_axis in TF, just numpy.

**Comment by raver119** [comment]
Closing this, since we have lots of failures and they are next stop any way.
