### ISSUE TITLE
ND4J does not init 

### ISSUE THREAD

**Issue by DaGump** [deeplearning4j/nd4j#2570]
#### Issue Description

Please describe your issue, along with:
I have two seperate applications ... one is training my YOLO Net, the other one is using it (along with other nets)
Since updating DL4J, ND4J, ...  to the actual Snapshot Version, my Software fails to start.

the CPU load is 100%, the application is stuck on initializing the networks.

Here are the ThreadDumps of both applications:
- From the learning Software:
https://gist.github.com/DaGump/8eab00069c107045d6d9e088fa1f0113
 - From the "using" Software:
https://gist.github.com/DaGump/0059889195165024e7f38c6054062528

Both seem to be stuck in the same function:
	at org.nd4j.nativeblas.Nd4jCuda$NativeOps.initializeDevicesAndFunctions(Native Method)

The different applications use different methods when it happens:
 * ModelSerializer.restoreComputationGraph
 * org.deeplearning4j.zoo.model.TinyYOLO.init

The last build of ND4J where it worked was on Jan 02, 2018. 

#### Version Information

* Deeplearning4j version: 0.9.2-SNAPSHOT build on Jan 26, 2018 at 08:00
* platform Linux Mint
* CUDA version 9.0

**Comment by saudet** [comment]
Because it takes so much time to build for CUDA, the SNAPSHOT are built for compute capability 3.0 right now. On recent GPUs, the code gets JIT compiled, but it takes about 10 minutes. How long did you try to wait?

**Comment by DaGump** [comment]
Now I have waited.... 1 hour 30 minutes.

**Comment by raver119** [comment]
O_o

**Comment by raver119** [comment]
What's your CPU and GPU model names?

**Comment by DaGump** [comment]
Graphics:  Card: NVIDIA GP106M [GeForce GTX 1060 Mobile 6GB] bus-ID: 01:00.0
           Display Server: X.Org 1.18.4 drivers: nvidia (unloaded: fbdev,vesa,nouveau)
           Resolution: 1920x1080@60.02hz
           GLX Renderer: GeForce GTX 1060/PCIe/SSE2 GLX Version: 4.5.0 NVIDIA 384.111 Direct Rendering: Yes

CPU~Quad core Intel Core i7-6700HQ (-HT-MCP-) speed/max~3033/3500 MHz Kernel~4.10.0-38-generic x86_64 Up~3:12 Mem~12340.4/15981.1MB HDD~1256.3GB(71.2% used) Procs~243 Client~Shell inxi~2.2.35

**Comment by saudet** [comment]
The code takes at least 8 GB of RAM to compile. You have at least that much free? I know @agibsonccc is also having issues with compiling CUDA code for libnd4j these days though...

**Comment by raver119** [comment]
@DaGump do you have high CPU use? Are there any signs that jit actually does something?

@saudet maybe we should bring back all-archs for snapshots? not PRs, just daily builds?

**Comment by raver119** [comment]
cc @sshepel

**Comment by DaGump** [comment]
CPU load before starting the application is very low (0,014)
RAM: before starting 12 GB unused.

**Comment by DaGump** [comment]
**Before Program execution**
`Tasks: 241 total,   1 running, 240 sleeping,   0 stopped,   0 zombie
top - 12:38:50 up 2 min,  1 user,  load average: 1,99, 1,50, 0,62
Tasks: 238 total,   1 running, 237 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,7 us,  0,3 sy,  0,0 ni, 98,8 id,  0,1 wa,  0,0 hi,  0,0 si,  0,0 st
KiB Mem : 16364620 total, 14436620 free,  1017948 used,   910052 buff/cache
KiB Swap: 16710652 total, 16710652 free,        0 used. 14982620 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                   
 2146 martin    20   0  568364  37216  28240 S   4,0  0,2   0:00.58 mate-terminal                                                                                                                                                             
 1082 root      20   0  251372  67260  50100 S   3,0  0,4   0:02.78 Xorg                                                                                                                                                                      
 1096 root     -51   0       0      0      0 S   0,7  0,0   0:01.62 irq/128-nvidia                                                                                                                                                            
 2062 martin    20   0 7109756 637496  48168 S   0,7  3,9   1:03.04 java                                                                                                                                                                      
    1 root      20   0  185488   5992   3872 S   0,0  0,0   0:01.15 systemd                                                                                                                                                                   
    2 root      20   0       0      0      0 S   0,0  0,0   0:00.00 kthreadd                                                                                                                                                                  
    3 root      20   0       0      0      0 S   0,0  0,0   0:00.00 kworker/0:0                                                                                                                                                               
    4 root       0 -20       0      0      0 S   0,0  0,0   0:00.00 kworker/0:0H                                                                                                                                                              
    5 root      20   0       0      0      0 S   0,0  0,0   0:00.00 kworker/u16:0                                                                                                                                                             
    6 root      20   0       0      0      0 S   0,0  0,0   0:00.00 ksoftirqd/0                                                                                                                                                               
    7 root      20   0       0      0      0 S   0,0  0,0   0:00.14 rcu_sched                                                                                                                                                                     8 root      20   0       0      0      0 S   0,0  0,0   0:00.00 rcu_bh  `

**During Execution**
`Tasks: 243 total,   1 running, 242 sleeping,   0 stopped,   0 zombie
%Cpu(s): 13,0 us,  0,5 sy,  0,0 ni, 86,5 id,  0,0 wa,  0,0 hi,  0,1 si,  0,0 st
KiB Mem : 16364620 total,  3762088 free, 11244184 used,  1358348 buff/cache
KiB Swap: 16710652 total, 16710652 free,        0 used.  4683532 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                                                                   
 2229 martin    20   0 29,257g 9,597g 174192 S 100,3 61,5   2:42.84 java                                                                                                                                                                      
 1082 root      20   0  253728  68376  50396 S   2,0  0,4   0:05.96 Xorg                                                                                                                                                                      
 1096 root     -51   0       0      0      0 S   2,0  0,0   0:03.68 irq/128-nvidia                                                                                                                                                            
 1747 martin    20   0  603276  34496  27752 S   0,7  0,2   0:02.64 nm-applet                                                                                                                                                                 
 2062 martin    20   0 7118724 650740  48216 S   0,7  4,0   1:15.32 java                                                                                                                                                                      
  926 root      20   0    4392   1212   1128 S   0,3  0,0   0:00.01 acpid                                                                                                                                                                     
 1666 martin    20   0 1264996  37680  26512 S   0,3  0,2   0:01.20 mate-settings-d                                                                                                                                                           
 1707 martin    20   0  481464  23576  19788 S   0,3  0,1   0:00.42 notification-ar                                                                                                                                                           
 2322 martin    20   0 1007692 157368 109820 S   0,3  1,0   0:01.55 chrome                                                                                                                                                                    
 2574 martin    20   0  442696  28028  22920 S   0,3  0,2   0:00.07 mate-notificati                                                                                                                                                           
    1 root      20   0  185488   5992   3872 S   0,0  0,0   0:01.15 systemd                                                                                                                                                                   
    2 root      20   0       0      0      0 S   0,0  0,0   0:00.00 kthreadd                                                                                                                                                                  
    3 root      20   0       0      0      0 S   0,0  0,0   0:00.00 kworker/0:0                                                                                                                                                               
    4 root       0 -20       0      0      0 S   0,0  0,0   0:00.00 kworker/0:0H            `

I do not see any "just-in-time" things happening. But That's quite new territory for me. How could I check the jit process?

**Comment by raver119** [comment]
I'm afraid here's it:
`100,3 61,5 2:42.84`

compilation goes on in 1 thread.

**Comment by DaGump** [comment]
2229 martin 20 0 28,022g 9,387g 187184 S 100,0 34,5 **21:12.32** java

and keeps going on

**Comment by saudet** [comment]
You should see `~/.nv/ComputeCache/` growing... Maybe it's corrupted and it's tripping on itself?

**Comment by DaGump** [comment]
I am sorry this will sound like a little girls diary now:

Yesterday I experimented a little with the behaviour of `~/.nv/ComputeCache/ ` directory.
On init of the network the  it shrinks from 265MB to 221MB
After 1minute it reaches 244MB and stays tat size for like forever.
I left for work, and when I came back it rached 264MB

---
Well I learned nothing so far... except for the obvious: something is working there.

---
So I decided, since it might be corrupt, I delete the entire thing ... said and done:
started up ... and nothing happend ... a "index" file was created, but nothing else for 2 min ... the the first cache dir was created (size: 77MB).
After that radio silence for 4min => another 3 cache dirs with 50MB in total were created
... I waited another 2hours but nothing more here.

---
I guess that does not help at all

**Comment by raver119** [comment]
@DaGump nono, your reports are VERY helpful. 
Now we're thinking how to tweak our CI/CD infra to get back compilation for all targets somehow, without holding back PR testing...

**Comment by DaGump** [comment]
good to know ... but in that case, a question:
Since you're focussing on compilation for all targets with that, souldn't that problem I have be solved if I compile ND4j and DL4j and the entire stack locally? Or am I mixing up stuff here?

Because I did actually always test twice:
- once 20min with the Snapshot from the Repository
- and the rest with a fresh local  build.

**Comment by saudet** [comment]
I think that's an area where separable compilation might help.. Now that I've fixed what was wrong with our CMake files for that, we should be able to start testing that as well.

**Comment by DaGump** [comment]
Everything works fine again.
THX
