### ISSUE TITLE
ae output

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#2574]
https://github.com/deeplearning4j/dl4j-test-resources/tree/d9ec58b0fec4d05d5d237f0aaa6c2820aa5334c3/src/main/resources/tf_graphs/examples/ae

In this graph, we have `output` and `output.0` in predictions. Where this come from?
There's shape [1, 1, 2] listed. And i can't understand where it comes from. It just has no sense in this graph. 

cc @eraly

**Comment by raver119** [comment]
same story with `norm_tests/norm_0`

Output only check fails, and intermediate check passes. Just due to difference between `output.0` and `output`

**Comment by eraly** [comment]
ae is fixed 
(FYI, @agibsonccc made minor changes to the ae python code)

norm_0 looks good.
However I am still seeing strange conflicting results from the output of the frozen graph and the non frozen graph with norm_4,6,7,10 and 11. 

Note that for conv_2 I found something that definitely looks like a bug/corner case in frozen graph.

**Comment by raver119** [comment]
tyvm!

**Comment by eraly** [comment]
This is fixed. Closing.
