### ISSUE TITLE
Calculating meanNumber() different result as List.stream().avarage vs. manual

### ISSUE THREAD

**Issue by frankkopp** [deeplearning4j/nd4j#2588]
When calculating the meanNUmber I have noticed that it is different from what I manually would get.
Example:

```
//  dsTrain.numExamples() = 5.000
List<Double> losses = new ArrayList<>(dsTrain.numExamples());
INDArray losses2 = Nd4j.zeros(dsTrain.numExamples());
double losses3 = 0;

for (int i=0; i<dsTrain.numExamples(); i++) {
  // do something here

  losses.add(loss);
  losses2.put(0, i, loss);
  losses3 += loss;
}

// average loss over all samples
OptionalDouble average = losses.stream().mapToDouble(a -> a).average();
LOG.debug("Overall loss 1: {}", average.isPresent() ? average.getAsDouble() : 0);
LOG.debug("Overall loss 2: {}", losses2.meanNumber());
LOG.debug("Overall loss 3: {}", losses3/dsTrain.numExamples());
```

23:30:09.865 [main] DEBUG Overall loss 1: 46.15634264221191
23:30:09.866 [main] DEBUG Overall loss 2: 46.1563**606262207**
23:30:09.866 [main] DEBUG Overall loss 3: 46.15634264221191

==> the List.average and manual average are identical. 
==> NDArray.mean Number() is always a bit higher (above +0,000017984..)

I assume rounding issue of some sort but could also be a bug - the error is rather big.
Or I'm doing something wrong.

#### Version Information

Windows 10
Java1.8.152
<nd4j.backend>nd4j-native-platform</nd4j.backend>
<nd4j.version>0.9.1</nd4j.version>
<dl4j.version>0.9.1</dl4j.version>
(no Cuda)

**Comment by AlexDBlack** [comment]
This could simply be a numerical precision issue - Float (the default) vs. Double.

Can you re-run after doing the following as the first step in your program:
Nd4j.setDataType(DataBuffer.Type.DOUBLE);

**Comment by frankkopp** [comment]
Thanks Alex - I already thought it might be a precision issue. Your tip to change the data type solved it. I did not know that FLOAT was default. As I only worked with doubles I did not expect ND4j to change that.

**Comment by AlexDBlack** [comment]
Great, I'll close this.

**Comment by agibsonccc** [comment]
@frankkopp we do this for memory reasons.
