### ISSUE TITLE
JVM Crash in 0.9.1 on CPU

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#2604]
Trying to run the following:
```
Nd4j.create(400,20).distance2(Nd4j.ones(1, 20)
```
Crashes the JVM.

[hs_err_pid3708.log](https://github.com/deeplearning4j/nd4j/files/1700260/hs_err_pid3708.log)

**Comment by raver119** [comment]
Fixed. Will be merged later.

Thanks for highlighting.
