### ISSUE TITLE
ND4J protobuf version: incompatible with hadoop-hdfs

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2612]
hadoop-hdfs 2.2.0 uses protobuf 2.5.0
ND4J uses protobuf 3.4.0

The simplest solution here is probably to shade ND4J's version, for internal use.

These appear to be incompatible. For example, when both are on the classpath:
https://gist.github.com/AlexDBlack/5dacba5af2183a233d42deba9a5af4a8

**Comment by AlexDBlack** [comment]
Looking at this again: it might not be quite so simple: we've got a whole lot of TF Java code here - https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/protobuf
This would need to be either renamed, or (ideally) we use an external hosted library (that can be shaded)...

**Comment by AlexDBlack** [comment]
Looking at this again: it might not be quite so simple - we use the protoc-jar-maven-plugin, which generates a bunch of sources in nd4j-api
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/pom.xml#L37-L79
Note that these generated sources are excluded in git: https://github.com/deeplearning4j/nd4j/blob/master/.gitignore#L261-L262

However, these generated sources reference the maven protobuf dependency directly. For example, the ```AllocatorMemoryUsed``` class:
```
public  final class AllocatorMemoryUsed extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:tensorflow.AllocatorMemoryUsed)
    AllocatorMemoryUsedOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AllocatorMemoryUsed.newBuilder() to construct.
  private AllocatorMemoryUsed(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AllocatorMemoryUsed() {
    allocatorName_ = "";
    totalBytes_ = 0L;
    peakBytes_ = 0L;
    liveBytes_ = 0L;
    allocationRecords_ = java.util.Collections.emptyList();
    allocatorBytesInUse_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AllocatorMemoryUsed(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
```


Thus, to shade our version of protobuf, we would *also* need to somehow get the ```protoc-jar-maven-plugin``` to directly use the shaded dependencies instead. Reading the notes here, I don't believe this is possible already: https://github.com/os72/protoc-jar-maven-plugin
That said that this may well be possible with (essentially) a find + replace on ```com.google.protobuf``` to say ```org.nd4j.shade.protobuf``` on the generated sources...

**Comment by saudet** [comment]
It would also cause problems for anyone trying to use/extend those
definitions from outside ND4J...
