### ISSUE TITLE
Workspace crash: CUDA

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2615]
Linux, CUDA 9, Kubuntu 17.04, GTX970 (x2)

Crash occurs every time that test is run on my system.

Reproduce using:
https://github.com/deeplearning4j/deeplearning4j/blob/46065ee814e5d9f6e6a86178db69d3d58cf4c661/deeplearning4j-core/src/test/java/org/deeplearning4j/gradientcheck/GradientCheckTestsComputationGraph.java#L755-L757

https://gist.github.com/AlexDBlack/496454947dce1a999074f28cdae056d5

**Comment by treo** [comment]
https://gist.github.com/treo/1dde7b8f4a802c171f011e5a35ad2654

Using this I can also reproduce the problem on CPU and CUDA (using a local build from today).

**Comment by AlexDBlack** [comment]
I can confirm this is reproducable on CPU too using @treo's code
Unless someone else gets to this first, I'll try to look at this later today as I'm running into it on CUDA (and the no workspace workaround is a major bottleneck for me)

**Comment by AlexDBlack** [comment]
I've made some progress on this: seems it is due to an attempt to migrate an outdated epsilon (activation gradient) array... still trying to determine why.
