### ISSUE TITLE
Import tests issues

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#2625]
There are some issues with tests framework:

- [x] `simpleif_0` - intermediate check tries to interpret boolean values as floats. fails.
- [x] `unstack` - intermediate passes, but output check fails with npe. somthing off with naming?
- [x] `simple_while` and `simple_cond` complaint about same variable `greater`. To be investigated.

**Comment by raver119** [comment]
Can't confirm fix. I still see the same exceptions.

**Comment by eraly** [comment]
Made more fixes. Other than unstack (which I can confirm is a test issue) I see all the conditionals passing. Please confirm.

**Comment by eraly** [comment]
Confirmed.
