### ISSUE TITLE
Windows - CUDA initialization blocked?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2632]
Not sure what's up here, seems to just get stuck on initializeDevicesAndFunctions...
![image](https://user-images.githubusercontent.com/2360237/36147242-91f2930a-110b-11e8-9058-9582a4f65d34.png)

CUDA test profile under windows 10. Attempting to run simple DL4J unit test. IntelliJ invalidate and restart doesn't help...

libnd4j: 4527181f7625b2312e6d631c3e48e336bf0e9262
nd4j: 90b1ef0fe7d2cf8f3081bf896e8822c9ab0faf66

**Comment by AlexDBlack** [comment]
Closing this for now - I haven't been able to reproduce this problem since... will re-open if it occurs again.

**Comment by AlexDBlack** [comment]
This has resurfaced for me... I'm seeing it again after building today.
Same exact method. Looks like Java is maxing out one single thread here with initializeDevicesAndFunctions()
![image](https://user-images.githubusercontent.com/2360237/36879847-c99ca082-1e19-11e8-96a1-9d80bc1728a1.png)

**Comment by saudet** [comment]
This happens even when building locally for your compute capability?

**Comment by AlexDBlack** [comment]
yeah, this is a fresh build today on Windows, running in IntelliJ (doesn't appear to be using sonatype snapshots as far as I can tell)

**Comment by raver119** [comment]
Hm. But i've used windows yesterday to test your issue - no problems at all, CUDA works for me as expected.

**Comment by raver119** [comment]
compilation params were the same as always: `-a native -c cuda -cc 61`

**Comment by AlexDBlack** [comment]
Right, and I've been rebuilding ND4J and DL4J every day (no ```-a native``` though) - and I'm only seeing it on occasion (not sure what the trigger is). It's been fine for me, for the last week or so (but obviously saw issues before that).

**Comment by AlexDBlack** [comment]
And after rebuilding today - it seems to be fine again... I'm inclined to keep this open until I know what's going on here and why.

**Comment by AlexDBlack** [comment]
It resurfaced today after building again in exactly the same way as before. I let it run for 2 hours without seeing any evidence of progress. Note that I've hit this on both CUDA 9.0 and 9.1 now. I'll rebuild and use CUDA 8.0 for a while, and see if it occurs there.

**Comment by wmeddie** [comment]
I also run into this 100% of the time on a V100.  Both in the SKIL version on 0.9.2 and the latest snapshots.

**Comment by DaGump** [comment]
This problem occured today to me as well .... on following machines
Windows 10 - CUDA 9.1
Linux - CUDA 9.0

**Comment by treo** [comment]
I'm running into only whenever I get a new snapshot version, it looks like Cuda decides that it should rebuild its cache.

What happens if you clean out your compute cache folders? Maybe it finds something there that forces it to recompile each time?

On windows it is in `C:\Users\%USERNAME%\AppData\Roaming\NVIDIA\ComputeCache`

**Comment by raver119** [comment]
That's still JIT compiler. Our CI/CD seems to be compiling snapshots against limited number of compute capabilities. 

cc @saudet @sshepel

**Comment by sshepel** [comment]
Latest snapshots should not have such problem, @treo please check once you will get some time.

**Comment by AlexDBlack** [comment]
OK, so what I've done:
- Delete all 0.9.2-SNAPSHOT versions from local Maven repository
- Run examples with 0.9.2-SNAPSHOT, downloaded from sonatype
- Result: I'm hitting this same blocked initialization (CUDA JIT?) issue

Second run:
- Delete contents of C:\Users\Alex\AppData\Roaming\NVIDIA\ComputeCache
- Run examples as above
- Result: same blocked initialization as before

Hardware/software:
Windows 10, CUDA 9.1 (9.1.85 with 3 updates installed), Titan X (Pascal) cc 6.1

Versions:
nd4j-api-0.9.2-20180308.223710-2605.jar
nd4j-cuda-9.1-0.9.2-20180308.223729-163.jar
nd4j-cuda-9.1-0.9.2-20180308.223729-163-windows-x86_64.jar

**Comment by saudet** [comment]
163 wasn't built for all compute capabilities (AppVeyor was still online until this morning). Please try again, and make sure you get nd4j-cuda-9.1-0.9.2-20180308.192451-160-windows-x86_64.jar  Sorry about that!

**Comment by AlexDBlack** [comment]
OK, so Windows + CUDA 8.0 - initialization is fine there...
nd4j-cuda-8.0-0.9.2-20180309.022215-782.jar
nd4j-cuda-8.0-0.9.2-20180309.022215-782-windows-x86_64.jar

I'll re-test 9.1 shortly

**Comment by saudet** [comment]
I've tested this on Linux (Fedora 27) and the JIT compiler works fine for CUDA 8 (takes less than 10 minutes), but never ends with CUDA 9.0 or 9.1. So this *is* a new problem with CUDA 9.

When not JIT compiling though, everything works fine with any version of CUDA.

**Comment by saudet** [comment]
@treo The maximum cache size is very small, that's why it recompiles on every run:
https://devblogs.nvidia.com/cuda-pro-tip-understand-fat-binaries-jit-caching/
We can increase it with the CUDA_CACHE_MAXSIZE environment variable.

**Comment by AlexDBlack** [comment]
New JARs with CUDA 9.1 - nd4j-cuda-9.1-0.9.2-20180309.022246-163 - that initializes correctly/immediately for me (again on Windows).

**Comment by treo** [comment]
Yep, it works fine for me as well now - using cuda 8.0 though.

**Comment by sshepel** [comment]
@AlexDBlack @treo how do you think, can we close this issue?

**Comment by AlexDBlack** [comment]
Yeah, I think we close this
