### ISSUE TITLE
Issue writing and reading NDArray with writeTxtString/readTxtString

### ISSUE THREAD

**Issue by frankkopp** [deeplearning4j/nd4j#2640]
#### Issue Description

Writing a "numberofrows by 1" NDArray to a file with writeTxtString and reading it with readTxtString will create a "numberofrows  by 1" NDArray filled with ZERO instead the values from the written file.

This test demonstrates it with a 4x2 array which works fine and also a 4x1 array which fails:

### Code:

    final String folderPathPlain = "./var/";
    final String testFile = folderPathPlain + "TEST_NDArrayRestore.txt";

    INDArray matrix4x2 = Nd4j.randn(4, 2, 123);
    INDArray matrix4x1 = Nd4j.randn(4, 1, 321);

    // WRITE NDArrays to txt file

    BufferedOutputStream outputStream = new BufferedOutputStream(new FileOutputStream(testFile));
    DataOutputStream dos = new DataOutputStream(outputStream);

    dos.writeBytes("[matrix4x2]" + System.lineSeparator());
    Nd4j.writeTxtString(matrix4x2, dos, 15);
    dos.writeBytes(System.lineSeparator());

    dos.writeBytes("[matrix4x1]" + System.lineSeparator());
    Nd4j.writeTxtString(matrix4x1, dos, 15);
    dos.writeBytes(System.lineSeparator());

    dos.flush();
    outputStream.close();

    LOG.debug("Matrix16x2 ORIG:\n{}\n{}", matrix4x2.shapeInfoToString(), matrix4x2);
    LOG.debug("Matrix16x1 ORIG:\n{}\n{}", matrix4x1.shapeInfoToString(), matrix4x1);

    // READ NDArrays from txt file

    INDArray read_Matrix4x2 = null;
    INDArray read_Matrix4x1 = null;

    BufferedReader inputStream = new BufferedReader(new FileReader(testFile));
    String line = "";
    while ((line = inputStream.readLine()) != null) {
      if (line.equals("[matrix4x2]")) {

        // weightMatrix
        StringBuilder sb_weightMatrix = new StringBuilder();
        while ((line = inputStream.readLine()) != null) {
          if (line.equals("[matrix4x1]")) break;
          // restore the line separator as the readLine() strips it
          sb_weightMatrix.append(line).append(System.lineSeparator());
        }
        read_Matrix4x2 = Nd4j.readTxtString(IOUtils.toInputStream(sb_weightMatrix.toString().trim()));

        // biasMatrix
        StringBuilder sb_biasMatrix = new StringBuilder();
        while ((line = inputStream.readLine()) != null) {
          // restore the line separator as the readLine() strips it
          sb_biasMatrix.append(line).append(System.lineSeparator());
        }
        read_Matrix4x1 = Nd4j.readTxtString(IOUtils.toInputStream(sb_biasMatrix.toString().trim()));
      }
      LOG.debug("Matrix16x2 READ:\n{}\n{}", read_Matrix4x2.shapeInfoToString(), read_Matrix4x2);
      LOG.debug("Matrix16x1 READ:\n{}\n{}", read_Matrix4x1.shapeInfoToString(), read_Matrix4x1);
    }
 
### The generated file looks like this:
[matrix16x2]
{
"filefrom":"dl4j",
"ordering":"c",
"shape":[4, 2],
"data":
[[2.014722824096680 ,   -0.860512375831604] ,   
 [-1.148215889930725 ,   0.466004282236099] ,   
 [-1.252894043922424 ,   0.935358524322510] ,   
 [0.668645322322845 ,   1.292527198791504]]
}

[matrix16x1]
{
"filefrom":"dl4j",
"ordering":"c",
"shape":[4, 1],
"data":
**[0.667600512504578 ,   -1.752173066139221 ,   0.105384469032288 ,   -0.607295751571655]**
}

The issue seems to be that the 4x1 array is writting as a 1x4 array but the shape info stills says 4x1
 
### The output looks like this:
21:57:10.133 [main] DEBUG f.n.n.NeuralNetworkTest - Matrix16x2 ORIG:
Rank: 2,Offset: 0
 Order: c Shape: [4,2],  stride: [2,1]
[[2.01,  -0.86],  
 [-1.15,  0.47],  
 [-1.25,  0.94],  
 [0.67,  1.29]]
21:57:10.135 [main] DEBUG f.n.n.NeuralNetworkTest - Matrix16x1 ORIG:
Rank: 2,Offset: 0
 Order: c Shape: [4,1],  stride: [1,1]
[0.67,  -1.75,  0.11,  -0.61]
21:57:10.145 [main] DEBUG f.n.n.NeuralNetworkTest - Matrix16x2 READ:
Rank: 2,Offset: 0
 Order: c Shape: [4,2],  stride: [2,1]
[[2.01,  -0.86],  
 [-1.15,  0.47],  
 [-1.25,  0.94],  
 [0.67,  1.29]]
21:57:10.146 [main] DEBUG f.n.n.NeuralNetworkTest - Matrix16x1 READ:
Rank: 2,Offset: 0
 Order: c Shape: [4,1],  stride: [1,1]
**[0.00,  0.00,  0.00,  0.00]**

The last line clearly shows that the second 4x1 array was not correctly read from file.

(Btw. I find it also irritating that a 4x1 array's toString() prints it as a line (1x4) instead of 4 lines (4x1) - maybe related?)

#### Version Information
* Deeplearning4j version
  <nd4j.version>0.9.1</nd4j.version>
* platform information (OS, etc)
Java8
Backend used: [CPU]; OS: [Windows 10]
* CUDA version, if used
N/A
* NVIDIA driver version, if in use
N/A

#### Contributing

My assumption ist that the bug is in NDArrayStrings.java line 107
`private String format(INDArray arr, int rank, int offset) {`
`...`
`        else if (arr.isVector()) {`
as the 4x1 ends there and there are NO new newlines added in this "if" statement. 
Obviously RowVectors and ColumnVectors are treated equally here which they shouldn't. 

Reading this 4x1 ColumnVector will fail as the shape info says "shape":[4, 1] but there is only one line.
It fails here: Nd4j.java line 2429:
` public static INDArray readTxtString(InputStream ndarray, String sep) {`
`...`
`    for (int i = 0; i < theShape[rank - 1]; i++) {`
As rank-1 is 1 and the shape is 4,1 it will not read any more numbers in this line. 
As the next line is "}" it stops reading.

IMHO ColumnVectors should be printed (toString()) and witten (writeTxtString) vertically not horizontaly.

WDYT?

**Comment by eraly** [comment]
Thanks!
Fixed in https://github.com/deeplearning4j/nd4j/pull/2735
