### ISSUE TITLE
Remove reflections library from ND4J

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2648]
Related:
https://github.com/deeplearning4j/deeplearning4j/issues/4504
https://github.com/deeplearning4j/deeplearning4j/issues/3899

ND4J extensively uses the reflections library, for a number of purposes. However, this causes problems:
1. **Performance**: classpath scanning can be very costly; in some cases, infeasibly so - https://github.com/deeplearning4j/deeplearning4j/issues/3899
2. **Compatability**: android can't use reflections - https://github.com/deeplearning4j/deeplearning4j/issues/4504

I'm opening this issue to plan out where and how to remove reflections.

-----
-----

Where reflections library is used:
1. **Version check**
    a. Where: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/versioncheck/VersionCheck.java
    b. Possible solution/replacement: ServiceLoader, that points to name and location of resources?
2. **Compression**
    a. Where: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/compression/BasicNDArrayCompressor.java#L38
3. **DifferentialFunctionClassHolder** (finds SameDiff DifferentialFunction instances)
    a. Where: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/imports/converters/DifferentialFunctionClassHolder.java#L120
4. **Nd4jBackend**: fallback (if ServiceLoader fails) for backend identification
    a. Where: https://github.com/deeplearning4j/nd4j/blob/de51cbe9bcb6d06c540be20ef596c5cf3665dd6a/nd4j-context/src/main/java/org/nd4j/linalg/factory/Nd4jBackend.java#L199
    b. Solution: Don't fix - should be fine *most* of the time (i.e., unless a backend can't be found). Alternatively, have this be disabled by default + log how to enable it.
5. **JacksonReflectionLoader** (not widely used - maybe Arbiter though?)
    a. Where: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-serde/nd4j-jackson-reflectionloader/src/main/java/org/nd4j/reflectionloader/JacksonReflectionLoader.java
6. **ND4J JDBC drivers** (DriverFinder)
    a. Where: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-jdbc/nd4j-jdbc-api/src/main/java/org/nd4j/jdbc/driverfinder/DriverFinder.java
    b. Solution: ServiceLoader - all JDBC 4 compliant drivers apparently use this already: https://stackoverflow.com/a/18297412
7. **TrainerProvider**
    a. Where: https://github.com/deeplearning4j/nd4j/blob/aafbd0101b1a10a0d4dae1a2671895410a1708b2/nd4j-parameter-server-parent/nd4j-parameter-server-node/src/main/java/org/nd4j/parameterserver/distributed/training/TrainerProvider.java#L42
    b. Solution: ServiceLoader mechanism
8. **ND4J tests - OpsMappingTests**
    a. Where: https://github.com/deeplearning4j/nd4j/blob/aadd8d68d105e4765eb85e56e73d3f09d28e92f3/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/nativ/OpsMappingTests.java#L126-L128
    b. Solution: Don't fix. Tests only, so performance here doesn't matter.

-----
-----

**General reflections alternatives:**
- Java ServiceLoader (fast, robust (other than badly configured uber-jars), easy to use)
- Hard-code classes - for use in ```Class.forName(String)```
    - Ugly, but *might* be "good enough" in a few cases.
- JSPF: https://code.google.com/archive/p/jspf/ (seems to rely on classpath scanning, according to docs - may have the same scalability issues as reflections library. ALso not maintained?
- OSGi (I don't know enough about this yet to comment. Might be overkill for many cases?)
- Reflections library, but with AOT scanning during build: https://github.com/ronmamo/reflections#integrating-into-your-build-lifecycle
    - Probably not suitable for most of our use cases (like: user custom functionality, uber-jars, etc)
- PF4J - https://github.com/decebals/pf4j

**Comment by agibsonccc** [comment]
@AlexDBlack thoughts for the apache folks?

**Comment by AlexDBlack** [comment]
Removing reflection library entirely is going to take a bit of work, given how extensively we use it (and, the fact that we want to maintain backward compatibility with functionality that currently relies on it.
There's not much benefit removing only a few bits and pieces - for dependency issues especially, it has to removed entirely (in ND4J, DL4J and DataVec).
It's important - but I was planning on looking at this after the release.

**Comment by cpoerschke** [comment]
Thanks for explaining! Okay, so https://github.com/deeplearning4j/deeplearning4j/pull/4662 won't be included in the release, that's totally fine.

**Comment by AlexDBlack** [comment]
Partially fixed here: https://github.com/deeplearning4j/nd4j/pull/2846

Only items 1 and 3 left (plus 8, but that's trivial to fix once the others are done).
