### ISSUE TITLE
Allow x *or* y to be the larger array in distance calculations

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#2656]
#### Issue Description
Right now, we only allow the first array. This won't work for all distance metrics though.
We should allow for any array to be  the "first" array in an x - y setting.
In my most recent commit on my PR, I added the ability to "search" for the max shape based on comparing the x or y, it would be good if our internals reflected this behavior.

Please describe your issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
As far as i remember, this was implemented.
