### ISSUE TITLE
putSlice(0,y) puts slice on slice(1) not slice(0)

### ISSUE THREAD

**Issue by supergitacc** [deeplearning4j/nd4j#2674]
The reported issue can be reproduced with the following lines of code and is appeared in DL4J Examples (nd4j 0.9.1)

```
INDArray x = Nd4j.ones(2,3,3);
INDArray y = Nd4j.zeros(3,3);
x.putSlice(0, y);
System.out.println("x: "+x);
System.out.println("x slice 0: "+x.slice(0));
```
 **Output:** 
> x: [[[0.00,  0.00,  0.00],  
>   [0.00,  0.00,  0.00],  
>   [0.00,  0.00,  0.00]],  
> 
>  [[1.00,  1.00,  1.00],  
>   [1.00,  1.00,  1.00],  
>   [1.00,  1.00,  1.00]]]
> x slice 0: **[[0.00,  0.00,  0.00],  
>  [0.00,  0.00,  0.00],  
>  [0.00,  0.00,  0.00]]**

In my opinion, x.slice(0) should be the matrix with ones. If x is of the size (1,3,3) then put.slice(0,y) does nothing and there is also no error message which makes this bug hard to find.

Quick Fix:
```
for (int s = 0; s < numInputFeaturesIntoLSTM; s++) {
            	for (int t = 0; t < maxLengthTimeSeries; t++) {
            		input.putScalar(new int[]{i,s,t}, currTrainingExample.getDouble(s, t));
            	}
}
```

Thanks in advance.

**Comment by agibsonccc** [comment]
@supergitacc can you try this with http://deeplearning4j.org/snapshots and see if this is still a problem?

**Comment by supergitacc** [comment]
@agibsonccc I tried it and it is the same behavior / bug in the current version

**Comment by agibsonccc** [comment]
Thanks! Let me take a closer look.

**Comment by eraly** [comment]
This is fixed in current master. Closing.
