### ISSUE TITLE
new (undefined) symbols in jnind4jcpu not implemented in embedded libnd4j.a on ios

### ISSUE THREAD

**Issue by johanvos** [deeplearning4j/nd4j#2679]
With the latest 0.9.2-SNAPSHOTS, it seems there are 3 new reshape functions being called by jnind4jcpu.o that are not defined in the embedded libnd4j.a:

[SUB]   "nd4j::NDArray<float>::reshape(std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
[SUB]       _Java_org_nd4j_nativeblas_Nd4jCpu_00024FloatNDArray_reshape___3I in jnind4jcpu.o
[SUB]       _Java_org_nd4j_nativeblas_Nd4jCpu_00024FloatNDArray_reshape__Ljava_nio_IntBuffer_2 in jnind4jcpu.o
[SUB]       _Java_org_nd4j_nativeblas_Nd4jCpu_00024FloatNDArray_reshape__Lorg_bytedeco_javacpp_IntPointer_2 in jnind4jcpu.o
[SUB]   "nd4j::NDArray<float16>::reshape(std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
[SUB]       _Java_org_nd4j_nativeblas_Nd4jCpu_00024HalfNDArray_reshape___3I in jnind4jcpu.o
[SUB]       _Java_org_nd4j_nativeblas_Nd4jCpu_00024HalfNDArray_reshape__Ljava_nio_IntBuffer_2 in jnind4jcpu.o
[SUB]       _Java_org_nd4j_nativeblas_Nd4jCpu_00024HalfNDArray_reshape__Lorg_bytedeco_javacpp_IntPointer_2 in jnind4jcpu.o
[SUB]   "nd4j::NDArray<double>::reshape(std::__1::vector<int, std::__1::allocator<int> > const&)", referenced from:
[SUB]       _Java_org_nd4j_nativeblas_Nd4jCpu_00024DoubleNDArray_reshape___3I in jnind4jcpu.o
[SUB]       _Java_org_nd4j_nativeblas_Nd4jCpu_00024DoubleNDArray_reshape__Ljava_nio_IntBuffer_2 in jnind4jcpu.o
[SUB]       _Java_org_nd4j_nativeblas_Nd4jCpu_00024DoubleNDArray_reshape__Lorg_bytedeco_javacpp_IntPointer_2 in jnind4jcpu.o
[SUB] ld: symbol(s) not found for architecture x86_64

**Comment by saudet** [comment]
Yes, https://github.com/deeplearning4j/libnd4j/pull/802 should fix this.

**Comment by johanvos** [comment]
ah indeed. Great, thanks!

**Comment by johanvos** [comment]
I can confirm this is fixed.
