### ISSUE TITLE
Add support for frozen output layer

### ISSUE THREAD

**Issue by ionspin** [deeplearning4j/nd4j#2706]
#### Issue Description

As discussed on gitter, currently frozen layers don't support output layers. If a frozen layer wraps an output layer an exception is thrown.
```
if (insideLayer instanceof OutputLayer) {
            throw new IllegalArgumentException("Output Layers are not allowed to be frozen " + layerId());
        }
```

#### Version Information

* Deeplearning4j 0.9.2-SNAPSHOT

#### Contributing

I'd like to help out with this issue, but would definitely need some guidance

**Comment by AlexDBlack** [comment]
Closing this - moved to DL4J repo instead of ND4J: https://github.com/deeplearning4j/deeplearning4j/issues/4760
