### ISSUE TITLE
relu derivative is returning ones

### ISSUE THREAD

**Issue by aurelienwaite** [deeplearning4j/nd4j#271]
Scala console reproduction

scala> import org.nd4j.linalg.factory.Nd4j
import org.nd4j.linalg.factory.Nd4j

scala> val vector = Nd4j.create(Array(1.3f, 0.0f, 0.0f,100f))
vector: org.nd4j.linalg.api.ndarray.INDArray = [ 1.30, 0.00, 0.00, 100.00]

scala> Nd4j.getExecutioner().execAndReturn(Nd4j.getOpFactory().createTransform("relu", vector).derivative())
res2: org.nd4j.linalg.api.ndarray.INDArray = [ 1.00, 1.00, 1.00, 1.00]

I'm pretty sure the derivative at 0 is not equal to 1! Looks like the issue is that org.nd4j.linalg.api.ops.impl.transforms.RectifedLinear is inheriting the derivative function from BaseTransformOp, which is just returning ones.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/commit/1ce24f73be229a94832023e0f05743698fcfb3f7
