### ISSUE TITLE
Is there an API like np.maximum

### ISSUE THREAD

**Issue by blackredscarf** [deeplearning4j/nd4j#2711]
I  need implement a prewhiten operation on java use nd4j.
Is there an API like np.maximum ?

prewhiten python code:
```python
def prewhiten(x):
    mean = np.mean(x)
    std = np.std(x)
    std_adj = np.maximum(std, 1.0/np.sqrt(x.size))
    y = np.multiply(np.subtract(x, mean), 1/std_adj)
    return y  
```

**Comment by AlexDBlack** [comment]
Yes - you can use Transforms.max(INDArray, INDArray)
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/ops/transforms/Transforms.java#L814-L821
