### ISSUE TITLE
CUDA runtime (ptx) compliation - detect when occuring, log message

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2715]
With current snapshots, we apparently aren't building for all architectures. For other architectures, a compilation step is required. This can take a considerable amount of time (10+ minutes?).

Currently, this provides zero feedback to the user when this is occuring - it just looks like ND4J has frozen during initialization, which provides a very poor user experience.

**Comment by raver119** [comment]
Isn't this issue resolved now?

**Comment by AlexDBlack** [comment]
Yeah, turns out it was related to snapshots only, shouldn't come up with releases or when building locally from source... I guess we can close this.
