### ISSUE TITLE
libnd4j/c++ error propagation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2774]
Goal: ensure errors at the libnd4j level are always propagated to ND4J exceptions. This doesn't seem to always be the case here.

From: https://github.com/deeplearning4j/deeplearning4j/issues/4818#issuecomment-374881402

> Error at [C:/DL4J/Git/libnd4j/include/ops/declarable/generic/convo/deconv2d.cpp:243:0]:
CUSTOM DECONV2D_BP OP: wrong shape of gradient_output (next epsilon) array !

> This error isn't actually propagated up to the ND4J level. The error occurs, gets logged from C++, and java execution continues on its merry way as if nothing is wrong. I'd much prefer to have an actual java exception occur as a result.

@maxpumperla 
> I find this discussion to be fairly important. A lot, if not most of the difficulty in debugging new SameDiff ops, for instance, come from this too.

@raver119 
> technically we have everything we need to propagate errors from libnd4j to nd4j
and we actually do that. just in simplified way - number of error codes used is limited. but obviously can be extended any time

**Comment by saudet** [comment]
BTW, if we're OK with using C++ exceptions, JavaCPP can take care of propagating that to Java exceptions automatically, but @raver119 has reservations...

**Comment by raver119** [comment]
Oh man, you're my hero! we are more then ok with exceptions! If you're ok with them - we'll switch immediately

**Comment by saudet** [comment]
Please go ahead! By default it will assume that you're throwing `std::exception`, or some subclass, and convert that to `java.lang.RuntimeException` along with the message, but if you need something different or more sophisticated, let me know.

**Comment by saudet** [comment]
I've confirmed that C++ exceptions are propagated well on Linux and Windows, but on Mac they don't appear to work across static libstdc++ libraries. I'll be updating the builds to bundle the dynamic version of `libstdc++.6.dylib` on Mac, I think...

**Comment by raver119** [comment]
Initial PR merged few days ago.
