### ISSUE TITLE
Gemm log spam + (MKL?) gemm crash

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2775]
Here's a simple DL4J gradient check (I'm still trying to isolate) that produces both issues...
https://gist.github.com/AlexDBlack/e719ee368ae705055debd2a5e95296fa

I'm not sure yet if this is limited to deconv2d or not.
Edit: possibly related - https://github.com/deeplearning4j/deeplearning4j/issues/4818

Edit 2: I'm not seeing the "Matrix A was recreated from view" message *or* crashes on any of the "normal" CNN gradient checks - oly deconv2d and separableConv2d (message + crashes on both, at least if I remove the check so it runs all tests).

Output:
```
o.n.n.NativeOpsHolder - Number of threads used for NativeOps: 8
o.n.n.Nd4jBlas - Number of threads used for BLAS: 8
o.n.l.a.o.e.DefaultOpExecutioner - Backend used: [CPU]; OS: [Windows 10]
o.n.l.a.o.e.DefaultOpExecutioner - Cores: [16]; Memory: [7.1GB];
o.n.l.a.o.e.DefaultOpExecutioner - Blas vendor: [MKL]
o.d.n.m.MultiLayerNetwork - Starting MultiLayerNetwork with WorkspaceModes set to [training: SEPARATE; inference: SEPARATE]
o.d.g.GradientCheckUtil - Setting softmax clipping epsilon to 0.0 for class org.nd4j.linalg.lossfunctions.impl.LossMCXENT loss function to avoid spurious gradient check failures
Matrix A was recreated from view.
Matrix A was recreated from view.
Matrix A was recreated from view.
Matrix A was recreated from view.
Matrix A was recreated from view.
Matrix A was recreated from view.
Matrix A was recreated from view.
Matrix A was recreated from view.
Matrix A was recreated from view.
Matrix A was recreated from view.
o.d.g.GradientCheckUtil - Setting softmax clipping epsilon to 0.0 for class org.nd4j.linalg.lossfunctions.impl.LossMCXENT loss function to avoid spurious gradient check failures
Matrix A was recreated from view.

Intel MKL ERROR: Parameter 11 was incorrect on entry to cblas_dgemm.
Matrix A was recreated from view.

Intel MKL ERROR: Parameter 11 was incorrect on entry to cblas_dgemm.
Matrix A was recreated from view.
Matrix A was recreated from view.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe7ee263a5, pid=12508, tid=0x000000000000093c
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [mkl_avx2.dll+0x3463a5]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\DL4J\Git\deeplearning4j\deeplearning4j-core\hs_err_pid12508.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Crash log:
https://gist.github.com/AlexDBlack/a763dd3abc26506497325f888ddcb251

**Comment by raver119** [comment]
that’s clearly problem caused by recent mmulhelper change related to views duplication

**Comment by raver119** [comment]
p.s. at libnd4j all tests were passing fine

**Comment by AlexDBlack** [comment]
I don't think this is ND4J mmul/gemm related: the following test executes without issue for me:
https://github.com/deeplearning4j/nd4j/blob/46b66214b15d4d1307999b2b9824d6de6e1a275d/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsComparisonC.java#L79-L143

As does an updated/expanded one that does a whole lot of gemm ops of different sizes/layouts/views (125k so far without issue)
https://gist.github.com/AlexDBlack/80e3472067b31bae56e14c79c188ce2a

**Comment by AlexDBlack** [comment]
Note that @shyrma has a branch with deconv2d fixes - it might be worthwhile checking again on that branch before digging into this too much?
https://github.com/deeplearning4j/deeplearning4j/issues/4818#issuecomment-375265447

**Comment by AlexDBlack** [comment]
Note log spam should be fixed here: https://github.com/deeplearning4j/libnd4j/pull/831
Won't impact the underlying gemm crash, however.

**Comment by raver119** [comment]
Gemm crash is caused by wrong use of transA/transB and correposning shapes. Basically internal gemm works ok (presumably), but logic doesn't matches regular BLAS libs.

**Comment by raver119** [comment]
As far as I understand, @AlexDBlack confirmed this issue as fixed.
