### ISSUE TITLE
Very slow cuBLAS

### ISSUE THREAD

**Issue by nfrik** [deeplearning4j/nd4j#2776]
For my project I need to run LU decomposition repeatedly as fast as possible to solve system of linear equations. I noticed extremely slow computation of LU decomposition with ND4j's Cuda Blas. I.e. for 1000x1000 matrix it takes 65 times more time for ND4j to compute LU factorization compared to Jblas.

Below is the code I wrote to compare LU decomposition of CPU Jblas and CUDA ND4J. This code was executed on under Ubuntu Xenial, with two 1080Ti cards. 

Is there any better way to improve the speed of Blas? 

```
        //Create random matrix in JBlas format
        int n=1000;
        FloatMatrix jmat = FloatMatrix.randn(n,n);
        float mat[][] = jmat.toArray2();

        //Pivot vector
        int piv[] = new int[n];

        //Initialize Nd4j matrix with previously created FloatMatrix
        INDArray arr = Nd4j.create(mat,'c');
        INDArray circuitPermute = 
        Nd4j.createArrayFromShapeBuffer(Nd4j.getDataBufferFactory().createInt((long)n), 
        Nd4j.getShapeInfoProvider().createShapeInformation(new int[]{1, n}));
        
        //Initialize lapack handler
        lapack = new JcublasLapack();
        
        //Compute processing time for ND4J Cuda 
        long starttime = System.nanoTime();
        lapack.sgetrf(n, n, arr, circuitPermute, INFO);
        System.out.println("Cuda completed: "+(System.nanoTime()-starttime));

        //Compute processing time for JBlas 
        starttime = System.nanoTime();
        boolean jblasres= lu(jmat,piv);
        System.out.println("Jblas completed: "+(System.nanoTime()-starttime));
```
The output time:
```
Cuda completed: 8329286925 nanoseconds
Jblas completed: 132113117 nanoseconds
```

**Comment by raver119** [comment]
Do you have some profiler screenshots for us?

**Comment by raver119** [comment]
p.s. as i remember, that's cuBLAS should be used there underneath.

**Comment by nfrik** [comment]
Yes you are right, this is BLAS.
Here is the image I have if I understood you correct.
![image](https://user-images.githubusercontent.com/1614059/37796286-4b4b5adc-2ded-11e8-85b0-907345608997.png)

**Comment by raver119** [comment]
No, that's not what i'm asking for. Show me JVM profiler screenshot. I.e. JVisualVM or YourKit profiler. I need to see what exactly takes time on your end.

**Comment by nfrik** [comment]
Ok, I ran it in loop and here is what I've got:
![image](https://user-images.githubusercontent.com/1614059/37797746-13d26e66-2df1-11e8-80e3-d91e0578b5d5.png)

**Comment by raver119** [comment]
I'm sorry,  but everything you have on screenshot is irrelevant - it's ALL background threads :)
Some of those are ours, others are JVM system threads... :)

**Comment by nfrik** [comment]
Sorry, haven't used yourkit that much :) How does this look?

![image](https://user-images.githubusercontent.com/1614059/37798497-4b28838a-2df3-11e8-9205-9246d26b6fe5.png)

**Comment by raver119** [comment]
That's exactly what i need. According to your screenshot all the time spent is spent on printing out NDArrays :)

Get rid of print calls within your timed loop, or make screenshot that you're actually trying to time.

**Comment by nfrik** [comment]
Ok thanks! Is there a way to control logging level then? I don't explicitly print arrays but at the end of the call JcublasLapack.sgetrf prints out whole array with log.info("A: {}", A); I tried to set log level manually JCublas.setLogLevel(LogLevel.LOG_QUIET) without success.

**Comment by raver119** [comment]
Ouch. That definitely a bug. Fixed that in my branch will merge later today.

Thanks for highlighting this one.

**Comment by raver119** [comment]
Should have been fixed month ago.
