### ISSUE TITLE
CompareAndSet ignoring eps when used with an Eps-Condition

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#2780]
I've been using `BooleanIndexing.replaceWhere(postOutput, Nd4j.EPS_THRESHOLD, Conditions.epsEquals(0))` to set close to zero values to Nd4j.EPS_THRESHOLD.

As I was still running into numerical stability issues, I've taken a closer look, and found that it uses the CompareAndSet op under the hood, which is passed the condition. Yet, it doesn't actually set an eps value, so the comparison is executed to be exact.

As a workaround I'm now using CompareAndSet directly, where I can easily pass an eps value, but I think the original problem still needs a solution.

**Comment by raver119** [comment]
great catch!

**Comment by raver119** [comment]
Fixed in my branch, will be merged a bit later today.

**Comment by raver119** [comment]
p.s. https://github.com/deeplearning4j/nd4j/blob/008bb68384b20e5375e98e9c596c0cc1bd0eadf2/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/indexing/BooleanIndexingTest.java#L582
