### ISSUE TITLE
nd4j native tests - general pass

### ISSUE THREAD

**Issue by eraly** [deeplearning4j/nd4j#2800]
Excluding the TF import tests:

- [X]  ~HierarchicSoftmaxTests  Errors: 0 Failures: 4~
- [X]  ~ConvolutionTests  Errors: 0 Failures: 4~
- [ ]  LoneTest  Failures: 3
- [X]  ~DataSetTest  Errors: 0 Failures: 2~
- [ ]    DerivativeTests Failures: 4
- [ ]    Nd4jTestsC, testSoftmaxDerivativeGradient fails
- [ ]   ReshapeTests.testColumnVectorReshape index out of bounds on getDouble
- [ ]   StackAggregatorTests.testScalarAggregator fails
- [X]  ~TestNDArrayCreation  Errors: 0 Failures: 1~
- [X]  ~PreProcessor3D4DTest  Errors: 0 Failures: 1~
- [X]  ~OpsMappingTests  Errors: 0 Failures: 1~
- [X]  ~NormalizerStandardizeTest  Errors: 0 Failures: 1~
- [X]  ~MultiDataSetTest  Errors: 0 Failures: 1~
- [ ]   GradCheckMisc  Failures: 7
- [X]  ~ConvolutionTestsC  Errors: 0 Failures: 1~
- [X]  ~ByteOrderTests  Errors: 0 Failures: 1~
- [X]  ~TwoPointApproximationTest  Errors: 1 Failures: 0~
- [X]  ~TestRandomProjection  Errors: 6 Failures: 0~
- [X]  ~SpecialTests  Errors: 1 Failures: 0~
- [ ]  SparseTests*
- [ ]  SameDiffTests  15 failures and 3 crash
- [ ]  SameDiffOpExecutionerTest 
- [ ]  OnnxImportTest  Errors: 1 Failures: 0
- [ ]  OnnxGraphMapperTests  Errors: 1 
- [X]  ~LossFunctionGradientChecks  Errors: 1 Failures: 0~
- [X]  ~GraphExecutionerTest  Errors: 2 Failures: 0~
- [ ]  GradCheckTransforms  
- [ ]  GradCheckReductions 
- [ ]  GradCheckLoss  
- [ ]  ExecutionTests  
- [X]  ~CustomOpsTests  Errors: 1 Failures: 0~
- [X]  ~CompressionSerDeTests  Errors: 2 Failures: 0~
- [X]  ~CompressionMagicTests  Errors: 2 Failures: 0~
- [X]  ~BooleanIndexingTest  Errors: 2 Failures: 0~

**Comment by raver119** [comment]
Please note: SparseTests* require MKL to be installed.

**Comment by eraly** [comment]
Running on libnd4j and nd4j r119_more_fixes branches

**Comment by saudet** [comment]
@sshepel Script commands to download MKL from Intel and install it unattended for all platforms:   https://github.com/bytedeco/javacpp-presets/tree/master/ci
