### ISSUE TITLE
Cuda memory allocation failure

### ISSUE THREAD

**Issue by jef5ez** [deeplearning4j/nd4j#2801]
#### Issue Description
With the ultimate goal of trying to upgrade to cuda 9.1 I have been playing with the dl4j-benchmark project trying to get the latest snapshots working.

A few of the changes were explicitly putting in dependencies and removing some NN config calls that seem to have been removed.
https://github.com/jef5ez/dl4j-benchmark/tree/f_new_snapshots

I have also confirmed that the 0.9.1 release works fine with dl4j-examples and cuda 8.0 on my machine. I was also able to run dl4j-benchmark with just cpu.

Here is a gist of the full error log.
https://gist.github.com/jef5ez/442132d4fa4133078c32100f59292ad7

My gpu is a GTX 750Ti with about 2GB of mem so al allocating 25MB should be no problem.

#### Version Information

since this was a snapshot version I am not completely sure what commit it was from but the newest looking jar in my .m2 repository is from around this time nd4j-native-0.9.2-20180329.190956-2920-linux-x86_64.jar

* Deeplearning4j version: 0.9.2-SNAPSHOT
* platform information (OS, etc): Ubuntu 16.04, x84_64
* CUDA version: 8.0
* NVIDIA driver version: 384.111 

#### Contributing

Would be glad to help get this working as soon as possible.

**Comment by raver119** [comment]
Suppressed: java.lang.RuntimeException: Failed to allocate 1283331072 bytes from DEVICE [0] memory

That's 1.28GB of VRAM. On top of regular 500MB taken by cuBLAS + video driver. On top of something allocated for DataSetIterator.

Also, your output log isn't complete. Please post full log.

**Comment by jef5ez** [comment]
Ah that's what I get for not reading closely. I reduced the batch size to 4 from 128 and it is able to run longer.
I still have an NPE that looks to be due to dropout. https://gist.github.com/jef5ez/e9b7336e1f4ba7c46884ec3af7c46537
but I will close this issue since it seems unrelated.

**Comment by raver119** [comment]
This NPE looks to be related to API changes we made in 0.9.2

**Comment by raver119** [comment]
cc @crockpotveggies

**Comment by crockpotveggies** [comment]
Yes benchmarks will need to be updated. I'm waiting to do this until we release v1.0 which will be coming soon.

**Comment by jef5ez** [comment]
Here is another strange thing. If I try and benchmark SimpleCNN which is smaller than AlexNet I am back to getting mem allocation failures.
i.e. `java -cp dl4j-core-benchmark/dl4j-core-benchmark.jar org.deeplearning4j.benchmarks.BenchmarkCnn -batch 4 -model SIMPLECNN`
gives me
https://gist.github.com/jef5ez/079aca715be6c64815ff1d1adf69b32f

**Comment by jef5ez** [comment]
Removing AdaDelta seems to decrease the memory enough to run something, but then gets another similar NPE. RmsProp was also no good. This model is so small it seems like there is something wrong with the updaters in general.

**Comment by raver119** [comment]
It should be safe enough to try with current master :)
