### ISSUE TITLE
Need more APP_ABI support for the use on Android

### ISSUE THREAD

**Issue by javaddict** [deeplearning4j/nd4j#2816]
When I use
```
implementation ('org.nd4j:nd4j-native-platform:0.9.1') {
    exclude group: 'com.github.stephenc.findbugs', module: 'findbugs-annotations'
}
annotationProcessor 'org.projectlombok:lombok:1.16.16'
```
to include `Nd4j` in my Android project, I found the `jniLibs` in the downloaded `.aar` only have one directory `armeabi`.

This will cause problems when there are also other libraries in my project using native code. If they provide other architecture, such as `armeabi-v7a` (they usually do), the final apk will have merged `jniLibs`:
```
jniLibs/
    armeabi/
        ... native library for Nd4j ...
    armeabi-v7a/
        ... native library for other libraries ...
```
And when the app is executed, the system selects a most closed architecture, which usually be `armeabi-v7a`, resulting a `java.lang.UnsatisfiedLinkError` error as it can not find `Nd4j` stuff in the `armeabi-v7a` directory.

This can be solved If `Nd4j` can also provide native libraries for other mainstream architectures in the `.aar`. (I am not an Android `NDK` expert but a quick fix seems to be adding `armeabi-v7a`, `arm64-v8a`, etc. into the [`APP_ABI`](https://developer.android.com/ndk/guides/application_mk.html) list.)

**Comment by saudet** [comment]
We've already switched from `armeabi` to `armeabi-v7a`. Try it out with 0.9.2-SNAPSHOT!

**Comment by saudet** [comment]
FYI, version `1.0.0-alpha` has been released. Please give it a try!

**Comment by polaroidkidd** [comment]
I have been trying to quite some time to use the alpha release but I keep on getting dexMergeErrors. (Android). Where could I try the armeabi-v7a-SNAPSHOT ? I can only see the 0.9.1 and 1.0.0-alpha variants the repository.

**Comment by saudet** [comment]
There's a few issues with 1.0.0-alpha, which have since been fixed. See https://github.com/deeplearning4j/deeplearning4j/issues/4330 for details.

**Comment by saudet** [comment]
Please upgrade to 1.0.0-beta, it's known to work on Android!

**Comment by polaroidkidd** [comment]
I've got it running with the snapshots in the end.
