### ISSUE TITLE
NDArray slicing produces IllegalArgumentException with valid code.

### ISSUE THREAD

**Issue by drlebedev** [deeplearning4j/nd4j#282]
This code produces IllegalArgumentException:

```{java}
Nd4j.zeros(1,10,100).slice(11,2).assign(Nd4j.ones(1,10))
```

Shapes are completely correct, but assigment just does not work. It leads  to exception in https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/recurrent/GravesLSTM.java#L387

jfyi @AlexDBlack

**Comment by agibsonccc** [comment]
Thanks will look in to this.

**Comment by drlebedev** [comment]
@agibsonccc Faced the same issue with
```{java}
Nd4j.zeros(1,2,3).slice(2,2).toString()
```

**Comment by agibsonccc** [comment]
@drlebedev Use tensorAlongDimension instead.
