### ISSUE TITLE
ViewIterator strange behavior

### ISSUE THREAD

**Issue by ospavel** [deeplearning4j/nd4j#2820]
ViewIterator has strange behavior - it iterates on next() more times than should
nd4j 0.9.1
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/ViewIterator.java

Code:
```
public DataSet next() {
        //only loop to the end
        if (cursor + batch() > numExamples())
            cursor = cursor() + batch() - numExamples();
        DataSet next = (DataSet) data.getRange(cursor, cursor + batch());
        if (preProcessor != null)
            preProcessor.preProcess(next);
        cursor += batch();
        return next;
}
```
If cursor + batch() > numExamples() at the end then cursor jumps to low value (omitted last and first values), not to the end and hasNext() still true.

**Comment by AlexDBlack** [comment]
Yeah, that looks wrong to me. Thanks for reporting.
