### ISSUE TITLE
Add Nd4j.meshgrid convenience method

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2824]
We have the op at the libnd4j level, but not accessible at the Java level.

It would be nice to have an ND4J equivalent of np.meshgrid
https://docs.scipy.org/doc/numpy/reference/generated/numpy.meshgrid.html
https://www.tensorflow.org/api_docs/python/tf/meshgrid

In the mean time, here's a way to access the libnd4j (c++) op in 1.0.0-alpha:

```
        INDArray input1 = Nd4j.linspace(0, 1, 4);
        INDArray input2 = Nd4j.linspace(0, 1, 5);
        INDArray output1 = Nd4j.create(5,4);
        INDArray output2 = Nd4j.create(5, 4);

        CustomOp op = DynamicCustomOp.builder("meshgrid")
            .addInputs(input1, input2)
            .addOutputs(output1, output2)
            .build();
        Nd4j.getExecutioner().exec(op);

        System.out.println(output1 + "\n\n" + output2);
```

**Comment by saudet** [comment]
Aah, but it is accessible, sort of, as the `float_meshgrid` class:
https://raw.githubusercontent.com/deeplearning4j/nd4j/master/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/org/nd4j/nativeblas/Nd4jCpu.java

**Comment by AlexDBlack** [comment]
Also select:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/controlflow/Select.java
https://github.com/deeplearning4j/libnd4j/blob/5dea2d228c61cdec7535d1c0c6aa093a15fef9fa/include/ops/declarable/generic/boolean/select.cpp#L10-L13
