### ISSUE TITLE
NDArrayUtil implementation to convert matrices is wrong

### ISSUE THREAD

**Issue by HDouss** [deeplearning4j/nd4j#2831]
#### Issue Description

`NDArrayUtil.toNDArray(int[][] nums)` implementation is wrong and give bad dimensions. The only place where this methos is called in deeplearning4j, datavec and nd4j is in `ImageLoader.asMatrix` method. To reproduce an issue, run `MnistImagePipelineExample` with these modifications before initializing the record reader:
```java
Configuration conf = new Configuration();
conf.setBoolean(RecordReader.APPEND_LABEL, true);
conf.set("org.datavec.api.records.reader.RecordReader.imageloader", "imageio");
recordReader.initialize(conf ,train);
```
The images read will have bad shapes.

#### Version Information

* version: master branch

**Comment by saudet** [comment]
Thanks for the fix!
