### ISSUE TITLE
Missing dependencies for nd4j-native-platform

### ISSUE THREAD

**Issue by klevis** [deeplearning4j/nd4j#2847]
#### Issue Description
Below dependency is failing to find some jars
```
 <repository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>daily</updatePolicy>
            </snapshots>
        </repository>
    <deeplearning4j>0.9.2-SNAPSHOT</deeplearning4j>
    <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>${deeplearning4j}</version>
        </dependency>
```

> Could not resolve dependencies for project  The following artifacts could not be resolved: org.nd4j:nd4j-native:jar:android-arm:0.9.2-SNAPSHOT, org.nd4j:nd4j-native:jar:android-arm64:0.9.2-SNAPSHOT, org.nd4j:nd4j-native:jar:android-x86:0.9.2-SNAPSHOT, org.nd4j:nd4j-native:jar:android-x86_64:0.9.2-SNAPSHOT, org.nd4j:nd4j-native:jar:ios-arm64:0.9.2-SNAPSHOT, org.nd4j:nd4j-native:jar:windows-x86_64:0.9.2-SNAPSHOT, org.nd4j:nd4j-native:jar:linux-ppc64le:0.9.2-SNAPSHOT: Failure to find org.nd4j:nd4j-native:jar:android-arm:0.9.2-SNAPSHOT

Looking at the maven repository https://oss.sonatype.org/content/repositories/snapshots/org/nd4j/nd4j-native-platform/0.9.2-SNAPSHOT/ those dependencies are indeed missing...

**Comment by AlexDBlack** [comment]
0.9.2-SNAPSHOT is obsolete.
The last release was 1.0.0-alpha - use that instead (it's what 0.9.2-SNAPSHOT became).

If you *really* need snapshots (you very likely don't) you can use 1.0.0-SNAPSHOT.
