### ISSUE TITLE
InitializeError caused by Nd4jBackendException

### ISSUE THREAD

**Issue by SuchtyTV** [deeplearning4j/nd4j#2848]
#### Issue Description

Hey the following code throws an exception:

```
public static void main(String[] args) throws Exception {
	  NeuralNetConfiguration config = new NeuralNetConfiguration.Builder()
			  .seed(123)
			  .optimizationAlgo(OptimizationAlgorithm.STOCHASTIC_GRADIENT_DESCENT)
	  		  .updater(Updater.NESTEROVS)
	  		  .layer(new ConvolutionLayer.Builder()
	  				  .nIn(1)
	  				  .nOut(1)
	  				  .build()
	  				  )
	  		  .layer(new OutputLayer.Builder()
	  				  .nIn(1)
	  				  .nOut(1)
	  				  .build()
	  				  )
	  		  .build();
	  		  
	  		  
	  		  
	  		 
	  		  			
	  System.out.println("Done");
  }
}
```

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at neuralnetwork.NeuralNetwork.main(NeuralNetwork.java:14)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6230)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:207)
	... 1 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:259)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6227)
	... 2 more

#### Version Information

Please indicate relevant versions, including, if relevant:

* deeplearning4j-core: 1.0.0-alpha
* Windows 10 
* nd4j-cuda-8.0: 1.0.0-alpha
* Cuda 8

#### Contributing

I installed the MKL automatically with Installer version...

```
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>suchtytv.complexservice</groupId>
  <artifactId>neuralnetwork</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>org.deeplearning4j</groupId>
      <artifactId>deeplearning4j-core</artifactId>
      <version>0.7.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>org.nd4j</groupId>
      <artifactId>nd4j-cuda-8.0</artifactId>
      <version>0.7.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <releases>
        <updatePolicy>never</updatePolicy>
      </releases>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>Central Repository</name>
      <url>https://repo.maven.apache.org/maven2</url>
    </pluginRepository>
  </pluginRepositories>
  <build>
    <sourceDirectory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\src\main\java</sourceDirectory>
    <scriptSourceDirectory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\src\main\scripts</scriptSourceDirectory>
    <testSourceDirectory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\src\test\java</testSourceDirectory>
    <outputDirectory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\target\classes</outputDirectory>
    <testOutputDirectory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\target\test-classes</testOutputDirectory>
    <resources>
      <resource>
        <directory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\src\main\resources</directory>
      </resource>
    </resources>
    <testResources>
      <testResource>
        <directory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\src\test\resources</directory>
      </testResource>
    </testResources>
    <directory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\target</directory>
    <finalName>neuralnetwork-0.0.1-SNAPSHOT</finalName>
    <pluginManagement>
      <plugins>
        <plugin>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>1.3</version>
        </plugin>
        <plugin>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>2.2-beta-5</version>
        </plugin>
        <plugin>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>2.8</version>
        </plugin>
        <plugin>
          <artifactId>maven-release-plugin</artifactId>
          <version>2.3.2</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <executions>
          <execution>
            <id>default-compile</id>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <source>1.8</source>
              <target>1.8</target>
            </configuration>
          </execution>
          <execution>
            <id>default-testCompile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
            <configuration>
              <source>1.8</source>
              <target>1.8</target>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-clean-plugin</artifactId>
        <version>2.5</version>
        <executions>
          <execution>
            <id>default-clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-resources-plugin</artifactId>
        <version>2.6</version>
        <executions>
          <execution>
            <id>default-testResources</id>
            <phase>process-test-resources</phase>
            <goals>
              <goal>testResources</goal>
            </goals>
          </execution>
          <execution>
            <id>default-resources</id>
            <phase>process-resources</phase>
            <goals>
              <goal>resources</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-jar-plugin</artifactId>
        <version>2.4</version>
        <executions>
          <execution>
            <id>default-jar</id>
            <phase>package</phase>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.12.4</version>
        <executions>
          <execution>
            <id>default-test</id>
            <phase>test</phase>
            <goals>
              <goal>test</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-install-plugin</artifactId>
        <version>2.4</version>
        <executions>
          <execution>
            <id>default-install</id>
            <phase>install</phase>
            <goals>
              <goal>install</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-deploy-plugin</artifactId>
        <version>2.7</version>
        <executions>
          <execution>
            <id>default-deploy</id>
            <phase>deploy</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-site-plugin</artifactId>
        <version>3.3</version>
        <executions>
          <execution>
            <id>default-site</id>
            <phase>site</phase>
            <goals>
              <goal>site</goal>
            </goals>
            <configuration>
              <outputDirectory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\target\site</outputDirectory>
              <reportPlugins>
                <reportPlugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-project-info-reports-plugin</artifactId>
                </reportPlugin>
              </reportPlugins>
            </configuration>
          </execution>
          <execution>
            <id>default-deploy</id>
            <phase>site-deploy</phase>
            <goals>
              <goal>deploy</goal>
            </goals>
            <configuration>
              <outputDirectory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\target\site</outputDirectory>
              <reportPlugins>
                <reportPlugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-project-info-reports-plugin</artifactId>
                </reportPlugin>
              </reportPlugins>
            </configuration>
          </execution>
        </executions>
        <configuration>
          <outputDirectory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\target\site</outputDirectory>
          <reportPlugins>
            <reportPlugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-project-info-reports-plugin</artifactId>
            </reportPlugin>
          </reportPlugins>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <reporting>
    <outputDirectory>C:\Users\Agando\Documents\Komplexe Leistung\Spielprojekt\neuralnetwork\target\site</outputDirectory>
  </reporting>
</project>
```

**Comment by treo** [comment]
Please post your pom.xml if you are using maven, or the file that your build system of choice uses.

You get that exception whenever you don't have a backend (just as it tells you) in you dependencies.

**Comment by SuchtyTV** [comment]
updated. Thank you for the quick support...

**Comment by SuchtyTV** [comment]
Bug still exists

**Comment by raver119** [comment]
Your pom.xml is a bit pointless.

- compile scope? why?
- version of 0.7.0? use something recent please.
- use -platform artifacts. i.e. nd4j-cuda-8.0-platform or nd4j-native-platform
- use deeplearning4j-cuda artifact + cuDNN as well.

**Comment by raver119** [comment]
p.s. To be clear: that's NOT a bug. That's bad pom.xml.

**Comment by SuchtyTV** [comment]
Would you please so kind, posting a working pom.xml. I am a bit new in this...

**Comment by SuchtyTV** [comment]
I read the article. But I have to admit that I am still unconscious about what I am doing.
First, I cannot select any scope to the dependencies I have added. I am not sure why I should link my own project in the dependencies like he did here:

> <dependency>
>     <groupId>junit</groupId>
>     <artifactId>junit</artifactId>
>     <version>4.12</version>
>     <scope>test</scope>
> </dependency>

My dependencies are now:

>  	<dependencies>
>  		<dependency>
>   			<groupId>org.deeplearning4j</groupId>
>   			<artifactId>deeplearning4j-core</artifactId>
>  			 <version>1.0.0-alpha</version>
>  		</dependency>
> 	<dependency>
>     		<groupId>org.nd4j</groupId>
>     		<artifactId>nd4j-cuda-8.0-platform</artifactId>
>     		<version>1.0.0-alpha</version>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.datavec</groupId>
> 		<artifactId>datavec-api</artifactId>
> 		<version>1.0.0-alpha</version>
> 	</dependency>
>  	</dependencies>

(All using the compile-scope, because other scopes throwning errors)
If I execute the project I still get a similar error:

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:786)
> 	at neuralnetwork.NeuralNetwork.main(NeuralNetwork.java:15)
> Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
> 	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6230)
> 	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:207)
> 	... 2 more
> Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
> 	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:259)
> 	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6227)
> 	... 3 more

**Comment by raver119** [comment]
That's good start. 

Now please show me `nvcc --version` output.

**Comment by SuchtyTV** [comment]
I am running Cuda 9:

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. Alle Rechte vorbehalten.

> nvcc --version
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2017 NVIDIA Corporation
> Built on Fri_Nov__3_21:08:12_Central_Daylight_Time_2017
> Cuda compilation tools, release 9.1, V9.1.85

**Comment by raver119** [comment]
see this: `<artifactId>nd4j-cuda-8.0-platform</artifactId>`
vs
`Cuda compilation tools, release 9.1, V9.1.85`

it should be nd4j-cuda-9.1-platform for you.

**Comment by SuchtyTV** [comment]
>  	<dependencies>
>  		<dependency>
>   			<groupId>org.deeplearning4j</groupId>
>   			<artifactId>deeplearning4j-core</artifactId>
>  			 <version>1.0.0-alpha</version>
>  		</dependency>
> 	<dependency>
>     		<groupId>org.nd4j</groupId>
>     		<artifactId>nd4j-cuda-9.1-platform</artifactId>
>     		<version>1.0.0-alpha</version>
> 	</dependency>
> 	<dependency>
> 		<groupId>org.datavec</groupId>
> 		<artifactId>datavec-api</artifactId>
> 		<version>1.0.0-alpha</version>
> 	</dependency>
>  	</dependencies>

Updated the libary. Although throwing the same error.

**Comment by raver119** [comment]
```
Could not transfer artifact org.bytedeco.javacpp-presets:cuda:jar:linux-x86_64:9.1-7.1-1.4.1 from/to central (https://repo.maven.apache.org/maven2): C:\Users\Agando.m2\repository\org\bytedeco\javacpp-presets\cuda\9.1-7.1-1.4.1\aether-04ab274e-9d10-4bf5-bb74-daa35b431ed4-cuda-9.1-7.1-1.4.1-linux-x86_64.jar-in-progress (Das System kann die angegebene Datei nicht finden)

org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.bytedeco.javacpp-presets:cuda:jar:linux-x86_64:9.1-7.1-1.4.1 from/to central (https://repo.maven.apache.org/maven2): C:\Users\Agando.m2\repository\org\bytedeco\javacpp-presets\cuda\9.1-7.1-1.4.1\aether-04ab274e-9d10-4bf5-bb74-daa35b431ed4-cuda-9.1-7.1-1.4.1-linux-x86_64.jar-in-progress (Das System kann die angegebene Datei nicht finden)
```

This means that you can't obtain artifacts from Maven Central.

**Comment by SuchtyTV** [comment]
Is that a problem? Does it a affect the other error? 
How to solve it ( I mean I am using Windows not Linux)

**Comment by raver119** [comment]
yes it does. as for how to solve it - no idea. probably try vpn. or intellij idea instead of eclipse.

**Comment by SuchtyTV** [comment]
IntellJ does not throw the error. But it gives information why the other bug appear:

```
Error:java: error reading C:\Users\Agando\.m2\repository\org\tukaani\xz\1.5\xz-1.5.jar; ZipFile invalid LOC header (bad signature)
Error:java: error reading C:\Users\Agando\.m2\repository\com\github\jai-imageio\jai-imageio-core\1.3.0\jai-imageio-core-1.3.0.jar; ZipFile invalid LOC header (bad signature)
Error:java: error reading C:\Users\Agando\.m2\repository\org\bytedeco\javacpp-presets\cuda\9.1-7.1-1.4.1\cuda-9.1-7.1-1.4.1.jar; ZipFile invalid LOC header (bad signature)
Error:java: error reading C:\Users\Agando\.m2\repository\org\bytedeco\javacpp-presets\cuda\9.1-7.1-1.4.1\cuda-9.1-7.1-1.4.1-linux-x86_64.jar; ZipFile invalid LOC header (bad signature)
Error:java: error reading C:\Users\Agando\.m2\repository\org\nd4j\nd4j-cuda-9.1\1.0.0-alpha\nd4j-cuda-9.1-1.0.0-alpha-macosx-x86_64.jar; ZipFile invalid LOC header (bad signature)
Error:java: error reading C:\Users\Agando\.m2\repository\org\nd4j\nd4j-cuda-9.1\1.0.0-alpha\nd4j-cuda-9.1-1.0.0-alpha-windows-x86_64.jar; ZipFile invalid LOC header (bad signature)
Error:java: error reading C:\Users\Agando\.m2\repository\joda-time\joda-time\2.9.2\joda-time-2.9.2.jar; ZipFile invalid LOC header (bad signature)
Error:java: error reading C:\Users\Agando\.m2\repository\org\freemarker\freemarker\2.3.23\freemarker-2.3.23.jar; ZipFile invalid LOC header (bad signature)
```

**Comment by treo** [comment]
In that case you have to delete the broken files and let maven redownload them again

**Comment by SuchtyTV** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>suchtytv.complexservice</groupId>
    <artifactId>NeuralNetworks</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>1.0.0-alpha</version>
        </dependency>
        <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-cuda-9.1-platform</artifactId>
            <version>1.0.0-alpha</version>
        </dependency>
        <dependency>
            <groupId>org.datavec</groupId>
            <artifactId>datavec-api</artifactId>
            <version>1.0.0-alpha</version>
        </dependency>
    </dependencies>

</project>
```

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> Exception in thread "main" java.lang.ExceptionInInitializerError
> 	at org.deeplearning4j.nn.conf.MultiLayerConfiguration$Builder.build(MultiLayerConfiguration.java:561)
> 	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$ListBuilder.build(NeuralNetConfiguration.java:303)
> 	at NeuralNetwork.main(NeuralNetwork.java:62)
> Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
> 	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6230)
> 	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:207)
> 	... 3 more
> Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException: Please ensure that you have an nd4j backend on your classpath. Please see: http://nd4j.org/getstarted.html
> 	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:259)
> 	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:6227)
> 	... 4 more

**Comment by raver119** [comment]
What's your actual GPU model?

**Comment by SuchtyTV** [comment]
I use a GTX 970, which is able to run Cuda and works successfully with Tensorflow, Pytorch and other libarys

**Comment by SuchtyTV** [comment]
The nd4j-native-platform version works, throwing:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Done

But why the cuda version is not?

**Comment by SuchtyTV** [comment]
I reinstalled Cuda. Now it works...
Thank for pleasant support!
