### ISSUE TITLE
CudaContext.syncOldStream overhead

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#2850]
Test machine: Windows 10, CUDA 8 + CuDNN, Titan X (Pascal)

This PR considerably refactors workspace use in DL4J: https://github.com/deeplearning4j/deeplearning4j/pull/4900

However, on a simple benchmark, it is considerably slower than 1.0.0-alpha (even though it eliminated the migrateInput bottleneck): https://github.com/deeplearning4j/dl4j-benchmark/blob/master/dl4j-core-benchmark/src/main/java/org/deeplearning4j/simple/SimpleBenchmark.java

According to profiling, the reason is due to the more frequent workspace closing.

Consider for example applying the updater... though there's some uncertainty here (profiling/tracing, plus grid executor, some functionality and workspace opening/closing moved elsewhere etc) it certainly looks like workspace closing (and, syncOldStream specifically) take a lot longer than the actual ops themselves.

https://github.com/deeplearning4j/deeplearning4j/blob/eafc97588d9037299b6044e765487ae169505bcb/deeplearning4j-nn/src/main/java/org/deeplearning4j/nn/updater/BaseMultiLayerUpdater.java#L275-L282

1.0.0-alpha:
![image](https://user-images.githubusercontent.com/2360237/39123079-105442b6-473a-11e8-9028-7c7fc023442e.png)

ab_workspace_opt:
![image](https://user-images.githubusercontent.com/2360237/39123037-f7ea8582-4739-11e8-86cd-318d7f7cc1a3.png)

For comparison on 100 fit ops for AlexNet, the migrateInput I was working to eliminate took 2437ms on 1.0.0-alpha, and for comparison the syncOldStream for the updater alone took 3879ms.

**Comment by raver119** [comment]
Is `SimpleBenchmark.java` enough to reproduce this behavior?

**Comment by AlexDBlack** [comment]
Yes, use that SimpleBenchmark class in benchmark repo.

**Comment by AlexDBlack** [comment]
Confirming that after some workspace changes - and finally merging my memory PR to master - the issue seems to still be present.

**Comment by saudet** [comment]
This might have something to do with separable compilation that was enabled after 1.0.0-alpha?

**Comment by raver119** [comment]
That's quite possible. But lets take a look into profiler dump first.

**Comment by raver119** [comment]
At this moment i don't see anything suspicious at profiler. Actually it looks pretty much ideal. But we  ( @crockpotveggies and me) are still looking into dumps.

**Comment by raver119** [comment]
Ye, everything looks legit in this case.
It's just increased number of synchronize calls, due to DL4j workspaces changes.
