### ISSUE TITLE
Any one notice the example code at https://nd4j.org is not correct?

### ISSUE THREAD

**Issue by songjun54cm** [deeplearning4j/nd4j#2855]
the example code is as follows:

Create a 2 x 2 NDarray:
```
INDArray arr1 = Nd4j.create(new float[]{1,2,3,4},new int[]{2,2});
System.out.println(arr1);
```
Output:
```
[[1.0 ,3.0]
[2.0 ,4.0]
]
```

However after trying it in java the I get the output as follows:
```
[[    1.0000,    2.0000], 
 [    3.0000,    4.0000]]
```

Am I miss something? I use ND4j version 1.0.0-alpha.

**Comment by raver119** [comment]
That’s just C vs F order difference.

**Comment by songjun54cm** [comment]
Hi @raver119 , can you explain the C vs F difference in more detail.
I think this difference will affect further computation, so why the developers allow this difference?

**Comment by raver119** [comment]
it's C array order vs Fortran array order. also known as Column major vs
Row major.
