### ISSUE TITLE
im2col - IndexOutofBoundsError on ConvolutionTest in DL4J

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#287]
Potential is based on different sizes: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/convolution/Convolution.java#L160

And/or related to Index changes

Test currently failing: https://github.com/deeplearning4j/deeplearning4j/blob/mw_cnn_tests/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/layers/convolution/TestConvolutionLayer.java#L34

In indexing, an extra 1 is being appended as 5,1,8,8 vs 5,1,1,1,8,8 in get vs col assign which has to do with how all is treated.
Values that it should be based on referenced test
Padded = 5,1,32,32
Get = 5,1,8,8
Ret = 5,1,9,9,8,8
Col assign is putting values into the middle of the shape vs just setting up as 5,1,8,8

**Comment by agibsonccc** [comment]
Doesn't exist anymore and shape errors have been fixed.
