### ISSUE TITLE
tensorMmul a and b same rank error

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#288]
Going through CNN test: https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/test/java/org/deeplearning4j/nn/layers/convolution/ConvolutionLayerTest.java#L79

It's throwing the java.lang.IllegalArgumentException: a and b must be same rank on tensorMmul. Contained example in the test was run through an other code base and numpy to verify expected results.

**Comment by agibsonccc** [comment]
fixed.
