### ISSUE TITLE
Seamless transfer of gpu data to cpu data workspaces does not work

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#2885]
#### Issue Description
We can't run cpu  ops on gpu based arrays.

Please describe your issue, along with:
- expected behavior
We should be able to detect where a buffer is located
and run ops transparently.
- encountered behavior
An exception fro cuda.

#### Version Information
snapshots

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
No, they do work mostly, we have lots of tests in nd4j-tests using custom ops, and tests pass.
That's probably something wrong tile op, or mapping for it. Can i see how you've used it?

**Comment by raver119** [comment]
Re: Tile.

Here's the test i've added: https://github.com/deeplearning4j/nd4j/blob/2138328469fc07bad0d5eed95112d73d9c445b72/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L6274-L6289

It passes on CPU and CUDA backend.

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/deeplearning4j/pull/5146
