### ISSUE TITLE
INDArray.get() single indexing on row vectors

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#289]
Single indexing on row vectors fails:
myRowVector.get(NDArrayIndex.interval(idx, range + idx));

whereas myRowVector.get(new NDArrayIndex(0),NDArrayIndex.interval(idx, range + idx)); works

**Comment by taisukeoe** [comment]
Would you specify example values?

I confirmed the following example works.

```scala
scala> import org.nd4j.linalg.indexing._

scala> val arr = Nd4j.create(Array(1f,2f,3f,4f))
arr: org.nd4j.linalg.api.ndarray.INDArray = [ 1.00, 2.00, 3.00, 4.00]

scala> val subarr = arr.get(NDArrayIndex.interval(0,2))
subarr: org.nd4j.linalg.api.ndarray.INDArray = [ 1.00, 2.00]
```

But row vector's `get` doesn't work,  if IntervalIndex has explicit stride field.

```scala
//This should return [1.00, 3.00].
scala> val subarr2 = arr.get(NDArrayIndex.interval(0,2,3))
subarr2: org.nd4j.linalg.api.ndarray.INDArray = [ 1.00, 2.00]
```

**Comment by AlexDBlack** [comment]
This was an issue that came from MultiLayerNetwork.setParams() and BaseLayer.setParams() doing .get() with single indexing on a row vector. I've just tested this with single indexing (i.e., just .get(interval(...)) as opposed to using .get(NDArrayIndex.point(0),interval(...))) an it seems to be functioning correctly at present.

**Comment by taisukeoe** [comment]
I see, so it must be fine if it's working on your side. :)

Can I close this issue?

**Comment by AlexDBlack** [comment]
Seems to be resolved.
