### ISSUE TITLE
Add bandwidth transfer stats for arrays

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#2890]
#### Issue Description
Idea: What does it take to load an array from disk to gpu ram?

A form of "network latency" from cpu ram to gpu and instrumentation for file systems like hadoop will help with understanding different interconnects (RDMA,Infiniband etc)

Please describe your issue, along with:
- expected behavior
- encountered behavior

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
* platform information (OS, etc)
* CUDA version, if used
* NVIDIA driver version, if in use

#### Contributing

If you'd like to help us fix the issue by contributing some code, but would
like guidance or help in doing so, please mention it!

**Comment by raver119** [comment]
Implemented, merged
