### ISSUE TITLE
INDArray#sum without arguments gives different results with CPU vs GPU backend

### ISSUE THREAD

**Issue by DrChainsaw** [deeplearning4j/nd4j#2891]
#### Issue Description

The following testcase fails when backend is changed from GPU to CPU:

    /**
     * Fails with CPU backend
     */
    @Test
    public void testSum() {
        final INDArray test = Nd4j.create(new double[]{1, 2});
        assertEquals("Incorrect result!", Nd4j.create(new double[] {3}), test.sum());
    }

java.lang.AssertionError: Incorrect result! 
Expected :3.00
Actual   :[1.00,  2.00]

#### Version Information

Please indicate relevant versions, including, if relevant:

* ND4j 1.0.0-alpha, also tested in 0.9.1

#### Contributing

Probably much faster for you to fix :)

**Comment by DrChainsaw** [comment]
Seems the same issue is present for INDArray#mean as well (because it uses sum?)

**Comment by raver119** [comment]
I'm afraid this issue is present for any reduction operation, because they share the same execution logic :)

**Comment by raver119** [comment]
Fixed merged
