### ISSUE TITLE
Reverse Tensor by reference

### ISSUE THREAD

**Issue by p6majo** [deeplearning4j/nd4j#2898]
Is it possible to have two tensors A and B referencing the same data but in reverse order, such that when the components of one tensor are changed, say by

`A.addi(C)`

the components of B are changed accordingly?

If this is possible, can it be extended to a higher dimensional tensor, which is only reversed in certain dimensions, as it is can be achieved with methods ([https://github.com/deeplearning4j/nd4j/issues/2313](url))

        INDArray test = Nd4j.linspace(1,b*d*c*r,b*d*c*r).reshape('c',b,d,c,r);
        INDArray test2 = Nd4j.createUninitialized(new int[]{b,d,c,r});
        CustomOp op = DynamicCustomOp.builder("reverse")
                .addIntegerArguments(0,1)
                .addInputs(test)
                .addOutputs(test2)
                .callInplace(false)
                .build();

        Nd4j.getExecutioner().exec(op);
        System.out.println(test2);

        test.getRow(0).getRow(0).put(0,0,5f);
        System.out.println(test);
        System.out.println(test2);

Here the tensor test2 does not notice the changes made in test.

**Comment by raver119** [comment]
No, it’s not possible.
