### ISSUE TITLE
Build error on NVIDIA Jetson TX2 

### ISSUE THREAD

**Issue by Spawn32** [deeplearning4j/nd4j#2918]
Was there any solution to:  https://github.com/deeplearning4j/nd4j/issues/2180 ?

I am getting the exact same errors on the TX2.

Version Information
platform information: NVIDIA Jetson TX2, Ubuntu 16.04:
CUDA version: release 9.0 V9.0.252

https://devtalk.nvidia.com/default/topic/1036132/jetson-tx2/deeplearning4j-nd4j/

**Comment by saudet** [comment]
No, please move the discussion to https://github.com/deeplearning4j/deeplearning4j/issues/3458

**Comment by Spawn32** [comment]
Sorry @saudet , didn't see deeplearning4j/deeplearning4j#3458
will test out the solution from 3458 on my TX2, thanks :)
