### ISSUE TITLE
Nd4j.diag() regression

### ISSUE THREAD

**Issue by emillynge** [deeplearning4j/nd4j#2919]
#### Issue Description
the diag function was broken in commit that was part of #2641 

Please describe your issue, along with:
- expected behavior
 When passing a matrix to diag, a vector is returned
- encountered behavior
 A HUGE matrix is returned

#### Version Information

Please indicate relevant versions, including, if relevant:

* Nd4j 1.0.0-beta

diag function no longer checks if input is a vector or a matrix. Native op is directly called and [n,m] matrices are treated as [nm] vector which produces a [nm, nm] matrix.

The error was introduced in https://github.com/deeplearning4j/nd4j/commit/206199b295c1adfbd72388abdd0405f6f7c9b5c8#diff-329bd29dd155454c7a45684179eacdffL2824 

NB. the old implementation does not seem correct for matrices if `k != 0`

**Comment by AlexDBlack** [comment]
This issue was moved to deeplearning4j/deeplearning4j#5482

**Comment by AlexDBlack** [comment]
Please use https://github.com/deeplearning4j/deeplearning4j for all issues from now on.
We've migrated to a mono-repository layout for our projects, and this repo will be locked soon.
