### ISSUE TITLE
NoAvailableBackendException only in REPL context - advice?

### ISSUE THREAD

**Issue by novog** [deeplearning4j/nd4j#2926]
I have nd4j working in my Maven Kotlin project when run from a packaged jar file. However, when I try calling some nd4j functions in the IntelliJ REPL under the context of the same project, I get an `Nd4jBackend$NoAvailableBackendException` error. It would vastly improve productivity when trying to explore data or new algorithms if nd4j could be used from the REPL.

I am aware that I will probably need to raise this issue with IntelliJ, but I was hoping that I could first get some information here on what it is that the REPL needs to do that it probably isn't doing. Does it have to do with the `ServiceLoader`? Is there anything that I could do in my application code or Maven configuration that would help?

Thanks!

Example Kotlin code that results in this error from the REPL:

    val a = zeros(1000, 1000)

Deeplearning4j version - `1.0.0-beta7`, both with `nd4j-cuda-10.2` and `nd4j-cuda-10.2-platform`.
platform information (OS, etc) - Windows 10
CUDA version - 10.2
cuDNN version - 7.6.5
NVIDIA driver version - 451.67

Excerpt from .pom:

        <dependencies>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-stdlib-jdk8</artifactId>
                <version>1.3.72</version>
            </dependency>
            <dependency>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-reflect</artifactId>
                <version>1.3.72}</version>
            </dependency>
            <dependency>
                <groupId>org.nd4j</groupId>
                <artifactId>nd4j-cuda-10.2</artifactId>
                <version>1.0.0-beta7</version>
            </dependency>
            <dependency>
                <groupId>org.deeplearning4j</groupId>
                <artifactId>deeplearning4j-cuda-10.2</artifactId>
                <version>1.0.0-beta7</version>
            </dependency>
            <dependency>
                <groupId>org.deeplearning4j</groupId>
                <artifactId>deeplearning4j-ui</artifactId>
                <version>1.0.0-beta7</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>1.16.20</version>
            </dependency>
        </dependencies>
...

    <build>
        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <configuration>
                    <jvmTarget>1.8</jvmTarget>
                </configuration>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals><goal>compile</goal></goals>
                        <configuration>
                            <sourceDirs>
                                <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                                <sourceDir>${project.basedir}/src/main/java</sourceDir>
                            </sourceDirs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <mainClass>com.my.project.Main</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <filters>
                                <filter>
                                    <artifact>org.eclipse*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

**Comment by saudet** [comment]
Could you try with, for example, OpenCV see if that works or not? If it doesn't work, we'll know it's something related to JavaCPP.

**Comment by novog** [comment]
@saudet Thanks for the tip. The following OpenCV code does work as expected in the REPL:

    import org.opencv.core.Core
    import org.bytedeco.opencv.opencv_core.Mat
    import org.opencv.core.CvType
    
    System.loadLibrary(Core.NATIVE_LIBRARY_NAME)
    val mat: = Mat.eye(3, 3, CvType.CV_8UC1).asMat()
    println(mat.diag().dot(mat.diag()))                // prints 3

I took a look at `Nd4jBackend.load()` and tried running it line-by-line. The following code results in `true` when run from a .jar file and `false` from the REPL:

    val loader = ServiceLoader.load(Nd4jBackend::class.java)
    val iter = loader.iterator()
    println("iter.hasNext() = ${iter.hasNext()}")

Please let me know if there is anything else that I can check on. Thanks again!

**Comment by saudet** [comment]
ND4J uses the ServiceLoader to locate available backends. That's a pretty
basic API used everywhere, so if that doesn't work, we should report it
upstream.

**Comment by novog** [comment]
After further investigation, I think that I have partially uncovered what is going wrong under the REPL and have a workaround.

In order to attempt to determine where things were being loaded from, I checked `Nd4jBackend::class.java.protectionDomain.codeSource.location`. When run from my packaged .jar file, it gives the location of that file; from the REPL, it gives the location of nd4j-api-1.0.0-beta7.jar in my local Maven repository; that all seems reasonable.

I noticed that nd4j-api-1.0.0-beta7.jar does not list `Nd4jBackend` in META-INF\services, which I assume is because it is provided by the chosen backend. Since the `ServiceLoader` didn't seem to be finding the class in the REPL context, I tried replacing the current thread's class loader with a child `URLClassLoader` that additionally includes the paths to nd4j-api-1.0.0-beta7.jar, nd4j-cuda-10.2-1.0.0-beta7.jar, and nd4j-cuda-10.2-1.0.0-beta7-windows-x86_64.jar in my local Maven repo. This time, the `ServiceLoader` did have a result, but retrieving it resulted in the following error:

> java.util.ServiceConfigurationError: org.nd4j.linalg.factory.Nd4jBackend: Provider org.nd4j.linalg.jcublas.JCublasBackend not a subtype

It appears that this error was due to the fact that `JCublasBackend` had already been loaded by some other `ClassLoader` (and not the current thread's or the system's). If I instead replace the current thread's `ClassLoader` with `JCublasBackend`'s, nd4j is finally able to load `Nd4jBackend` successfully. The following code produces no errors in the REPL:

    Thread.currentThread().contextClassLoader = JCublasBackend::class.java.classLoader
    val a = Nd4j.zeros(1000, 1000)

I am in no way an expert on Java class loading. @saudet, would you say that this behavior suggests that `Nd4jBackend.load` should be checking for a subclass `ClassLoader` to use, rather than allowing the default to be used by not specifying one in the `ServiceLoader.load` call? Or is the fact that the IDEA REPL appears to have already loaded `JCublasBackend` but not `Nd4jBackend`, while `Nd4jBackend`'s .jar file path is not included by the default `ClassLoader` surprising in some way? If the latter, I will follow up with IntelliJ. Thanks again for the help!

**Comment by saudet** [comment]
Yes, it does sound like it's not using the right class loader, and possibly related to pull https://github.com/eclipse/deeplearning4j/pull/8972?

In any case, please open an issue about that at https://github.com/eclipse/deeplearning4j.
This repository is no longer being maintained.

**Comment by novog** [comment]
Re-created as [https://github.com/eclipse/deeplearning4j/issues/9058](https://github.com/eclipse/deeplearning4j/issues/9058). Thanks again!
