### ISSUE TITLE
How to include specific platform jars

### ISSUE THREAD

**Issue by sumeet610** [deeplearning4j/nd4j#2937]
#### Issue Description

Please describe your issue, along with:
- expected behavior: Only linux-x86_64 jars should be included when building using maven.
- encountered behavior: All the jars for different platforms are getting included with maven.

#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version: 1.0.0-beta4
* platform information (OS, etc) : platform where the build is deployed : linux-x86_64
* CUDA version, if used
* NVIDIA driver version, if in use

**Comment by jljljl** [comment]
@sumeet610 It happens if you use -platform dependencies because it contains stuff for all supported platforms. Pom.xml is needed for debug.

**Comment by sumeet610** [comment]
I was able o build linux only jars by passing command line argument
-Djavacpp.platform=linux-x86_64
