### ISSUE TITLE
Cuda C side calculations for complex numbers

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#30]
Need to finish cuda functions for the cuda kernels.

**Comment by thompsjj** [comment]
Did this tag get closed?

**Comment by agibsonccc** [comment]
Issue still open. Complex numbers have fallen in priority since we migrated convolutions away. The boiler plate is there.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/issues/555
