### ISSUE TITLE
BaseNDArray broadcast issue - not copying all the data across as expected

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#313]
CNNtests failing on the expected values for contained test results because bias is being reshaped correctly but the values are not propagated across the new structure.

Tests failing: 
- testActivateResults
- testBackpropResults
- testPreOutputMethod
- TestCalculateDelta

Issue starts on this loop:https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L3987

If bias is a row vector and ret is shape 1,4,4,2 - it only loops on the slice at 1 based on slices() method at: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L1737

Otherwise: it only fills in part of the shape not all of the shape in this section of the broadcast:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L3998

- testPreOutputMethod is the easiest to follow for checking this value

**Comment by agibsonccc** [comment]
Now uses dimshuffle.

**Comment by nyghtowl** [comment]
Tests are still not passing - broadcast doesn't fill in bias fully

**Comment by agibsonccc** [comment]
Now synced to master.
