### ISSUE TITLE
BaseNDArray get returning incorrect shape and result order on dl4j test

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#325]
Issue outlined in Deeplearning4j repo under: testSubSampleLayerAvgBackprop issue in SubsamplingLayerTests #593

**Comment by agibsonccc** [comment]
This is fixed . Make sure your nd4j is updated.

https://github.com/deeplearning4j/deeplearning4j/commit/a07cc139751cbbcc696cd78a462763a80c61dc66
