### ISSUE TITLE
[Feature Request] Convienence method Structured Sort

### ISSUE THREAD

**Issue by MikeDepies** [deeplearning4j/nd4j#338]
There exists an option ND4J.sort(...) that will ascend or descend the data in the ND array. However, there seems to not be any way to sort rows or columns of data out of the box. 2D sorting seems to be pretty natural, I'm unsure how often 3+ dimensional sorting would be needed.

I propose a method that allows a specific dimension to sorted upon, while maintaining structure of the ND array.

I.E.
Nd4j.sortRows(INDArray array, int idx, boolean ascending)
Nd4j.sortColumns(INDArray array, int idx, boolean ascending)

A rough general purpose:
ND4J.sortByDim(INDArray array, int dimension, int index, boolean ascending)

An example:
array = [
[.32,.22,.34],
[.11,.45,.62],
[.58,.98,.57],
[.43,.52,.74]
]

Nd4j.sortRows(INDArray array, int idx, boolean ascending)
giving us:
array = [
[.58,.98,.57],
[.43,.52,.74]
[.11,.45,.62],
[.32,.22,.34],
]

**Comment by AlexDBlack** [comment]
Very quick sortRows and sortColumn methods I threw together:

```java
public static void main( String[] args ){
	Nd4j.getRandom().setSeed(123);
	
	INDArray arr = Nd4j.rand(10,4);
	System.out.println("Original:");
	System.out.println(arr);
	System.out.println("\nSort rows (idx=2):");
	System.out.println(sortRows(arr,2,true));
	
	System.out.println("\nSort columns (idx=1):");
	System.out.println(sortColumns(arr,1,true));
	
}


public static INDArray sortRows( INDArray in, int idx, boolean ascending ){
	if(in.rank() != 2 ) throw new IllegalArgumentException();
	
	INDArray out = Nd4j.create(in.shape());
	int nRows = in.rows();
	ArrayList<Pair<Double,Integer>> list = new ArrayList<>(nRows);
	for( int i=0; i<nRows; i++ ) list.add(new Pair<>(in.getDouble(i, idx),i));
	Collections.sort(list, new PairComp(ascending));
	for( int i=0; i<nRows; i++ ){
		Pair<Double,Integer> p = list.get(i);
		out.putRow(i, in.getRow(p.getSecond()));
	}
	return out;
}

public static INDArray sortColumns( INDArray in, int idx, boolean ascending ){
	if(in.rank() != 2 ) throw new IllegalArgumentException();
	
	INDArray out = Nd4j.create(in.shape());
	int nCols = in.columns();
	ArrayList<Pair<Double,Integer>> list = new ArrayList<>(nCols);
	for( int i=0; i<nCols; i++ ) list.add(new Pair<>(in.getDouble(idx, i),i));
	Collections.sort(list, new PairComp(ascending));
	for( int i=0; i<nCols; i++ ){
		Pair<Double,Integer> p = list.get(i);
		out.putColumn(i, in.getColumn(p.getSecond()));
	}
	return out;
}

public static class PairComp implements Comparator<Pair<Double,Integer>> {
	private final boolean ascending;
	public PairComp(boolean ascending){
		this.ascending = ascending;
	}
	
	@Override
	public int compare(Pair<Double, Integer> o1, Pair<Double, Integer> o2) {
		if( ascending ) return Double.compare(o1.getFirst(), o2.getFirst());
		else return -Double.compare(o1.getFirst(), o2.getFirst());
	}
}
```

Output:
Original:
[[0.70,0.29,0.23,0.55]
 [0.72,0.42,0.98,0.68]
 [0.48,0.39,0.34,0.73]
 [0.44,0.06,0.40,0.74]
 [0.18,0.18,0.53,0.53]
 [0.63,0.85,0.72,0.61]
 [0.72,0.32,0.36,0.23]
 [0.29,0.63,0.09,0.43]
 [0.43,0.49,0.43,0.31]
 [0.43,0.89,0.94,0.50]]

Sort rows (idx=2):
[[0.29,0.63,0.09,0.43]
 [0.70,0.29,0.23,0.55]
 [0.48,0.39,0.34,0.73]
 [0.72,0.32,0.36,0.23]
 [0.44,0.06,0.40,0.74]
 [0.43,0.49,0.43,0.31]
 [0.18,0.18,0.53,0.53]
 [0.63,0.85,0.72,0.61]
 [0.43,0.89,0.94,0.50]
 [0.72,0.42,0.98,0.68]]

Sort columns (idx=1):
[[0.29,0.55,0.70,0.23]
 [0.42,0.68,0.72,0.98]
 [0.39,0.73,0.48,0.34]
 [0.06,0.74,0.44,0.40]
 [0.18,0.53,0.18,0.53]
 [0.85,0.61,0.63,0.72]
 [0.32,0.23,0.72,0.36]
 [0.63,0.43,0.29,0.09]
 [0.49,0.31,0.43,0.43]
 [0.89,0.50,0.43,0.94]]

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/nd4j/pull/339
