### ISSUE TITLE
MMUL optimization; shape.toOffsetZero() + BaseNDArray.getDouble() overhead

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#345]
So matrix multiplication (mmul) calls Shape.toOffsetZero() which adds quite an overhead to matrix operations. For example on x86 backend toOffsetZero() takes significantly longer than the actual matrix multiplication (sgemm)

Some possible/proposed solutions/speed improvements
- Bytecode generation + loop flattening for BaseNDArray.getDouble()
- Maybe, not sure: possible to avoid calling toOffsetZero() in some cases?

See below for VisualVM output (x86 backend) on a GravesLSTM example I'm working on

![getdouble2](https://cloud.githubusercontent.com/assets/2360237/9560723/e50f1cba-4e68-11e5-90c0-5c1ca452a68a.png)

![getdouble3](https://cloud.githubusercontent.com/assets/2360237/9560725/0f6e7c58-4e69-11e5-9a9e-c0c861e269d7.png)

**Comment by agibsonccc** [comment]
Please time with: #351

**Comment by AlexDBlack** [comment]
Going to close this. GravesLSTM optimizations were possible that avoided overhead of needing to do toOffsetZero (and hence getDouble) in the first place.
