### ISSUE TITLE
Unexpected INDArray mmul or toString behavior

### ISSUE THREAD

**Issue by soumen-chakrabarti** [deeplearning4j/nd4j#379]
Can't figure out what I am doing wrong:

            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-jblas</artifactId>
            <version>0.0.3.5.5.6-SNAPSHOT</version>

        INDArray nda = Nd4j.create(new double[]{1, 2, 10, 20, 2, 3}, new int[]{3, 2});
        INDArray query = Nd4j.create(new double[]{3, 4}, new int[]{2, 1});
        INDArray dots = nda.mmul(query);
        System.out.println("nda=" + nda);
        System.out.println("query=" + query);
        System.out.println("dots=" + dots);

Prints out:
nda=[[1.00,2.00]
 [10.00,20.00]
 [2.00,3.00]]
query=[ 3.00, 4.00]
dots=[ 83.00, 14.00, 42.00]

dots would be correct if nda was initialized internally as column major, as in
[ [ 1, 20], [2, 2], [10, 3] ]
but then why is nda printed as it is? For what is printed as nda, we should get
[ [11], [110], [18] ] (3x1 matrix)

Interestingly, if I change the code to 
INDArray nda = Nd4j.create(new double[]{1, 10, 2, 2, 20, 3}, new int[]{3, 2});
then it prints as
nda=[[1.00,10.00]
 [2.00,2.00]
 [20.00,3.00]]
but then we do get
dots=[ 11.00, 110.00, 18.00]

Now I add the following code:
        INDArray norms0 = nda.norm2(0);
        System.out.println("norms0=" + norms0);
        INDArray norms1 = nda.norm2(1);
        System.out.println("norms1=" + norms1);

For the second initialization of nda, I get outputs:
norms0=[ 20.12, 10.63]
norms1=[ 10.05, 2.83, 20.22]

Given the value of dots, let us assume the internal representation of nda is
[(1, 2); (10, 20); (2, 3)]
If I understand norms correctly, we should get 
norm0 = [ L2norm(1, 10, 2), L2norm(2, 20, 3) ]
norm1 = [L2norm(1, 2); L2norm(10, 20); L2norm(2, 3)]

Clearly I am misunderstanding something.

**Comment by agibsonccc** [comment]
Please use the latest dl4j/nd4j. Thanks!
