### ISSUE TITLE
getRow/Column with a 1d array fails

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#38]
I have a function that extracts a single column from an array using ```getColumn(idx)```.
If i call it with e.g. 
```scala
val m1 = Nd4j.create(Array[Float](-1f, 1f, 1f, -1f), Array[Int](2,2))
```
it works as expected however if i call it with:
```scala
val m2 = Nd4j.create(Array[Float](-1f, 1f, 1f, -1f), Array[Int](1,4))
```
it fails with an exception: ```java.lang.IllegalArgumentException: Unable to getFloat scalar column of non 2d matrix```. ```getColumn``` and ```getRow``` should handle the edge cases. See also: https://groups.google.com/forum/#!topic/nd4j/Eqch_WK1m28

**Comment by agibsonccc** [comment]
Fixed.
