### ISSUE TITLE
CUDA7.5 support

### ISSUE THREAD

**Issue by yunge** [deeplearning4j/nd4j#389]
CUDA7.5 for Win10 was released, any plan for it?

**Comment by agibsonccc** [comment]
Backend relies on: http://jcuda.org/ Will likely either migrate or re compile binaries. Need to do some due diligence to see if anything has changes in 7.5 or note.

**Comment by yunge** [comment]
Hi, jcuda supports cuda7.5 now, could you please update nd4j/dl4j?

**Comment by agibsonccc** [comment]
Thanks for the alert.

**Comment by Ueland** [comment]
Since this issue is still open i suspect that 7.5 support is not quite there yet?

(Tested the examples after a pom change, it still gets processed on the CPU)

**Comment by agibsonccc** [comment]
The problem is me compiling the binaries for the different platforms at
this point. I can do linux but not osx or windows. You are welcome to help
the process along and I can release it.

**Comment by agibsonccc** [comment]
#432
