### ISSUE TITLE
Nesterov does not use Scheduling

### ISSUE THREAD

**Issue by gowthamnatarajan** [deeplearning4j/nd4j#390]
Nesterov method does use the iteration parameter for scheduling. But scheduling is available in the configuration I think.
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/learning/Nesterovs.java#L56

**Comment by agibsonccc** [comment]
This has been fixed. https://github.com/deeplearning4j/deeplearning4j/pull/774
