### ISSUE TITLE
Performance Issue: Transform Operations: Hotspot snapshot attached

### ISSUE THREAD

**Issue by gowthamnatarajan** [deeplearning4j/nd4j#395]
![jvnvisual](https://cloud.githubusercontent.com/assets/5133248/9905529/5cc64e0c-5c3a-11e5-9664-72ed8f0aff8b.png)

Operations like addi takes the most time!!

**Comment by gowthamnatarajan** [comment]
![vis2](https://cloud.githubusercontent.com/assets/5133248/9924437/6cb668d6-5cb4-11e5-9450-71fce9e82775.png)

**Comment by gowthamnatarajan** [comment]
![vis4](https://cloud.githubusercontent.com/assets/5133248/9924570/5ffd5824-5cb5-11e5-9203-81fdcb309522.png)

**Comment by gowthamnatarajan** [comment]
![vis5](https://cloud.githubusercontent.com/assets/5133248/9924593/bb92d178-5cb5-11e5-999b-c383ea3c422f.png)

**Comment by agibsonccc** [comment]
Fixed.
