### ISSUE TITLE
Optimize addiRowVector and muliRowVector

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#408]
These two operations are currently bottlenecks for GravesLSTM

see the following for some basic benchmarks
https://gist.github.com/AlexDBlack/cf3bf7ae26b43763f771
https://gist.github.com/AlexDBlack/43620911319c57fdde20

see also https://github.com/deeplearning4j/nd4j/issues/405 for some possible optimization approaches

![image](https://cloud.githubusercontent.com/assets/2360237/9953194/ff0ec4a8-5e21-11e5-8d68-540304015bb5.png)

**Comment by agibsonccc** [comment]
I added forkjoin for this. https://github.com/deeplearning4j/nd4j/pull/414

See how much that helps.
