### ISSUE TITLE
class ScalarSetValue not found

### ISSUE THREAD

**Issue by PhoenixDai** [deeplearning4j/nd4j#41]
I checked out the deeplearning4j project to run the CNN example ConvolutionDownSampleLayerTest

The compiler prompted the error:

C:\Programs\DL\deeplearning4j\deeplearning4j-core\src\main\java\org\deeplearning4j\optimize\solvers\BackTrackLineSearch.java
Error:(28, 54) java: cannot find symbol
  symbol:   class ScalarSetValue
  location: package org.nd4j.linalg.api.ops.impl.scalar.comparison
Error:(182, 40) java: cannot find symbol
  symbol:   class ScalarSetValue
  location: class org.deeplearning4j.optimize.solvers.BackTrackLineSearch

**Comment by agibsonccc** [comment]
If you are pulling from master ensure you have the latest src for both nd4j and canova.

Run mvn clean install -DskipTests on both. I also do this in the ./setup.sh in deeplearning4j's root directory.

**Comment by PhoenixDai** [comment]
Thanks. Problem solved.
