### ISSUE TITLE
Test failures after recent PRs

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#412]
Some recent changes have caused a small number of test failures (Nd4jTestsC)

tests are not passing as of:
- "minor optimizations for concat" 352ae2ec137950551f241f44b52378b4f6b13369
- Merge pr 410 (forkjoin) 438e1d3337a98c45e6d5a79099396cc7488f5a23

tests are passing as of:
- Merge pr 409 (caching)	98d97ee46b6aab097f27eb7c4e5216b8d64e9578

details of test failures:
org.nd4j.linalg.Nd4jTestsC.testSum(Nd4jTestsC.java:803)
org.nd4j.linalg.Nd4jTestsC.testMeans(Nd4jTestsC.java:1564)
org.nd4j.linalg.Nd4jTestsC.testSum2(Nd4jTestsC.java:894)
org.nd4j.linalg.Nd4jTestsC.testSums(Nd4jTestsC.java:1575)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/413
