### ISSUE TITLE
Scores not matching x86 & jcublas-7.0

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#419]
Use this [example] (https://github.com/deeplearning4j/dl4j-snapshot-examples/blob/master/src/main/java/org/deeplearning4j/convolution/CNNMnistExample.java) 

x86 scores:
 Accuracy:  0.76
 Precision: 0.855
 Recall:    0.8571
 F1 Score:  0.8560592378544338

jcublas-7.0 scores:
 Accuracy:  0.68
 Precision: 0.7019
 Recall:    0.7393
 F1 Score:  0.7201104529041091

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/issues/555
