### ISSUE TITLE
GPU - Examples are killed mid execution 

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#420]
GPU EC2 instance with 4 chips & Mac with single GPU chip kills programs after a certain threshold of computations and/or data size.

- DBNFullMnist example at 60K samples gets killed (if scaled down to 30k with SGD for optimization it can complete on even the Mac)
- MultiLayer examples especially are having difficulties (CMGS with just 10K samples)

**Comment by agibsonccc** [comment]
Batch size? Loading all 60k in to the GPU isn't a good idea.

**Comment by nyghtowl** [comment]
Its happening for batch sizes ranging as small as 100 to 1000.

**Comment by agibsonccc** [comment]
Sounds like a potential memory leak.

**Comment by agibsonccc** [comment]
There's been a lot of fixes. This is too generic to be actionable. I'm going to close this. If the issue persists, re open this with something more specific (eg: ram used, gpu specs,..)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/issues/555
