### ISSUE TITLE
Matrix multiplication returns zero

### ISSUE THREAD

**Issue by gowthamnatarajan** [deeplearning4j/nd4j#421]
Multiplying (mmul) 2 non zero matrices returns just zeros. But, I multiplied the same 2 matrices using normal java code and it returned non zero array. I use this code
http://www.javawithus.com/programs/matrix-multiplication

Adam has the 2 matrices I tested with. Don't know how to attach them here?

**Comment by gowthamnatarajan** [comment]
```
package org.nd4j;

import org.nd4j.linalg.api.buffer.DataBuffer;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.factory.Nd4j;

import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.util.zip.GZIPInputStream;
import org.junit.Assert.*;

/**
 * Hello world!
 *
 */
public class App {
    public static void main( String[] args ) throws Exception {
        Nd4j.factory().setDType(DataBuffer.Type.DOUBLE);
        Nd4j.dtype = DataBuffer.Type.DOUBLE;
        BufferedInputStream bis = new BufferedInputStream(new GZIPInputStream(new FileInputStream("/home/agibsonccc/Downloads/matrix2.txt.gz")));
        DataInputStream dis = new DataInputStream(bis);
        INDArray first = Nd4j.read(dis);
        INDArray second = Nd4j.read(dis);
        first.setData(Nd4j.createBuffer(first.data().asDouble()));
        second.setData(Nd4j.createBuffer(second.data().asDouble()));
        first.setOrder('f');
        second.setOrder('f');
        System.out.println("First " + first);
        System.out.println("Second " + second);
        INDArray third = first.mmul(second);
        System.out.println(first.mmul(second));
        assertEquals(third.getDouble(0), -0.0016883233711104662d, 0.0001);
    }
}
```

**Comment by agibsonccc** [comment]
@gowthamnatarajan Could you get me the whole matrix for assertion as well?

**Comment by gowthamnatarajan** [comment]
Ok.


Sent from my T-Mobile 4G LTE Device-------- Original message --------From: Adam Gibson <notifications@github.com> Date: 9/21/2015  8:34 PM  (GMT-08:00) To: deeplearning4j/nd4j <nd4j@noreply.github.com> Cc: Gowtham <gowtham.n.mail@gmail.com> Subject: Re: [nd4j] Matrix multiplication returns zero (#421) 
@gowthamnatarajan Could you get me the whole matrix for assertion as well?

**Comment by gowthamnatarajan** [comment]
third = first.mmul(second)

On Mon, Sep 21, 2015 at 9:42 PM, Gowtham Natarajan <gowtham.n.mail@gmail.com
> wrote:

> Ok.
>
>
>
> Sent from my T-Mobile 4G LTE Device
> -------- Original message --------
> From: Adam Gibson <notifications@github.com>
> Date: 9/21/2015 8:34 PM (GMT-08:00)
> To: deeplearning4j/nd4j <nd4j@noreply.github.com>
> Cc: Gowtham <gowtham.n.mail@gmail.com>
> Subject: Re: [nd4j] Matrix multiplication returns zero (#421)
>
> @gowthamnatarajan <https://github.com/gowthamnatarajan> Could you get me
> the whole matrix for assertion as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deeplearning4j/nd4j/issues/421#issuecomment-142170391>
> .
>



-- 
Gowtham Natarajan

**Comment by gowthamnatarajan** [comment]
The result is not a scalar. It's a vector.

On Mon, Sep 21, 2015 at 10:56 PM, Gowtham N <gowtham.n.mail@gmail.com>
wrote:

> third = first.mmul(second)
>
> On Mon, Sep 21, 2015 at 9:42 PM, Gowtham Natarajan <
> gowtham.n.mail@gmail.com> wrote:
>
>> Ok.
>>
>>
>>
>> Sent from my T-Mobile 4G LTE Device
>> -------- Original message --------
>> From: Adam Gibson <notifications@github.com>
>> Date: 9/21/2015 8:34 PM (GMT-08:00)
>> To: deeplearning4j/nd4j <nd4j@noreply.github.com>
>> Cc: Gowtham <gowtham.n.mail@gmail.com>
>> Subject: Re: [nd4j] Matrix multiplication returns zero (#421)
>>
>> @gowthamnatarajan <https://github.com/gowthamnatarajan> Could you get me
>> the whole matrix for assertion as well?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/deeplearning4j/nd4j/issues/421#issuecomment-142170391>
>> .
>>
>
>
>
> --
> Gowtham Natarajan
>



-- 
Gowtham Natarajan

**Comment by agibsonccc** [comment]
K will update this.

**Comment by gowthamnatarajan** [comment]
Updated the old code with the new assert

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/428
