### ISSUE TITLE
Master branch is broken!

### ISSUE THREAD

**Issue by linkerlin** [deeplearning4j/nd4j#435]
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building nd4j-jcublas-kernels 0.4-rc4.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ nd4j-jcublas-kernels ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ nd4j-jcublas-kernels ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 222 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ nd4j-jcublas-kernels ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ nd4j-jcublas-kernels ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ nd4j-jcublas-kernels ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[3,23] package junit.framework does not exist
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[4,23] package junit.framework does not exist
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[5,23] package junit.framework does not exist
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[11,13] cannot find symbol
  symbol: class TestCase
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[26,19] cannot find symbol
  symbol:   class Test
  location: class org.nd4j.AppTest
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[28,20] cannot find symbol
  symbol:   class TestSuite
  location: class org.nd4j.AppTest
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[36,9] cannot find symbol
  symbol:   method assertTrue(boolean)
  location: class org.nd4j.AppTest
[INFO] 7 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] nd4j ............................................... SUCCESS [  0.862 s]
[INFO] nd4j-bytebuddy ..................................... SUCCESS [  0.583 s]
[INFO] nd4j-api ........................................... SUCCESS [  0.240 s]
[INFO] nd4j-jblas ......................................... SUCCESS [  2.185 s]
[INFO] nd4j-jdbc .......................................... SUCCESS [  0.007 s]
[INFO] nd4j-jdbc-api ...................................... SUCCESS [  0.042 s]
[INFO] nd4j-jdbc-mysql .................................... SUCCESS [  0.034 s]
[INFO] nd4j-netlib-blas ................................... SUCCESS [  1.164 s]
[INFO] nd4j-jcublas-parent ................................ SUCCESS [  0.009 s]
[INFO] nd4j-jcublas-common ................................ SUCCESS [  0.219 s]
[INFO] nd4j-jcublas-6.5 ................................... SUCCESS [  1.864 s]
[INFO] nd4j-jcublas-5.5 ................................... SUCCESS [  1.677 s]
[INFO] nd4j-jcublas-6.0 ................................... SUCCESS [  1.746 s]
[INFO] nd4j-jcublas-7.0 ................................... SUCCESS [  1.775 s]
[INFO] nd4j-jcublas-kernels ............................... FAILURE [  0.037 s]
[INFO] nd4j-jcublas-7.5 ................................... SKIPPED
[INFO] nd4j-instrumentation ............................... SKIPPED
[INFO] nd4j-java .......................................... SKIPPED
[INFO] nd4j-jocl-parent ................................... SKIPPED
[INFO] nd4j-jocl-1.9 ...................................... SKIPPED
[INFO] nd4j-jocl-common ................................... SKIPPED
[INFO] nd4j-cpu ........................................... SKIPPED
[INFO] nd4j-tests ......................................... SKIPPED
[INFO] nd4j-perf .......................................... SKIPPED
[INFO] nd4j-serde ......................................... SKIPPED
[INFO] nd4j-jackson ....................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.692 s
[INFO] Finished at: 2015-09-26T22:42:42+08:00
[INFO] Final Memory: 69M/1035M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:testCompile (default-testCompile) on project nd4j-jcublas-kernels: Compilation failure: Compilation failure:
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[3,23] package junit.framework does not exist
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[4,23] package junit.framework does not exist
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[5,23] package junit.framework does not exist
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[11,13] cannot find symbol
[ERROR] symbol: class TestCase
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[26,19] cannot find symbol
[ERROR] symbol:   class Test
[ERROR] location: class org.nd4j.AppTest
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[28,20] cannot find symbol
[ERROR] symbol:   class TestSuite
[ERROR] location: class org.nd4j.AppTest
[ERROR] /Users/linkerlin/gits/nd4j/nd4j-jcublas-parent/nd4j-jcublas-kernels/src/test/java/org/nd4j/AppTest.java:[36,9] cannot find symbol
[ERROR] symbol:   method assertTrue(boolean)
[ERROR] location: class org.nd4j.AppTest
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :nd4j-jcublas-kernels

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/commit/8e75169c7e5f62714dd87782759b2b1aaa00eb8e

**Comment by linkerlin** [comment]
Thanks for quick-fixing.  :)
