### ISSUE TITLE
Bug in Softmax computation (jblas)

### ISSUE THREAD

**Issue by phvu** [deeplearning4j/nd4j#44]
The current implementation of [Softmax OP](https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/SoftMax.java#L146) looks like this:

```java
@Override
    public void init(INDArray x, INDArray y, INDArray z, int n) {
        super.init(x, y, z, n);
        if(x instanceof IComplexNDArray) {
            this.maxComplex = Nd4j.getExecutioner().execAndReturn(new Max(x)).currentResultComplex();
            IComplexNDArray complexX = (IComplexNDArray) x;
            this.y = Transforms.exp(complexX.sub(maxComplex));
            this.sumComplex =  Nd4j.getExecutioner().execAndReturn(new Sum(y)).currentResultComplex();
            this.y.divi(sumComplex);
            this.extraArgs = new Object[] {maxComplex,sumComplex};
        }
        else {
            this.max = Nd4j.getExecutioner().execAndReturn(new Max(x)).currentResult();
            INDArray xMinusMax = x.sub(max);
            this.y = Transforms.exp(xMinusMax);
            this.sum = Nd4j.getExecutioner().execAndReturn(new Sum(this.y)).currentResult();
            this.y.divi(sum);
            this.extraArgs = new Object[] {max,sum};
        }
    }
```

However this won't give the correct results because `this.sum = Nd4j.getExecutioner().execAndReturn(new Sum(this.y)).currentResult();` gives a scalar sum of all elements in `this.y`.
What we actually want to do is to sum `this.y` row-by-row, so that when we normalize it, each row of `this.y` will be a proper pdf.

Any idea how should we fix this?

**Comment by phvu** [comment]
For the non-complex case, I fixed it like this. However I am not sure this is  the right way.
Could you confirm?

```
        super.init(x, y, z, n);
        if(x instanceof IComplexNDArray) {
            this.maxComplex = Nd4j.getExecutioner().execAndReturn(new Max(x)).currentResultComplex();
            IComplexNDArray complexX = (IComplexNDArray) x;
            this.y = Transforms.exp(complexX.sub(maxComplex));
            this.sumComplex =  Nd4j.getExecutioner().execAndReturn(new Sum(y)).currentResultComplex();
            this.y.divi(sumComplex);
            this.extraArgs = new Object[] {maxComplex,sumComplex};
        }
        else {
            this.max = Nd4j.getExecutioner().execAndReturn(new Max(x)).currentResult();
            INDArray xMinusMax = x.sub(max);
            this.y = Transforms.exp(xMinusMax);
            //this.sum = Nd4j.getExecutioner().execAndReturn(new Sum(this.y)).currentResult();
            //this.y.divi(sum);
            INDArray aSum = this.y.sum(1).repmat(new int[]{this.y.shape()[1], 1}).transpose();
            this.y.divi(aSum);
            this.extraArgs = new Object[] {max,sum};
        }
```

**Comment by agibsonccc** [comment]
Mind submitting a pull request?

**Comment by phvu** [comment]
Ok

**Comment by agibsonccc** [comment]
Hey Vu,

I redid that pull request. I had some stuff fail. I get what you mean. This is what the dimension wise operations are for. Nd4j.getExecutioner().exec(op,dimension) executes an op along a dimension.

In the case of each op, I'm ASSUMING it's a vector that's being operated on. If you want to do on a row by row basis or what have you do execAlongDimension to make it work.

**Comment by phvu** [comment]
Ok I see, thanks for clarification.
I got the error because I am trying to build a classifier, with a softmax on top. Regardless of the lower layers, in any case I will have an OutputLayer on top, with "softmax" as the activation function.
Now if I train it using a batch of samples, the forward computation of the OutputLayer is wrong.

Since `extraArgs` doesn't take vectors, how should we fix this? Is there any workaround that I am unaware of?

**Comment by phvu** [comment]
I re-opened this issue because I think this should be fixed properly.
Please feel free to close if it is not top priority for the moment.

**Comment by agibsonccc** [comment]
JFYI: I do executeAlongDimension with the proper sums in OutputLayer:
           https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/OutputLayer.java#L131

**Comment by agibsonccc** [comment]
Closing again. If this executeAlongDimension isn't adequate, we can discuss this in a separate issue.
