### ISSUE TITLE
It's hard to configure Native BLAS 

### ISSUE THREAD

**Issue by junbochen** [deeplearning4j/nd4j#456]
I'm following the quick start instructions in : 
http://deeplearning4j.org/quickstart.html 

When running the MLPBackpropIrisExample example, there're warnings saying:
WARNING: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS 
and nd4j falls back to use the java implementation as com.github.fommil.netlib.F2jBLAS. 
It's very slow compared to the native implementation.

I dig the source code and find netlib-java tries to load a jni component like 'netlib-native_system-linux-x86_64.so' in the standard lib path like '/usr/lib64', etc. However, it just can't find it. 
Here is how I fixed this problem:
1. Download the source code of 'netlib-java', and build/install it with maven. 
    Why would I build it from source code? It's because the lib in maven repository downloaded is inconsistent with the version of gfortran in the server.
     Note that the build would fail. And here's how to fix it: 
    1) replace the version number '1.2-SNAPSHOT' with '1.1.2' in every pom.xml
    2) in native_ref/native_system dir, remove the xos/win modules from the pom.xml files
    3) in xbuild/linux-x86_64 dir, build and install the .so lib
2. make a softlink of netlib-native_system-linux-x86_64.so in maven repository to /usr/lib64

The above steps solved the problem for me. However digging the source code to find what's the problem and find ways to fix all the situations took me more than 1 day. So, here is my  question:
Why it's so hard to configure Native BLAS for nd4j? why the standard installation in the quick start tutorial doesn't config the BLAS properly?

**Comment by agibsonccc** [comment]
Just use this if you can't configure open blas:
-Dorg.nd4j.linalg.cpu.force_native=false

Run this as a jvm argument.

What OS are you trying to run?

**Comment by junbochen** [comment]
-Dorg.nd4j.linalg.cpu.force_native=false, will this option disable native BLAS, so that the performance is slow?
My OS is :
Red Hat Enterprise Linux Server release 6.3 (Santiago)

**Comment by agibsonccc** [comment]
That's the idea yes. System blas (no matter what deep learning framework
you use) will be hard to setup ;/
ᐧ

**Comment by junbochen** [comment]
make me sad~

**Comment by agibsonccc** [comment]
What would you like to make it better? It's only a few steps to configure
openblas. It's not like it's impossible to do?
ᐧ
