### ISSUE TITLE
include support for the sin(x) 

### ISSUE THREAD

**Issue by DonBeo** [deeplearning4j/nd4j#465]
I would like to have the option to evaluate the `sin(x)` function. 
Something to write this two lines in a nicer way:

`val x = Nd4j.linspace(-10, 10, nSamples).reshape(nSamples, 1)`
   ` val y =  Nd4j.getExecutioner().execAndReturn(new Sin(x));`

I do not know if this is possible but I think that the most comfortable way would be to integrate a map function over the array.  
Something like:

`val y = x map ( element => f(element))` where `f` is a function taken from a good math library. (Maybe `breeze` ?  )

**Comment by AlexDBlack** [comment]
Added convenience methods for sin and cos:
Transforms.sin(INDArray in) and Transforms.sin(INDArray in, boolean copy)
Transforms.cos(INDArray in) and Transforms.cos(INDArray in, boolean copy)
former two default to copying
https://github.com/deeplearning4j/nd4j/pull/505
