### ISSUE TITLE
glibc 2.14 required when using Maven JCuda binaries

### ISSUE THREAD

**Issue by dersmon** [deeplearning4j/nd4j#469]
You will get *UnsatisfiedLinkError* if you try running your program on a linux machine with glibc < 2.14 using the JCuda binaries provided by Maven. The libraries for _JCuparse, JCusolver, JCudaRuntime and JCublas**2**_ seem to be the ones needing at least 2.14.

```
java.lang.UnsatisfiedLinkError (...)
version `GLIBC_2.14' not found (required by  ... )
```

**Comment by dersmon** [comment]
Provided you have the compiled binaries for your glibc version, you can replace the binaries in your local maven repository-download: 
1) Open the nd4j-jcublas jar-file at _~/.m2/repository/org/nd4j/nd4j-jcublas-VERSION/ND4J-VERSION/nd4j-jcublas-VERSION-ND4J-VERISON.jar_ with some archive manager.
2) Inside, replace the _lib/*.so_ binaries with the ones compiled for your glibc version.

**Comment by agibsonccc** [comment]
So let's use this to start a neat discussion. It might be neat to have a custom loader for this kind of stuff (basically allowing you to drop in your own binaries instead)

**Comment by agibsonccc** [comment]
Now that we are encouraging people to test cuda I intend on revisiting this.
