### ISSUE TITLE
DataSetIterator: duplicate method

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/nd4j#474]
It seems like the methods `totalExamples()` and `numExamples()` in the `DataSetIterator` interface are duplicates. According to the Java doc, they are supposed to return the 
> Total examples in the iterator

and the 

> Total number of examples in the dataset

respectively.
Not sure whether this is just a documentation issue.

**Comment by eraly** [comment]
They return the same value. The docs are correct.

**Comment by carschno** [comment]
In that case, I think that one of the method should be removed to avoid confusion, if not already done.
