### ISSUE TITLE
Nd4j.sortWithIndices returns zeros and unsorted input

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/nd4j#478]
The method `Nd4j.sortWithIndices(INDArray ndarray, int dimension, boolean ascending)` returns a two-dimensional array, its elements are supposed to contain the indexes and the values of the sorted input array respectively. However, the first array (the indexes) contains zeros only, and the second index contains the unsorted input index.
I've created a test case which failes for me on the netlib backend:
https://gist.github.com/carschno/10ffd71dd57da03dfeb9

This might be related to https://github.com/deeplearning4j/deeplearning4j/issues/818.

**Comment by AlexDBlack** [comment]
The provided unit test creates an NDArray with shape [1,4] (1 row, 4 col), then sorts dimension 0 (rows)
In this case: expected output is indices [0,0,0,0] and values same as input.
Use Nd4j.create(double[], int[]) to create a column vector.

Row vector + sorting along dimension 1 (columns - i.e., Nd4j.sortWithIndices(toSort, 1, true)) causes unit test to pass.
Column vector + sorting along dimension 0 causes unit test to pass.

Closing this.
