### ISSUE TITLE
Infinite loop in DefaultOpExecutioner

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#479]
Here's example code, based on dl4j-0.4-examples DeepAutoEncoder example.

https://gist.github.com/raver119/98c5003509cf134aabb1

On nd4j-x86 0.4-rc3.5 it causes something like infinte loop in DefaultOpExecutioner, 
Starting sequence at <b>exec</b> function, at line 92, 
in between lines 414 and 432.
Debugger shows, that Shape.iterate loops forever. 

Current master branch on the same code throws following exception:
https://gist.github.com/raver119/55933dd11371deb60eb0

Please note: in both cases, rc3.5 and current master issue happens at the last layer training, and in DefaultOpExecutioner.exec command chain.

**Comment by AlexDBlack** [comment]
This was due to an issue in DL4J that is now fixed. Current version properly catches incorrect shape and throws exception.
https://github.com/deeplearning4j/deeplearning4j/pull/833
