### ISSUE TITLE
ArrayUtil.toNDArray(int[][] nums) only takes the first row

### ISSUE THREAD

**Issue by Sebubu** [deeplearning4j/nd4j#48]
public static INDArray toNDArray(int[][] nums) {
        if (Nd4j.dataType() == DataBuffer.DOUBLE) {
            double[] doubles = toDoubles(nums);
            INDArray create = Nd4j.create(doubles, new int[]{1, nums.length});
            return create;
        } else {
            float[] doubles = toFloats(nums);
            INDArray create = Nd4j.create(doubles, new int[]{1, nums.length});
            return create;
        }
    }

There is a issue in the function above.
INDArray create = Nd4j.create(doubles, new int[]{1, nums.length});
Here it creates a new INDArray with 1 row instead of nums[0].length.

I've found the problem within my tests with the ImageVectorizer of deepleaning4j. Currently this class loads only the first row of pixels.

I wanted to do a pull request, but I can't run the nd4j project. ND4j.initContext() has a problem to find the LINALG_PROPS(nd4j.properties). Wired...

Kind regards
Sevi

**Comment by agibsonccc** [comment]
Put nd4j-jblas or one of the nd4j backends and you'll be set. We say this on the nd4j site as well as deepleanring4j.

If you are getting anything not found, please ensure the latest version is installed. I look forward to the pull request. I'll close this when it's received. 

Thanks!
