### ISSUE TITLE
Missing library file.  

### ISSUE THREAD

**Issue by tlasseter** [deeplearning4j/nd4j#482]
I'm running x64 on Wiindows 7 using IntelliJ.  In trying to run DBNIrisExample, I get the following exception: 

Exception in thread "main" java.lang.ExceptionInInitializerError: unable to load from [netlib-native_system-win-x86_64.dll]  (  See Gist tlasseter/dl4j_bug1  ).

This file should be in the dependencies I would think.  I downloaded the required dll from mvn 
but the downloaded file from the maven repo is named: netlib-native_system-win-x86_64-1.1.dll.

There is an older version named netlib-native_system-win-x86_64.dll, but presumably we want the latest (greatest?).  

So it needs to be renamed for the loader to find it.  

I was told that it in turn requires 6 other *.dll files which I also downloaded manually: 

libgcc_s_seh-1.dll
libgfortran-3.dll
libquadmath-0.dll
libwinpthread-1.dll
libblas3.dll
liblapack3.dll

These should also be in the dependencies, right?

**Comment by AlexDBlack** [comment]
See http://nd4j.org/getstarted.html#open
specifically section "For OpenBlas on Windows..."
If you are still having trouble, please talk to us on Gitter: https://gitter.im/deeplearning4j/deeplearning4j
