### ISSUE TITLE
Zero vector as result of matrix-vector multiplication

### ISSUE THREAD

**Issue by rockt** [deeplearning4j/nd4j#486]
Based on the [tutorial](http://nd4j.org/matrixwise.html) I wrote the following simple code that should perform a matrix vector product.

```java
    public static void main(String[] args) {
        INDArray nd2 = Nd4j.create(new float[]{3, 4}, new int[]{2, 1}); //column vector
        INDArray nd4 = Nd4j.create(new float[]{3,4,5,6},new int[]{2, 2});
        System.out.println("nd4\n" + nd4);
        System.out.println("nd2\n" + nd2);
        System.out.println("res\n" + nd4.mmul(nd2));
    }
```

It gives me the following strange result.

```
[main] INFO org.reflections.Reflections - Reflections took 326 ms to scan 3 urls, producing 82 keys and 375 values 
nd4
[[3.00,4.00]
 [5.00,6.00]]
nd2
[ 3.00, 4.00]
-- org.jblas INFO Deleting /var/folders/ys/hqpkdtqj373d8d_4xjwwd16m0000gn/T/jblas3428166547944317656/libjblas.dylib
-- org.jblas INFO Deleting /var/folders/ys/hqpkdtqj373d8d_4xjwwd16m0000gn/T/jblas3428166547944317656/libjblas_arch_flavor.dylib
-- org.jblas INFO Deleting /var/folders/ys/hqpkdtqj373d8d_4xjwwd16m0000gn/T/jblas3428166547944317656
res
[ 0.00, 0.00]

Process finished with exit code 0
```

Any ideas what might be happening here? Am I doing something wrong?

**Comment by AlexDBlack** [comment]
I have tested this on x86 backend (current nd4j master) and it gives the correct output.
Confirmed that jblas given incorrect (zero) output on jblas.

We will likely be retiring the jblas backend, plase use x86 (which is much faster anyway).

**Comment by rockt** [comment]
Thanks for the quick reply. Is there a pointer to how I can switch to x86?

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/pom.xml#L54
i.e., change your pom: nd4j-jblas -> nd4j-x86
btw feel free to talk on gitter if you have any issues: https://gitter.im/deeplearning4j/deeplearning4j

**Comment by KIC** [comment]
This is a serious bug! and took me hours to find out .. I would really appreciate when you could fix this or remove the jblas support as a whole.

**Comment by agibsonccc** [comment]
We are removing jblas support actually. We are mainly using x86. I'm closing this in light of that.

**Comment by KIC** [comment]
Just in case someone is interested, the results are also fine with netlib-blas.

**Comment by agibsonccc** [comment]
We are also removing support for net lib ;). x86 will be the one cpu backend. That will simplfiy things on both us and the user.
