### ISSUE TITLE
CUDA kernel compilation on Windows not yet supported

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#502]
Kernel complication uses process builder + bash + make:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-jcublas-parent/nd4j-jcublas-7.5/src/main/java/org/nd4j/linalg/jcublas/kernel/KernelFunctionLoader.java#L307

This obviously doesn't work for Windows: no bash on Windows, and no make by default

java.io.IOException: Cannot run program "bash" (in directory "C:\Users\Alex\AppData\Local\Temp\nd4j-kernels"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.loadCudaKernels(KernelFunctionLoader.java:312)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:245)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.compileAndLoad(KernelFunctionLoader.java:200)
	at org.nd4j.linalg.jcublas.kernel.KernelFunctionLoader.load(KernelFunctionLoader.java:167)

**Comment by jaycaz** [comment]
Hi @AlexDBlack, I'm also using Windows and, although I've been running into other issues, I managed to fix the bash issue by using a Windows bash program.  There are a few available, such as Cygwin, MinGW, or Babun.  You can install one of these programs and, wherever it's installed, it should have a "bin" folder with "bash.exe" inside.  Add the path to the folder to your PATH environment variable, and the bash error should go away.

**Comment by AlexDBlack** [comment]
This issue is more of a todo list than anything.
Thanks for the suggestions, but we need to (and intend to) properly support compilation of cuda kernels on Windows, without having to do those sorts of workarounds. Bash vs. cmd is probably the easiest to solve; there's a bunch of others (mostly related to make) that also need fixing on Windows. At any rate, proper Windows support should be part of the next release (along with instructions etc), I'm just waiting on the final work on cuda kernel etc before I properly implement this.

**Comment by EronWright** [comment]
@AlexDBlack I believe the recommended approach is to leverage the PTX intermediate format.   The nd4j build process should make PTX files using nvcc, and embed them into the nd4j JAR.   The kernel source files need not be included.  At runtime, the driver will JIT-compile the PTX files into device-specific executable code.    This approach will eliminate the runtime dependency on make/gcc/nvcc altogether.

**Comment by AlexDBlack** [comment]
Right, that certainly sounds like a much better solution
@agibsonccc @raver119

**Comment by agibsonccc** [comment]
Everything has a reason: http://forum.byte-welt.net/byte-welt-projekte-projects/swogl-jcuda-jocl/jcuda/17557-dynamic-parallelism.html ;)

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/issues/555
