### ISSUE TITLE
Dependency issue - remove spring

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#519]
We are only using it for the classpath resource. It would be great if we just had our own fork of the classpath resource embedded in the project. This would greatly reduce jar file size.

**Comment by raver119** [comment]
As for nlp use, there'll be no need for it at all, since i've already added InputStream-based iterators into d2v pack of changes at forked repo.

So, there's like 1 string of code can be used: YourClass.class.getResourceAsStream("SomeFile.txt");

**Comment by raver119** [comment]
Oh, sry, that's nd4j repo issues :(

**Comment by agibsonccc** [comment]
getResourceAsStream doesn't resolve nearly as nicely. I've ran in to all sorts of strange null edge cases with it (especially when you start talking about deployment in a jar vs the eclipse/intellij environments)

**Comment by raver119** [comment]
It just requires more thouroughly testing. If the only need of jar reading is file access, i think i can handle it after i'm done with d2v.

**Comment by raver119** [comment]
I've added ClassPathResource implementation into Canova

https://github.com/deeplearning4j/Canova/commit/ef07cd5ba5607bbefdf8106a17318e17d10e9fdd

**Comment by agibsonccc** [comment]
I've removed it from here as well.
