### ISSUE TITLE
Get slices of dimension 2 from a Tensor created by Nd4j.rand(new int[]{7,7,3}) doesn't work as expected / numpy

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#53]
I guess I found an error in Nd4J, I m not sure. Can somebody help me please? I debuged my code a lot of time and now I found thats the error could be in this method:

embeddingSize = 7
sliceSize= 3

INDArray wTest = Nd4j.rand(new int[]{embeddingSize,embeddingSize,sliceSize});
System.out.println("wTest: "+ wTest);
for (int slice = 0; slice < sliceSize; slice++) {
                INDArray sliceOfW = Nd4j.rand(new int[]{embeddingSize,embeddingSize,5}).slice(slice,2);
                System.out.println("W slice "+slice+" :"+ "" +"rows: "+ sliceOfW.rows() + " | col: "+sliceOfW.columns());    
}

Output:
wTest: [[[0.7200214228267641, 0.7202750076975886, 0.7718032292076493]
 [0.38765444669951377, 0.32369460683644036, 0.7058093564827723]
  ,[0.3343151859432618, 0.46628826961565206, 0.07034136976033589]
 ]
[[0.2641282865265637, 0.28981887290062436, 0.8153072824629022]
 [0.24904016001437213, 0.41339034130097274, 0.30997688472127116]
  ,[0.9127800270142215, 0.4855833310988886, 0.6287827519788904]
 ]
 ,[[0.7927622926214546, 0.8119690207554953, 0.46370021076447787]
 [0.1492103759333565, 0.6069449427179854, 0.5789931861501005]
  ,[0.10624927638491166, 0.9482597509375716, 0.3238692062641324]
 ]
]
W slice 0 :rows: 7 | col: 7
W slice 1 :rows: 7 | col: 7
W slice 2 :rows: 7 | col: 3

I think the last slice of this tensor should have 7 columns, too! Is it a failure of using or in the ND4J code?

**Comment by agibsonccc** [comment]
Did you try this?

    @Test
    public void testMultipleSlices() {
        int embeddingSize = 7;
        int sliceSize= 3;

        INDArray wTest = Nd4j.rand(new int[]{embeddingSize,embeddingSize,sliceSize});
        System.out.println("wTest: "+ wTest);
        for (int slice = 0; slice < wTest.slices(); slice++) {
            INDArray sliceOfW = wTest.slice(slice);
            System.out.println("W slice "+slice+" :"+ "" +"rows: "+ sliceOfW.rows() + " | col: " +sliceOfW.columns());

        }


    }

**Comment by c0der1337** [comment]
Hey Adam, 

thanks for your response. The code that I posted above has a mistake through a lot of testing. 

I want to get the slices of dimension 2. My intention was to create something similar to 
W = numpy.random.random((7,7,3)) and then I want to access the slice of dimension 2 with W[:,:,slice] , for slice 0,1,2 ... . 
![slices_correct](https://cloud.githubusercontent.com/assets/6539636/6942491/425612b8-d888-11e4-8356-8bb335b378b0.png)

But when I try this with ND4J I use your code:
[code]
	    int embeddingSize = 7;
	    int sliceSize= 3;

	    INDArray wTest = Nd4j.rand(new int[]{embeddingSize,embeddingSize,sliceSize});
	    System.out.println("wTest: "+ wTest);
	    for (int slice = 0; slice < wTest.slices(); slice++) {
	        INDArray sliceOfW = wTest.slice(slice,2);
	        System.out.println("W slice "+slice+" :"+ "" +"rows: "+ sliceOfW.rows() + " | col: " +sliceOfW.columns());
[/code]

I got as output:
[code]
wTest: [[[0.46807225416806264, 0.28237531724113096, 0.9180362239009829]
 [0.27181003328932274, 0.3597549440460759, 0.7439247897994679]
  ,[0.5298566335415522, 0.5971238485238259, 0.9664393208164594]
 ]
[[0.09990938429849461, 0.24080991518818662, 0.608016542801376]
 [0.5672097360892319, 0.6637712464956169, 0.6341546852385245]
  ,[0.7548099359540081, 0.8159462147524887, 0.1890823096114429]
 ]
 ,[[0.8298506359376079, 0.46611267139181, 0.17966076308777557]
 [0.9392845841223807, 0.39534184897475444, 0.9990017867863641]
  ,[0.8788192588815877, 0.4375749012209509, 0.9765185717659335]
 ]
]

W slice 0 :rows: 7 | col: 7
W slice 1 :rows: 7 | col: 7
W slice 2 :rows: 7 | col: 3
W slice 3 :rows: 7 | col: 7
W slice 4 :rows: 7 | col: 7
W slice 5 :rows: 7 | col: 7
W slice 6 :rows: 7 | col: 7
[/code]

 Output with corresponding slice:
[code]
W slice 0 :rows: 7 | col: 7
[[0.8756196681595723, 0.6605887230946861, 0.027275054596501924, 0.39805201963537273, , ..., 0.4875733483960496, 0.7963800909449643, 0.23138724269384348]
 [0.35161940972354433, 0.7457842089536002, 0.755348831743379, 0.13769265654393892, , ..., 0.38976242404691774, 0.9411755914481965, 0.5730059091423194]
  ,[0.23992067172171616, 0.32410723148696463, 0.4846889187527672, 0.5797645912743672, , ..., 0.4607358262148067, 0.5188423195590264, 0.18547784911438914]
 ]

W slice 1 :rows: 7 | col: 7
[[0.18203544927492987, 0.5557234297220821, 0.33236579974579694, 0.7627532121558889, , ..., 0.08032433621067692, 0.1470013289513621, 0.4025641333196661]
 [0.6662214013183856, 0.8333696035531701, 0.4189728696500563, 0.06581520630433979, , ..., 0.8497750305722442, 0.3609561775924168, 0.22738193338352009]
  ,[0.18887365942095036, 0.374778790611739, 0.3294992648517845, 0.37012482391341583, , ..., 0.0713271511082707, 0.6781226026300771, 0.14917266183939093]
 ]

W slice 2 :rows: 7 | col: 3
[[0.23992067172171616, 0.18887365942095036, 0.48007829115673006]
 [0.32410723148696463, 0.374778790611739, 0.3823265543944443]
  ,[0.4846889187527672, 0.3294992648517845, 0.9131889598938545]
 ]

W slice 3 :rows: 7 | col: 7
Exception in thread "main" java.lang.IllegalArgumentException: Illegal index 147 derived from 0 with offset of 147 and stride of 7
	at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2575)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.getDouble(BaseNDArray.java:2858)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:3840)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.toString(BaseNDArray.java:3868)
	at java.lang.String.valueOf(String.java:2854)
	at java.io.PrintStream.println(PrintStream.java:821)
	at org.deeplearning4j.models.ntn.Run_NTN.main(Run_NTN.java:83)
[/code]


My issue is, why the 3. slice or slice = 2 has only 3 columns and not 7? Why there are 7 slices when I slice dimension 2?

So please reopen the issue... thanks in advance for your support

**Comment by c0der1337** [comment]
Here is a little workaround to get correct slices of dimension=2 / 3. dimension of a tensor

static INDArray getSliceOfaTensor(INDArray tensor, int numOfSlice){
		//create the slice array	
		INDArray slice = Nd4j.zeros(tensor.slices(), tensor.slice(0).rows());
		//check for maximum possible slices
		if (numOfSlice<tensor.slice(0).columns()) {
			//extract the column of numOfSlice from each of the false slices
			for (int i = 0; i < tensor.slices(); i++) {
				//extract with getScalar, because slice.getColumn(1) on getSlice() returns false values
				INDArray sliceRow = Nd4j.zeros(1, tensor.slice(0).rows());				
				for (int row = 0; row < tensor.slice(0).rows(); row++){
					//slice.putRow(i, tensor.slice(i).getColumn(numOfSlice).swapAxes(0, 1));
					sliceRow.put(row, tensor.slice(i).getScalar(row, numOfSlice));
				}
				slice.putRow(i, sliceRow);
			}
		}else {
			System.out.println("Your Tensor has only "+tensor.slice(0).columns()+"-1 slices to extract");
		}		
		return slice;	
	}

I will try to fix it in nd4j the next days...

**Comment by agibsonccc** [comment]
Fixed the 2 related issues.
