### ISSUE TITLE
randomness in DataSet#splitTestAndTrain 

### ISSUE THREAD

**Issue by sato-cloudian** [deeplearning4j/nd4j#536]
Consider the following example from DBNIrisExample.

```
        log.info("Load data....");
        DataSetIterator iter = new IrisDataSetIterator(batchSize, numSamples);
        DataSet next = iter.next();
        next.normalizeZeroMeanZeroUnitVariance();

        log.info("Split data....");
        SplitTestAndTrain testAndTrain = next.splitTestAndTrain(splitTrainNum, new Random(seed));
        DataSet train = testAndTrain.getTrain();
        DataSet test = testAndTrain.getTest();
```

The training is done on "train" set. And evaluation is done on "test" set.

The method accepts Random object. But it simply returns two data set split at splitTrainNum.

Since the iris data set is ordered by class in ascending order, the training is biased towards 0 and 1. While the evaluation is made mostly against 2.

I suggest to add randomness to splitTestAndTrain implementation to improve the experience of examples and the usability of the API.

**Comment by LostSummer233** [comment]
Call Nd4j.shuffle twice will fix that. Though, the shuffled result is imbalanced due to the own problem in Nd4j.shuffle

**Comment by chrisvnicholson** [comment]
re: LostSummer33's comment, see this issue https://github.com/deeplearning4j/nd4j/issues/537

**Comment by eraly** [comment]
Outdated. Closing
