### ISSUE TITLE
Support Singular Value Decomposition in CUDA

### ISSUE THREAD

**Issue by taisukeoe** [deeplearning4j/nd4j#540]
Like `numpy.linalg.svd`, SVD is quite useful e.g. whitening of image as pre-processing.

http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linalg.svd.html

While LAPACK for CPU is already prepared in ND4J and LAPACK includes `dgesdd` for SVD, LAPACK for CUDA is not supported yet. So please let me file an issue here.

https://github.com/deeplearning4j/nd4j/blob/df24b0274dc26bb3c9a5ad4a20605bfc521ab961/nd4j-x86/src/main/java/org/nd4j/linalg/cpu/blas/CpuLapack.java

https://github.com/deeplearning4j/nd4j/blob/df24b0274dc26bb3c9a5ad4a20605bfc521ab961/nd4j-jcublas-parent/nd4j-jcublas-7.5/src/main/java/org/nd4j/linalg/jcublas/blas/JcublasLapack.java

**Comment by huitseeker** [comment]
SVD is supported by sgesvd in https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/linalg/jcublas/blas/JcublasLapack.java#L631
