### ISSUE TITLE
struggling with nd4j-jcublas initialization

### ISSUE THREAD

**Issue by newikov** [deeplearning4j/nd4j#550]
Hi, 

I'm getting the following error .. 

Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.newikov.neuralnetworks.arquitecture.TestNd4JCuda.main(TestNd4JCuda.java:11)
Caused by: java.lang.RuntimeException: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4525)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:141)
	... 1 more
Caused by: org.nd4j.linalg.factory.Nd4jBackend$NoAvailableBackendException
	at org.nd4j.linalg.factory.Nd4jBackend.load(Nd4jBackend.java:148)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:4522)
	... 2 more

Can you help me with this? I have been trying to get it running for about a week. I followed absolutely all instructions i have on nd4j manuals. Fixed some other errors on the way. I'm using the latest nd4j version 0.4-rc3.8. 

I completed the following steps: 

1. Added path to cl.exe C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin to the PATH 

2. Added to the PATH the folder with: libblas3.dll, libgcc_s_seh-1.dll, libgfortran-3.dll, 
liblapack3.dll, libopenblas.dll, libquadmath-0.dll, netlib-native_system-win-x86_64-1.1.dll 

2. I have NVIDIA GTX 980 TI. It's working ok. I checked with Theano/Lasange, Caffe and Aparapi for Java. 

in pom.xml i have the following

	<properties>
		<nd4j.version>0.4-rc3.8</nd4j.version>
	</properties>

	<dependencies>

		

		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-jcublas-7.0</artifactId>
			<version>${nd4j.version}</version>
		</dependency>

		

		<dependency>
			<groupId>org.nd4j</groupId>
			<artifactId>nd4j-api</artifactId>
			<version>${nd4j.version} </version>
		</dependency>

		<dependency>
			<groupId>com.googlecode.combinatoricslib</groupId>
			<artifactId>combinatoricslib</artifactId>
			<version>2.1</version>
		</dependency>

	</dependencies>
</project>

What could be the reason? 

I would really appreciate any help. 

Thank you for your time!

**Comment by agibsonccc** [comment]
Please come in to gitter for these kinds of questions. We put it on every page of the site for a reason. Thanks! 
https://gitter.im/deeplearning4j/deeplearning4j
