### ISSUE TITLE
Optimize BaseNDArrayFactory.toFlattened

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#553]
Multiple toFlattened methods utilize NDArrayIndexIterator; this is slow and inherently single threaded.
It would be faster to use an assign call here.

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseNDArrayFactory.java

**Comment by agibsonccc** [comment]
Fixed;
