### ISSUE TITLE
GPU Status

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#555]
Keep an eye on this repo:

https://github.com/deeplearning4j/nativeoperations

This is a new c/c++ core for all of nd4j. This is making it more economical for us to do cuda as well as 
have a unified code base for native code and unit tests. I will be closing any gpu issues and posting here with an update.

**Comment by andreas-eberle** [comment]
What is the status on this? I'm currently not able to use deeplearning4j with CUDA and it seams that many others are also not able to use it.

Is deeplearning4j currently even supporting CUDA (with so many bugs just closed and linked to an "enhancement" issue)?

**Comment by treo** [comment]
As far as I can tell cuda is being actively worked on but not yet ready for general use.

**Comment by AlexDBlack** [comment]
@andreas-eberle We've been pretty open about the fact that we are in the middle of a significant rewrite for our cuda code, and that it's not ready for use (past versions of our cuda backend worked (provided correct results), but had poor performance). If you don't want to help fix bugs or deal with compiling from source, then wait until the next release.
If you do want to keep an eye on things and/or test things before the release, (or just talk about this) then I suggest hanging around here: https://gitter.im/deeplearning4j/deeplearning4j/earlyadopters

**Comment by andreas-eberle** [comment]
Thanks for the update. I think it is important to have this information in this central ticket instead of parts of it in different tickets (to your advantage). 

Can you tell me, which version is the latest stable version that was able to use CUDA (in which version)?

**Comment by agibsonccc** [comment]
@andreas-eberle agreed. It's just moving so fast right now little bandwidth to update it. It's not like development is happening behind closed doors. You are welcome to ask in the channel where we are at right now.

**Comment by agibsonccc** [comment]
Closing in favor of: https://github.com/deeplearning4j/nd4j/issues/848

3 tests left to get going. We're almost there!
