### ISSUE TITLE
LD_LIBRARY_PATH in pom.xml

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#56]
Hi, I had to change https://github.com/deeplearning4j/nd4j/blob/656855ca48bf16386ab87e3c60b9804e1800c311/pom.xml#L183 to:
```xml
<LD_LIBRARY_PATH>${env.LD_LIBRARY_PATH}:${user.dir}</LD_LIBRARY_PATH>
```

Without it, it couldn't find the cuda libs.

**Comment by agibsonccc** [comment]
Fixed.
