### ISSUE TITLE
Add license to pom file

### ISSUE THREAD

**Issue by benmccann** [deeplearning4j/nd4j#564]
Thank you for licensing under Apache License Version 2.0. We have tools which automatically report the license of libraries that we use by looking in the pom file.

Please add the following to the pom file so that automated tools can run license detection:

    <licenses>
      <license>
        <name>Apache License, Version 2.0</name>
        <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        <distribution>repo</distribution>
      </license>
    </licenses>

**Comment by chrisvnicholson** [comment]
done

**Comment by benmccann** [comment]
Thanks!
