### ISSUE TITLE
JavaDoc typo in the INDArray.java

### ISSUE THREAD

**Issue by 125626748** [deeplearning4j/nd4j#565]
**1**
INDArray.cumsum has the documentation (in place) while cumsumi doesn't have.
**2**
INDArray.eq documented as less than operation, the same as eqi.

**Comment by chrisvnicholson** [comment]
i don't understand what we need to change. but you can fix the typo here: https://github.com/deeplearning4j/nd4j/blob/e6af42a708624bd9cf9f4bd394c3fae0bac11974/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/INDArray.java

**Comment by 125626748** [comment]
OK, I fix the cumsum doc
