### ISSUE TITLE
Broken IMax in java version (already fixed in libnd4j)

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#570]
IMax should be returning 3 for this. I'm seeing it return 11 for multi index
[[[1.00,2.00,3.00]
[4.00,5.00,6.00]]
[[7.00,8.00,9.00]
[10.00,11.00,12.00]]]
2,2,3
Nd4j.getExecutioner.exec(new IMax(arr),0,1)
res6: org.nd4j.linalg.api.ndarray.INDArray = [ 11.00, 11.00, 11.00]
tad length is 4
that should be 3
here's the first tad:
[[1.00,7.00]
[4.00,10.00]]

This is fixed in libnd4j. This is a bug in the java version.

**Comment by Zixxy** [comment]
@agibsonccc asked me on chat to add this code to issue:

```
INDArray arr = Nd4j.linspace(1,12,12).reshape(2,2,3);
INDArray result = Nd4j.getExecutioner().exec(new IMax(arr), 0, 1);
```
// after computation:
result = [ 11.00, 11.00, 11.00]

the same result on current master and also in stable release 0.4-rc3.8.
And that is considered wrong. 


I am not sure what should be correct than..[5.0, 5.0] ?? or [3.0, 3.0, 3.0] ?? I couldn't deduce that from documentation, neither tests on lower dimensions.

**Comment by agibsonccc** [comment]
Redundant with libnd4j being the only backend.
