### ISSUE TITLE
DataSet.splitTestAndTrain: Random argument ignored

### ISSUE THREAD

**Issue by danielnaber** [deeplearning4j/nd4j#574]
At https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/dataset/DataSet.java#L688, the random argument doesn't seem to be used at all. If that happens for a reason, it should probably be documented in the javadoc do avoid confusion.

~~Even if it was used, in https://github.com/deeplearning4j/dl4j-0.4-examples/blob/master/src/main/java/org/deeplearning4j/examples/mlp/MLPMnistCMGSExample.java#L62 a new `Random`  is created every time in the loop, but with the same seed. That looks wrong?~~

**Comment by eraly** [comment]
Merged PR. Closing.
