### ISSUE TITLE
Tests fail on Jenkins as of 139b75e2c185a74d6b79990763c70ad3d806ec7b

### ISSUE THREAD

**Issue by mkocikowski** [deeplearning4j/nd4j#578]
Currently the nd4j Jenkins job runs with `-DskipTests` because the tests fail. I am not sure what the problem is - is it the tests, or the way the Jenkins is set up (or maybe how libnd4j is built?). Please have a look: https://52.36.50.179/job/nd4j/14/console

**Comment by agibsonccc** [comment]
All tests passing now.
