### ISSUE TITLE
List of performance issues on current master (x86 + non-backend-specific)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#583]
Current biggest optimization issues:
- Nd4j.toFlattened
- assign

MnistAnomalyExample: Biggest bottleneck is Nd4j.toFlattened (due to getDouble and putScalar):
![image](https://cloud.githubusercontent.com/assets/2360237/13032025/dbae72c0-d337-11e5-9636-e318fdac70a6.png)

GravesLSTMCharModellingExample: perhaps the biggest bottleneck here is assign (assign is used in multiple places: directly, plus in some reshape-with-copy ops, also in dup->CopyOp->assign). Seems this is at least in part due to getting shape info for each element:
![image](https://cloud.githubusercontent.com/assets/2360237/13032073/60e1ee94-d339-11e5-95ed-67dbe38231d0.png)

LenetMnistExample: toFlattened (~18% total cost); assign (within tensorMmul reshape operation - 60-70% of total cost?)
![image](https://cloud.githubusercontent.com/assets/2360237/13032115/bdc11eea-d33a-11e5-9729-49fd07f99e69.png)

**Comment by raver119** [comment]
raw buffer access will also be the issue for CUDA backend, since it will cause device -> host and further host->device memory updates.

**Comment by agibsonccc** [comment]
Fixed.
