### ISSUE TITLE
Ensure all special cases for ops (weird strides) are tested and handled in new code

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#588]
Example:

```java
public class Temp {
    public static void main(String[] args){
        List<Pair<INDArray,String>> list = NDArrayCreationUtil.getAll3dTestArraysWithShape(123,3,4,5);
        for(Pair<INDArray,String> p : list){
            System.out.println(Arrays.toString(p.getFirst().stride()));
        }
    }
}
```

Note that a number of these arrays have strides that are not strictly ascending or descending (hence aren't strictly speaking c or f order):
[20, 5, 1]
[1, 3, 12]
[20, 5, 1]
[45, 5, 1]
[40, 10, 1]
[90, 10, 1]
[3, 9, 36]
[1, 1]
[1, 3, 12]
[60, 1, 12]   *****
[1, 45, 3]    *****
[1, 15, 3]    *****
[20, 5, 1]

**Comment by agibsonccc** [comment]
This is out of date now.
