### ISSUE TITLE
Add element-wise power operations (inc. row/column ops)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#591]
Currently, we have row/column operations for add/subtract/multiply/divide, etc. No option to do element-wise power, x^y (can only do x^scalar currently). This would be x.pow(y), x.powiRowVector(y) and x.powiColumnVector(y), with both x and y being INDArrays.

This would occasionally be useful in certain contexts (one example in calculating the Kumaraswamy distribution PDF and CDF, https://en.wikipedia.org/wiki/Kumaraswamy_distribution, with different a/b parameters on each column)

**Comment by raver119** [comment]
Pairwise POW is available now.
