### ISSUE TITLE
out of date doc for DataSetIterator @ idosi.com?

### ISSUE THREAD

**Issue by joachimdb** [deeplearning4j/nd4j#596]
joachimdb 21:03
Quick question: anything up with DataSetIterator in nd4j? I find the doc at http://idosi.com/javadoc/DL4J/org/nd4j/linalg/dataset/api/iterator/DataSetIterator.html, but not at http://nd4j.org/apidocs/org/nd4j/linalg/dataset/api/iterator/DataSetIterator.html

agibsonccc 21:04
@joachimdb please use nd4j.org
the idosi stuff is out of date
thanks for flagging that
mind filing an issue?

**Comment by chrisvnicholson** [comment]
The link changed: 
http://nd4j.org/doc/org/nd4j/linalg/dataset/api/iterator/DataSetIterator.html
