### ISSUE TITLE
ND4J - Issues During BLAS setup for Amazon Linux AMI

### ISSUE THREAD

**Issue by vvpreetham** [deeplearning4j/nd4j#600]
ND4J on Amazon Linux AMI (have tried T2 instances types)... requires the following exact steps to install the BLAS/lapack libraries.

Disclaimer: This is for 64 bit only

Disclaimer** : PLEASE REMOVE OpenBLAS if you have already installed it as the Amazon 64bit Linux distros continues to have problems not able to find the netlib-native_system-linux-x86_64.so

Once you create and setup your Amazon Linux Instance (and clone your Canova, DL4J, ND4J, etc repos).. you have to follow these instructions to setup your blas/lapack math libs..

sudo yum install -y lapack-devel blas-devel 

 (I was assuming that just the blas and lapack devel was good enough to run ND4J but was getting the following error POST loading the netlib-native_system-linux-x86_64.so

ERROR : ......“undefined reference to 'cblas_ddot'” when using cblas library ....

to circumvent this I had to also load 

**sudo yum -y install atlas-sse3-devel**

The atlas-sse3-devel seems to contain the cblas library that is required for blas. 

This resolved my issues of successfully running both Java as well as Scala libraries from ND4J (and DL4J along with Scala Stubs)

**Comment by agibsonccc** [comment]
@chrisvnicholson this is a doc issue. Mention this in the nd4j installation.
