### ISSUE TITLE
Documentation: Custom loss functions/ Integration into Optimizers

### ISSUE THREAD

**Issue by mschaars** [deeplearning4j/nd4j#604]
It is currently not documented/clear how to interface custom loss functions: 

Research literature often derives custom loss function expressions. It would be helpful if documentation would point to an example or explain how to use these within the Optimization framework, e.g. if I have a specific loss expression that I want to use to perform RMSProp.

**Comment by eraly** [comment]
Custom Loss Functions are available and an example is in the example repo.
