### ISSUE TITLE
DataSet: handle normalization for 3d (time series) data

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#607]
Currently, normalization in DataSet for 3d data won't work (can't do a subiRowVector on 2d return value from mean(0)/std(0)).

https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/dataset/DataSet.java#L462

Solution here is to calculate means/variances along 2 dimensions (both 0 and 2) instead of just along dimension 0. Also (importantly) when a feature mask array is present, the means/sums shouldn't include the masked time steps.

**Comment by agibsonccc** [comment]
Isn't this solved now?

**Comment by eraly** [comment]
https://github.com/deeplearning4j/nd4j/pull/1114
