### ISSUE TITLE
INDArray serialization on views broken (x86 backend)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#608]
The following code fails on x86 backend. The issue seems to be specifically due to serialization on views (issue is also impacting spark training).

```java
    @Test
    public void testSerialization() throws Exception {

        INDArray[] arr = new INDArray[]{
                Nd4j.ones(1,10),
                Nd4j.ones(5,10).getRow(2)
        };

        for( INDArray a : arr ){
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            try(ObjectOutputStream oos = new ObjectOutputStream(baos)){
                oos.writeObject(a);
            }

            byte[] bytes = baos.toByteArray();

            ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
            ObjectInputStream ois = new ObjectInputStream(bais);

            INDArray aDeserialized = (INDArray)ois.readObject();

            System.out.println(aDeserialized);
            assertEquals(Nd4j.ones(1,10),aDeserialized);
        }
    }
```

**Comment by AlexDBlack** [comment]
Update: This appears to be a problem with the DataBuffer length. The FloatBuffer on the getRow view should have a length of 10, but has a length of 30:
![image](https://cloud.githubusercontent.com/assets/2360237/13348654/cc15696e-dcc8-11e5-9be9-b6ca0427d5c9.png)


I believe the cause of the incorrect length value is the Nd4j.createBuffer(DataBuffer,int) method: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/factory/Nd4j.java#L956-956
The underlying length is 50 (5x10) and the offset 20 (3rd row) resulting in a length of 30 for the row, not the correct value of 10.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/620
