### ISSUE TITLE
Javacpp compile issue on osx

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#625]
https://gist.github.com/nyghtowl/ec78cc293c6f003d6adf

https://gist.github.com/nyghtowl/77e0b87e7cde915a2664

@agibsonccc

**Comment by saudet** [comment]
Using `long long` instead of `long` in C++ will fix this. The same kind of thing will happen on Windows as well because `long` is always 32-bit on that platform...

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/libnd4j/commit/93c9454927d4bae83c62244663d444da0ae1d440
