### ISSUE TITLE
ND4j.Sum on axis/dimension=1 returns a row vector instead of a column vector

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#63]
Hello guys,

For me meant to sum on axis 1 to sum over all columns, so I should receive a columon vector with (14,1). Instate I got a row vector with (1,14)?

                INDArray test = Nd4j.rand(14,4);
                System.out.println("_TEST"+test + ": rows: "+test.rows()+"|columns: "+test.columns());
                test = Nd4j.sum(test,1);
                System.out.println("_TEST"+test + ": rows: "+test.rows()+"|columns: "+test.columns());

Output:
_TEST[[-0.6503771530244814, -0.09711740662728431, -0.4572625595744501, -1.209913733312069]
 [0.29042888218949964, 0.6907569104940962, -0.44769136544368654, -1.8051549580705541]
  ,[1.1440285483512203, 0.31564186879493294, 0.4548678321481088, -0.055579811942328854]
 ]
: rows: 14|columns: 4

_TEST[-2.414670852538285, -1.2716605308306448, 1.8589584373519332, 2.1447850164735573, , ..., 1.1077631068954537, -1.3298955523074434, -0.826947892660828]
 : rows: 1|columns: 14

Sure, I can use the transpose method to create the column vector. However a column vector as result is more intuitive. What do you think?

**Comment by agibsonccc** [comment]
>>> import numpy as np
>>> linspace = 14 * 4
>>> a = np.linspace(1,linspace,linspace).reshape(14,4,order='f')
>>> a
array([[  1.,  15.,  29.,  43.],
       [  2.,  16.,  30.,  44.],
       [  3.,  17.,  31.,  45.],
       [  4.,  18.,  32.,  46.],
       [  5.,  19.,  33.,  47.],
       [  6.,  20.,  34.,  48.],
       [  7.,  21.,  35.,  49.],
       [  8.,  22.,  36.,  50.],
       [  9.,  23.,  37.,  51.],
       [ 10.,  24.,  38.,  52.],
       [ 11.,  25.,  39.,  53.],
       [ 12.,  26.,  40.,  54.],
       [ 13.,  27.,  41.,  55.],
       [ 14.,  28.,  42.,  56.]])
>>> a.sum(1)
array([  88.,   92.,   96.,  100.,  104.,  108.,  112.,  116.,  120.,
        124.,  128.,  132.,  136.,  140.])
>>> a.sum(1).shape
(14,)


Not consistent with numpy behavior. Closing.
