### ISSUE TITLE
Poor performance and Unsafe.park

### ISSUE THREAD

**Issue by bennylut** [deeplearning4j/nd4j#632]
I am evaluating ND4J for my project - and in order to test its speed I constructed a very simple test:

```java
        int n = 1000;
        int repeats = 1000000;

        double[] arrJava = new double[n];
        INDArray arrND = Nd4j.create(n);

        for (int i = 0; i < n; i++) {
            arrJava[i] = i;
            arrND.putScalar(i, i);
        }

        System.out.println("double[]...");
        long time = System.currentTimeMillis();
        int sum = 0;
        for (int i = 0; i < repeats; i++) {
            for (int j = 0; j < n; j++) {
                sum += arrJava[j];
            }
        }
        System.out.println("time: " + (System.currentTimeMillis() - time));

        System.out.println("NDArray...");
        time = System.currentTimeMillis();
        for (int i=0; i<repeats; i++) {
            sum += arrND.sumNumber().doubleValue();
        }
        System.out.println("time: " + (System.currentTimeMillis() - time));
```
Note that for warmup this method is executed 10 times and only the last timing is considered. 
I am getting a results that are inconsistent with the benchmarks published on the site, I tried x86 backend (since my server does not have GPU installed) and received that using simple java double arrays takes about 6.5s and with ND4j it took 21s 

When profiling the code, I noticed that most of the time was spent on the Unsafe.park method.
I know that this is a micro-benchmark but I also integrated ND4j into my server and noticed a huge slow down - what can be the reason?

My testing machine is ubuntu 14.04 64bit. 
EDIT: I am using the latest version on the maven repository (0.4-rc3.8)

**Comment by agibsonccc** [comment]
I'm closing this for now. We are in the midst of getting a new release out which will address any and all concerns you have. If you have further questions please come in to gitter. We can coordinate with you on benchmarks and what not.
