### ISSUE TITLE
Remove old loss calculation code

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#633]
Here is the code that DL4J actually uses for loss calculation: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/lossfunctions/LossFunctions.java

here's some other loss calculation code (duplicate - at least the score function) that should be removed:
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/lossfunctions/LossFunctions.java

**Comment by agibsonccc** [comment]
This 404s, we can close this. https://github.com/deeplearning4j/nd4j/blob/master/nd4j-api/src/main/java/org/nd4j/linalg/lossfunctions/LossFunctions.java
