### ISSUE TITLE
build error on ubuntu14.04 (x86_64)

### ISSUE THREAD

**Issue by guangwei** [deeplearning4j/nd4j#642]
error log:

[INFO] Building nd4j-native 0.4-rc3.9-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ nd4j-native ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ nd4j-native ---
[INFO] 
[INFO] --- javacpp:1.2-SNAPSHOT:build (generate-sources) @ nd4j-native ---
[INFO] Generating /home/username/ai/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/jniNd4jBlas.cpp
[INFO] Compiling /home/username/ai/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/libjniNd4jBlas.so
[INFO] g++ -I/home/username/tools/jdk1.8.0_73/include -I/home/username/tools/jdk1.8.0_73/include/linux /home/username/ai/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/jniNd4jBlas.cpp -Wl,-rpath,$ORIGIN/ -march=x86-64 -m64 -Wall -O3 -fPIC -shared -s -o /home/username/ai/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/libjniNd4jBlas.so -lnd4j 
/home/username/ai/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/src/main/java/jniNd4jBlas.cpp:63:24: fatal error: NativeBlas.h: No such file or directory
 #include "NativeBlas.h"
                        ^
compilation terminated.
username@username-VirtualBox:~/ai/nd4j$

**Comment by raver119** [comment]
Right now building nd4j from sources requires libnd4j to be available.

So, here's the compile instructions for it:

```
git clone https://github.com/deeplearning4j/libnd4j/
cd libnd4j
./buildnativeoperations.sh blas cpu
export LIBND4J_HOME=/path/to/libnd4j
cd ../nd4j
mvn clean install -DskipTests=true
```

**Comment by guangwei** [comment]
@raver119  thank you for your instructions
