### ISSUE TITLE
Example issues: rc3.8 (x86) vs. rc3.9-SNAPSHOT (native)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#645]
This issues summarizes some problems and differences in DL4J examples, when they are run on nd4j-native as compared to nd4j-x86 (on 0.4-rc3.8). I'll continue to update this as I test more examples, and start to work out what operations are resulting in these differences/issues.
**NOTE: These are all run on Windows 8.1. Issues here could be platform-specific.**

**[Last updated: 23 Mar, 9:40pm PDT]**

**Examples that look OK:**
- RegressionMathFunctions (graphs appear to be identical, and scores are same to 5 decimal places after 20k parameter updates...)
- Word2VecRawTextExample: runs OK. words nearest are the same (slightly different order)
- MLP classification examples
- CSV example (note non-repeatability in unmodified example due to shuffle etc)
- MLPMnistSingleLayerExample
- GravesLSTMCharModellingExample: Getting *slight* differences by the end of the first epoch, but this could easily be explained by the accumulation of minor rounding errors.

**Examples with significantly different results on 3.8-x86 and 3.9-native:**
- Word2VecSentimentRNN: JVM crash (https://gist.github.com/AlexDBlack/fb3c942900c90aaa1e00)
- LenetMNIST example: memory leak. Memory use grows continually... gets to >21GB before the first epoch is out. (run with batch size 64 or so to reproduce this quicker) [due to this: https://github.com/deeplearning4j/nd4j/issues/699]

CNN gradient checks: not passing yet, so I have not tested CNN examples.

**Examples that *might* be ok, might not be:**
- MNISTAnomalyExample: score differences in 5th significant figure... 41.4384... vs. 41.4352, 37.20275 vs. 37.20249 etc

**Comment by nyghtowl** [comment]
Update: MLPClassifier* examples confirmed OK

**Comment by agibsonccc** [comment]
Could we update this a bit?

**Comment by AlexDBlack** [comment]
Closing this. I'll re-run everything here + add benchmarks in a separate issue.
