### ISSUE TITLE
Nd4j native: sum(0) on row vector and f order fails intermittently

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#650]
The following code intermittently fails:
```for( int i=0; i<10000; i++ ) Nd4j.create(1,10).sum(0);```

However, the non-row-vector sum(0) operation is OK:
```for( int i=0; i<10000; i++ ) Nd4j.create(2,10).sum(0);```

See also:
```java
for( int i=0; i<10000; i++ ){
	Nd4j.create(new int[]{2,10},'f').sum(0);      //jvm crash
	//Nd4j.create(new int[]{2,10},'c').sum(0);        //ok
}
```

These result in the following error: No stack trace or any other info (no error log either). Just that one line.
Process finished with exit code -1073741819 (0xC0000005)

There doesn't seem to be any pattern to the iteration it is failing on.

**Comment by agibsonccc** [comment]
Not seeing this on linux. Will need to test on a windows box. I need a gist of your log the jvm outputs when it crashes.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/666
