### ISSUE TITLE
Implement sparse matrix operations

### ISSUE THREAD

**Issue by carschno** [deeplearning4j/nd4j#66]
Referring to https://groups.google.com/forum/#!msg/nd4j/YAgumxCwc7k/OHE7T6CCW9AJ, there should be a sparse matrix implementation supporting (all) matrix operations.

Just adding this as an issue to keep track.

**Comment by agibsonccc** [comment]
Wanted to address this: This will be on a backend basis. Need to get the scaffolding for it in place, but we could likely support this in:

opencl
java
cuda

I'm going to have to add some additional layers to the api for this.

**Comment by agibsonccc** [comment]
Talking with some other folks, it is likely we are going to add sparse matrix operations next. I'm seeing this be possibly a breeze backend as the primary benefactor of this.

**Comment by rahulpalamuttam** [comment]
So the apace spark community is looking for another linear algebra library to wrap around, for their linear algebra operations. This issue is one of the criteria
1. license
2. sparse support
3. performance
4. Java compatibility

**Comment by agibsonccc** [comment]
So here's where I'm at. We'd fit the bill. The only thing we need to be able to do is add it at the api level.
Read:

INDArray arr = Nd4j.createSparse


and then pick 1 or 2 backends to implement sparse ops. Try pitching it to them and see what they think.

Our main reason for existing is swappable chips and the like anyways (while being able to optimize in isolation.

**Comment by asevans48** [comment]
There is also JOCL which I am currently implementing which takes away most of the arguments. In fact, it could fit the bill for what you are looking for. I have created a fairly fast CSC matrix and dot product with it. Please consider.

**Comment by agibsonccc** [comment]
@asevans48 Is it general purpose though? I'd be looking for something equivalent to a cusparse, not something half baked with only 1 algorithm ;/

**Comment by kateri1** [comment]
Hello, Adam @agibsonccc.
Lately we at Apache Flink started the discussion about integration of Flink with DL4J. 
During analysis we have found the following issue: FLINK-5782:  Support GPU calculations.  
Shortly speaking it means: we would like to use ND4J as math library, supporting GPU, but we need the following issues to be covered in it:
1)	ND4J doesn’t support sparse matrixes.
2)	It’s impossible for now programmatically configure ND4J to use currently for calculations CPU or GPU, to switch you need to take another library. But we need to switch between this resources when they are available.  
3)	Flink manages consumed memory and performs spill on the disk, when memory is not enough. But ND4J allocates offheap memory also, and this cases incorrect memory assessment for Flink process. It seems that ND4J should provide some API to get information how much memory was already allocated. 
So, as you can see, we need some help from the side of DL4J/ND4J community.
Could we solve these issues in ND4J?

Related to #https://github.com/deeplearning4j/deeplearning4j/issues/1831

**Comment by agibsonccc** [comment]
1.  This is being worked on this summer (including sparse cuda and sparse cpu native routines).
2. Yes you technically use a *backend*: http://nd4j.org/backend.html . You can have multiple backends on the classpath now and it will usually automatically pick whatever is available to it for a job. Admittedly this isn't a well tested scenario (we typically just include 1 needed backend). If you have a particular scenario we are happy to talk about it though.
3. We use javacpp for this (we maintain this as well) which the mahout project also uses. Javacpp itself obeys heap space, see: https://deeplearning4j.org/spark#memory1

**Comment by raver119** [comment]
3) For both backends we know amount of RAM/vRAM being used. However in case of CUDA it's bit of vague due to optional memory reuse mechanics.

**Comment by kateri1** [comment]
Thank you, guys.
Regarding 1 -> could you please suppose how long this implementation could take? 
Regarding 2 -> I will check the integration scenario closer in Flink.
Regarding 3-> >>However in case of CUDA it's bit of vague due to optional memory reuse mechanics. How currently is this managed?

**Comment by raver119** [comment]
3. There's configurable options that allow you tweak different aspects of CUDA backend, and switch between direct allocation & memory reuse available as well. However, memory reuse is mostly suited for cyclic workloads, like model training. So if your workload isn't cyclic - you don't need cache anyway :)

**Comment by agibsonccc** [comment]
1 -> No comment. We just don't know.
2 -> For flink it should be the exact same mechanics.
3 -> We typically pre allocate our own memory. You can see the implementation for the memory management here:https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-backend-impls/nd4j-cuda/src/main/java/org/nd4j/jita/allocator

**Comment by agibsonccc** [comment]
We have an "early" version of this merged with basic blas support via mkl and cusparse with indexing working. https://github.com/deeplearning4j/nd4j/pull/1711

**Comment by guv** [comment]
When will the next release containing this enhancement be done? Is it possible to get an up-to-date snapshot release meanwhile?

**Comment by raver119** [comment]
1) Sorry, we’re not announcing public release dates
2) Yes, we’re working on snapshots atm. However, you should be still able to build everything from sources, since that’s just CPU backend.
