### ISSUE TITLE
CUDA Ops state

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#660]
We currently missing: 
1. Kernel params tuning. Existent one is wrong, and causes core dump.
2. We missing CUDA streams passing/usage for kernels calls.
3. We still have few cudaDeviceSynchronize calls, but mostly due to p.2

**Comment by agibsonccc** [comment]
Where are we with this?

**Comment by raver119** [comment]
Everything is fixed/improved appropriately for a quite time now. Forgot to close this :)
