### ISSUE TITLE
DataSet split train and test does not handle mask arrays + time series

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#670]
splitTrainAndTest: this does not properly handle time series, and does not split mask arrays if mask arrays are present.
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/DataSet.java#L688

**Comment by sadatanwer** [comment]
On the topic of mask arrays, could you maybe explain what is their purpose? An example of where one could use it?

**Comment by AlexDBlack** [comment]
Have a read of this: http://deeplearning4j.org/usingrnns#masking
If that doesn't adequately explain it, let me know.
Also the movie review RNN/word2vec example uses masking.

**Comment by agibsonccc** [comment]
Isn't this fixed now?

**Comment by eraly** [comment]
Yes. Closing.
