### ISSUE TITLE
Master branch is broken!

### ISSUE THREAD

**Issue by linkerlin** [deeplearning4j/nd4j#677]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ nd4j-native ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 12 source files to /Users/linkerlin/gits/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes
[INFO] 
[INFO] --- javacpp:1.2-SNAPSHOT:build (process-classes) @ nd4j-native ---
[INFO] Generating /Users/linkerlin/gits/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/jniNd4jBlas.cpp
[INFO] Compiling /Users/linkerlin/gits/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/libjniNd4jBlas.dylib
[INFO] clang++ -I/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home/include/darwin /Users/linkerlin/gits/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/jniNd4jBlas.cpp -Wl,-rpath,@loader_path/. -march=x86-64 -m64 -Wall -O3 -fPIC -dynamiclib -undefined dynamic_lookup -o /Users/linkerlin/gits/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/libjniNd4jBlas.dylib -lnd4j -framework JavaVM 
/Users/linkerlin/gits/nd4j/nd4j-backends/nd4j-backend-impls/nd4j-native/target/classes/org/nd4j/nativeblas/macosx-x86_64/jniNd4jBlas.cpp:63:10: fatal error: 
      'NativeBlas.h' file not found
#include "NativeBlas.h"
         ^
1 error generated.

**Comment by treo** [comment]
Actually, it is not. You have to have libnd4j setup, and the right environment variables to point it there.
The documentation is lacking concerning that point though.

**Comment by AlexDBlack** [comment]
Drop by here if you want to discuss. https://gitter.im/deeplearning4j/deeplearning4j/earlyadopters
