### ISSUE TITLE
Documentation: Unable to find good documentation for random access INDArray elements

### ISSUE THREAD

**Issue by sadatanwer** [deeplearning4j/nd4j#678]
Documentation is not available on how to properly access INDArray elements randomly. Example, I create an array like this:
`INDArray arr = Nd4j.zeros(1, sizeOfCols);`
And now I want to write a loop that would populate every element of this INDArray
`for(int i=0; i<numCols; i++){`
       `      arr.insertAt(row, col, val);`
`}`
Is there something of this sort available, or any way of achieving it? 
Thanks

**Comment by AlexDBlack** [comment]
As in generating random arrays? We have Nd4j.rand() for uniform(0,1) distributions, Nd4j.randn() for gaussian(0,1) distributions.

**Comment by sadatanwer** [comment]
No not really random, I want to populate this with values that I have. I just want to set specific elements in the INDArray with specific values. 
Right now what I have done is 

```
ArrayList<Double> allValues = new ArrayList<>();
        for ( int i = 0; i < windowEntries.size(); i++ ) {
            allValues.addAll(windowEntries.get(i));
        }
        INDArray arr =  Nd4j.create(ArrayUtil.toArrayDouble(allValues), new int[]{1, allValues.size()});
```

I am always having to create a new INDArray every time a single element in my allValues changes, 
I was hoping maybe there is a way I could just change the single element. Make sense?

**Comment by AlexDBlack** [comment]
Right. putScalar is the method you want. And yes, that needs to be documented better.

**Comment by AlexDBlack** [comment]
Closing this - I've opened another issue to keep track of this (and other) stuff we need to properly document.
https://github.com/deeplearning4j/nd4j/issues/679
