### ISSUE TITLE
Don't try to build nd4j-cuda-7.5, if cuda version of libnd4j wasn't built

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#680]
Right now building cuda (or working around the fact that it wasn't built) is a requirement. But if one doesn't even intend to do anything with it, that seems superfluous.

**Comment by treo** [comment]
An alternative is to document how to skip it. I.e. add `-pl '!org.nd4j:nd4j-cuda-7.5'` to the mvn command.

**Comment by agibsonccc** [comment]
You sent us the PR for this.
