### ISSUE TITLE
Performance Bottlenecks

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#691]
The new backend comes a long very fine and still there seem to be some bottlenecks.

- Here fillPointerWithZero works way longer than it should
![very-native](https://cloud.githubusercontent.com/assets/509379/13858884/e61af762-ec80-11e5-981d-a06445ea162f.png)

- And I don't know whats up here, but it kills concurrency for a minute:
![not-very-native](https://cloud.githubusercontent.com/assets/509379/13859338/4b8bc96c-ec83-11e5-9366-7eb085d5af0b.png)

**Comment by AlexDBlack** [comment]
Closing this; these issues (and more) are discussed in https://github.com/deeplearning4j/nd4j/issues/695
