### ISSUE TITLE
Used memory fluctuating wildly

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#692]
While my network is training, JVisualVM reports wildly fluctuating used memory. It jumps around between 700MB and 7GB (and values inbetween) each second.

### CPU Sample
![memory-jumps](https://cloud.githubusercontent.com/assets/509379/13863019/1d399508-ec97-11e5-8687-fadcdba5e4f0.png)

### Memory Sample
![memory-jumps-2](https://cloud.githubusercontent.com/assets/509379/13863036/2d12b78e-ec97-11e5-9d3f-09ee04791c23.png)

**Comment by agibsonccc** [comment]
Appears to be related to javacpp usage. We are going to implement an allocator for this.
