### ISSUE TITLE
ND4J Optimization Issues

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#695]
I'll use this issue to summarize the most important optimization issues I'm currently seeing (tested on MLPs only, nd4j-native so far).

1. [**BaseOp.ensureProperVectors()**](https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/BaseOp.java#L155): I assume this is totally unnecessary, and is  adding quite an overhead to things like Norm2. Norm2 is now used for dl4j network L2 calculations, hence this is a major bottleneck for training networks with L2 regularization.
2. [**Nd4j.toFlattened()**](https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/factory/BaseNDArrayFactory.java#L360) [multiple toFlattened methods]: Using getDouble, putScalar and NDIndexIterator. This really needs to be native and parallelized; I'm seeing this as a *very significant* bottleneck in network learning (>60% of total training time). 
3. ~~[**BaseDataBuffer.fillPointerWithZero()**](https://github.com/deeplearning4j/nd4j/blob/master/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java#L1049): this is a simple java for-loop (line 511) essentially calling BaseDataBuffer.put(int,double). This is about 7.7% of total time on a 256x256 MLP.~~ [Fixed]
4. [**BaseNDArray.assign()**](https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L1022): Utilizes NDIndexIterator, getDouble and putScalar. For the assign-with-different-shapes case, I prototyped a parallel assign op (CPUAssignTask) here: https://github.com/deeplearning4j/nd4j/pull/538/files

------------------------------------------------------
------------------------------------------------------
Issue 1: ensureProperVectors:
![image](https://cloud.githubusercontent.com/assets/2360237/13876022/70a0ef3e-ed55-11e5-937f-cf657a219b8d.png)

**Comment by raver119** [comment]
as for things like put/putScalar used in cycle, as well as NioCopyStrided - we'll transparently switch to smth like memcpy soon.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/711
