### ISSUE TITLE
Heartbeat uses Logback

### ISSUE THREAD

**Issue by darrenfoong** [deeplearning4j/nd4j#698]
The latest snapshot version of Heartbeat (https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/heartbeat/Heartbeat.java) depends on Logback, whose inclusion will interfere with the use of other logging frameworks.

I understand that it's to switch off logging of the external stuff :smile:

**Comment by raver119** [comment]
Removed in current master.
