### ISSUE TITLE
nd4j-native: softmax incorrect/unstable for row vectors

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#706]
Consider the following code:
```java
    @Test
    public void testSoftmaxRow() {
        for( int i=0; i<20; i++ ){
            INDArray arr1 = Nd4j.zeros(100);
            Nd4j.getExecutioner().execAndReturn(new SoftMax(arr1));
            System.out.println(Arrays.toString(arr1.data().asFloat()));
        }
    }
```

The above code reproduces the issue. Seems to be stochastic.

Output of above code: https://gist.github.com/AlexDBlack/50fa43f4ce38f0e7710e

----------------------------------
Old version:

```java
    @Test
    public void testSoftmaxRow() {
        for (int i = 100; i <= 1000; i += 100) {
            INDArray arr1 = Nd4j.zeros(i);
            INDArray arr2 = Nd4j.zeros(2, i);

            Nd4j.getExecutioner().execAndReturn(new SoftMax(arr1));
            Nd4j.getExecutioner().execAndReturn(new SoftMax(arr2));

//            System.out.println(Arrays.toString(arr1.data().asFloat()));
//            System.out.println(Arrays.toString(arr2.data().asFloat()));
            System.out.println(i + "\t" + arr1.sumNumber().doubleValue() + "\t" + arr2.sumNumber());
        }
    }
```

In all cases, we expect the sum to be 1.0 and 2.0 below (numerical precision issues aside):
(note the softmax values themselves are wrong; this is not an issue with sum).

The results here are from 3 separate runs of the above code:

100	0.9999993443489075	1.9999984502792358
200	0.9999992251396179	1.9999983310699463
300	0.9999991655349731	1.9999982118606567
400	1.0928940773010254	2.0000219345092773
500	1.2019264698028564	1.99998140335083
600	0.9999991059303284	1.9999982118606567
700	1.0526331663131714	2.000014305114746
800	1.0913952589035034	2.0000338554382324
900	1.090908169746399	2.0000267028808594
1000	0.999990701675415	2.000037431716919

100	1.0869567394256592	1.9999984502792358
200	1.0928971767425537	1.9999983310699463
300	0.9999991655349731	1.9999982118606567
400	0.9999991655349731	2.0000219345092773
500	0.9999942183494568	1.99998140335083
600	0.9999991059303284	1.9999982118606567
700	0.9999914169311523	2.000014305114746
800	1.0000109672546387	2.0000338554382324
900	1.086948275566101	2.0000267028808594
1000	0.999990701675415	2.000037431716919

100	1.0869567394256592	1.9999984502792358
200	0.9999992251396179	1.9999983310699463
300	0.9999991655349731	1.9999982118606567
400	0.9999991655349731	2.0000219345092773
500	0.9999942183494568	1.99998140335083
600	0.9999991059303284	1.9999982118606567
700	0.9999914169311523	2.000014305114746
800	1.0389677286148071	2.0000338554382324
900	1.123592734336853	2.0000267028808594
1000	1.09052312374115	2.000037431716919

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/libnd4j/commit/fa3c57a98b82c9621a4fa8039f4696bbf253708c
