### ISSUE TITLE
 Nd4jTestsC.testMultiSum   test failure

### ISSUE THREAD

**Issue by guangwei** [deeplearning4j/nd4j#707]
error log:

Tests run: 4, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.119 sec - in org.nd4j.linalg.convolution.ConvolutionTests
Running org.nd4j.linalg.convolution.ConvolutionTestsC
Tests run: 6, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.213 sec - in org.nd4j.linalg.convolution.ConvolutionTestsC
Getting val bias corrected 2.000000 vs normal variance 1.000000 and n 2.000000
Getting val bias corrected 2.000000 vs normal variance 1.000000 and n 2.000000
Getting val bias corrected 0.136927 vs normal variance 0.105519 and n 3.000000
Getting val bias corrected 0.136927 vs normal variance 0.105519 and n 3.000000
Getting val bias corrected 2.500000 vs normal variance 2.000000 and n 5.000000
Getting val bias corrected 2.500000 vs normal variance 2.000000 and n 5.000000
Getting val bias corrected 30200.000000 vs normal variance 29998.666016 and n 150.000000
Getting val bias corrected 30200.000000 vs normal variance 29998.666016 and n 150.000000
Getting val bias corrected 30200.000000 vs normal variance 29998.666016 and n 150.000000
Getting val bias corrected 30200.000000 vs normal variance 29998.666016 and n 150.000000
Getting val bias corrected 0.136927 vs normal variance 0.105519 and n 3.000000
Getting val bias corrected 0.136927 vs normal variance 0.105519 and n 3.000000
Getting val bias corrected 0.136927 vs normal variance 0.105519 and n 3.000000
Getting val bias corrected 2.500000 vs normal variance 2.000000 and n 5.000000
Getting val bias corrected 2.500000 vs normal variance 2.000000 and n 5.000000

Results :

Failed tests: 
  Nd4jTestsC.testMultiSum:477 expected:<[ 10.00, 18.00]> but was:<[ 6.00, 10.00]>

Tests run: 418, Failures: 1, Errors: 0, Skipped: 11

my env:

java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)

OS:
Linux gao-VirtualBox 4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by agibsonccc** [comment]
passes.
