### ISSUE TITLE
put(row,column,value) do not work for a row vector, only for column vector

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#71]
After a lot of debugging I found the error, there is a issue with put function

Code with the bug:
  INDArray a = Nd4j.zeros(1,4);
            a.put(0,0, 5F);
            a.put(0,1, 2F);
            a.put(0,2, 3F);
            a.put(0,3, 4F);
           
            System.out.println("test: "+a);

   Output test: [4.0, 0.0, 0.0, 0.0]

I expected: [5,2,3,4]

Workaround: When I use a row vector with Nd4j.zeros(4,1), the function works fine and

**Comment by agibsonccc** [comment]
Fixed.
