### ISSUE TITLE
Random distribution functions don't appear to work and cause seg-faults

### ISSUE THREAD

**Issue by Bam4d** [deeplearning4j/nd4j#72]
Playing with the random distribution functions in order to try and get RNTN to work, I came across the following issues 

1. Some of the kernels (uniform.cu) don't match the variables being passed in. in `doSampleUniform`:
```
Object[] kernelParams = new Object[]{
                Pointer.to(new int[]{n})
                , Pointer.to(new double[]{min})
                , Pointer.to(new double[]{max})
                , Pointer.to(out)
                , Pointer.to(random.generator())

        };
```

does not match the kernel:
```
uniform_float(int n,float lower,float upper,float *result)
```

2. binomial distribution random generators always return blocks of 0s (curand never gets used, just an empty allocated INDArray)

3. The numbers coming back from these functions don't appear to fit the parameters:
```
INDArray arr = Nd4j.rand(200,200,-0.4,0.4,Nd4j.getRandom());
``` 
will sometimes give back numbers that aren't within 0.4 and -0.4 and will also sometimes be all 0s

**Comment by Bam4d** [comment]
I'd say we want to keep this open for the point about binomial distribution (I haven't fixed that one yet.) It always just gives back 0s

**Comment by agibsonccc** [comment]
I'm going to use the cpu for rng. The GPU is error prone here.
