### ISSUE TITLE
CPU Backend Crashes the JVM with negative Stride (MulOp, Set)

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#724]
The following code crashes the JVM:

```java
package com.example;
import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.api.ops.TransformOp;
import org.nd4j.linalg.api.ops.impl.transforms.Set;
import org.nd4j.linalg.api.ops.impl.transforms.arithmetic.MulOp;
import org.nd4j.linalg.factory.Nd4j;
import org.nd4j.nativeblas.NativeOps;

public class App 
{
    public static void main( String[] args ){
        /* Doesn't crash:
        INDArray x = Nd4j.rand(new int[]{1024, 2, 29, 2});
        INDArray y = Nd4j.rand(new int[]{2, 1024, 29, 2}).permute(1, 0, 2, 3); */

        INDArray x = Nd4j.rand(new int[]{1024, 2, 30, 2});
        INDArray y = Nd4j.rand(new int[]{2, 1024, 30, 2}).permute(1, 0, 2, 3);

        TransformOp op = new MulOp(x, y, x, x.length());
        //TransformOp op = new Set(x, y, x, x.length());
        NativeOps loop = new NativeOps();

        long[] dummy = new long[0];
        int opNum = op.opNum();
        long address = op.x().data().address();
        int xStride = op.x().elementWiseStride();
        long address1 = op.y().data().address();
        int yStride = op.y().elementWiseStride();
        long address2 = op.z().data().address();
        int resultStride = op.z().elementWiseStride();
        int extraParamsAddress = 0;
        int n = op.n();
        System.out.println("Dummy: "+dummy);
        System.out.println("opNum: "+opNum);
        System.out.println("X address: "+address);
        System.out.println("Y address: "+address1);
        System.out.println("Z address: "+address2);
        System.out.println("X stride: "+xStride);
        System.out.println("Y stride: "+yStride);
        System.out.println("Z stride: "+resultStride);
        System.out.println("Extra Params Address: "+extraParamsAddress);
        System.out.println("N: "+n);


        loop.execPairwiseTransformFloat
                (dummy, opNum,
                        address,
                        xStride,
                        address1,
                        yStride,
                        address2,
                        resultStride,
                        extraParamsAddress,
                        n);
    }
}
```

#### Newer analysis
Using a smaller array (the "doesn't crash" one), a negative stride doesn't crash the jvm, while a slightly bigger one does, but if it has a positive stride, it doesn't.

#### Old analysis
The reason is that the yStride is negative, which results in an Access Violation in [pairwise_transform.h line 570](https://github.com/deeplearning4j/libnd4j/blob/master/include/pairwise_transform.h#L570).

The origin of the negative stride in the example is the `.permute` method, which creates a new NDArray through a [factory](https://github.com/deeplearning4j/nd4j/blob/f3f66b36bb01aae1ad333e1461269a049bec63c3/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ndarray/BaseNDArray.java#L134), that in turn calls [Shape.elementWiseStride](https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/shape/Shape.java#L599) which decides that it is  "not contiguous enough", and returns -1.

While I tested this only with MulOp and Set, It should probably crash every pairwise operation.

This problem manifested itself in https://github.com/deeplearning4j/libnd4j/issues/47, which is "fixed" in current master, as native `.assign` was reverted (used the Set Op), and still manifests itself when running current master when running the EarlyStoppingMNIST example.

**Comment by treo** [comment]
The example where this crashing case was extracted from, doesn't crash any more. So I guess this can be closed :)

**Comment by agibsonccc** [comment]
Closing this - invalid test case
