### ISSUE TITLE
Difference in mean along dimension between 3.8 and 3.9

### ISSUE THREAD

**Issue by nyghtowl** [deeplearning4j/nd4j#731]
@Test
    public void testMean(){

        INDArray val = Nd4j.create(new double[] {
                1.00,3.00, 2.00,8.00, 1.00,7.00, 2.00,4.00,
                5.00,3.00, 2.00,4.00, 1.00,3.00, 6.00,4.00,
                3.00,6.00, 5.00,9.00, 3.00,7.00, 5.00,8.00,
                4.00,6.00, 4.00,9.00, 4.00,7.00, 4.00,8.00}).reshape(1,2,2,2,2,2);

        INDArray avgActual = val.mean(2, 3);
        INDArray avgExpected = Nd4j.create(new double[] {
                2.0, 4,0, 3.0, 5.0, 3.5, 6.5, 4.5, 8.5
        }).reshape(1,2,2,2);

        assertEquals(avgExpected, avgActual);
    }

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/734
