### ISSUE TITLE
nd4j-native one-dimensional sum incorrect for large arrays

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#733]
While trying out if https://github.com/deeplearning4j/libnd4j/issues/17 is solved yet, I came across the problem that for large enough arrays the sum is calculated incorrectly.

```java
package com.example;

import org.nd4j.linalg.factory.Nd4j;

public class App {
    public static void main(String... args){
        System.out.println(Nd4j.ones(1024*1024*17).sumNumber().longValue());
    }
}
// Output: 16777216
// Correct: 17825792
```

This result can also be observed using `Nd4j.rand` but then the array has to be larger (e.g. times 50 instead of times 17). So I'd guess that the problem is that the sum can not be larger than 2^24.

**Comment by agibsonccc** [comment]
I wonder if this is because long is currently limited by int as the type?

**Comment by treo** [comment]
2^24 isn't even near Integer.MAX_VALUE(2^31-1), so I'd expect the limitations of the int type to be culprit.

From the looks of it, it seems that the actual problem here is the float that is used to compute the sum. 

```C
	float res = 0;
	for (int i = 0; i < 1024*1024*17; i++)
	{
		res = res + 1;
	}
	printf("%f", res);
```
This results exactly in 16777216, even though it should have been 17825792.

**Comment by AlexDBlack** [comment]
@saudet FYI: this behaviour might be different now on the newtoflattened branch

**Comment by agibsonccc** [comment]
Could we get this checked again? I've merged the newtoflattened branch

**Comment by treo** [comment]
Checked the current master, and this is still an issue.

**Comment by saudet** [comment]
Works for me now with the latest changes!

**Comment by agibsonccc** [comment]
Are we ready to merge your branch?

**Comment by agibsonccc** [comment]
Update on this? The long indexing has been merged now.

**Comment by treo** [comment]
The long indexing works fine, but due to how the parallel merge on cpu is implemented, large numbers still eat up the small numbers and this still results in results that are at max 2^24 (aka, the largest integer value a float can hold) if the whole array consists of small numbers.

To be honest I'm not sure why that still happens, because the code does looks right to me, aside from the parallel pragma on the block information constructor (https://github.com/deeplearning4j/libnd4j/blob/master/include/pairwise_util.h#L313).

**Comment by saudet** [comment]
IIRC, sum() ends up executing this simple for loop:
https://github.com/deeplearning4j/libnd4j/blob/master/include/reduce.h#L886
So, it's pretty normal that this is happening with a float as accumulator...

**Comment by treo** [comment]
Oh, I thought it would go into this:
https://github.com/deeplearning4j/libnd4j/blob/master/include/reduce.h#L600

**Comment by saudet** [comment]
Yes, you're right, sorry, so this for loop goes over most of the elements:
https://github.com/deeplearning4j/libnd4j/blob/master/include/reduce.h#L613

**Comment by treo** [comment]
Right, and on anything with more then 1 cores / threads, this should result in in the local variable accumulating a correct (big) result, that when updated to the finalVal should be the correct result, as far as I understand it.

That in itself is a bit of a problem, because now the result of a calculation would depend on the number of available cores... But right now it somehow looks like it is worked through serially.

**Comment by saudet** [comment]
What if we used the same number of chunks, regardless of the number of threads? At least we'd get the same results...

**Comment by agibsonccc** [comment]
Where are we with this?

**Comment by saudet** [comment]
Well, floating point arithmetic has limits, but do you think it's important to get the same results regardless of the number of threads?

**Comment by eraly** [comment]
@saudet Will you file a fresh issue if this is something we need to revisit?

**Comment by saudet** [comment]
If it becomes a problem for someone, I'm sure that someone will open an issue for us :)
