### ISSUE TITLE
OpExecutionerTestsC.testLogSoftmaxVector failure on skylake CPU

### ISSUE THREAD

**Issue by guangwei** [deeplearning4j/nd4j#736]
this case can be passed on hasswell cpu (i5 4300m)
but failed on skylake cpu (i76700k)

the OS is the same (ubuntu 14.04)

error log:

Tests run: 4, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.059 sec - in org.nd4j.linalg.convolution.ConvolutionTests

Results :

Failed tests: 
  OpExecutionerTestsC.testLogSoftmaxVector:582 expected:<[ -3.44, -2.44, -1.44, -0.44]> but was:<[ -3.13, -2.13, -1.13, -0.13]>

Tests run: 429, Failures: 1, Errors: 0, Skipped: 11

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] nd4j ............................................... SUCCESS [  0.187 s]
[INFO] nd4j-common ........................................ SUCCESS [  0.254 s]
[INFO] nd4j-context ....................................... SUCCESS [  0.013 s]
[INFO] nd4j-buffer ........................................ SUCCESS [  0.023 s]
[INFO] nd4j-backends ...................................... SUCCESS [  0.002 s]
[INFO] nd4j-api-parent .................................... SUCCESS [  0.001 s]
[INFO] nd4j-api ........................................... SUCCESS [  0.050 s]
[INFO] nd4j-jdbc .......................................... SUCCESS [  0.001 s]
[INFO] nd4j-jdbc-api ...................................... SUCCESS [  0.024 s]
[INFO] nd4j-native-api .................................... SUCCESS [  0.020 s]
[INFO] nd4j-backend-impls ................................. SUCCESS [  0.002 s]
[INFO] nd4j-native ........................................ FAILURE [ 22.060 s]
[INFO] nd4j-cpu ........................................... SKIPPED
[INFO] nd4j-jdbc-mysql .................................... SKIPPED
[INFO] nd4j-instrumentation ............................... SKIPPED
[INFO] nd4j-perf .......................................... SKIPPED
[INFO] nd4j-serde ......................................... SKIPPED
[INFO] nd4j-jackson ....................................... SKIPPED
[INFO] nd4j-bytebuddy ..................................... SKIPPED
[INFO] nd4j-cuda-7.5 ...................................... SKIPPED
[INFO] nd4j-tests ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.775 s
[INFO] Finished at: 2016-03-26T14:11:09+08:00
[INFO] Final Memory: 29M/518M

code base :0d2045c8610a7efd361b74cdc6ced228f994c4cd

**Comment by agibsonccc** [comment]
@guangwei can you ensure you have the commit id hash for libnd4j or make sure libnd4j is up to date?

Thanks!

**Comment by treo** [comment]
On current master for both nd4j and libnd4j this works fine for me (also on i7-6700k).

**Comment by guangwei** [comment]
I'm using the older version of nd4j.
I have compilation error with the latest nd4j master.
do you have any hint?

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/xxx/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[127,40] no suitable method found for create(org.bytedeco.javacpp.DoublePointer)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(double[],int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(java.nio.DoubleBuffer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(org.bytedeco.javacpp.DoublePointer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(org.bytedeco.javacpp.DoublePointer,int[],int[],boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[145,39] no suitable method found for create(org.bytedeco.javacpp.FloatPointer)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(float[],int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(java.nio.FloatBuffer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(org.bytedeco.javacpp.FloatPointer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(org.bytedeco.javacpp.FloatPointer,int[],int[],boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[164,37] no suitable method found for create(org.bytedeco.javacpp.IntPointer)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(int[],int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(java.nio.IntBuffer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(org.bytedeco.javacpp.IntPointer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(org.bytedeco.javacpp.IntPointer,int[],int[],boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[239,35] no suitable method found for create(org.bytedeco.javacpp.FloatPointer)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(float[],int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(java.nio.FloatBuffer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(org.bytedeco.javacpp.FloatPointer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(org.bytedeco.javacpp.FloatPointer,int[],int[],boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[291,36] no suitable method found for create(org.bytedeco.javacpp.DoublePointer)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(double[],int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(java.nio.DoubleBuffer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(org.bytedeco.javacpp.DoublePointer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(org.bytedeco.javacpp.DoublePointer,int[],int[],boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[338,37] no suitable method found for create(org.bytedeco.javacpp.IntPointer)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(int[],int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(java.nio.IntBuffer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(org.bytedeco.javacpp.IntPointer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(org.bytedeco.javacpp.IntPointer,int[],int[],boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[556,40] no suitable method found for create(org.bytedeco.javacpp.DoublePointer)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(double[],int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(java.nio.DoubleBuffer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(org.bytedeco.javacpp.DoublePointer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.create(org.bytedeco.javacpp.DoublePointer,int[],int[],boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[563,39] no suitable method found for create(org.bytedeco.javacpp.FloatPointer)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(float[],int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(java.nio.FloatBuffer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(org.bytedeco.javacpp.FloatPointer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.FloatIndexer.create(org.bytedeco.javacpp.FloatPointer,int[],int[],boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[570,37] no suitable method found for create(org.bytedeco.javacpp.IntPointer)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(int[],int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(java.nio.IntBuffer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(org.bytedeco.javacpp.IntPointer,int[],int[]) is not applicable
      (actual and formal argument lists differ in length)
    method org.bytedeco.javacpp.indexer.IntIndexer.create(org.bytedeco.javacpp.IntPointer,int[],int[],boolean) is not applicable
      (actual and formal argument lists differ in length)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[1020,47] no suitable method found for get(long)
    method org.bytedeco.javacpp.indexer.FloatIndexer.get(int) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.FloatIndexer.get(int...) is not applicable
      (varargs mismatch; possible lossy conversion from long to int)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[1029,45] no suitable method found for get(long)
    method org.bytedeco.javacpp.indexer.IntIndexer.get(int) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.IntIndexer.get(int...) is not applicable
      (varargs mismatch; possible lossy conversion from long to int)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[1037,48] no suitable method found for get(long)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.get(int) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.get(int...) is not applicable
      (varargs mismatch; possible lossy conversion from long to int)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[1067,55] no suitable method found for get(long)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.get(int) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.get(int...) is not applicable
      (varargs mismatch; possible lossy conversion from long to int)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[1075,43] no suitable method found for get(long)
    method org.bytedeco.javacpp.indexer.FloatIndexer.get(int) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.FloatIndexer.get(int...) is not applicable
      (varargs mismatch; possible lossy conversion from long to int)
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[1109,45] no suitable method found for put(long,double)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.put(int,double) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.put(int,double...) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.put(int,int,double...) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.DoubleIndexer.put(int[],double) is not applicable
      (argument mismatch; long cannot be converted to int[])
    method org.bytedeco.javacpp.indexer.DoubleIndexer.put(int[],double...) is not applicable
      (argument mismatch; long cannot be converted to int[])
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[1116,42] no suitable method found for put(long,int)
    method org.bytedeco.javacpp.indexer.IntIndexer.put(int,int) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.IntIndexer.put(int,int...) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.IntIndexer.put(int,int,int...) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.IntIndexer.put(int[],int) is not applicable
      (argument mismatch; long cannot be converted to int[])
    method org.bytedeco.javacpp.indexer.IntIndexer.put(int[],int...) is not applicable
      (argument mismatch; long cannot be converted to int[])
[ERROR] /home/gao/ai/nd4j/nd4j-buffer/src/main/java/org/nd4j/linalg/api/buffer/BaseDataBuffer.java:[1123,44] no suitable method found for put(long,float)
    method org.bytedeco.javacpp.indexer.FloatIndexer.put(int,float) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.FloatIndexer.put(int,float...) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.FloatIndexer.put(int,int,float...) is not applicable
      (argument mismatch; possible lossy conversion from long to int)
    method org.bytedeco.javacpp.indexer.FloatIndexer.put(int[],float) is not applicable
      (argument mismatch; long cannot be converted to int[])
    method org.bytedeco.javacpp.indexer.FloatIndexer.put(int[],float...) is not applicable
      (argument mismatch; long cannot be converted to int[])
[INFO] 17 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] nd4j ............................................... SUCCESS [  0.489 s]
[INFO] nd4j-common ........................................ SUCCESS [  1.218 s]
[INFO] nd4j-context ....................................... SUCCESS [  0.063 s]
[INFO] nd4j-buffer ........................................ FAILURE [  5.024 s]
[INFO] nd4j-backends ...................................... SKIPPED
[INFO] nd4j-api-parent .................................... SKIPPED
[INFO] nd4j-api ........................................... SKIPPED
[INFO] nd4j-jdbc .......................................... SKIPPED
[INFO] nd4j-jdbc-api ...................................... SKIPPED
[INFO] nd4j-native-api .................................... SKIPPED
[INFO] nd4j-backend-impls ................................. SKIPPED
[INFO] nd4j-native ........................................ SKIPPED
[INFO] nd4j-cpu ........................................... SKIPPED
[INFO] nd4j-jdbc-mysql .................................... SKIPPED
[INFO] nd4j-instrumentation ............................... SKIPPED
[INFO] nd4j-perf .......................................... SKIPPED
[INFO] nd4j-serde ......................................... SKIPPED
[INFO] nd4j-jackson ....................................... SKIPPED
[INFO] nd4j-bytebuddy ..................................... SKIPPED
[INFO] nd4j-cuda-7.5 ...................................... SKIPPED
[INFO] nd4j-tests ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.930 s
[INFO] Finished at: 2016-03-27T09:56:02+08:00
[INFO] Final Memory: 36M/361M
[INFO] ------------------------------------------------------------------------

**Comment by AlexDBlack** [comment]
@guangwei clone and install (mvn clean install) the latest version of javacpp
https://github.com/bytedeco/javacpp

**Comment by guangwei** [comment]
@AlexDBlack  the pom of nd4j refer a 1.2-SNAPSHOT from Sonatype Nexus snapshot repository
is this a bug of pom?

**Comment by agibsonccc** [comment]
@guangwei no git clone from that and run mvn clean install -DskipTests

**Comment by guangwei** [comment]
by your instruction I fixed the nd4j-buffer compilation.
now the code base are 
nd4j commit id :a93c5c193d323283bf9d28208e79625ba993cf55
libnd4j commit id: 437a3463607cb8c733eee7cd4e39941c017a9ec9

this issue still exist.  any other dependencies?

**Comment by guangwei** [comment]
After I compiled the cuda mode for libnd4j,this test case passed. 
Strange but anyway this issue can be closed.
