### ISSUE TITLE
nd4j-cuda-7.5 test cases failure

### ISSUE THREAD

**Issue by guangwei** [deeplearning4j/nd4j#741]
[INFO] 
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ nd4j-cuda-7.5 ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] nd4j ............................................... SUCCESS [  0.209 s]
[INFO] nd4j-common ........................................ SUCCESS [  0.294 s]
[INFO] nd4j-context ....................................... SUCCESS [  0.015 s]
[INFO] nd4j-buffer ........................................ SUCCESS [  0.023 s]
[INFO] nd4j-backends ...................................... SUCCESS [  0.001 s]
[INFO] nd4j-api-parent .................................... SUCCESS [  0.002 s]
[INFO] nd4j-api ........................................... SUCCESS [  0.056 s]
[INFO] nd4j-jdbc .......................................... SUCCESS [  0.001 s]
[INFO] nd4j-jdbc-api ...................................... SUCCESS [  0.024 s]
[INFO] nd4j-native-api .................................... SUCCESS [  0.022 s]
[INFO] nd4j-backend-impls ................................. SUCCESS [  0.001 s]
[INFO] nd4j-native ........................................ SUCCESS [ 56.646 s]
[INFO] nd4j-cpu ........................................... SUCCESS [  0.009 s]
[INFO] nd4j-jdbc-mysql .................................... SUCCESS [  0.220 s]
[INFO] nd4j-instrumentation ............................... SUCCESS [  0.115 s]
[INFO] nd4j-perf .......................................... SUCCESS [  0.014 s]
[INFO] nd4j-serde ......................................... SUCCESS [  0.004 s]
[INFO] nd4j-jackson ....................................... SUCCESS [  0.418 s]
[INFO] nd4j-bytebuddy ..................................... SUCCESS [  0.295 s]
[INFO] nd4j-cuda-7.5 ...................................... FAILURE [  6.819 s]
[INFO] nd4j-tests ......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:05 min
[INFO] Finished at: 2016-03-27T23:19:59+08:00
[INFO] Final Memory: 35M/607M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project nd4j-cuda-7.5: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test failed: There was an error in the forked process
[ERROR] java.lang.NoClassDefFoundError: test-classes/org/nd4j/linalg/ops/OpExecutionerTestsC (wrong name: org/nd4j/linalg/ops/OpExecutionerTestsC)
[ERROR] at java.lang.ClassLoader.defineClass1(Native Method)
[ERROR] at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
[ERROR] at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[ERROR] at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[ERROR] at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[ERROR] at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[ERROR] at java.security.AccessController.doPrivileged(Native Method)
[ERROR] at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[ERROR] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[ERROR] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.loadClass(DefaultScanResult.java:131)
[ERROR] at org.apache.maven.surefire.util.DefaultScanResult.applyFilter(DefaultScanResult.java:96)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.scanClassPath(JUnit4Provider.java:311)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.setTestsToRun(JUnit4Provider.java:191)
[ERROR] at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:134)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
[ERROR] at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :nd4j-cuda-7.5

**Comment by raver119** [comment]
All tests within nd4j-cuda-7.5 package are dev-time only, and will be marked as @ Ignore pretty soon. They are only suitable for testing of 1 thing: allocator.

**Comment by raver119** [comment]
Nvm. Will add ignore now.
