### ISSUE TITLE
putSlice() is not correct implemented (see issue 53, issues with tensors)

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#75]
I think the error is because of a false implementation of a tensor and slice in nd4j, see that other unfixed issue also: https://github.com/deeplearning4j/nd4j/issues/53

Example code:
INDArray w_grad_for_r = Nd4j.create(100,100,3);
w_grad_for_r.putSlice(0, Nd4j.create(100,100));

Output:
Exception in thread "main" java.lang.IllegalArgumentException: Illegal assignment, must be of same length
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:683)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putRow(BaseNDArray.java:2951)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putSlice(BaseNDArray.java:1213)
	at TensorTest(NTN.java:261)

Normally I should be able to add 3 slices of (100x100)

**Comment by agibsonccc** [comment]
Not true. This is interpreted in matlab syntax. This is actually numpy so the interpretation is 100 100 x 3 matrices.

The number of slices is 100. The correct interpretation for you here is 3 x 100 x 100

**Comment by c0der1337** [comment]
In Matlab or nupy the creation of a tensor works with: (x,y,slice) and to get a slice I use (:,:,slice)
I only need a function where I can access the last dimension / matrix. What is the best way to do this in nd4j?
-----------------
Use slice(arr.shape().length - 1)
Could you submit an issue for better slice syntax?
I should support -1 there

**Comment by c0der1337** [comment]
Please reopen, the issue with putslice() into a tensor is not fixed.

Test:
		INDArray w2 = Nd4j.rand(new int[]{2,2,3});
		w2.putSlice(1, Nd4j.rand(new int[]{2,2}));
		System.out.println("w: "+w2);

Output:
Exception in thread "main" java.lang.IllegalArgumentException: Illegal assignment, must be of same length
	at org.nd4j.linalg.api.ndarray.BaseNDArray.assign(BaseNDArray.java:695)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putRow(BaseNDArray.java:2918)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putSlice(BaseNDArray.java:1233)

numpy example:
In [7]: slice = np.random.random((2,2))
In [15]: w = np.random.random((2,2,3))

In [16]: w
Out[16]:
array([[[ 0.77356729,  0.89651426,  0.2167316 ],
        [ 0.84439425,  0.40246326,  0.40325025]],

       [[ 0.75520672,  0.4955578 ,  0.75185719],
        [ 0.85602582,  0.7248187 ,  0.45401675]]])

In [17]: w[:,:,0] = slice

In [18]: w
Out[18]:
array([[[ 0.64532771,  0.89651426,  0.2167316 ],
        [ 0.90602107,  0.40246326,  0.40325025]],

       [[ 0.91080093,  0.4955578 ,  0.75185719],
        [ 0.74651461,  0.7248187 ,  0.45401675]]])

In [19]: slice
Out[19]:
array([[ 0.64532771,  0.90602107],
       [ 0.91080093,  0.74651461]])
