### ISSUE TITLE
Issues with newtoflattened branch

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#752]
Hi @agibsonccc,
since you asked me to test the branch, here are some Issues that I encountered:

### ND4J not Initializing
Unless I add something like `-Dwhatever=org.nd4j.linalg.cpu.nativecpu.CpuBackend` ND4J doesn't even initialize any more. That is with only a single backend defined in my pom.xml and no other option that would allude to me wanting to specifically select a backend.

### Sum calculation results in wrong values
The calculation that is used in https://github.com/deeplearning4j/nd4j/issues/733 now results in wrong values even when forcing doubles. (The result is correct when OMP_NUM_THREADS=1).

### Using OpenMP is still slower than not using it
Still using the example from issue #733, but increasing the size to Integer.MAX_VALUE, setting OMP_NUM_THREADS=1 reduces the runtime to 13 seconds, while using a single core, when it uses all cores, it takes 21 to 25 seconds.

**Comment by AlexDBlack** [comment]
Tested on the most recent version of this branch: all issues mentioned above seem ok.
Though note this: https://github.com/deeplearning4j/nd4j/issues/754
