### ISSUE TITLE
ND4j CUDA Windows

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#755]
We need to highlight somehow, that for CUDA backend on Windows, if users got casual gaming gpu (like gtx 970/980 etc,) or literally non-Tesla gpu/driver - he needs to turn off Windows TDR watchdog. Otherwise, all long-running kernels will be crashing after a second or two.

Detailed instructions can be obtained from MS website: https://msdn.microsoft.com/en-us/library/windows/hardware/ff569918%28v=vs.85%29.aspx

**Comment by treo** [comment]
I've added a note about it to the windows.md of libnd4j, 8927fd0f8c7005a7906ee1ce1bd5f0f3922355a1
