### ISSUE TITLE
Multiple backends issue

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#756]
Right now, when using javacpp if two backends are specified in pom.xml, only the first one gets loaded and used. In both native cpu and cuda backends, target resource name is still jniNativeOps.

And since it would be nice to have different backends loaded at the same time, what workaround can we have there?

Here's how it works right now: https://github.com/deeplearning4j/nd4j/blob/0abcdf5d0493126506798c5ff057544495b7fd34/nd4j-backends/nd4j-api-parent/nd4j-native-api/src/main/java/org/nd4j/nativeblas/NativeOps.java#L15-L19

And javacpp Loader is scanning classpath for first target binary occurence: jniNativeOps.dll for example.

p.s. with maven-shade situation will become worse, if someone will have two backends at the same time, since two out of three backend binaries share name and they share common package name.

@saudet what would be the best solution here, from JavaCPP point of view?

**Comment by raver119** [comment]
Maybe make NativeOps abstract, and for each backend add it's own extender class? So, we'll have own namespace for each backend, while  relying on the same java code from parent abstract class? And since each of them will be located in its own namespace, we'll not have conflicts.

**Comment by saudet** [comment]
Basically, I guess we could copy `NativeOps.java` and `Nd4jBlas.java` to `nd4j-native` and `nd4j-cuda-7.5`, under different package names, and have them extend the original ones in `nd4j-native-api`, taking care to switch the methods from "native" to "abstract", and create instances of those two new classes in `JCublasNDArrayFactory` and `CpuNDArrayFactory`. How does that sound?

**Comment by agibsonccc** [comment]
If you know of a better way to do it give it a  shot.

**Comment by saudet** [comment]
BTW, we could automatically generate at build time these proxy classes with JavaCPP's Parser. That's what it's for. We could also use something like Byte Buddy to create the proxy classes dynamically, but I have a feeling this won't play well with Android. Another option is to use virtual dispatch from native C++. This would allow us to have only one Java class, but it wouldn't work on Windows, for example, where we need to use MSVC for CUDA and GCC for OpenMP: Their C++ runtimes are incompatible. This is one reason why people came up with things like Java and .NET in the first place. :)

**Comment by agibsonccc** [comment]
Any new thoughts here given recent changes?

**Comment by saudet** [comment]
In the end, do we need to be able to use two backends simultaneously?

**Comment by agibsonccc** [comment]
@saudet how will the new JIT loader in javacpp affect this?

**Comment by saudet** [comment]
It won't, it should behave same, that is we can choose our backend once at runtime by putting what we need in the class path, and that's it. As for uber JARs, the library files are still going to cause a conflict, yes...

**Comment by saudet** [comment]
Fixed: https://github.com/deeplearning4j/nd4j/pull/1508
