### ISSUE TITLE
Critical problem with padWithZeros

### ISSUE THREAD

**Issue by zomux** [deeplearning4j/nd4j#76]
Fix page:  https://github.com/deeplearning4j/nd4j/pull/9
Diff: https://github.com/guillempalou/nd4j/commit/421036835e070e822323e8bc7b91eb0b1b9b95b6

This fix causes critical problem that System.arraycopy actually fails to work.

asDouble() returns a duplicated array here.

**Comment by agibsonccc** [comment]
Fixed.
