### ISSUE TITLE
CUDA Ops state

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#766]
- [x] Current ReduceScalar<T>/IndexReduceScalar<T> explicitly favours 1-block execution architecture.
- [x] Some kernels rely on stack allocation. Especially SummaryStatsReduce. Here's compiler stats for it: https://gist.github.com/raver119/643eff6cc0e75d5cee46a8280752c5a2
- [ ] Guaranteed non-coalesced access for everything with stride != 1.

**Comment by raver119** [comment]
Pools were added to address cuBLAS resources sharing, but better synchronization policy should be considered there.

**Comment by raver119** [comment]
All allocator optimizations were disabled for till tests go stable. 

For now, no matter what zero-copy memory is used, without any caching, promotion, context sharing etc.

**Comment by raver119** [comment]
It's probably worth reconsidering referenceQueue use in allocator, since WeakHashMap isn't used anymore.

**Comment by saudet** [comment]
If you guys are talking about JavaCPP, to make use of its ReferenceQueue, we basically just need to register a deallocator. Here's an example where it's needed for TensorFlow:
https://github.com/bytedeco/javacpp-presets/blob/master/tensorflow/src/main/java/org/bytedeco/javacpp/helper/tensorflow.java#L160
Don't worry about the allocation bit, we just need to implement the `Pointer.Deallocator` interface, and make sure to call `Pointer.deallocator()` with it at some point after construction. (The TensorFlow example also extends `Session`, but that's for convenience only. It's not required by the deallocation mechanism.)

**Comment by saudet** [comment]
Be careful though, the deallocator must NOT hold any reference to the registered `Pointer` object. Create a copy or hold the raw address.

Anyway, @raver119 let me know when you're to try this out :)

**Comment by raver119** [comment]
Missed this one. When mentioned referenceQueue i was just planning migration (later, when we get to performance phase) from WeakReference to PhantomReference in one place, and change the reference direction within cuda allocator, nothing more. Just to make garbage collection a bit more simple.

Issue update for me: there's some JVM GC issue with Reduce kernel calls. Reproducible via appropriate stress-test.

**Comment by raver119** [comment]
- Multi-gpu environment seems to be working properly, but blas context synchronization is still an issue.

- almost all kernel-related tests are passing. those left are either multidimensional, or c/f ordering cases.

**Comment by raver119** [comment]
- blockwise reductions were added for everything except of reduce3 and transforms.

- got rid of memory allocations within kernels

**Comment by raver119** [comment]
blockwise scalar reductions are +- fine. but non-scalar reductions (especially along single dimension) should be reconsidered. they are only look like block-wise. but technically they are not.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/issues/848
