### ISSUE TITLE
Cuda tests failing

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#767]
https://gist.github.com/agibsonccc/19d2c5f4f937dc24d3a612bfd6ba6218

Of note here:

1. Add exec special cuda for transform
2. Implement im2col/col2im/softmax for exec special
3. Reduce with > 1 dimension needs  a do over
4. Broadcast needs some work
5. Gemv appears to be broken?
6. Summary stats reduce needs to be updated.
7. Dup/assign broke

**Comment by raver119** [comment]
5. Basic tests there were passing, but i'll check once again.
7. The same. Will check once again.

**Comment by agibsonccc** [comment]
@raver119 There are still edge cases there.. eg: result order != input order that we just found. We ned to replicate all of the cases found in cpu now. I think cpu has good enough coverage.

**Comment by raver119** [comment]
so 7. dup/assign is about INDArray level, not DataBuffer?

**Comment by agibsonccc** [comment]
Not sure what's going on there haven't investigated it. I just ran mvn
clean test and pasted the output in an issue :P

**Comment by raver119** [comment]
I've added separate tests to Level2/Level3 tests for gemv/gemm with different combinations of orders, but they are passing, giving out results equal to rc3.8.

**Comment by raver119** [comment]
Also, i've just changed streams assignment mechanics, to address jvm multithreading with futures etc, when short-living threads are spamming allocator/cuda for streams.

**Comment by agibsonccc** [comment]
Current status: https://gist.github.com/agibsonccc/d2f5fc1e2b69e6541b9c52d0029ca1df

**Comment by agibsonccc** [comment]
Down to only a few test left.

**Comment by agibsonccc** [comment]
Down to 3. Closing this in favor of the https://github.com/deeplearning4j/nd4j/issues/848
