### ISSUE TITLE
nd4j-native: crash in SoftMax class

### ISSUE THREAD

**Issue by newikov** [deeplearning4j/nd4j#777]
I tried to run the following code with nd4j-native and nd4j-cuda-7.5 on 0.4-rc3.9-SNAPSHOT

INDArray input = Nd4j.create(new double[]{ -0.75, 0.58, 0.42, 1.03, -0.61, 0.19, -0.37, -0.40, -1.42, -0.04}).transpose();
INDArray output = Nd4j.create(10,1); 
Nd4j.getExecutioner().exec(new Sigmoid(input, output));   
System.out.println("Sigmoid = " + output);
Nd4j.getExecutioner().exec(new SoftMax(input, output));   
System.out.println("Softmax = " + output);

With nd4j-cuda-7.5 it works slower than with 0.4-rc3.8 but does the job and returns correct result.  

With nd4j-native it crashes on the line when i use SoftMax. 

The console output is: 

Sigmoid = [ 0.32, 0.64, 0.60, 0.74, 0.35, 0.55, 0.41, 0.40, 0.19, 0.49]

A fatal error has been detected by the Java Runtime Environment:

  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000006c09b590, pid=8456, tid=6280

 JRE version: Java(TM) SE Runtime Environment (8.0_66-b18) (build 1.8.0_66-b18)
 Java VM: Java HotSpot(TM) 64-Bit Server VM (25.66-b18 mixed mode windows-amd64 compressed oops)
Problematic frame:
[libnd4j.dll+0x1b590]

I've attached the log file 

[hs_err_pid12836.zip](https://github.com/deeplearning4j/nd4j/files/200040/hs_err_pid12836.zip)

**Comment by agibsonccc** [comment]
I need more than this ;/ I can't reproduce this on my laptop.

**Comment by newikov** [comment]
I'm sure yes. I have cloned libnd4j and nd4j today for the first time. 
I will also try tomorrow on my home pc.

**Comment by agibsonccc** [comment]
Good find thanks !https://github.com/deeplearning4j/libnd4j/commit/9b0b398f85574e4d59190f76977eed979b0293a8
