### ISSUE TITLE
DataSet.shuffle() is very slow for arrays of rank > 2

### ISSUE THREAD

**Issue by jmacglashan** [deeplearning4j/nd4j#778]
The DataSet.shuffle() method seems to run exceedingly slow when the input data is a data array greater than 2 dimensions. For example, consider the following code that constructs a dataset:

```
INDArray tmpX = Nd4j.rand(new int[]{198, 57600});
INDArray tmpY = Nd4j.rand(new int[]{198, 3});
DataSet tds = new DataSet(tmpX, tmpY);
System.out.println("constructed temp");
long time = System.currentTimeMillis();
tds.shuffle();
long time2 = System.currentTimeMillis();
System.out.println("done shuffling; time: " + (time2 - time)/1000.);
```

The time it will take to shuffle this data is listed as 0.6 seconds on my system.

Now consider using a dataset of rank 4, but otherwise same number of elements.
```
INDArray tmpX = Nd4j.rand(new int[]{198, 3, 160, 120});
INDArray tmpY = Nd4j.rand(new int[]{198, 3});
DataSet tds = new DataSet(tmpX, tmpY);
System.out.println("constructed temp");
long time = System.currentTimeMillis();
tds.shuffle();
long time2 = System.currentTimeMillis();
System.out.println("done shuffling; time: " + (time2 - time)/1000.);
```

On my system, this operation takes 50 seconds, nearly 100 fold slower than when data is condensed into a 2D matrix. 

Since the rank 4 matches what you'd expect for images input, having it slow on a higher rank is problematic and I don't think it ought to take this long, since the 2D example and 4D example are shifting sections of the same number of consecutive elements.

Also, looking at the DataSet.shuffle() method, it appears that while it shuffles both the feature matrix and labels, it does not shuffle the masks for features and labels, which may be problematic?

**Comment by eraly** [comment]
Fixed. Masks will also now get shuffled.
Current snapshot:
I only see a 10% degradation when I go from a 2d to a 4d.
