### ISSUE TITLE
Add IsMax operation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#780]
The short version: IsMax would return an array of 0s and 1s; 0s everywhere except for a 1 if the value is the maximum. This would be most useful when executed along a dimension.

Motivation and explanation here:

https://gist.github.com/AlexDBlack/8f6572f00e5e3dd0f9b2346fee3a7eb7

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/786 https://github.com/deeplearning4j/libnd4j/pull/70
