### ISSUE TITLE
Dropout Distribution Sampling Performance Bottleneck

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#789]
When Dropout is enabled, it bottlenecks the learning process quite a bit.

![dropout-bottleneck](https://cloud.githubusercontent.com/assets/509379/14235024/a33ca786-f9f2-11e5-8d20-02d1ddfb1239.png)
![dropout-bottleneck-stack](https://cloud.githubusercontent.com/assets/509379/14235025/a6960daa-f9f2-11e5-8291-fd22713b4c6e.png)

**Comment by agibsonccc** [comment]
This was fixed with native dropout.
