### ISSUE TITLE
Check Shapes of Ops to make sure they are compatible before submitting them for native execution

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#798]
Today I have run into multiple JVM crashes due to incompatible array shapes. That the shapes are incompatible is my own error, but I would expect an Exception and not a JVM crash.

Interestingly the JVM only crashes when the arrays are large enough. So the following crashes the JVM:
```java
Nd4j.ones(10000, 1).sub(Nd4j.ones(1, 2));
```

While this seems to work:
```java
Nd4j.ones(10, 1).sub(Nd4j.ones(1, 2));
```

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/commit/f848e5baa87ef3629a309165813138d84d94b8a6
