### ISSUE TITLE
Load from Numpy binary

### ISSUE THREAD

**Issue by vladmaraev** [deeplearning4j/nd4j#801]
I would like to suggest to implement loading from Numpy binary files that are constructed by numpy.save method. 
Now loading of 3.5GB txt file (saved by numpy.savetxt) takes about 1 minute while loading correspondent 500MB binary is done in seconds in numpy.

**Comment by raver119** [comment]
We have Nd4j.createFromNpy now, it reads binary numpy file and creates INDArray
