### ISSUE TITLE
Allocating / Deallocating Array seems to become major bottleneck

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#806]
While training an RNN, I notice that it gets slower and slower, taking a look at the sampler, it shows that it spends most of its time now on allocating and deallocating arrays:

![array-allocation](https://cloud.githubusercontent.com/assets/509379/14359231/c84770dc-fcf0-11e5-8de4-5868729fce06.png)

@saudet maybe you know what is going on there. It uses between 10GB and 20GB of RAM.

**Comment by saudet** [comment]
Is this on Windows? That's a known issue: https://github.com/deeplearning4j/nd4j/issues/768#issuecomment-205133554

**Comment by treo** [comment]
Oh, I didn't see that issue. So this can be closed.
