### ISSUE TITLE
Bug executing operations on subArray 

### ISSUE THREAD

**Issue by tverbele** [deeplearning4j/nd4j#81]
I have the following error when executing operations on subArrays in c ordering.

For example

```
Nd4j.factory().setOrder('c');
       
INDArray nd = Nd4j.create(new double[]{1,2,3,4,5,6},new int[]{2,3});
System.out.println(nd);

INDArray sub = nd.subArray(new int[]{0,1}, new int[]{2,2}, new int[]{3,1});
System.out.println(sub);
       
Nd4j.getExecutioner().exec(new ScalarAdd(sub, 2));
       
System.out.println(sub);
System.out.println(nd);
```

Results in
```
[[1.0, 2.0, 3.0]
 [4.0, 5.0, 6.0]]

[[2.0, 3.0]
 [5.0, 6.0]]

[[4.0, 5.0]
 [7.0, 6.0]]

[[1.0, 4.0, 5.0]
 [6.0, 7.0, 6.0]]
```

While expected:
```
[[1.0, 4.0, 5.0]
 [4.0, 7.0, 6.0]]
```

This could also be related to #80

**Comment by agibsonccc** [comment]
Yeah there's  a lot of cases related to c ordering to work out. I am in the process of adding test cases for different common cases like this. Thanks for the report!

**Comment by agibsonccc** [comment]
Again: Just adding that a separate battery of tests has been created for both which should help this situation.

**Comment by agibsonccc** [comment]
This is fixed in bugfixes.
