### ISSUE TITLE
nd4j-native: IsMax along dimension incorrect

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#819]
IsMax along dimension for 2 dimensions appears to be OK, but appears to be incorrect for 3+ dimensions.
Specifically:
- Incorrect values (not 0 or 1) for 3d, c order and f order
- Various crashes for f order (see this, **note, multiple runs here with different results** https://gist.github.com/AlexDBlack/76a903c8e0346439bb39b610aed757c1)

```java
    @Test
    public void testIsMaxAlongDimensionSimple(){
        //Simple test: when doing IsMax along a dimension, we expect all values to be either 0 or 1
        //Do IsMax along dims 0&1 for rank 2, along 0,1&2 for rank 3, etc

        for( int rank = 2; rank <= 6; rank++ ){

            int[] shape = new int[rank];
            for( int i=0; i<rank; i++ ) shape[i] = 2;
            int length = ArrayUtil.prod(shape);


            for( int alongDimension=0; alongDimension<rank; alongDimension++ ){
                System.out.println("Testing rank " + rank + " along dimension " + alongDimension + ", (shape=" + Arrays.toString(shape) + ")");
                INDArray arrC = Nd4j.linspace(1,length, length).reshape('c',shape);
                INDArray arrF = arrC.dup('f');
                Nd4j.getExecutioner().execAndReturn(new IsMax(arrC, alongDimension));
                Nd4j.getExecutioner().execAndReturn(new IsMax(arrF, alongDimension));

                double[] cBuffer = arrC.data().asDouble();
                double[] fBuffer = arrF.data().asDouble();
                for( int i=0; i<length; i++ ){
                    assertTrue("c buffer value at ["+i+"]="+cBuffer[i] + ", expected 0 or 1; dimension = " + alongDimension
                        + ", rank = " + rank + ", shape=" + Arrays.toString(shape),
                        cBuffer[i]==0.0 || cBuffer[i] == 1.0);
                }
                for( int i=0; i<length; i++ ){
                    assertTrue("f buffer value at ["+i+"]="+fBuffer[i] + ", expected 0 or 1; dimension = " + alongDimension
                            + ", rank = " + rank + ", shape=" + Arrays.toString(shape),
                        fBuffer[i]==0.0 || fBuffer[i] == 1.0);
                }
            }
        }
    }
```

**Comment by agibsonccc** [comment]
I'm not seeing this, the test is in there now, could you verify? https://github.com/deeplearning4j/nd4j/blob/8ed48b66c1e4ba8527dcf9154615b2c025f1cbd4/nd4j-backends/nd4j-tests/src/test/java/org/nd4j/linalg/Nd4jTestsC.java#L667-L667

**Comment by AlexDBlack** [comment]
Well, consider me thoroughly confused :/

Running this test in nd4j: works fine (even running it in a loop - no issues), with nd4j-native backend.
Running this test in another project (specifically, a version of examples using nd4j-native): fails consistently. And yes, I've reinstalled nd4j and done reimport/invalidated caches etc int intellij (multiple times).
Also tried running it both on float vs. double: no difference.

**Comment by eraly** [comment]
So in the IDE - one of two things happen. I see the test fail or I see a core dump. Pasting part of the error report file. I suspect this has to do with mixing up malloc/new with free/delete.

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff90b3c2d2, pid=47336, tid=5891
#
# JRE version: Java(TM) SE Runtime Environment (8.0_66-b17) (build 1.8.0_66-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.66-b17 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libsystem_malloc.dylib+0x62d2]  tiny_free_list_remove_ptr+0x10b
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

...
...
...
...
...

R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value


Stack: [0x000070000011a000,0x000070000021a000],  sp=0x0000700000216e90,  free space=1011k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libsystem_malloc.dylib+0x62d2]  tiny_free_list_remove_ptr+0x10b
C  [libsystem_malloc.dylib+0x4fc4]  szone_free_definite_size+0xc16
C  [libnd4j.dylib+0x1a7a9]  shape::tad2Sub(int, int*, int, int*)+0x319
C  [libnd4j.dylib+0x87a3]  .omp_microtask.13+0x183
C  [libiomp5.dylib+0x400b3]  __kmp_invoke_microtask+0x93
C  [libiomp5.dylib+0x14d03]  __kmp_invoke_task_func+0xa1
C  [libiomp5.dylib+0x120f3]  __kmp_fork_call+0x13f3
C  [libiomp5.dylib+0x9e49]  __kmpc_fork_call+0xc8
C  [libnd4j.dylib+0x1b8f7]
