### ISSUE TITLE
Segfault in running tests (using native backend)

### ISSUE THREAD

**Issue by xuy** [deeplearning4j/nd4j#822]
Environment: Mac OS X 10.10.5
JVM version: 8.0_66 (Oracle)

Core dump:

---------------  T H R E A D  ---------------

Current thread (0x00007fae09806800):  JavaThread "main" [_thread_in_native, id=4867, stack(0x0000000102283000,0x0000000102383000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000028

Registers:
RAX=0x4000000000000000, RBX=0x00007fae0964cb90, RCX=0x0000000000000020, RDX=0x0000000000000004
RSP=0x0000000102380610, RBP=0x0000000102380640, RSI=0x00000000571c4a36, RDI=0x00000000571d23bb
R8 =0x00007fae09600000, R9 =0x00007fae0964cb80, R10=0x00007fae09600000, R11=0x000000000f840080
R12=0x0000000102155000, R13=0x00007fae0964cb98, R14=0x0000000000000000, R15=0x0000000000000000
RIP=0x00007fff912e84bf, EFLAGS=0x0000000000010202, ERR=0x0000000000000006
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x0000000102380610)
0x0000000102380610:   000000010215bc00 00007fae0964cb90
0x0000000102380620:   0000000000000010 0000000000000005
0x0000000102380630:   00000000000004ca 000000010215bc00
0x0000000102380640:   00000001023806e0 00007fff912e710d
0x0000000102380650:   00007fae0964cb70 0000000000000001
0x0000000102380660:   0000000102155000 00000000000004cb
0x0000000102380670:   00007fae09600000 00007fff02000000
0x0000000102380680:   00007fae096fc080 00007fae0964cb80
0x0000000102380690:   0000000000000001 00007fae0964cb80
0x00000001023806a0:   00007fae09600000 0000000102150001
0x00000001023806b0:   0000000102155000 00007fae0964e100
0x00000001023806c0:   00007fae0964d130 0000000000000001
0x00000001023806d0:   0000000000000000 0000000000000000
0x00000001023806e0:   0000000102380750 000000011b37ba8a
0x00000001023806f0:   0000000000000004 0000000000000006
0x0000000102380700:   00007fae0964e100 0000000000000005
0x0000000102380710:   00007fae0964d130 00007fae0964e120
0x0000000102380720:   00007fae0964cb80 000000011b367a80
0x0000000102380730:   000000011b444328 000000000000001f
0x0000000102380740:   00007fae0ba37600 0000000000000001
0x0000000102380750:   0000000102380a70 000000011b367c03
0x0000000102380760:   0000000102380810 00007fae00000001
0x0000000102380770:   0000000100000000 0000000102380ad0
0x0000000102380780:   00007fae09400cc0 00000001043cc860
0x0000000102380790:   00007fae00001fa0 0000000102380aa0
0x00000001023807a0:   0000000102380ea0 0000000102380eb0
0x00000001023807b0:   0000000102380df8 0000000102380e14
0x00000001023807c0:   0000000102380e08 0000000102380ea8
0x00000001023807d0:   00007fae09400d78 0000000000000000
0x00000001023807e0:   0000004000000000 0000000000000000
0x00000001023807f0:   000000011b3ae8e0 00000001166ba7b8
0x0000000102380800:   00000007b447df80 0000000102380c50

Instructions: (pc=0x00007fff912e84bf)
0x00007fff912e849f:   89 c7 48 c1 ef 30 01 f7 48 c1 e8 38 01 f8 48 83
0x00007fff912e84af:   e0 0f 48 39 c2 75 14 48 85 c9 74 1a 49 8b 45 00
0x00007fff912e84bf:   48 89 41 08 4d 85 f6 75 1e eb 3c 4c 89 e7 48 89
0x00007fff912e84cf:   de e8 db a1 00 00 44 89 f8 48 8b 55 d0 4c 89 74

Register to memory mapping:

RAX=0x4000000000000000 is an unknown value
RBX=0x00007fae0964cb90 is an unknown value
RCX=0x0000000000000020 is an unknown value
RDX=0x0000000000000004 is an unknown value
RSP=0x0000000102380610 is pointing into the stack for thread: 0x00007fae09806800
RBP=0x0000000102380640 is pointing into the stack for thread: 0x00007fae09806800
RSI=0x00000000571c4a36 is an unknown value
RDI=0x00000000571d23bb is an unknown value
R8 =0x00007fae09600000 is an unknown value
R9 =0x00007fae0964cb80 is an unknown value
R10=0x00007fae09600000 is an unknown value
R11=0x000000000f840080 is an unknown value
R12=0x0000000102155000 is an unknown value
R13=0x00007fae0964cb98 is an unknown value
R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value

Stack: [0x0000000102283000,0x0000000102383000],  sp=0x0000000102380610,  free space=1013k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libsystem_malloc.dylib+0x64bf]  tiny_free_list_remove_ptr+0x10b
C  [libsystem_malloc.dylib+0x510d]  szone_free_definite_size+0xc0e
C  [libnd4j.dylib+0x1ca8a]  shape::tad2Sub(int, int*, int, int*)+0x3da
C  [libnd4j.dylib+0x8c03]  .omp_microtask.13+0x183
C  [libiomp5.dylib+0x42053]  __kmp_invoke_microtask+0x93
C  [libiomp5.dylib+0x140bf]  __kmp_invoke_task_func+0xa1
C  [libiomp5.dylib+0x1145c]  __kmp_fork_call+0x1362
C  [libiomp5.dylib+0x9061]  __kmpc_fork_call+0xc0
C  [libnd4j.dylib+0x1dc2a]  functions::transform::ops::IsMax<float>::execSpecial(float*, int*, float*, int*, float*)+0xb6a
C  [libnd4j.dylib+0x7149]  NativeOps::execTransformFloat(long long*, int, long long, long long, long long, long long, long long)+0x49
C  [libjniNativeOps.dylib+0x937e]  Java_org_nd4j_nativeblas_NativeOps_execTransformFloat___3JIJJJJJ+0xbe
j  org.nd4j.nativeblas.NativeOps.execTransformFloat([JIJJJJJ)V+0
j  org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(Lorg/nd4j/linalg/api/ops/TransformOp;)V+1088
j  org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.exec(Lorg/nd4j/linalg/api/ops/Op;)Lorg/nd4j/linalg/api/ops/Op;+34
j  org.nd4j.linalg.api.ops.executioner.DefaultOpExecutioner.execAndReturn(Lorg/nd4j/linalg/api/ops/TransformOp;)Lorg/nd4j/linalg/api/ndarray/INDArray;+2
j  org.nd4j.linalg.Nd4jTestsC.testIsMaxAlongDimensionSimple()V+146
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x2ea35e]  JavaCalls::call_helper(JavaValue*, methodHandle*, JavaCallArguments*, Thread*)+0x6ae
V  [libjvm.dylib+0x4ca7e0]%

**Comment by agibsonccc** [comment]
Could I get some code that reproduces this? Also do you have the latest libnd4j?

**Comment by xuy** [comment]
Just running mvn test on the lastest code cloned from github.

**Comment by agibsonccc** [comment]
Can you give me a whole gist of the run log?

**Comment by agibsonccc** [comment]
I'm not seeing this. Closing this.
