### ISSUE TITLE
JVM-based backend for hosted java / spark environments

### ISSUE THREAD

**Issue by kmader** [deeplearning4j/nd4j#835]
I am trying to use ND4J on a hosted Spark environment (Databricks Cloud) but the dependency (```org.nd4j:nd4j-x86:0.4-rc3.8```) won't load presumably because the blas dependency (fommil.netlib_all, see below). I saw there was an abandoned repository at (https://github.com/SkymindIO/nd4j-vectorz), is there another way of having a JVM only backend for ND4J? This would be useful deploying models on a number of hosted Java/Scala/Spark environments.

```
Error: Unknown error while checking maven dependencies.?FileNotFoundException: /root/.ivy2/jars/com.github.fommil.netlib_all-1.1.2.jar (No such file or directory)?java.io.FileNotFoundException: /root/.ivy2/jars/com.github.fommil.netlib_all-1.1.2.jar (No such file or directory)?	at java.io.FileInputStream.open0(Native Method)?	at java.io.FileInputStream.open(FileInputStream.java:195)?	at java.io.FileInputStream.<init>(FileInputStream.java:138)?	at com.databricks.libraries.server.MavenInstaller$$anonfun$uploadToDBFS$1.apply(MavenLibraryResolver.scala:60)?	at com.databricks.libraries.server.MavenInstaller$$anonfun$uploadToDBFS$1.apply(MavenLibraryResolver.scala:58)?	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224)?	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)?	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403)?	at com.databricks.libraries.server.MavenInstaller.uploadToDBFS(MavenLibraryResolver.scala:58)?	at com.databricks.libraries.serve
```

**Comment by raver119** [comment]
I doub't there's sense for that, due to performance issues with JVM-based math. That's why we're working on better native code.

Java is just slow.

**Comment by kmader** [comment]
It is undoubtably slow, but there are many environments where it is not possible to use native libraries so it would be great if there was a pure jvm solution.

**Comment by agibsonccc** [comment]
I'm closing this, I'm not sure why we wouldn't be able to have native binaries if it was self contained. If you have more specific requirements than "some environments" I'd be happy to hear that in a separate issue. We work directly with cloudera and horton works on this, if that's "other environments" for you, we'd be happy to have that conversation.

**Comment by kmader** [comment]
@agibsonccc see the original post, neither Databricks Cloud, Jupyter Spark Notebook, Jupyter Scala Notebook, nor IBM Analytics for Apache Spark can successfully use DL4J.  Either the dependencies cannot even be loaded (DBC in error message above, IBM) or where the dependencies can be loaded, the native libraries cannot be found (Spark Notebook, Scala Notebook). In several other tools the ```java.library.path``` cannot be changed at runtime which will make loading the dependencies dynamically problematic.

**Comment by fac2003** [comment]
I second the feature request for a pure java backend. I think it makes sense in specific cases. 

For instance, we have older servers on our compute farm that just cannot be upgraded to the latest versions of libraries needed to compile nd4j (by cannot I don't mean that it is impossible technically, it just would require a full OS upgrade and our IT staff won't take up the tasks for a 400 core cluster at this time, when they could do it is an open question). 

A pure Java backend, although much slower, would still make sense to support older systems where ND4J cannot be linked to shared libraries. In this case, we have trained the models on more recent systems and only need to execute them, so speed of model evaluation is not a key issue when we can parallelize on 400 cores.

**Comment by fac2003** [comment]
Another specific example is to help adoption. We are planning to distribute DL4J models with an open-source, so far pure Java bioinformatics tool. The tool can typically be downloaded and run directly with no other requirement than Java. Once we pack DL4J models into the distribution we will need the end-users to have a compatible system to link the native libraries. Users likely to download the tool may not have the patience to install all required dependencies, so this could hurt adoption. It would be much better in this instance to have a pure java backend that can be used if everything else fails. Then users can try the tool with the models and if they like the results but find the tool too slow can go through the native installation. 

I think this is another reason why a pure java backend would make sense.

**Comment by AlexDBlack** [comment]
"For instance, we have older servers on our compute farm that just cannot be upgraded to the latest versions of libraries needed to compile nd4j"
Then don't compile nd4j? Just use the versions on maven central like everyone else. We strongly recommend people do that unless they are developing dl4j/nd4j.

"A pure Java backend, although much slower, would still make sense to support older systems where ND4J cannot be linked to shared libraries."
We need specifics. What operating systems are you trying to run, that you can't run currently?

"Users likely to download the tool may not have the patience to install all required dependencies,"
There are no other dependencies to install - it's all jars. All required native dependencies are bundled. Use nd4j-native-platform for distribution (that includes native binaries for all platforms).

**Comment by fac2003** [comment]
I cloned the DL4J examples plugin on one of these servers. The maven package command succeeded. I believe the jars, including native ones are built. I execute runexamples and select option 2, see the error below.
This suggests to me that the library GOMP_4.0 is not installed on this system and cannot be linked to. You use shared linking after all  (.so), not static linking.

With respect to the OS, it's some older release of redhat (5 or 6, we have servers on both depending on when they were configured).


Enter a number for the example to run: 2

====== org.deeplearning4j.examples.convolution.LenetMnistExample

o.d.e.c.LenetMnistExample - Load data....
o.d.b.MnistFetcher - Downloading mnist...


o.d.e.c.LenetMnistExample - Build model....
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnind4j in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:845)
	at java.lang.System.loadLibrary(System.java:1084)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:726)
	at org.bytedeco.javacpp.Loader.load(Loader.java:501)
	at org.nd4j.nativeblas.NativeOps.<clinit>(NativeOps.java:31)
	at org.nd4j.linalg.cpu.nativecpu.ops.NativeOpExecutioner.<init>(NativeOpExecutioner.java:33)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
	at java.lang.Class.newInstance0(Class.java:374)
	at java.lang.Class.newInstance(Class.java:327)
	at org.nd4j.linalg.factory.Nd4j.initWithBackend(Nd4j.java:5093)
	at org.nd4j.linalg.factory.Nd4j.initContext(Nd4j.java:5021)
	at org.nd4j.linalg.factory.Nd4j.<clinit>(Nd4j.java:169)
	at org.deeplearning4j.nn.conf.NeuralNetConfiguration$Builder.seed(NeuralNetConfiguration.java:487)
	at org.deeplearning4j.examples.convolution.LenetMnistExample.main(LenetMnistExample.java:45)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/javacpp8128481090622289/libjnind4j.so: /usr/lib64/libgomp.so.1.0.0: version `GOMP_4.0' not found (required by /tmp/javacpp8128481090622289/libnd4j.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1939)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1864)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1825)
	at java.lang.Runtime.load0(Runtime.java:792)
	at java.lang.System.load(System.java:1059)
	at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:709)
	... 14 more

**Comment by saudet** [comment]
The binaries we distribute run seamlessly just like any other Java library on systems used by most people these days (Windows 7+, Ubuntu 14.04+, CentOS 6+, Mac OS X 10.9+). For anything else such as CentOS 5, it should be possible to patch libnd4j and make it work with older compilers -- it's just C++ after all. No need to reinstall your whole compute farm.

Sure, a pure Java implementation has its merits, but what happens when we switch to Java 8 and your compute farm doesn't support Java 8? It's not because it's Java that it will always work on older machines... We're open to contributions though. We're not against the idea. We just don't have the bandwidth to support everything.

**Comment by fac2003** [comment]
I understand your constraints, I just wanted to point out that a pure java backend has merit.
We might instead run DL4j in the cloud for now, it won't help the adoption issue, but at least will get us the data we are trying to produce.

**Comment by saudet** [comment]
@fac2003 Let us know if you encounter any issues building libnd4j on CentOS 5 though. We can help with that at least!
