### ISSUE TITLE
Performance Bottleneck / Cuda

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#836]
Running the SyntheticRNN, most of the time seems to be spent allocating minor arrays:
![image](https://cloud.githubusercontent.com/assets/509379/14637816/0fbbf8c4-0634-11e6-9801-78e375775812.png)

**Comment by agibsonccc** [comment]
The problem here is ops are created every time. Are we going to do a cuda specific fix here?

**Comment by raver119** [comment]
Not sure yet. But we definitely don't wont those minor allocations and copies flying all over the stack

**Comment by raver119** [comment]
Fixed.
