### ISSUE TITLE
Maven convergence error happens

### ISSUE THREAD

**Issue by wihoho** [deeplearning4j/nd4j#843]
Dependency convergence error for com.github.fommil.netlib:core:1.1.2 paths to dependency are:
  +-org.nd4j:nd4j-x86:0.4-rc3.8
    +-com.github.fommil.netlib:all:1.1.2
      +-com.github.fommil.netlib:core:1.1.2
and
  +-org.nd4j:nd4j-x86:0.4-rc3.8
    +-com.github.fommil.netlib:all:1.1.2
      +-com.github.fommil.netlib:netlib-native_ref-osx-x86_64:1.1
        +-com.github.fommil.netlib:native_ref-java:1.1
          +-com.github.fommil.netlib:core:1.1
and
  +-org.nd4j:nd4j-x86:0.4-rc3.8
    +-com.github.fommil.netlib:all:1.1.2
      +-com.github.fommil.netlib:netlib-native_system-osx-x86_64:1.1
        +-com.github.fommil.netlib:native_system-java:1.1
          +-com.github.fommil.netlib:core:1.1

56165 [WARNING] Rule 0: org.apache.maven.plugins.enforcer.DependencyConvergence failed with message:
Failed while enforcing releasability the error(s) are [
Dependency convergence error for com.github.fommil.netlib:core:1.1.2 paths to dependency are:
  +-org.nd4j:nd4j-x86:0.4-rc3.8
    +-com.github.fommil.netlib:all:1.1.2
      +-com.github.fommil.netlib:core:1.1.2
and
  +-org.nd4j:nd4j-x86:0.4-rc3.8
    +-com.github.fommil.netlib:all:1.1.2
      +-com.github.fommil.netlib:netlib-native_ref-osx-x86_64:1.1
        +-com.github.fommil.netlib:native_ref-java:1.1
          +-com.github.fommil.netlib:core:1.1
and
  +-org.nd4j:nd4j-x86:0.4-rc3.8
    +-com.github.fommil.netlib:all:1.1.2
      +-com.github.fommil.netlib:netlib-native_system-osx-x86_64:1.1
        +-com.github.fommil.netlib:native_system-java:1.1
          +-com.github.fommil.netlib:core:1.1

**Comment by agibsonccc** [comment]
We got rid of net lib java for the newest release. I'm closing this..

**Comment by wihoho** [comment]
May you tell me when you are going to release the new version? Thanks.
