### ISSUE TITLE
Error with Nd4j.toFlattened(arr) - order for flattened tensor not correct

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#85]
Numpy:
In [1]: import numpy as np

In [2]: w = np.random.random((2,2,2))

In [4]: w.flatten()
Out[4]:
array([ 0.63019179,  0.86873732,  0.32258349,  0.77040096,  0.43205056,
        0.5644703 ,  0.75162634,  0.61234062])

In [5]: w
Out[5]:
array([[[ 0.63019179,  0.86873732],
        [ 0.32258349,  0.77040096]],

       [[ 0.43205056,  0.5644703 ],
        [ 0.75162634,  0.61234062]]])

ND4J:
INDArray w = Nd4j.rand(new int[]{2,2,2});
		System.out.println("w: "+w);
		System.out.println("w flattened: " + Nd4j.toFlattened(w));

Output:
w: [[[0.4068617820739746, 0.2341649830341339]
 [0.10328156501054764, 0.9875390529632568]]
[[0.47300493717193604, 0.6653125882148743]
 [0.02655656635761261, 0.007591337896883488]]

w flattened: [0.4068617820739746, 0.47300493717193604, 0.10328156501054764, 0.02655656635761261, , ..., 0.6653125882148743, 0.9875390529632568, 0.007591337896883488]

expected:
[0.4068617820739746, 0.2341649830341339, 0.10328156501054764, 0.9875390529632568, 0.47300493717193604, 0.6653125882148743, 0.02655656635761261, 0.007591337896883488

**Comment by c0der1337** [comment]
This issue seems to be corresponding to the tensor implementation of nd4j, such as that error https://github.com/deeplearning4j/nd4j/issues/53

**Comment by agibsonccc** [comment]
Could you try that with fortran ordering? I wonder if it'd be the same. nd4j defaults to fortran ordering whereas numpy does to c ordering.

**Comment by agibsonccc** [comment]
Closing due to lack of response. Re open if this is an issue.
