### ISSUE TITLE
Problem to classify separate image at one model , loaded from disk. 

### ISSUE THREAD

**Issue by alekospj** [deeplearning4j/nd4j#857]
Hello, i created a program which training and evaluating a model with set of images, now in the next step, i am loading my model and my configurations of the model , i am creating a new data set from a alone image... and i want evaluation statistics for this image. I just want the classification quota for this image.. something is going wrong with the size of the matrices.. there is an other way to achieve this? when can i see a good example.. thanks..
[my_code.txt](https://github.com/deeplearning4j/nd4j/files/234434/my_code.txt)

**Comment by agibsonccc** [comment]
Please ask these kinds of things in gitter. This is better off as a discussion.
