### ISSUE TITLE
getRow index out of bounds exception

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#858]
I'm seeing array index out of bounds exceptions on any getRow operations (both c and f order), on nd4j master.

Easy to reproduce:
INDArray arr = Nd4j.create(new int[]{4,5},'c');
arr.getRow(0);

**Comment by treo** [comment]
That error is due to the forced tensor shape commit (24a3b297626fc46a6083bb078edd36240e26444e). `getRow` asks for only a single dimension, which results in a tensorShape that has only a single dimension.

I haven't quite figured out what is supposed to happen in that case.
