### ISSUE TITLE
DataSet.merge not generalizing to any shape, causing crash when training with Spark

### ISSUE THREAD

**Issue by Habitats** [deeplearning4j/nd4j#861]
I'm trying to train with Spark using  the following code:
```
    var net = FeedForward.create(...) 
    val sparkNetwork = new SparkDl4jMultiLayer(sc, net)

    val trainIter: List[DataSet] = new FeedForwardIterator(...).asScala.toList  // Iterator works without Spark
    val rddTrain: JavaRDD[DataSet] = sc.parallelize(trainIter)

    for (i <- 0 until neuralPrefs.epochs) {
      net = sparkNetwork.fitDataSet(rddTrain, 200, 2) // CRASH
      ... 
    }

    net
```

But it crashes. According to Adam it's because `DataSet.merge` is not generalizing to any shape.

Full stack trace: https://gist.github.com/Habitats/9f86775c13dbfe958e1817142398dd9a

**Comment by AlexDBlack** [comment]
What shape data specifically are you using?

**Comment by crockpotveggies** [comment]
I've encountered the same issue and the dataset that created the same bug consists of black and white JPEGS (for convolutional nets).

**Comment by Habitats** [comment]
For the FFN I'm using 1000D vectors, and for the RNN I'm using n 1000D vectors in a timeseries.

**Comment by Habitats** [comment]
More specifically, the features for the RNN are of shape `[3,50,1000,68,68000,68,1,0,1,99]` and the FFN `[2,500,1000,1000,1,0,1,99]`,

**Comment by AlexDBlack** [comment]
Forgot to close this one earlier.
Fixed here: https://github.com/deeplearning4j/nd4j/pull/867
