### ISSUE TITLE
DataSet.asList does not work (correctly) for time series data

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#862]
DataSet.asList():
https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/dataset/DataSet.java#L672

This method uses getRow, which is not suitable for use with time series data (which have 3d arrays).

**Comment by agibsonccc** [comment]
I changed this to slice. Feel free to close this if it's suitabl.

**Comment by agibsonccc** [comment]
Is this still the case? I know @eraly did a pass on this.

**Comment by AlexDBlack** [comment]
Sorry, I missed the earlier comment on the changes.
Note re: the slice change, this won't work:
https://github.com/deeplearning4j/nd4j/commit/5747ff30362730216cf5e87e6fa2db855aa20081

A few things wrong with that:
- Slice returns a 2d array, we get miniBatchsize arrays of shape [vectorSze, timeSeriesLength] from the original 3d time series array of shape [miniBatchsize, vectorSize, timeSeriesLength]. What we really need is outputs of shape [1, vectorSize, timeSeriesLength] (otherwise: merge methods etc will think it's a 2d data set, not a 3d time series data set
- Currently the mask arrays (if present) are not being added to the outputs.

Also @eraly if you are going to take a look at this: at least one unit test would be good.

**Comment by eraly** [comment]
Fixed so will work on 3d and 4d. Includes mask arrays as well. Also, added a test.
Closing.
