### ISSUE TITLE
BaseNDArray.rank() is lost when using spark

### ISSUE THREAD

**Issue by wobu** [deeplearning4j/nd4j#863]
As soon as using an BaseNDArray, or maybe any other implementation, within a RDD of spark. The rank information gets lost. I assume some other fields are affected as well.

This bug was nonexistant in 0.4-rc3.8

Sample test code in scala:

```scala
import org.apache.spark.SparkContext

object Test extends App {
  import org.nd4j.linalg.factory.Nd4j

  val sc = new SparkContext("local", "Test")

  val array = Nd4j.create(1, 100, 100)

  println(array.rank())

  sc.parallelize(Seq(array)).foreach {
    s => println(s.rank())
  }
}
```

I had a time series dataset and was training a RNN with Spark and got following stacktrace: [Stacktrace](https://gist.github.com/wobu/5e296430b07706b76153b523dfe1dac9)

My observations when debugging locally:
- changes since rc3.8 the shapeInformation was marked as transient, which isn't preserverd when serializing withing spark jobs
- the exceptions in the stacktrace happens when spark is trying to merge several datasets. In this method it is explicitly checked for a timeseries dataset with Rank() == 3 but getting only 0.

**Comment by wobu** [comment]
commit d40d4e9ec748904f15c329178dee133be9d76f51 seems to have fixed this issue. I will test this further.

**Comment by AlexDBlack** [comment]
Fixed here: https://github.com/deeplearning4j/nd4j/pull/867
