### ISSUE TITLE
Encountered Java fatal error SIGFPE during training

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/nd4j#869]
While training a convolutional net using a dataset of <10,000 black and white JPEGs,  I encountered a fatal error while training my net using Spark `1.6.1`:
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGFPE (0x8) at pc=0x000000012a82c8ba, pid=32002, tid=76291
#
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.65-b01 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libnd4j.dylib+0x278ba]  _ZN5shape8ind2subCEiPiii+0x8a
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

Application output is here: https://gist.github.com/crockpotveggies/8fdcaa59224a25b62f6d237a8c2120c3

This is the configuration of my convolutional neural net: https://gist.github.com/crockpotveggies/d342bbb8a614fc88286bb8e75a8454e1

**Comment by crockpotveggies** [comment]
I noticed the behavior of this bug changed when I changed the target JVM to `1.7` from `1.8`. It's possible something may not be compatible with the never JVM or there's a bug in the newer JVM.

**Comment by agibsonccc** [comment]
Could you give us a way to reproduce this? This is actually a c++ error in libnd4j. I'm closing this. Reopen this with a way to reproduce it under libnd4j.
