### ISSUE TITLE
ND4j.Concat() in current version do not work correct

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#87]
Code:
System.out.println("one:"+one);
		System.out.println("one flatten: "+Nd4j.toFlattened(one));
		System.out.println("two:"+two);
		System.out.println("two flatten: "+Nd4j.toFlattened(two));
		System.out.println("concated:" + Nd4j.concat(0, Nd4j.toFlattened(one), Nd4j.toFlattened(two)));;
		System.out.println("rows: "+Nd4j.concat(0, Nd4j.toFlattened(one), Nd4j.toFlattened(two)).rows()+"| columns: "+Nd4j.concat(0, Nd4j.toFlattened(one), Nd4j.toFlattened(two)).columns());

-------------------------------------------------
Output (correct) with 0.0.3.5.5.1:
one:[0.0, 0.0, 0.0, 0.0]
 
one flatten: [0.0, 0.0, 0.0, 0.0]
 
two:[[1.0, 1.0, 1.0]
 [1.0, 1.0, 1.0]]

two flatten: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
 
concated:[0.0, 0.0, 0.0, 0.0, , ..., 1.0, 1.0, 1.0]
 
rows: 1| columns: 10

-------------------------------------------------
Output current version (or with one (1,1) the concated array has the size of (1,2), no error):
one:[0.0, 0.0, 0.0, 0.0]
 
one flatten: [0.0, 0.0, 0.0, 0.0]
 
two:[[1.0, 1.0, 1.0]
 [1.0, 1.0, 1.0]]

two flatten: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
 
Exception in thread "main" java.lang.IllegalArgumentException: Illegal index 8 derived from 8 with offset of 0 and stride of 1
	at org.nd4j.linalg.api.ndarray.BaseNDArray.linearIndex(BaseNDArray.java:2649)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.putScalar(BaseNDArray.java:705)
	at org.nd4j.linalg.factory.BaseNDArrayFactory.concat(BaseNDArrayFactory.java:939)
	at org.nd4j.linalg.factory.Nd4j.concat(Nd4j.java:2020)
-------------------------------------------------
And in an other case I also get an error because of dimension 0...

**Comment by agibsonccc** [comment]
Current version?

**Comment by agibsonccc** [comment]
Concat is fixed in bugfixes.
