### ISSUE TITLE
BaseNDArray: shapeInformation.asNioInt() overhead?

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#875]
I'm not 100% sure on this, but it looks like the various shapeInformation.asNioInt() calls in BaseNDArray result in object creation. It should be possible to cache the resulting IntBuffer, so that it's only ever created once.

**Comment by agibsonccc** [comment]
Fixed with recent PR. https://github.com/deeplearning4j/nd4j/pull/874
