### ISSUE TITLE
arr.getColumns(int[] indices) only returns zeros

### ISSUE THREAD

**Issue by c0der1337** [deeplearning4j/nd4j#89]
Bitchy bug, wondering about crazy results.... if I try to read values via arr.getColumns(int[] indices), I only get zeros as return.

I use currently version 0.0.3.5.5.2

Code:
System.out.println("columns: "+columns.length+"e1:"+e1.length());
			System.out.println("e1: "+e1);
			int[] indices_test = new int[]{2,3,4};
			System.out.println("e1.getInt(columns): "+e1.getColumns(indices_test));
			System.out.println("e1.getInt(columns): "+e1.getColumn(3));

Output:
columns: 31e1:40
e1: [5431.0, 18.0, 28580.0, 15.0, , ..., 23.0, 9097.0, 26096.0]
 
e1.getInt(columns): [0.0, 0.0, 0.0]
 
e1.getInt(columns): 15.0

**Comment by agibsonccc** [comment]
Not applicable for current versions.

**Comment by c0der1337** [comment]
ok, i will waiting for the new build. However in the latest build 0.0.3.5.5.3 its also the same issue...

**Comment by agibsonccc** [comment]
Then re open the issue.

**Comment by agibsonccc** [comment]
I have a fortran and c ordering test for each now. No problems in master.
