### ISSUE TITLE
Eps returning incorrect results

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#895]
The following test passes on 3.8, fails on 3.9-native. Note abs(0-0.01) < Nd4j.EPS_THRESHOLD, where EPS_THRESHOLD is 1e-5.
```java
    @Test
    public void testEps2(){

        INDArray first = Nd4j.ones(10).divi(100);    //0.01
        INDArray second = Nd4j.zeros(10);            //0.0

        INDArray expAllZeros1 = Nd4j.getExecutioner().execAndReturn(new Eps(first,second,Nd4j.create(new int[]{1,10},'f'), 10));
        INDArray expAllZeros2 = Nd4j.getExecutioner().execAndReturn(new Eps(second,first,Nd4j.create(new int[]{1,10},'f'), 10));

        System.out.println(expAllZeros1);
        System.out.println(expAllZeros2);

        assertEquals(0, expAllZeros1.sumNumber().doubleValue(), 0.0);
        assertEquals(0, expAllZeros2.sumNumber().doubleValue(), 0.0);
    }
```

Also:
eps has op number 10: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/impl/transforms/comparison/Eps.java#L58
but 10 is less or equal in libnd4j: https://github.com/deeplearning4j/libnd4j/blob/ff8655407d6d571e1f9e0571c6fcfb54fe24f770/include/scalar.h#L1041

**Comment by agibsonccc** [comment]
This is fixed. https://github.com/deeplearning4j/libnd4j/commit/90d1e61f94ff20cd806df861962a9afd77ffca23
