### ISSUE TITLE
Shape mis match error on multiple models

### ISSUE THREAD

**Issue by crockpotveggies** [deeplearning4j/nd4j#897]
Experiencing a shape error on both AlexNet and my own custom configured network. I've uploaded a repo for reproducibility, and forwarded a dataset to @agibsonccc.

Repo (run with `gradle run`): https://github.com/crockpotveggies/libnd4j-SIGFPE-error

Stacktrace:
```
INFO  [2016-05-05 22:55:19,093] org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer: Starting early stopping training
WARN  [2016-05-05 22:55:22,641] org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer: Early stopping training terminated due to exception at epoch 0, iteration 0
! java.lang.IllegalStateException: Mis matched shapes
! at org.nd4j.linalg.util.LinAlgExceptions.assertSameLength(LinAlgExceptions.java:38) ~[nd4j-api-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2715) ~[nd4j-api-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.nd4j.linalg.api.ndarray.BaseNDArray.subi(BaseNDArray.java:2696) ~[nd4j-api-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.nd4j.linalg.api.ndarray.BaseNDArray.sub(BaseNDArray.java:2476) ~[nd4j-api-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.nn.layers.BaseOutputLayer.getGradientsAndDelta(BaseOutputLayer.java:181) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.nn.layers.BaseOutputLayer.backpropGradient(BaseOutputLayer.java:160) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.calcBackpropGradients(MultiLayerNetwork.java:1075) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.backprop(MultiLayerNetwork.java:1028) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.computeGradientAndScore(MultiLayerNetwork.java:1689) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.optimize.solvers.BaseOptimizer.gradientAndScore(BaseOptimizer.java:152) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.optimize.solvers.StochasticGradientDescent.optimize(StochasticGradientDescent.java:56) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.optimize.Solver.optimize(Solver.java:51) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1365) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.nn.multilayer.MultiLayerNetwork.fit(MultiLayerNetwork.java:1402) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.earlystopping.trainer.EarlyStoppingTrainer.fit(EarlyStoppingTrainer.java:60) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at org.deeplearning4j.earlystopping.trainer.BaseEarlyStoppingTrainer.fit(BaseEarlyStoppingTrainer.java:113) ~[deeplearning4j-core-0.4-rc3.9-SNAPSHOT.jar:na]
! at ai.bernie.researchtests.TrainNetStandalone$.main(TrainNetStandalone.scala:95) [main/:na]
! at ai.bernie.researchtests.TrainNetStandalone.main(TrainNetStandalone.scala) [main/:na]
```

**Comment by agibsonccc** [comment]
So the root cause is an assertion where : 
https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-core/src/main/java/org/deeplearning4j/nn/layers/BaseOutputLayer.java#L181

Output length isn't matching labels.
See:
        INDArray outSubLabels = output.sub(getLabels2d());

The assertion is happening here:
https://github.com/deeplearning4j/nd4j/blob/ad3abf62b7e07e7ac55cfc70aedd091ee9f9b8c5/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/ops/BaseTransformOp.java#L34-L34

Is labels returning the wrong length or maybe there's a race condition happening here with spark?

**Comment by crockpotveggies** [comment]
Okay I was able to finally get this to run, and it appears to be an API issue with `ImageRecordReader`. When `appendLabels` is set to `true` *and* you are also providing your own empty `ArrayList` as a destination for the labels, somehow this class isn't utilized properly and/or the labels aren't actually appended.

The following changes in `TrainNetStandalone` made it work:
```
    //val trainLabels = new java.util.ArrayList[String]()
    //List("0","1","2","3","4","5","6","7").foreach { label => trainLabels.add(label) }

    val trainRecordReader = new ImageRecordReader(imageWidth, imageHeight, nChannels, true)
    trainRecordReader.initialize(new FileSplit(new java.io.File("./cnn_dataset")))

    //println(s"\n\nNumber of labels: ${trainLabels}\n\n")

    //val trainingSetIterator: DataSetIterator = new RecordReaderDataSetIterator(trainRecordReader, batchSize, imageWidth*imageHeight*nChannels, trainLabels.size())
    val trainingSetIterator: DataSetIterator = new RecordReaderDataSetIterator(trainRecordReader, batchSize, -1, 8)
```

Note the key changes here are that I'm using a different constructor `ImageRecordReader(imageWidth, imageHeight, nChannels, true)` and stopped using my own user-provided class. Somehow this is causing issues within the trainer.

Interestingly, making this change also solved https://github.com/deeplearning4j/deeplearning4j/issues/1462 and I will leave a comment there.

Is `ImageRecordReader` a part of Canova? I might be able to jump in and fix this.

**Comment by AlexDBlack** [comment]
@crockpotveggies just a heads up: we're in the process of doing a major rewrite on the ImageRecordReader... see this for details: https://github.com/deeplearning4j/Canova/issues/135

**Comment by agibsonccc** [comment]
Is this still the case?

**Comment by crockpotveggies** [comment]
Let me give this a shot with 3-channel images and get back to you.

**Comment by crockpotveggies** [comment]
Potential issue here: what happens if the dataset is mixed with 3-channel sRGBs and black and white images?

**Comment by saudet** [comment]
@crockpotveggies It shouldn't matter at all anymore with NativeImageLoader.

**Comment by crockpotveggies** [comment]
Have tested this and confirmed I have no issues on my end. Closing. Nice work!
