### ISSUE TITLE
Master not building any more for people who haven't built master yet

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#902]
With the introduction of the new distribution system, the nd4j backends became dependent on themselves.

While nd4j-native is published in the Sonatype Snapshots, nd4j-cuda-7.5 is not. Now when someone tries to build the current master, it tries to resolve the dependency, and fails on nd4j-cuda-7.5 if you don't have a snapshot of it already.

I'm pretty sure this is the culprit:
https://github.com/deeplearning4j/nd4j/commit/41d7d3ef4b3b0029c014f6aeee05974b9bfe221d#diff-fed97ac498d35c7e30209682d5d13f91R25

@agibsonccc @saudet Can you take a look?

**Comment by agibsonccc** [comment]
I'm not seeing that...What happens when you rebuild from root?

**Comment by treo** [comment]
You have to clean out your ~/.m2 folder first. We have found that upon trying to install on a fresh machine. And I could reproduce it after clearing out my .m2 folder.

**Comment by saudet** [comment]
Looks like we have to hack this a bit more...
