### ISSUE TITLE
Optimize random number generation

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#922]
In some circumstances (weight init for large networks, dropout), random number generation can take a noticeable amount of time.

The ideal RNG implementation would be c-based and parallel, and GPU-based for CUDA. The current implementation is java-based and inherently serial: https://github.com/deeplearning4j/nd4j/blob/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/rng/DefaultRandom.java

See also:
https://developer.nvidia.com/curand
https://software.intel.com/en-us/node/521842

**Comment by fac2003** [comment]
You could have a look at this for high quality and efficient random number generators http://xoroshiro.di.unimi.it/

**Comment by treo** [comment]
Actually I have already taken a look at xoroshiro128+ when I first noticed the random number generation to be a bottle neck, and it wasn't noticeably faster.

To be fair I only replaced the MerseneTwister that is currently used with xoroshiro128+ there.

**Comment by AlexDBlack** [comment]
https://github.com/deeplearning4j/nd4j/pull/1363
