### ISSUE TITLE
CUDA crash - dl4j gradient checks (double precision)

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#926]
Running dl4j gradient checks on branch r119_ews_and_everyone (libnd4j branch r119_polishing) results in crash. [Note as discussed minor op executioner change was made for double precision]

For example, in GradientCheck.testGradientMLP2LayerIrisSimple():

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffcd6465a33, pid=6260, tid=5580
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# C  [nd4j.dll+0x25a33]
```

full log:
https://gist.github.com/AlexDBlack/4327104ece2015bf8b5a9b3fc065d505

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/libnd4j/pull/175
