### ISSUE TITLE
Docs: rc-3.9

### ISSUE THREAD

**Issue by agibsonccc** [deeplearning4j/nd4j#928]
For rc-3.9 it turns out that gradle and sbt don't know how to use classifiers.

We need to document how to add classifiers eg: linux_x86_64 for users.

The reason for this change was splitting out the binaries in to their own jar files.

Maven knows how to handle this transparently.

This would be just updating the user's guide to mention this.

**Comment by saudet** [comment]
This was merged for Gradle: https://github.com/deeplearning4j/nd4j/pull/920

So, let me add a snippet for sbt there...
