### ISSUE TITLE
"RBM needs some love" ?? (well StackedAutoEncoderMnistExample to be exact)

### ISSUE THREAD

**Issue by ianpjohnson** [deeplearning4j/nd4j#935]
Quick test of a few examples on git pull from 14/5 for 3.9-SNAPSHOT
Openblas, Windows 8-64 16GB Core I5-2500K, Java 1.8.0:77 64 bit

CNN are looking good - LenetMnistExample
v3.8 1324ms -> v3.9(14/5)  398ms

StackedAutoEncoderMnistExample - a lot slower
v3.8 206ms -> v3.9(14/5) 352ms *********

DeepAutoEncoderExample - about the same
v3.8 507/255/128/49/15/52 -> v3.9 506/255/128/49/15/51

**Comment by agibsonccc** [comment]
A lot of that is sampling related.
