### ISSUE TITLE
Input Validation missing for Concat

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#947]
Using a sufficiently invalid concat, can crash the jvm, using a just a bit invalid one will corrupt memory:

For example:
`System.out.println(Nd4j.concat(0, Nd4j.ones(1000000), Nd4j.create(1)));`

Will crash the JVM on rc3.9.

The problem is present for both nd4j-native and nd4j-cuda-7.5.

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/967
