### ISSUE TITLE
nd4j.rc3.9. Crashes with cuda

### ISSUE THREAD

**Issue by newikoff256** [deeplearning4j/nd4j#948]
Crashes when trying to run a primitive code with nd4j-cuda-7.5 (with nd4j-native everything works)
Code: 
https://gist.github.com/newikov/0c4b61bf18d7767c938e21315c22423f

pom.xml: 
https://gist.github.com/newikov/7c69a2a1f3b4b96a54a333f0eb901966

DeviceQuery info:
https://gist.github.com/newikov/c29e9466c17c4db6aba5046256f76932

Error log: 
https://gist.github.com/newikov/43b382886f1005fc5294f95ee66335f4

**Comment by raver119** [comment]
You've forgot to include full output log. Please attach it.

**Comment by newikov** [comment]
Done

**Comment by raver119** [comment]
Fixed by reinstalling CUDA toolkit and driver.
