### ISSUE TITLE
Remove obsolete CPU execution code

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#950]
CPU tasks etc here: no longer needed and should be removed.
https://github.com/deeplearning4j/nd4j/tree/master/nd4j-backends/nd4j-api-parent/nd4j-api/src/main/java/org/nd4j/linalg/api/parallel

**Comment by agibsonccc** [comment]
https://github.com/deeplearning4j/nd4j/pull/968
