### ISSUE TITLE
Diverging scores when using nd4j-cuda-7.5

### ISSUE THREAD

**Issue by EdwinLUSTlab** [deeplearning4j/nd4j#951]
When running GravesLSTMCharModellingExample using the nd4j-cuda-7.5 0.4-rc3.9 backend I face diverging scores after roughly 600 iterations. When using the nd4j-native backend I do not have this problem.

**Comment by AlexDBlack** [comment]
This is likely contributing, if not entirely causing the issue: https://github.com/deeplearning4j/nd4j/issues/953

**Comment by AlexDBlack** [comment]
Above-linked issue is fixed; tested cpu vs. gpu out to ~700 iterations. Slight score difference between the two, but looks like this is just the compounding effect of limited numerical precision.
