### ISSUE TITLE
l2 norm incorrect on CUDA for large arrays

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#953]
```java
    @Test
    public void l2NormTest(){
        for( int i=1; i<1e7; i *= 10){
            INDArray arr = Nd4j.linspace(1,i,i);
            System.out.println(i + "\t" + arr.norm2Number());
        }
    }
```

**Nd4j-native: 3.10-SNAPSHOT**
1	0.0
10	19.621416091918945
100	581.6785888671875
1000	18271.1015625
10000	577393.625
100000	1.8257556E7
1000000	5.77351104E8

**nd4j-cuda-7.5: 3.10-SNAPSHOT**
1	0.0
10	19.621416091918945
100	581.6785888671875
1000	18271.111328125
10000	1.11600361472E11
100000	4.5027413721088E13
1000000	4.4947515652440064E16

**Comment by raver119** [comment]
Fixed now, pushed to master.
