### ISSUE TITLE
nd4j-native: crash on gemm with multithreading

### ISSUE THREAD

**Issue by AlexDBlack** [deeplearning4j/nd4j#954]
Running the Iris Spark example (in Spark local) results in a crash with a large number (10 or more) threads in the spark configuration.
https://gist.github.com/AlexDBlack/ceb127ac5e3fd8f8f3a15cf36a60a024

This behaviour can be easily replicated with the following code:

``` java
    public static void main(String[] args){
        final INDArray first = Nd4j.create(10,10);
        final INDArray second = Nd4j.create(10,10);

        int nThreads = 10;
        final int iterationCount = 1000;
        for( int i=0; i<nThreads; i++ ){

            Thread t = new Thread(new Runnable(){
                @Override
                public void run() {
                    for( int i=0; i<iterationCount; i++ ){
                        first.mmul(second);
                    }
                }
            });
            t.start();
        }
    }
```

**Comment by AlexDBlack** [comment]
This appears to be due to openblas (bundled); running this on 0.4-rc3.10-SNAPSHOT (i.e., nd4j/libnd4j master) with MKL works fine (even with 1000 threads doing mmuls simultaneously).

**Comment by vladimir-nazarenko** [comment]
@AlexDBlack, could you confirm that bug persists? I wasn't able to reproduce it even increasing sizes of the arrays and the number of threads.

**Comment by raver119** [comment]
Probably it was fixed ages ago...
