### ISSUE TITLE
JVM Crash on TransformOps with equal sized, but differently oriented parameters

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#959]
While trying out the example code from https://github.com/deeplearning4j/nd4j/issues/958 I've made a mistake and didn't change the result shape. This resulted in a JVM crash. 

BaseTransformOp already has a check to make sure that both arrays have the same length, but it doesn't check the orientation.

The following code produces reliably a crash with an error dump:
```java
package com.example;

import org.nd4j.linalg.api.ndarray.INDArray;
import org.nd4j.linalg.api.ops.impl.transforms.SoftMax;
import org.nd4j.linalg.api.ops.impl.transforms.SoftMaxDerivative;
import org.nd4j.linalg.factory.Nd4j;

public class App {

    public static void main(String[] args) {
        INDArray input1 = Nd4j.create(1000).transpose();
        INDArray input2 = Nd4j.zerosLike(input1);
        Nd4j.copy(input1, input2);
        INDArray output1 = Nd4j.create(1, 1000);
        Nd4j.getExecutioner().exec(new SoftMax(input1, output1));
        System.out.println("Softmax = " + output1);
        INDArray output2 = Nd4j.create(1,1000);
        Nd4j.getExecutioner().exec(new SoftMaxDerivative(input2, output2));
        System.out.println("Softmax Derivative = " + output2);
    }
}
```

**Comment by agibsonccc** [comment]
Does this affect softmax only?

**Comment by treo** [comment]
With current master it looks like it only happens on SoftMaxDerivative

**Comment by eraly** [comment]
So softmax derivative still crashes on current master. Looking into it.

**Comment by raver119** [comment]
Is CUDA affected?

**Comment by eraly** [comment]
Haven't looked into cuda

**Comment by raver119** [comment]
Ok, i've checked it's not affected. 

sumNumber returns 1.0 for both outputs.

**Comment by eraly** [comment]
@raver119 🎉 
Let me hunt down what it is in cpu.

**Comment by eraly** [comment]
Closing. Merged and fixed in current master. Throws an exception instead of a crash in all such cases.
