### ISSUE TITLE
JVM Crash when trying to create a too large Array

### ISSUE THREAD

**Issue by treo** [deeplearning4j/nd4j#960]
The following crashes the JVM quite reliably (Win 10):

```java
package com.example;

import org.nd4j.linalg.factory.Nd4j;

public class App {

    public static void main(String[] args) {
        Nd4j.create(new int[]{3000,5000,7000}, 'c');
    }
}
```

Error log: https://gist.github.com/treo/caddd0b17cc9b9749c271816ba5fac59

**Comment by raver119** [comment]
Is it only cpu, or cuda affected too?

**Comment by saudet** [comment]
So, you're trying to allocate 392g of RAM... Can you actually commit that much memory on your system? Or are you expecting an exception instead of a crash?

**Comment by saudet** [comment]
This fixes the crash, at least: https://github.com/bytedeco/javacpp/commit/587f9e836d547f4d7ea72306a7846fd7cfd888bc

**Comment by treo** [comment]
Was expecting an exception. So the fix looks to be fine :)
