### ISSUE TITLE
i7 3820 beating 32 core Xeon by 3x

### ISSUE THREAD

**Issue by Habitats** [deeplearning4j/nd4j#962]
Training LSTM using MKL, all on current master. Atm an iteration takes 19~s on the i7 while it takes well over a minute on both of the Xeon ones.

Is this performance expected?

# Desktop
```
processor       : 7
vendor_id       : GenuineIntel
cpu family      : 6
model           : 45
model name      : Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz
stepping        : 7
cpu MHz         : 3708.000
cache size      : 256 KB
physical id     : 0
siblings        : 8
core id         : 3
cpu cores       : 4
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 x2apic popcnt aes xsave osxsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

# Google compute engine 32 core instance
`Linux corpus 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`
```
processor       : 31
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(R) Xeon(R) CPU @ 2.30GHz
stepping        : 0
microcode       : 0x1
cpu MHz         : 2300.000
cache size      : 46080 KB
physical id     : 0
siblings        : 32
core id         : 15
cpu cores       : 16
apicid          : 31
initial apicid  : 31
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc nopl xtopology eagerfpu pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm xsaveopt fsgsbase bmi1 avx2 smep bmi2
bogomips        : 4600.00
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

# Xeon box running on Joyent (20 cores available, no other restrictions)
`Linux sparktest 3.13.0 BrandZ virtual linux x86_64 x86_64 x86_64 GNU/Linux`
```
processor       : 31
vendor_id       : GenuineIntel
cpu family      : 6
model           : 63
model name      : Intel(r) Xeon(r) CPU E5-2640 v3 @ 2.60GHz
stepping        : 2
cpu MHz         : 2599.964
cache size      : 0 KB
physical id     : 1
siblings        : 16
fdiv_bug        : no
hlt_bug         : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 15
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm pni monitor ds_cpl est tm2 cx16 xtpr
```

**Comment by raver119** [comment]
So, obvious concern for me here, is actual avx support on those boxes. And there's a thing that surprises me: E5-2640 should have AVX support available, and can't have 0KB cache size. So this looks to me more like "fake" cpuinfo provided by virtualization layer.

Google's cpuinfo looks way better. Something like E5-2699 or something similar. And has avx/avx2 listed as it should be. At some point it would be nice to check, what's actually wrong there for libnd4j

**Comment by AlexDBlack** [comment]
Also: any chance of getting a breakdown of runtimes from each, in visualvm or something? That might give us some clues as to what's going on behind the scenes.

**Comment by Habitats** [comment]
I only have shell access; visualVM output isn't trivial. Also, I pay by the hour for that google instance, so I can't just have it running for diagnostics. 

The joyent box I can do pretty much what I want with, though.

**Comment by treo** [comment]
Sofar we have figured out that for some reason GNU OpenMP seems to choke on libnd4j on linux. 
Running it with OMP_NUM_THREADS=1 solves the problem, in so far as it is a lot faster than any other number of threads.

Using intels OpenMP runtime (with the most current version from http://packages.ubuntu.com/de/source/yakkety/openmprtl) as a drop in replacement via LD_PRELOAD, improves the problem somewhat, but using only a single thread is still faster than using several. But at least the difference isn't that large anymore.

**Comment by Habitats** [comment]
For some perspective; using OMP_NUM_THREADS=1 reduced average iteration from 60s to 12s on both of my Xeons, and the remaining changes reduced it even further to 10s average.

Running two jobs at the same time yielded a cumulative increase of around 50%, i.e. 33% more iterations combined.

**Comment by Habitats** [comment]
Numbers are average ms over 10 last iterations. Batches aren't identical, so some vary.

### Single
Google (32c) 1x OMP_NUM_THREADS=1 MKL_NUM_THREADS=32, maxing 100% on 32c
35431

Google (32c) 1x OMP_NUM_THREADS=1 MKL_NUM_THREADS=32, maxing 100% on 16c
8934
11132
11892
10746

Google (32c) 1x OMP_NUM_THREADS=2 MKL_NUM_THREADS=32, maxing 100% on 16c
7911
10311
10991
10212

Google (32c) 1x OMP_NUM_THREADS=4 MKL_NUM_THREADS=32, maxing 100% on 16c
7399
9681

Google (32c) 1x OMP_NUM_THREADS=4 MKL_NUM_THREADS=32, maxing 100% on 16c
7796
9295

Google (32c) 1x OMP_NUM_THREADS=32 MKL_NUM_THREADS=32, maxing 100% on 16c
7816
9070

### Two jobs at the same time
Google (32c) 2x OMP_NUM_THREADS=2 MKL_NUM_THREADS=32 
11681 + 10085 
14346 + 13147
18059 + 16360 

Google (32c) 2x OMP_NUM_THREADS=1 MKL_NUM_THREADS=32 
11308 + 11620
14761 + 14587
15911 + 15770

### Single 
Joyent (20c) 1x 
38887

Joyent (20c) 1x OMP_NUM_THREADS=1 MKL_NUM_THREADS=32 
10303
10599
12789
10235
10418

Joyent (20c) 1x OMP_NUM_THREADS=2 MKL_NUM_THREADS=32 
9600
10644
13396

11032
11584

### Two jobs at the same time
Joyent (20c) 2x OMP_NUM_THREADS=2 MKL_NUM_THREADS=32 
22880 + 22562
29853 + 29889

**Comment by treo** [comment]
@Habitats can you please update this with numbers from current master?

**Comment by Habitats** [comment]
Ran some more benches with more machines:

```
                             Job completion (init, IO, training) Average over 840 iterations
Ubuntu native (OpenBlas):     8 minutes 40 seconds (520355 ms)   340 ms
Ubuntu native (MKL):         12 minutes 11 seconds (731039 ms)   519 ms
Google dataproc (OpenBlas):  13 minutes 50 seconds (830619 ms)   578 ms
Google dataproc (MKL):       14 minutes 25 seconds (865642 ms)   609 ms
Joyent (OpenBlas):           18 minutes            (1080674 ms)  820 ms
Joyent (MKL):                16 minutes 32 seconds (992494 ms)   713 ms
Desktop (MKL):               18 minutes 10 seconds (1090409 ms)  811 ms
```

**Comment by treo** [comment]
@Habitats if you have some time it would be great to know how fast current master is.

**Comment by raver119** [comment]
So, what's up there now?

**Comment by raver119** [comment]
Closing this issue as "probably irrelevant now"
