### ISSUE TITLE
CUDA State beyond 3.9

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#970]
***Asynchronous execution:***

At this moment, we’re able to provide next-to-100% (or pure 100%) occupancy on any given kernel.
Besides of overall total coolness, that gives us simple fact: this greatly reduces theoretical external parallelism available there. If any single kernel tends to occupy whole device, what’s the point then trying to execute things asynchronously? The only possible gain here is async out-of-order memcpy. Everything else will suffer when executed on full-occupied device.

So, probably async backend should be retired (or left as prototype, for possible future devices, that are better then my gtx 970), and simple delayed execution backend should be introduced, just to make sure that cuda device always has next grid already available for execution.

***Multi-GPU scaling:***

To be discussed separately.

***Shared memory improvements:***

Currently we have pretty small shared memory use, since it’s used for initial Op creation + as reduction buffer for appropriate kernels. And we also want to have low maxrreg count. So since we have average shmem use below 300 bytes, we could be pretty comfortable with some caching involved, probably. However, most of caches do not have anything to cache now: shape & TAD stuff is already at constant memory, and there’s not too much left beyond that. However, we could increase shmem use for local variables, where that could bring performance gains.

***Kernel atomization:***

IndexReduce should be split into Scalar, 1D, 3D and xD kernels, like it was previously done with Reduce kernel.

***Kernels i’m happy with:***

pairwiseStrided
reduceScalar (however, i’d prefer to make it with dp instead of threadfence)
broadcast
ismax filler, however, it maybe worth to make ismax and it’s filler to be the same kernel.

***Kernels i’m NOT happy with:***

All kernels that use ind2sub.
All reduce3 sub-kernels.
Concat HStack for columns would be also nice to have as separate implementation, within HStackGeneric probably.
toFlatten should be executed in the same way as concat does - one kernel call with multiple src pointers.

***FP16 problem:***

We definitely want to have FP16 support. on pascal-generation gpu that should bring some performance boost, together with x2 reduced storage footprint.
The only problem there for us is host memory. JVM should be aware of fp16 somehow, otherwise data use on host side will become impossible. I think the first solution here is JavaCPP fp16 support for host memory. On JVM level methods like getFloat()/getDouble() should just return floats.

**Comment by raver119** [comment]
For asynchronous DataSetIterator prefetch and multi-gpu handling in spark environment following changes are considered:

- We introduce manual thread-device affinity management. Just a way to explicitly force any given thread to be bound to any specific device. That should be enough for most of standalone usecases.
- For spark(or any future cluster environment) there will be special solution, due to different multi-threading models.

I.e. within spark you have some RDD<DataSet>. Driver serializes them, and sends to executors. Then deserialization happens in one thread (we don't have access to that thread obviously), and then deserialized DataSet is processed using casual fit() in executor. 

For such environment we'll probably just introduce slightly different memory strategy: we won't allocate device memory before first actual Op call.

**Comment by raver119** [comment]
So, since there's possible environments, where we don't have control of DataSet instantiation (and it means we also don't have ways to control thread->device affinity) , one of possible solutions would be something like this:

- We introduce one more allocation model, that'll work as hybrid: HOST memory first, DEVICE memory by request.
- So, during deserialization - array is created in host memory only, and since deserialization process is pretty straightforward - it'll stay intact until its internal features INDArray gets accessed by model.
- On first getDevicePointer() request, memory chunk gets copied to DEVICE, with appropriate deviceId being set.

P.S. To reduce overhead there, a bit more aggressive device memory allocation at the beginning of training process, so memory cache will get filled faster.

**Comment by agibsonccc** [comment]
This is done right?

**Comment by raver119** [comment]
Nope, debugging multi-gpu scaling in spark environment using Alex's pc right now.

**Comment by raver119** [comment]
So, multi-gpu spark issue was tracked down to the bottom.

Spark uses multiple threads internally, besides of worker threads. So for SparkDL4jMultilayer data flows in the following manner:

- inital model creation happens in root thread, aka 1.
- some serialization processes happen, but they do not affect DataSets, so we don't care
- worker threads are spawned, initial model is duplicated through ser/de
- after calculation is finished, data returned back through ser/de
- aggregation starts in root thread, but spawns additional thread: https://github.com/deeplearning4j/deeplearning4j/blob/61b1d7edaa349e5f3eca8d0eb26fa9b990f62512/deeplearning4j-scaleout/spark/dl4j-spark/src/main/java/org/deeplearning4j/spark/impl/paramavg/ParameterAveragingTrainingMaster.java#L233-L233
- after aggregation is finished, technically we're still in thread 1, but data we got after aggregation is attached to another thread (and probably ***another device***)

**Comment by raver119** [comment]
So, yep, initial multi-gpu scaling via data parallelism is available now, and will be merged after all required tests. However, performance there should be improved in subsequent releases.
