### ISSUE TITLE
length of NDArrayIndex

### ISSUE THREAD

**Issue by migel** [deeplearning4j/nd4j#98]
Hi, the ```length``` method of ```NDArrayIndex``` returns an incorrect length:

```scala
  val i0 = NDArrayIndex.interval(0, 5)            //> i0  : org.nd4j.linalg.indexing.NDArrayIndex = NDArrayIndex{indices=[0, 1, 2,
                                                  //|  3, 4]}
  i0.length()                                     //> res0: Int = 4
```

**Comment by agibsonccc** [comment]
Put include = true. in the interval and it will return 5.

**Comment by migel** [comment]
With include = true:
```scala
  val i0 = NDArrayIndex.interval(0, 5, true)      //> i0  : org.nd4j.linalg.indexing.NDArrayIndex = NDArrayIndex{indices=[0, 1, 2,
                                                  //|  3, 4, 5]}
  i0.length()                                     //> res0: Int = 5
```

For include = false, the list of indices shows five elements: ```[0, 1, 2, 3, 4]``` and for include = true the list shows six elements: ```[0, 1, 2, 3, 4, 5]```. It looks like it's off by one for both cases.

**Comment by agibsonccc** [comment]
Which version is this? I'm seeing 5 for NDArrayIndex.interval(0,5)

**Comment by agibsonccc** [comment]
This will be fixed when bugfixes is merged.
