### ISSUE TITLE
NDArray#setOrder throws RuntimeException

### ISSUE THREAD

**Issue by taisukeoe** [deeplearning4j/nd4j#982]
I found this bug in 0.4-rc3.9.

```scala
scala> Nd4j.linspace(1,5,5).setOrder('f')
java.lang.RuntimeException: setOrder() called
  at org.nd4j.linalg.api.ndarray.BaseNDArray.setOrder(BaseNDArray.java:891)
  ... 42 elided
```

**Comment by raver119** [comment]
ShapeInfo is considered to be immutable. So calls like setOrder(), setShape(), setStride(), should create new shapeInfo buffer, instead of existing buffer modification.

I'll take care of this one, thanks for flagging it.

**Comment by raver119** [comment]
Fixed here: https://github.com/deeplearning4j/nd4j/pull/977

Will be merged a bit later
