### ISSUE TITLE
CPU state beyond 3.9

### ISSUE THREAD

**Issue by raver119** [deeplearning4j/nd4j#986]
After rc3.9 release we've already implemented few improvements for nd4j-native both in libnd4j and nd4j, and got better performance.

But right now we have few major concerns to be solved now:
- SIMD actually isn't working in like 99% of codebase.
- Op calls are NOT getting inlined. 

Using GCC to get SIMD working on math.h calls glibc >=2.22 is required. Or another external SIMD-aware math library.

And we're still looking for solutions, to make op calls inlined in our code design without too much changes. Right now i have a hope that static allocation and call for op will help. If not - we'll have a look for another options. But non-inlined calls worth too much for us at this for us.

I.e. scalar add op on array with length of 20480 elements using our op factory is worth of 36k ns, and the same operation using hardcoded thing like dx[i] * scalar takes only 4k ns.

**Comment by treo** [comment]
Having SIMD working for math.h calls can get huge improvements. SIMD enabled expf is 4.6 times faster than a non-SIMD enabled one on my machine.

**Comment by raver119** [comment]
You've tested expf statically linked for both with/without SIMD, right?

**Comment by treo** [comment]
Right.

**Comment by raver119** [comment]
Well, that's exactly 4 operations per 1 cycle then. Exactly 256 bits lanes for AVX2

**Comment by treo** [comment]
So, some numbers how our refactoring has affected the performance so far:
I'm using the GravesLSTMCharModellingExample with a miniBatchSize of 512 and I'm measuring how long a single `.fit(ds)` call takes.

On Windows (with MKL):
Using rc3.9: 53 seconds
With optimizations: 40 seconds

On Linux (with self compiled OpenBlas):
Using rc3.9: 43 seconds
With optimizations: 26s (not on most recent nd4j/dl4j combination, as that appears to have problems)

**Comment by raver119** [comment]
1) Linux with MKL? :)
2) Reductions are still in TODO list...
3) It looks like we don't have too much options for Transform ops besides of glibc >= 2.22

**Comment by raver119** [comment]
On top of that:
4) Most memory-bound ops, like broadcast, pairwise, scalar got booster x15-x20 times. I.e. row-wise broadcast on 1024x1024 array in 3.9 takes around 1.1-1.5ms, now it takes only 75k ns.
5) Maybe we could build libnd4j statically with glibc 2.23 and corresponding libstdc?

**Comment by raver119** [comment]
6) extraArgs. Its time to deal with them. 

So, next perf iteration on cpu will have following goals: reductions via openmp + extraArgs reorganization. Cuda will also greatly benefit from that.

**Comment by raver119** [comment]
@agibsonccc @saudet can we build statically against latest glibc, for their vectorized math library?

**Comment by treo** [comment]
Also, at some point we should checkout using ICC. Windows doesn't get the benefit of a new Glibc version, so the only way there is to compile it with something that has a simd math library.

**Comment by saudet** [comment]
Linking statically might be technically tricky:
http://stevehanov.ca/blog/index.php?id=97
And there would be licensing issues because glibc is LGPL...

**Comment by treo** [comment]
I've tried out Intel SVML on Windows, and it takes off 10 seconds from the time I reported earlier.

**Comment by raver119** [comment]
In other words, if we build libnd4j with mkl for windows, svml should be used as math library for best performance

**Comment by treo** [comment]
Another data point:
Running GravesLSTMCharModellingExample to completion, on Linux with MKL:
rc3.9: 20 Minutes
master with libmvec: 9 minutes 18 seconds
master with svml: 9 minutes 40 seconds

So on a linux with a new enough glibc (>= 2.22) it looks like it is the best to simply use libmvec. On windows svml or acml are probably the only way to get vectorized basic math. On macosx clang has vectorized intrinsic math, so that shouldn't be a problem there, esp. as it lacks some other vital openmp features.

**Comment by raver119** [comment]
So, latest checks show that since refactoring we already have SIMD reductions working.
And this means that extraArgs change is the last planned improvement for current pass.
