### ISSUE TITLE
UnsatisfiedLinkError, no jniopencv_core in java.library.path (Gradle, sbt)

### ISSUE THREAD

**Issue by junyongyou** [deeplearning4j/nd4j#991]
I got the exception as follwing:

Exception in thread "main" java.lang.UnsatisfiedLinkError: no jniopencv_core in java.library.path
...
Caused by: java.lang.UnsatisfiedLinkError: no opencv_imgproc310 in java.library.path

Actually I got the same exception when I was running opencv in IntellijIDEA. The way I fixed the problem is to add 

compile 'org.bytedeco.javacpp-presets:opencv:3.1.0-1.2:windows-x86_64'

in Gradle command. We have to specify the platform "windows-x86_64" (but just in my case).

Hope this helps.

**Comment by saudet** [comment]
Instructions for that are given on this page:
https://github.com/bytedeco/javacpp-presets/#downloads
So I guess that should become part of the gettingstarted.md page when it gets updated.

**Comment by agibsonccc** [comment]
Where is this?

**Comment by agibsonccc** [comment]
Could we close this if it's done?

**Comment by saudet** [comment]
It's not done, but it's not an issue with nd4j or dl4j, but with javacv, so we can close this here.
