### ISSUE TITLE
sbt failed to fetch 0.4-rc3.9 library 

### ISSUE THREAD

**Issue by zpfxellose** [deeplearning4j/nd4j#992]
i am using sbt 0.13.11 on macosx 10.11.5

i put following into build.sbt
`classpathTypes += "maven-plugin"
libraryDependencies += "org.nd4j" % "nd4j-native" % "0.4-rc3.9" classifier "macosx-x86_64"
`

but got error trying to build the project

`
[error] 1 not found
[error] https://repo1.maven.org/maven2/org/nd4j/nd4j-native/0.4-rc3.9/nd4j-native-0.4-rc3.9-${os.name}-${os.arch}.${project.packaging}
`

**Comment by zpfxellose** [comment]
i put my problematic project on github. here is the address:

https://github.com/zpfxellose/nd4j_sbt_bug_demo

**Comment by zpfxellose** [comment]
I figured it out. It's caused by sbt-coursier... the problem goes away when i disable the plugin.. sorry for the trouble.

**Comment by saudet** [comment]
So I guess that's an issue that should be reported to the guys at sbt-coursier :)
