### ISSUE TITLE
INDArray elementwise product and reshaping

### ISSUE THREAD

**Issue by Jajawah** [deeplearning4j/nd4j#994]
Hi,

like I wrote on the gitter chat with @agibsonccc, I want to do an element wise product between tensors.
But the reshape operation seems to fail.

Numpy equivalence
`t1=array([1,2])`
`t2=array([[[3,4,5],[6,7,8]],[[9,10,11],[12,13,14]]])`
`print(t2*t1.reshape(2,1,1))`
>[[[ 3  4  5]
  [ 6  7  8]]
 [[18 20 22]
  [24 26 28]]]

`print(t2*t1.reshape(1,2,1))`
>[[[ 3  4  5]
  [12 14 16]]
 [[ 9 10 11]
  [24 26 28]]]

while with nd4j 
`INDArray t1 = Nd4j.create(new double[]{1,2});`
`INDArray t2 = Nd4j.create(new double[]{3,4,5,6,7,8,9,10,11,12,13,14},new int[]{2,2,3},'c');`
`System.out.println(t2.mul(t1.reshape(2,1,1).broadcast(2,2,3)));`
>[[[ 3,00,  4,00,  5,00],
  [ 6,00,  7,00,  8,00]],
 [[18,00, 20,00, 22,00],
  [24,00, 26,00, 28,00]]]

`System.out.println(t2.mul(t1.reshape(1,2,1).broadcast(2,2,3)));`
>[[[3,00, 4,00, 5,00],
  [6,00, 7,00, 8,00]],
 [[0,00, 0,00, 0,00],
  [0,00, 0,00, 0,00]]]

So what am I missing ?

**Comment by Jajawah** [comment]
I find a workaround by reshaping and broadcasting keeping intial order and then permuting
'System.out.println(t2.mul(t1.reshape(2,1,1).broadcast(2,2,3).permute(new int[]{1,0,2})));
> [[[ 3,00,  4,00,  5,00],
  [12,00, 14,00, 16,00]],
 [[ 9,00, 10,00, 11,00],
  [24,00, 26,00, 28,00]]]

**Comment by Jajawah** [comment]
@agibsonccc  in #313 you wrote (about the same issue)

> Now uses dimshuffle.

I try but it does not broadcast on all dimensions, a (2,2,1) tensor mul (2,1,2) return a (2,2,1) tensor in place of a (2,2,2) tensor as expected (and as numpy does). 

If I do the broadcast (with my tip described on my previous message),  on big tensors the perf is very poor (it seems that the broadcast works with tensor repeated copy and not by working only on indexes).

So is there a way to do an outer product of tensors with different shapes ?

**Comment by eraly** [comment]
Hi Jajawah. You are right this is a known issue. 
https://github.com/deeplearning4j/nd4j/issues/1101
It will probably make it into the next release (not the one tomorrow). Thanks!
